### ISSUE TITLE
International calendars that the @internationalized/date supported

### ISSUE THREAD

**Issue by blue-range** [huntabyte/shadcn-svelte#1006]
### Describe the feature

As you know the @internationalized/date Support for 13 calendar systems used around the world, including Gregorian, Buddhist, Islamic, Persian, and more.
can we have them in shadcn-svelte calendar component?

**Comment by huntabyte** [comment]
Closing as already open in bits

**Comment by itskazemk** [comment]
Can't wait to see that, it's the only thing that hold my coworkers from svelte
