### ISSUE TITLE
A misaligned icon on the Themes Page of the website on the button(dropdown) Security Level

### ISSUE THREAD

**Issue by elciodalosto** [huntabyte/shadcn-svelte#1020]
### Describe the bug

Just a little misaligned icon, that is supossed to be in the right side of the button, I think.

![image](https://github.com/huntabyte/shadcn-svelte/assets/15917796/dcf048a1-d63f-42d5-a28a-82df5e515673)
![image](https://github.com/huntabyte/shadcn-svelte/assets/15917796/7f07a1b8-4948-4c1b-9cdd-a49dd55e3bc5)

### Reproduction

1. Access the path [/themes](https://www.shadcn-svelte.com/themes) from the website https://www.shadcn-svelte.com/
2. scroll down until you find the card entitled "**Report an issue**"
3. Look for the button label "Security Level" where the text is "Severity 2"

### System Info

```bash
Browsers:
- MS Edge - v. 123.0.2420.81
- G. Chrome v. 123.0.6312.107
```

### Severity

annoyance

**Comment by Scooter1337** [comment]
#910 addresses this, but has not been updated for some time now.

**Comment by elciodalosto** [comment]
> #910 addresses this, but has not been updated for some time now.

Thanks for the reply! Maybe I've searched for the wrong words, so I didn't find that old issue, before I post.
