### ISSUE TITLE
Format installed components using local prettier config

### ISSUE THREAD

**Issue by H0R5E** [huntabyte/shadcn-svelte#1022]
Hi, thanks for the amazing project, I'm really enjoying using it.

### Describe the feature

I was wondering if it would be possible to format the installed component code with the local prettier configuration?

For instance, the installed components use tab indentation, whereas I have the indentation set to default (i.e. with spaces).

I think [shadcn-ui#1014](https://github.com/shadcn-ui/ui/issues/1014) is a relevant issue, but I don't know if it conforms to the local formatting config on install.

All the best,

Mat

**Comment by AdrianGonz97** [comment]
Thanks for the suggestion! 

We used to do this, but decided to take it out as it increased the complexity of CLI for very little benefit. It's far more simple for users to just run `npm run format` after installing the components than it is for us to do it for them.
