### ISSUE TITLE
Drawer direction not working or not implemented

### ISSUE THREAD

**Issue by WeAreELIC** [huntabyte/shadcn-svelte#1025]
### Describe the bug

When looking at the [vaul-svelte](https://github.com/huntabyte/vaul-svelte) API reference, the Root contains a `direction` property. When adding this to the Drawer.Root element — <Drawer.Root direction="top"> — it doesn't position it to any other position except the bottom. The animations change, but it's always positioned at the bottom.

### Reproduction

Example: https://stackblitz.com/edit/github-vyjvwn?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: macOS 14.3
    CPU: (11) arm64 Apple M3 Pro
    Memory: 124.20 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
  Browsers:
    Brave Browser: 123.1.64.113
    Chrome: 123.0.6312.124
    Safari: 17.3
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.6 
    bits-ui: ^0.21.3 => 0.21.3 
    svelte: ^4.2.7 => 4.2.14 
    vaul-svelte: ^0.3.0 => 0.3.0
```

### Severity

annoyance

**Comment by huntabyte** [comment]
You need to update the styles applied depending on the direction you're opening the drawer.

https://stackblitz.com/edit/github-vyjvwn-jzsppp?file=src%2Froutes%2F%2Bpage.svelte

**Comment by WeAreELIC** [comment]
Great, thanks! Would it be worthwhile to bake this into the component?

**Comment by MentalGear** [comment]
I agree, it would be great if this could work like the normal vaul component. :)
