### ISSUE TITLE
Add big warning in docs that installing shadcn-svelte will overwrite existing Tailwind Config

### ISSUE THREAD

**Issue by patagoniapy** [huntabyte/shadcn-svelte#1040]
### Change Type

Addition

### Proposed Changes

I installed `shdacn-svelte` to an existing project and soon thereafter I noticed my existing styling was broken. It wasn't until after a lot of troubleshooting that I realized it had completely overwritten my existing `tailwind.config.ts`. 

It's very possible I missed a warning in the CLI or the docs, but I've looked through both since and can't seem to find a reference to the behavior of overwriting the existing `tailwind.config.ts`.

**Comment by huntabyte** [comment]
It warns you in the CLI and you have to confirm.
