### ISSUE TITLE
Combobox example in documentation shows wrong results

### ISSUE THREAD

**Issue by Flo0807** [huntabyte/shadcn-svelte#1041]
### Change Type

Correction

### Proposed Changes

The [Form Combobox Example](https://www.shadcn-svelte.com/docs/components/combobox) in the documentation (the last example on the page) shows languages to choose from. Each language has a value and a label. The label is displayed to the user in the list and the value is used internally when selecting and submitting languages.

The problem is that the value is used to determine search results. Since the values and labels are entirely different (e.g., `{label: "German", value: "de" }`), this results in displaying *wrong* results.  For example, if I type "de" into the search bar, the result will be "German".

From a user perspective, this doesn't make sense because I want to search the languages by label, since that's the property I see in the list. 

Showcase video below: 

https://github.com/huntabyte/shadcn-svelte/assets/60519307/ca61be5f-32c1-4ba6-877b-0f739f768cfe

**Comment by shyakadavis** [comment]
Hi;

If this is not intentional (I'm pretty sure it's not), I'll go ahead and start working on a fix. 🙂
