### ISSUE TITLE
Temp Component: Select

### ISSUE THREAD

**Issue by huntabyte** [huntabyte/shadcn-svelte#105]
This issue will be used to track the identification and integration of a temporary select component. See https://github.com/huntabyte/shadcn-svelte/issues/95 for more details.

Currently considering:

[CaptainCodeman/svelte-headlessui](https://captaincodeman.github.io/svelte-headlessui/listbox/)

Open to others as well, so if you know of any, please let me know!

**Comment by saturnonearth** [comment]
> [CaptainCodeman/svelte-headlessui](https://captaincodeman.github.io/svelte-headlessui/listbox/)

I have used this before it works great

**Comment by geerew** [comment]
> > [CaptainCodeman/svelte-headlessui (https://captaincodeman.github.io/svelte-headlessui/listbox/)
> 
> I have used this before it works great

I second this. I have used this component myself and it works incredibly well. I also wrapped it in a floating ui which radix uses so the api should be straight forward to switch

**Comment by acidlake** [comment]
This is a great component to use for the Select
