### ISSUE TITLE
Issue with Svelte Sonner

### ISSUE THREAD

**Issue by vexkiddy** [huntabyte/shadcn-svelte#1053]
### Describe the bug

Installing and then running my project displays the following error after installing `svelte-sonner`. 

I'm doing the below in my `+layout.svelte` file :

```
import { Toaster } from '$lib/components/ui/sonner';
<Toaster />
```

It does seem to be the import that is causing the problem. I'm using svelte-5 and had to use --force to install it via NPM. Any advice ?

![image](https://github.com/huntabyte/shadcn-svelte/assets/2254553/026095d7-7af2-4ac2-aa08-1cd059469657)

### Reproduction

```
<script>
	import { Toaster } from 'svelte-sonner';
</script>

<Toaster />

<div class="max-w-6xl mx-auto h-[100vh]" class:hidden={hidden}>
	<slot />
</div>
```

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 53.70 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 124.1.65.114
    Chrome: 124.0.6367.92
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: 2.5.5 => 2.5.5 
    bits-ui: ^0.16.0 => 0.16.0 
    cmdk-sv: ^0.0.13 => 0.0.13 
    formsnap: ^0.4.3 => 0.4.3 
    lucide-svelte: ^0.368.0 => 0.368.0 
    mode-watcher: ^0.2.2 => 0.2.2 
    svelte: ^5.0.0-next.55 => 5.0.0-next.55 
    svelte-sonner: ^0.3.22 => 0.3.22 
    sveltekit-superforms: ^1.13.4 => 1.13.4
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
This issue isn't related to shadcn-svelte based on the stack trace. https://github.com/wobsoriano/svelte-sonner instead.

**Comment by shyakadavis** [comment]
Hey, @vexkiddy 

IIRC, when this happened to me, killing the dev server and restarting it solved the issue for me. 🤷‍♂️ 

Wdyt?

**Comment by vexkiddy** [comment]
@shyakadavis thanks for the tip! that worked :D
