### ISSUE TITLE
Temp Component: Toast

### ISSUE THREAD

**Issue by huntabyte** [huntabyte/shadcn-svelte#106]
This issue will be used to track the identification and integration of a temporary `Toast` component. See #95 for more details.

**Comment by alexanderscpo** [comment]
Hello, I would like to contribute to this feature. My plan is to maintain the same philosophy shadcn/ui: Toast -> svelte.

**Comment by huntabyte** [comment]
Hey there @alexanderscpo !

I'm cool with letting you run with this, but I first want to emphasize that we don't want to create and maintain our own headless toast component if that makes sense. Ideally we'd find a solid headless toast and wrap it in our styles/API structure.

The biggest thing for me is that it it aligns with this [ARIA design pattern](https://www.w3.org/TR/wai-aria/#aria-live), and has most of the same capabilities as Radix UI's [Toast Primitive](https://www.radix-ui.com/docs/primitives/components/toast).

Before writing any code, ensure to let us know your plan / high-level implementation idea so that you aren't wasting valuable time 🙂
