### ISSUE TITLE
svelte-sonner slots

### ISSUE THREAD

**Issue by Carlos-err406** [huntabyte/shadcn-svelte#1062]
### Describe the feature

the original svelte-sonner provides slots for modifying the default iconst of the toast
see [this section of the svelte-sonner readme](https://github.com/wobsoriano/svelte-sonner#changing-icon)

my request is to add those slots to the installed component to make it more extendable, and so users dont have to modify the /ui/sonner.svelte component just to add them

**Comment by Carlos-err406** [comment]
also i would be glad to work on this, and if needed update the docs

**Comment by huntabyte** [comment]
That would be great @Carlos-err406 !

**Comment by Carlos-err406** [comment]
@huntabyte Do you think it's sane to copy and paste the Icon and Loader components from [svelte-sonner](https://github.com/wobsoriano/svelte-sonner/tree/main/src/lib), to use as default values of the slots, or is it better to get a quick PR on svelte-sonner to export the Icon component (and Loader) to the index, i dont know their stand on that though?

or maybe is preferable to just use lucide-svelte icons and forget about the defaults of svelte-sonner?

**Comment by Carlos-err406** [comment]
i tried the lucide icons approach, i think it came out pretty nice

**Comment by oliverdowling** [comment]
I've done this in a simpler way, by just forwarding the slots if they have been specified by using `{#if $$slots...` which doesn't require copy+paste of the other components or add an import.

```
{#if $$slots["loading-icon"]}<slot slot="loading-icon" name="loading-icon" />{/if}
{#if $$slots["success-icon"]}<slot slot="success-icon" name="success-icon" />{/if}
{#if $$slots["error-icon"]}<slot slot="error-icon" name="error-icon" />{/if}
{#if $$slots["warning-icon"]}<slot slot="warning-icon" name="warning-icon" />{/if}
{#if $$slots["info-icon"]}<slot slot="info-icon" name="info-icon" />{/if}
```

Happy to make a PR if you would like.

**Comment by huntabyte** [comment]
With snippets coming up in `svelte-sonner@next` (not yet published) this issue will no longer be relevant.
