### ISSUE TITLE
Tooltip on click

### ISSUE THREAD

**Issue by triadmoko** [huntabyte/shadcn-svelte#1068]
### Describe the feature

![image](https://github.com/huntabyte/shadcn-svelte/assets/23721375/1790b8bc-9e13-4e6d-935a-7d9fbdb3e885)

tooltip feature is now very helpful,

What if the tooltip is clicked and it displays as I have attached?

**Comment by AdrianGonz97** [comment]
What you're looking for is a [Popover](https://www.shadcn-svelte.com/docs/components/popover). Tooltips should only appear when they are [hovered or focused](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role).

Closing as duplicate #1044
