### ISSUE TITLE
Wrong access to plugin states pagination attribute

### ISSUE THREAD

**Issue by Carlos-err406** [huntabyte/shadcn-svelte#1074]
### Change Type

Correction

### Proposed Changes

Current data-table docs section [enable-the-addpagination-plugin](https://www.shadcn-svelte.com/docs/components/data-table#enable-the-addpagination-plugin)

line 71, says to access `pluginStates.page`, but `page` does not exist in `pluginStates`, instead seems to have been renamed to `pagination`

![image](https://github.com/huntabyte/shadcn-svelte/assets/81443707/a39fff2c-7704-4498-80a3-ce3711da38e2)

**Comment by Carlos-err406** [comment]
i would gladly open a PR for this

**Comment by huntabyte** [comment]
That would be awesome @Carlos-err406 !
