### ISSUE TITLE
isVisible is not an exported Prop of Pagination.Item

### ISSUE THREAD

**Issue by Carlos-err406** [huntabyte/shadcn-svelte#1077]
### Change Type

Correction

### Proposed Changes

see here the [usage section of the pagination docs](https://www.shadcn-svelte.com/docs/components/pagination#usage)

but the isVisible prop from Pagination.Item does not exist, since the props of this component are actually `HTMLAttributes<HTMLLIElement>`, see below for current implementation 
![image](https://github.com/huntabyte/shadcn-svelte/assets/81443707/fe046cb6-3c35-447b-9d74-8cf73b6f481f)

here a copy/paste from the docs showing the error
![image](https://github.com/huntabyte/shadcn-svelte/assets/81443707/39fe5dd4-3410-465f-b261-c9a27014b5c2)

my suggestion is to replace isVisible for hidden

**Comment by Carlos-err406** [comment]
i could open a PR for this

**Comment by huntabyte** [comment]
Hey @Carlos-err406, let me investigate this a bit to see where the disconnect is here before opening a PR!

**Comment by Carlos-err406** [comment]
sure!

**Comment by jdgamble555** [comment]
I just came across this error. The examples are incorrect on the main site. Should this be there?

**Comment by kallaviktor** [comment]
> Fixed in `shadcn-svelte@next` / `bits-ui@next`

I'm still getting this error using shadcn-svelte@next / bits-ui@next + sample code from the next docs.

**Comment by baderj** [comment]
I'm also getting the error for this line of [the pagination sample code](https://next.shadcn-svelte.com/docs/components/pagination):
```js
<Pagination.Item isVisible={currentPage === page.value}>
```

```Error: Object literal may only specify known properties, and '"isVisible"' does not exist in type 'HTMLLiAttributes & { ref?: HTMLElement | null | undefined; }'```

Using 
- bits-ui: "1.0.0-next.63"
- shadcn-svelte: "1.0.0-next.3"

**Comment by benjaminschreck** [comment]
I also get the same error using

bits-ui: "1.0.0-next.65"
shadcn-svelte: "1.0.0-next.4"
