### ISSUE TITLE
Bug in Example Task Page

### ISSUE THREAD

**Issue by acidlake** [huntabyte/shadcn-svelte#1079]
### Describe the bug

Looks like the last deployment went with a bug in the example task page in the home.

### Reproduction

Go to https://www.shadcn-svelte.com/examples/tasks or go to https://www.shadcn-svelte.com and click on the task tab in the example, the app will crash.
![Screenshot 2024-05-07 at 8 55 26 AM](https://github.com/huntabyte/shadcn-svelte/assets/4008759/ea8356a6-5ecc-468b-a1c0-154631b70e9f)

### System Info

```bash
Mac
```

### Severity

annoyance

**Comment by AdrianGonz97** [comment]
Thanks for the heads-up! It looks like #1074 introduced this issue. Will investigate more deeply in a few.

**Comment by Carlos-err406** [comment]
im so sorry, just took another look at it, and the access to the page prop is conditioned by the key you use the createTable function. again, sorry for the inconvenience and trouble, Ill be more carefull
