### ISSUE TITLE
ScrollArea.ScrollBar missing in firefox

### ISSUE THREAD

**Issue by vlausargs** [huntabyte/shadcn-svelte#1086]
### Describe the bug

scroll bar missing

### Reproduction

https://www.shadcn-svelte.com/docs/components/scroll-area

### System Info

```bash
firefox ver.125.0.3 (64-bit)
```

### Severity

annoyance

**Comment by jagged3dge** [comment]
I'm using Firefox 125.0.3 (64-bit) as well and it seems to be working fine in my browser.

Screencap video: 



https://github.com/huntabyte/shadcn-svelte/assets/3892333/cb195670-8df1-45ae-82a1-a08be4e5e95b

**Comment by huntabyte** [comment]
Closing as this issue belongs in Bits UI.
