### ISSUE TITLE
Cryptic css rules needed to get out-of-the-box results

### ISSUE THREAD

**Issue by hegelstad** [huntabyte/shadcn-svelte#1090]
### Describe the bug

I find it very confusing that there are cryptic css rules needed to replicate examples:

![Screenshot 2024-05-11 at 15 54 24](https://github.com/huntabyte/shadcn-svelte/assets/6997343/60d78ea3-ce4b-49e6-9fcc-5eb230d0057e)

### Reproduction

N/A

### System Info

```bash
N/A
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Not sure how `border-color` is a cryptic style. It's applied to the CSS configuration for you.
