### ISSUE TITLE
Resizable abstraction leaks when importing type PaneAPI 

### ISSUE THREAD

**Issue by tero-kiituri** [huntabyte/shadcn-svelte#1091]
### Describe the bug

Resizable namespace does not export type PaneAPI. The type is needed when TypeScript is used. The type can be imported straight from `paneforge` package, but I think this is a leaking abstraction. This isn't a big problem, just a mild annoyance.

### Reproduction

`import * as Resizable from "$lib/components/ui/resizable";` -> No type PaneAPI.

`import { type PaneAPI } from "paneforge";` -> All ok.

### System Info

```bash
-
```

### Severity

annoyance

**Comment by huntabyte** [comment]
The only types that exist on any of the `import * as ___` are the component props. `PaneAPI` isn't a component prop. You could technically access it using one of the properties of the pane props type.
