### ISSUE TITLE
Checkbox component is a 'invalid form control'

### ISSUE THREAD

**Issue by trgsv** [huntabyte/shadcn-svelte#110]
### Current Behavior

I have this component inside a form:

`<Checkbox id="terms" name="terms" bind:checked required />`.

I get the following error when trying to submit the form while `checked = false`:
`An invalid form control with name='terms' is not focusable.`

### Expected Behavior

The browser should focus the checkbox and tell the user, that it is required to be checked.

### Steps To Reproduce

Use this component inside a form.

**Comment by huntabyte** [comment]
I will look into this as soon as I can! Thanks for bringing it up!

**Comment by ferntheplant** [comment]
I setup a super minimal example and couldn't recreate the error. However I was seeing an issue where the server side form data for the checkbox was coming through as an empty string instead of a boolean

```typescript
<script lang="ts">
  import Checkbox from "$components/ui/checkbox/Checkbox.svelte";

  let checked: boolean = false
</script>

<form method="POST">
  <label for="checkbox">Check this</label>
  <Checkbox id="checkbox" name="checkbox" bind:checked required={true} />
  <button type="submit">Submit</button>
</form>
```

**Comment by huntabyte** [comment]
I'm going to need a reproduction of the issues so I can confirm it's something within the control of this project.

**Comment by huntabyte** [comment]
Closing this as missing a reproduction! If it happens again, I'd love to hear about it so we can address it!
