### ISSUE TITLE
Web component option

### ISSUE THREAD

**Issue by npetrangelo** [huntabyte/shadcn-svelte#1104]
### Describe the feature

Svelte is able to compile to web components, which play nice with tools like htmx. It would be cool if you could configure this to install the components as web components. Ideally, the CLI could produce a whole vite project with the requested components and bundle them up for an htmx dev to use without needing to dabble in much front end code unless they wished to make edits.

**Comment by huntabyte** [comment]
This would be great in some sort of 3rd party fork or other project that pulls from this as the upstream/source of truth, but we don't have the cycles to maintain such a thing within this repo.
