### ISSUE TITLE
Adding a input otp component

### ISSUE THREAD

**Issue by VerburgtJimmy** [huntabyte/shadcn-svelte#1107]
### Describe the feature

I saw that the react based shadcn/ui (https://ui.shadcn.com/docs/components/input-otp) created a new input otp component. So since I also need this component for my own project i thought I could help out by start creating this component for this library. The component is based on the bits-ui input otp(https://www.bits-ui.com/docs/components/pin-input) component but shares the visuals and functionality of the shadcn/ui input otp component. See photo for example running locally. The full functionality is not done yet and there are some discussions to be had on how to implement some things but a start is always nice

I have already made a basic version in a local environment so if someone can assign me to this feature i can commit the new input otp component for what i have so far so that you guys can correct some things or provide more feedback. This component is highly requested for this package and would be a great addition.

If you need more info please ask.
<img width="898" alt="Screenshot 2024-05-22 at 09 30 55" src="https://github.com/huntabyte/shadcn-svelte/assets/47350871/ee48c65c-667e-48c1-b227-81c28dea1657">

**Comment by victorDigital** [comment]
+1 🤗

**Comment by shyakadavis** [comment]
Related:

- https://github.com/huntabyte/shadcn-svelte/issues/881
- https://github.com/huntabyte/shadcn-svelte/issues/995
- https://github.com/huntabyte/shadcn-svelte/issues/1027

**Comment by VerburgtJimmy** [comment]
Ok so we are not basing it on the bits ui for this one? But we are waiting for the same person who created the input otp wrapper/api for the react version to make a svelte variant.

**Comment by shyakadavis** [comment]
Tbh, I'm not sure.

But, Hunter made a remark that there might be the possibility of making the `Bits-UI` version as good as the `input-otp` one.

>  Pin Input (I think we can make this as good as the input-otp library)

https://github.com/huntabyte/bits-ui/pull/469#issue-2247113476

Guess time will tell the direction this goes in.

**Comment by VerburgtJimmy** [comment]
Ah ok. I looked at the input-opt multiple frameworks branch and it looked already pretty far along for svelte but who knows how much time it will actually be before it is production ready. I will keep an eye open for a any changes and for now I will be using my own created input-otp component based on the react one.

**Comment by shyakadavis** [comment]
@VerburgtJimmy if you're ever up for it, please do share your component. 🙂

**Comment by VerburgtJimmy** [comment]
@huntabyte don't know how far you are with the svelte input-otp implementation but this is what I have and use so far. Still a work in progress but has the same features and foundation as the input-otp package for react.
https://github.com/VerburgtJimmy/svelte-input-otp/tree/main

**Comment by VerburgtJimmy** [comment]
Here is a small demo video

https://github.com/huntabyte/shadcn-svelte/assets/47350871/e64d7e50-7c66-4c08-835e-7abd70ceb61f

**Comment by huntabyte** [comment]
Hey @VerburgtJimmy! Thanks for that! I'll check it out once I get through some of these higher-priority components in the Bits UI rewrite for Svelte 5 first.

**Comment by VerburgtJimmy** [comment]
Sure take all the time you need! I am developing it further and publishing it on npm as a unstyled component. That component can than be used to create the shadcn variant. And thanks for all the hard work you provide for this community👍🏻

**Comment by VerburgtJimmy** [comment]
fyi: just deployed the package. For more info see: https://svelte-input-otp.jimmyverburgt.com/

**Comment by DaniAcu** [comment]
@VerburgtJimmy Awesome job 🚀 ! I was checking the accesibility of your component and I saw some improvements that we can do. I open a PR https://github.com/VerburgtJimmy/svelte-input-otp/pull/2

With this change the copy and paste will work better in mobile, and we wil have a aria-label to set to the control.

Let me know, happy to contribute in any other things 😄

**Comment by kjmj** [comment]
Not to rush anything here, but I'm just curious if the plan is still to add input otp to this awesome library

**Comment by VerburgtJimmy** [comment]
> Hey @VerburgtJimmy! Thanks for that! I'll check it out once I get through some of these higher-priority components in the Bits UI rewrite for Svelte 5 first.

Like mentioned here. The priority for now is on rewriting bits-ui to svelte 5 and then convert this library to svelte 5 as well I guess but @huntabyte can correct me if I am wrong! 

For now I guess the only option is to use a different input-otp package and then add shadcn/ui styles to it or if you are familiar with bits-ui you can check out the pin-input component over there: [https://www.bits-ui.com/docs/components/pin-input](bits-ui)

**Comment by huntabyte** [comment]
Added to @next
