### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by triadmoko** [huntabyte/shadcn-svelte#1109]
### Describe the feature

I really like using Shadcn Svelte, I see there is a date picker feature, but I don't see the time picker feature. Can you create a time picker feature like the one in the following link?

https://flowbite.com/docs/forms/timepicker/

**Comment by ExpertzZ** [comment]
+1

**Comment by huntabyte** [comment]
This would be something that would fall under Bits UI more than shadcn-svelte. https://github.com/huntabyte/bits-ui/issues/282

**Comment by vladceresna** [comment]
Hello, I found it usable: https://github.com/Maliksidk19/shadcn-datetime-picker

**Comment by vladceresna** [comment]
but it is next

**Comment by vladceresna** [comment]
This is project for svelte, which able to stylize and add to shadcn-svelte: https://mskocik.github.io/svelty-picker/properties
![image](https://github.com/user-attachments/assets/ef8773c7-3d17-4ed2-8563-9f95828b7d36)

**Comment by vladceresna** [comment]
I hope can you reopen this issue?)

**Comment by 1bye** [comment]
Here is new package for svelte shadcn time-picker: [Shadcn or Headless Time Picker](https://github.com/1bye/time-picker-svelte)
