### ISSUE TITLE
Basic install breaks tailwind

### ISSUE THREAD

**Issue by stackermans** [huntabyte/shadcn-svelte#1111]
There must be something missing from the docs because after following the instructinons to create a new project none of the tailwind styles work.

Even basic HTML stuff like `<h1>` is broken as you can see below.

Since everyone must be having this issue, I'm missing something basic.

Here's how this is rendered:
```
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
<h1>sdgdfg</h1>
```

<img width="495" alt="Screenshot 2024-05-24 at 6 13 42 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/126448378/a04e0c5b-c56a-4a7b-958f-b663c2781015">

**Comment by shyakadavis** [comment]
> none of the tailwind styles work.

What styles are you referring to here? Do you mean the typography ones? If so, you should know that you are the one to manually apply those.

> Even basic HTML stuff like `<h1>` is broken as you can see below.

I'm lost here. Are you aware that installing tailwind basically resets all native/default styles?

Pardon me if I misunderstood you, but I'm pretty sure there is no issue here. All is as it should be.

**Comment by huntabyte** [comment]
As @shyakadavis said. These are the default tailwind styles. They remove the defaults in favor of ease of customization.
