### ISSUE TITLE
Data Table "On this page" is missing Row Selection

### ISSUE THREAD

**Issue by brucegl** [huntabyte/shadcn-svelte#1118]
### Change Type

Addition

### Proposed Changes

The Data Table "On this page" section is missing the Row Selection index and link to https://www.shadcn-svelte.com/docs/components/data-table#row-selection

**Comment by jonasaurus** [comment]
@brucegl Has this been fixed? I'm seeing Row Selection with an `href="#row-selection"` in “On This Page”.

**Comment by brucegl** [comment]
> @brucegl Has this been fixed? I'm seeing Row Selection with an `href="#row-selection"` in “On This Page”.

Hi @jonasaurus , it looks like it has. Thanks!
