### ISSUE TITLE
TabTrigger submits form

### ISSUE THREAD

**Issue by kevinmac61** [huntabyte/shadcn-svelte#112]
### Current Behavior

I have added the tabs component inside a form which really cleaned up my form and looks awesome. Unfortunately, when I change tabs it automatically submits the form.

### Expected Behavior

 Is there a way to override this behaviour so it waits for the submit button to be hit? Thanks.

### Steps To Reproduce

1. Add the tabs component inside a form with multiple tabs
2. click on various  tabs and see if form submits without Submit button being used

**Comment by huntabyte** [comment]
Hey, @kevinmac61! It's good to see you using the project!

Try passing `type="button"` as a prop to the `TabsTrigger` elements! I don't believe it has a default type on Radix which is why it's just assuming you want to submit the form. That's something we should definitely fix on our end though so I'll take care of it as soon as I can!

**Comment by kevinmac61** [comment]
This sort of works. It no longer submits the form unless I intentionally submit it with the button, but it only submits the info for the currently selected tab. Here is how my triggers look: 
<TabsTrigger type="button" value="location">Location Info</TabsTrigger>
					<TabsTrigger type="button" value="vendors">Vendor Info</TabsTrigger>
					<TabsTrigger type="button" value="baseinfo">Base Info</TabsTrigger>
					<TabsTrigger type="button" value="taxes">Tax Info</TabsTrigger>
					<TabsTrigger type="button" value="description">Description</TabsTrigger>
					<TabsTrigger type="button" value="listed">Date Listed</TabsTrigger>
					<TabsTrigger type="button" value="garage">Garage</TabsTrigger>
					<TabsTrigger type="button" value="features">Features</TabsTrigger>

**Comment by huntabyte** [comment]
I think this is the expected out-of-the-box behavior. The content is removed from the DOM and swapped out when you switch tabs. I'd have to mess around with it but this should be possible with stores or with a hacky input implementation. You could have the real inputs hidden outside of the tabs but within the form and bind the values of the visible tab inputs to those so they are removed when you switch tabs!

**Comment by kevinmac61** [comment]
I used the hidden inputs as you suggested and it solves my problem. Thank you.

**Comment by huntabyte** [comment]
Awesome! You're welcome!
