### ISSUE TITLE
 UI bug for example/card

### ISSUE THREAD

**Issue by hansaskov** [huntabyte/shadcn-svelte#1121]
### Change Type

Cleanup (formatting, typos, etc.)

### Proposed Changes

Under the "Report an issue" card the select element has incorrect styling of the select icon. You can see it in the attached image

![Select-example-ui-issue](https://github.com/huntabyte/shadcn-svelte/assets/70580312/2515636b-4f62-4ad6-a4a3-c747830e2042)

**Comment by huntabyte** [comment]
Closed by #1122
