### ISSUE TITLE
Reopening with reproduction: Data table becomes empty when email column removed #1117

### ISSUE THREAD

**Issue by brucegl** [huntabyte/shadcn-svelte#1126]
### Describe the bug

HI,

I followed the guide in the Data Table section and when I hide the email column then all the rows are removed, and the row selection checkbox is checked.

### Reproduction

I reproduced this code on Stackblitz [here](https://stackblitz.com/edit/github-ihthdo-g2rp5k?file=src%2Froutes%2F%2Bpage.svelte) and I added the fix (i.e. adding the line, `includeHiddenColumns: true`, which is currently commented out)

If you uncomment the line, you can then hide the email column without removing all rows.

### System Info

```bash
Stackblitz
```

### Severity

annoyance

**Comment by huntabyte** [comment]
So is this just an issue with the guide? If so, PRs welcome 😃

**Comment by brucegl** [comment]
Ok, I'll do that now :-)

**Comment by brucegl** [comment]
submitted PR https://github.com/huntabyte/shadcn-svelte/pull/1133 to close this
