### ISSUE TITLE
Adding Lightswitch to the components list

### ISSUE THREAD

**Issue by benquan** [huntabyte/shadcn-svelte#113]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I dug out the light switch used on the main shadcn-svelte page  [light-switch](https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/components/docs/light-switch) , I copied it to my app and it works like a charm. Why is it not added to the components list?

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

[light-switch](https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/components/docs/light-switch)

**Comment by huntabyte** [comment]
The component will be replaced with a dropdown menu soon, and I kinda just threw that lightswitch together by pulling a lot of it from SkeletonUI. The functionality that the lightswitch provides is more of a utility. The code is open if you want to copy it from the docs but not sure about it being a component in and of itself.
