### ISSUE TITLE
Checkbox doesn't include hidden input

### ISSUE THREAD

**Issue by gtm-nayan** [huntabyte/shadcn-svelte#1134]
### Describe the bug

The checkbox component only shows the indicator button and doesn't render the hidden input which means the checkbox doesn't show up in form submissions unless you manually bind the value and render it in another hidden checkbox

### Reproduction

https://stackblitz.com/edit/github-ofar7n?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Bpage.server.ts

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.2 
    bits-ui: ^0.18.2 => 0.18.2 
    cmdk-sv: ^0.0.13 => 0.0.13 
    formsnap: ^0.5.0 => 0.5.0 
    lucide-svelte: ^0.303.0 => 0.303.0 
    mode-watcher: ^0.2.1 => 0.2.1 
    svelte: ^4.2.9 => 4.2.9 
    svelte-sonner: ^0.3.18 => 0.3.18 
    sveltekit-superforms: ^2.5.0 => 2.5.0 
    vaul-svelte: ^0.2.4 => 0.2.4
```

### Severity

annoyance

**Comment by dyc3** [comment]
I'd like to contribute a fix for this. Should I make a PR for this repo or `bits-ui`?

**Comment by huntabyte** [comment]
Fixed in @next
