### ISSUE TITLE
Dialog and Sheet not scrollable

### ISSUE THREAD

**Issue by hvuhsg** [huntabyte/shadcn-svelte#1135]
### Describe the bug

When the dialog or sheet content are exceeding the screen size the content can't be scrolled

### Reproduction

![Screenshot from 2024-06-10 17-43-59](https://github.com/huntabyte/shadcn-svelte/assets/34660046/f6689c0a-b49b-49b5-8db2-4d044a9441e6)

### System Info

```bash
Firefox bu I don't think its a browser related issue.
```

### Severity

annoyance

**Comment by hvuhsg** [comment]
Adding the `preventScroll={false}` to `Dialog.Root`  only make i so the the page under the dialog overlay is scrollable not the dialog itself

**Comment by fromaline** [comment]
Hey! I'm having the same issue. I expected the `DialogPrimitive.Content` (or even better the `Dialog.Description`) to be scrollable by default. To me, it seems like an intuitive thing to have out of the box. What do you think?

**Comment by MentalGear** [comment]
I second that it would be inuitive that Dialog/Modals should be scrollable by default! Maybe wrap inside scroll area (by default)?
(What would be the benfict from not having them scrollable?)
