### ISSUE TITLE
Add hide/unhide functionality to <Input/> component for password fields

### ISSUE THREAD

**Issue by gzuuus** [huntabyte/shadcn-svelte#1139]
### Describe the feature

I'm requesting a new feature to be added to the `<Input/>` component to allow users to hide/unhide password fields. This would enable users to mask or unmask the passwords for inputs with type="password". It would be beneficial to provide an option to toggle the visibility of the password. This is a common feature in many password input fields, allowing users to verify their password entry without compromising security.

Thanks before hand!

**Comment by seb-goodman** [comment]
Have you come across [this](https://www.bits-ui.com/docs/components/toggle) bits-ui example, to use in the meantime?

**Comment by gzuuus** [comment]
Didn't saw it, thanks!

**Comment by huntabyte** [comment]
The problem with this is that it conflicts with some browsers that add this feature by default
