### ISSUE TITLE
[Slider] vertical orientation's styling is broken

### ISSUE THREAD

**Issue by mnpqraven** [huntabyte/shadcn-svelte#1147]
### Describe the bug

if we set `orientation='vertical'` to Slider component then only the direction is vertical, the draggable viewport is still the small height from the default horizontal direction
![image](https://github.com/huntabyte/shadcn-svelte/assets/8957788/5d3d88da-d51d-4281-9197-a9d4c84aee39)

pictured is the vertical slider inside a square div
```
    <TooltipContent class="h-48 w-48">
      <Slider max={100} step={1} orientation="vertical" />
    </TooltipContent>
```

### Reproduction

https://stackblitz.com/edit/shadcn-svelte-select-label-jacxfi?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
from repro sandbox
```

### Severity

annoyance

**Comment by ohthepain** [comment]
I am getting the same thing. I would give it a bit more severity.

**Comment by huntabyte** [comment]
There are no vertical styles provided out of the box for this component. This is something we leave up to you to add.
