### ISSUE TITLE
[Separator] Vertical separator not rendering

### ISSUE THREAD

**Issue by TheGroobi** [huntabyte/shadcn-svelte#1149]
### Describe the bug

Whenever the separator element has the orientation of "vertical" it sets a tailwind class of h-full which for whatever reason does not render the element at all (it has 1x0px  inside the dev tools).

What i found is that you can just remove the class completely from the SeparatorPrimitive.Root and it works fine, or add "min-h-full"

```svelte
class={cn(
	"shrink-0 bg-border",
	orientation === "horizontal" ? "h-[1px] w-full" : "min-h-full w-[1px]",
	className
)}
```

or 
```svelte
class={cn(
	"shrink-0 bg-border",
	orientation === "horizontal" ? "h-[1px] w-full" : "w-[1px]",
	className
)}
```

Both work as i tested on Brave and firefox.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/github-fzhplc?file=src%2Froutes%2F%2Bpage.svelte)

### System Info

```bash
not neccesseray
```

### Severity

annoyance

**Comment by Stadly** [comment]
I ran into the same problem. It happens when the parent container doesn't have a defined height. `min-h-full` seems like a good solution.

https://chatgpt.com/share/3e6600ef-fe9e-4260-9a8e-2d273c5a8975

**Comment by huntabyte** [comment]
What @Stadly said!

**Comment by Stadly** [comment]
Should I provide a PR for this, @huntabyte?
