### ISSUE TITLE
Docs: List all components, even if not done or "soon"

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/shadcn-svelte#115]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently the docs list 1.) supported components, and 2.) "soon".

If the goal is feature parity, it'd be helpful if the sidebar listed all components, even if they're not done or "soon".
It'd give readers clarity of how far along the lib is, the roadmap and vision for this lib, and where they could contribute.

I found myself comparing `shadcn-svelte` vs `shadcn` sidebars in detail to get a sense of how far along it is.

### What type of pull request would this be?

Docs

**Comment by huntabyte** [comment]
I had it like this at first but it felt odd having so many disabled links on the sidebar. I've been working on the menu/dropdown/popper builders for MeltUI which will be replacing Radix Svelte, and it's getting close to being released which will give shadcn-svelte almost complete feature parity.

**Comment by rajaiswal** [comment]
Hi @huntabyte ! This is a great library and really appreciate all your efforts here! You metioned working on the dropdown component, are you aiming to release it anytime soon as part of shadcn-svelte?

**Comment by huntabyte** [comment]
Hi @rajaiswal - yes, I have been actively working on MeltUI which will be the backbone for this and allow us to have a lot more components.

I’m waiting until we get the APIs more stable to move this over, as I don’t want to keep having to deal with breaking changes.

We’re getting close & I can assure you many hours of my time have been invested into it so I can get this project where I want it to be for the community!
