### ISSUE TITLE
CLI wont install

### ISSUE THREAD

**Issue by NafunaAfrica** [huntabyte/shadcn-svelte#1150]
### Describe the bug

PS C:\Users\Nqo Mlilo\OneDrive\Documents\APP DEV\nafunaxredo> npx shadcn-svelte@latest init
npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\Nqo Mlilo\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\Nqo Mlilo\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: C:\Users\Nqo Mlilo\AppData\Local\npm-cache\_logs\2024-06-17T17_12_52_537Z-debug-0.log

I get this when I try run the cli

### Reproduction

I followed steps on the sveltekit guide and got this

### System Info

```bash
windows, amd ryzen 7, 16 gb ram,
```

### Severity

blocking all usage of shadcn-svelte

**Comment by SureshPradhana** [comment]
Try running `npm cache clean --force`. It seems like npm can't find the directories.

**Comment by huntabyte** [comment]
I'm not able to reproduce this. Are you still having this issue?

**Comment by AdrianGonz97** [comment]
This looks to be more of a systems issue than an issue with out CLI. Without more info, there's not much we can do. Therefore, closing.
