### ISSUE TITLE
PandaCSS support?

### ISSUE THREAD

**Issue by lolmaus** [huntabyte/shadcn-svelte#1152]
### Describe the feature

Hi!

I would like to have an equivalent of `shadcn-svelte` driven by [Panda CSS](https://panda-css.com) rather than Tailwind.

Can `shadcn-svelte` offer a choice between Tailwind and Panda CSS?

I would like to contribute, but I will not be able to leverage the whole endeavor alone.

**Comment by huntabyte** [comment]
Hey there, I think a fork or similar would be a better solution rather than adding that into this project.
