### ISSUE TITLE
Option to use form fields without <form>, SuperForms and Formsnap

### ISSUE THREAD

**Issue by lolmaus** [huntabyte/shadcn-svelte#1160]
### Describe the feature

Hi!

Sometimes, you need a form field for page layout, without all the feavy lifting provided by `<form>`, SuperForms and Formsnap.

It is quite tedious to vivisect existing `shadcn-svelte` form components in order to strip them off unwanted complexity. I wish I were able to either generate separate simple form fields or opt out of SuperForms and Formsnap when generating existing form components.

**Comment by huntabyte** [comment]
That is too simple of a component that could be implemented in user-land. Form Fields in the context of this project and Formsnap have a different meaning than just "laying out the field" and I don't want that to be confused.
