### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by LargatSeif** [huntabyte/shadcn-svelte#1165]
### Describe the feature

A full calendar block with Upcoming events, categories and a calendar view with options  Month, Week, Day and List.

Example
https://example.crm.refine.dev/calendar

**Comment by huntabyte** [comment]
As mentioned in the issue template. If the feature isn't in the original shadcn/ui it won't be added here.

**Comment by LargatSeif** [comment]
> As mentioned in the issue template. If the feature isn't in the original shadcn/ui it won't be added here.

sorry didn't pay attention.
