### ISSUE TITLE
Add Icon Page

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#1167]
### Change Type

Addition

### Proposed Changes

Searching the docs, there's no mention of "icons" or even which icon set is used. It would be very helpful to have a short page that mentions the icon set and links to the awesome icon search on https://lucide.dev/.

**Comment by huntabyte** [comment]
Agree with @keisanng on this one! A whole page seems excessive, but could add something to the FAQ with a link to the icon projects used.

**Comment by MentalGear** [comment]
As long as it's discoverable by search, it seems fine!

**Comment by huntabyte** [comment]
Going to close this as not planned at the moment. If someone wants to submit a PR to add this to the FAQ I'll happily merge it but trying to cleanup/focus issues
