### ISSUE TITLE
Checkbox docs improvement

### ISSUE THREAD

**Issue by manicar2093** [huntabyte/shadcn-svelte#1170]
### Change Type

Addition

### Proposed Changes

Hi!

I had a problem with this Checkbox component. The issue #948 helped me, but I was wondering if there is the chance to add this explicitly in docs

I know, I should've seen it reading the implementation, but why not be explicit showing the solution? 😃 

By the way, thanks for your awesome work!!! you are amaizing

**Comment by huntabyte** [comment]
Absolutely! Thank you!

**Comment by manicar2093** [comment]
> Absolutely! Thank you! Is this something you want to tackle?

Sure! I can do it! 😃

**Comment by manicar2093** [comment]
@huntabyte could you assign me this issue? 😃 I just saw how to contribute and I'm ready 😃

**Comment by manicar2093** [comment]
Hi! I've created the PR! I hope is well done!

**Comment by huntabyte** [comment]
This is no longer necessary in shadcn-svelte@next! Just adding the `name` prop is sufficient to handle the rendering of a hidden input!
