### ISSUE TITLE
Adding "command" component fails on fresh install

### ISSUE THREAD

**Issue by jrsalazar-dev** [huntabyte/shadcn-svelte#1172]
### Describe the bug

From a 100% fresh install, first time trying both sveltekit and shadcn-svelte. 

All it takes is (answering yes to everything):
```bash
npm create svelte@latest forward
npx @svelte-add/tailwindcss@latest
npx shadcn-svelte@latest init
npx shadcn-svelte@latest add command
```
The error I get is:
<img width="1197" alt="Screenshot 2024-07-04 at 22 20 30" src="https://github.com/huntabyte/shadcn-svelte/assets/6126883/970c889e-530f-4602-a740-87304d0134cc">

It hints at a missing peer-dependency which is very odd since I have done nothing else but install the base packages.

It installs fine if I use `bunx` instead of `npx` and install the packages with bun instead (because bun ignores the peer-dep error).

Sorry I can't provide a full reproduction.

### Reproduction

Steps to reproduce
```bash
npm create svelte@latest forward
npx @svelte-add/tailwindcss@latest
npx shadcn-svelte@latest init
npx shadcn-svelte@latest add command
```

### System Info

```bash
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 181.14 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - ~/.node_modules/bin/yarn
    npm: 8.4.0 - ~/.node_modules/bin/npm
    pnpm: 6.11.0 - ~/.node_modules/bin/pnpm
    bun: 1.0.12 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.62
    Safari: 17.4.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.18
    bits-ui: ^0.21.11 => 0.21.11
    cmdk-sv: ^0.0.17 => 0.0.17
    lucide-svelte: ^0.399.0 => 0.399.0
    svelte: ^5.0.0-next.1 => 5.0.0-next.174
```

### Severity

blocking all usage of shadcn-svelte

**Comment by alephpt** [comment]
I have the same problem, but it's with the bits-ui, next and svelte versions. "Fix upstream" it tells me

**Comment by AdrianGonz97** [comment]
Resolved by https://github.com/huntabyte/cmdk-sv/pull/88
