### ISSUE TITLE
Switch style from default to new york

### ISSUE THREAD

**Issue by 0x090909** [huntabyte/shadcn-svelte#1179]
### Describe the feature

Hello I created a new project a while and have been working so far, but I realized the default style is not as good as new york. 

Why is it so hard to migrate to the new configuration? 

I changed my componets.json, with the new style and rebuilt the project but the style is still the default.

**Comment by huntabyte** [comment]
You need to re-add all of the components. The CLI looks at the components.json when adding a component, it doesn't do anything during build or dev.

**Comment by 0x090909** [comment]
Thanks!
