### ISSUE TITLE
npx shadcn-svelte init: Error resolving dependencies with Svelte 4

### ISSUE THREAD

**Issue by faulander** [huntabyte/shadcn-svelte#118]
### Current Behavior

Error: Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority clsx tailwind-merge lucide-svelte
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.0.1
npm ERR! Found: svelte@4.0.0
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.49.0" from lucide-svelte@0.248.0
npm ERR! node_modules/lucide-svelte
npm ERR!   lucide-svelte@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

### Expected Behavior

should install i guess?

### Steps To Reproduce

just run the commands as given in the tutorial to install it here: https://www.shadcn-svelte.com/docs/installation

**Comment by huntabyte** [comment]
Hey there! This seems to be an issue with Lucide Svelte, as it only supports Svelte 3 at the moment. You can still use Lucide icons if you use something like [unplugin-icons](https://github.com/antfu/unplugin-icons).

**Comment by steddyman** [comment]
Is it possible to install this library without the Lucide Icons?

**Comment by mastmagan007** [comment]
Just downgraded sveltkit ver to 3.49.0 and it worked.

**Comment by huntabyte** [comment]
This issue will be resolved once [this PR](https://github.com/lucide-icons/lucide/pull/1388) is merged with Lucide Svelte

**Comment by huntabyte** [comment]
Closing this to consolidate the dependency issues in a single issue #125
