### ISSUE TITLE
Migrate from Lucide Icons to Unplugin Icons

### ISSUE THREAD

**Issue by huntabyte** [huntabyte/shadcn-svelte#119]
Right now we're using Lucide Icons as a dependency and as part of the 'install guide' for using the components. I think a better approach might be to use [unplugin-icons](https://github.com/antfu/unplugin-icons). You can still use the Lucide Icons, but also just about any other icon library you could think of.

My time is limited at the moment, but if someone wants to contribute by making this happen (keeping the same icons just with unplugin-icons), it'd be greatly appreciated. Otherwise, I will get to it as soon as I can!

This is in regards to issue #118

**Comment by faulander** [comment]
would that mean that it's only changing the imports in the components to:
import IconAccessibility from '~icons/lucide/accessibility'
if that's all that is todo (except documentation and scripts) i can probably submit a PR.

**Comment by huntabyte** [comment]
Now that I think about it we'd also have to update the Vite config to import / add unplugin-icons with the `init` script as well. This would open up the opportunity for people to use whatever icons they wanted to very easily though. What are your thoughts on this @AdrianGonz97 ?

**Comment by mastmagan007** [comment]
> Now that I think about it we'd also have to update the Vite config to import / add unplugin-icons with the `init` script as well. This would open up the opportunity for people to use whatever icons they wanted to very easily though. What are your thoughts on this @AdrianGonz97 ?

Flowbite is best, forget it, its just a mess.

**Comment by tika** [comment]
Surely this defeats the purpose of having a unified styling kit? Being able to use ANY icon possible means inconsistency across apps (if multiple icon sets are used).

Of course, this solution would remove any possibility of an icon that is wanted but absent in the lucide icon set - but I think this would just promote UI mess.

**Comment by huntabyte** [comment]
You might be right about that @tika - I guess keeping the components with Lucide by default but giving creative freedom to the consumer should they choose to swap them out.

I'd be interested to hear thoughts from others as well!

**Comment by huntabyte** [comment]
Closing as not planned.
