### ISSUE TITLE
Tab component missing defaultValue prop

### ISSUE THREAD

**Issue by pricetula** [huntabyte/shadcn-svelte#1190]
### Describe the feature

Tab.Root component seems to have a missing **defaultValue** prop, which exists in [shadcn/ui](https://ui.shadcn.com/docs/components/tabs)
<img width="839" alt="Screenshot 2024-07-16 at 09 08 42" src="https://github.com/user-attachments/assets/77ca6dfe-c701-42ab-93fb-7613044617a1">

**Comment by huntabyte** [comment]
We don't have a `defaultValue`, just `value`
