### ISSUE TITLE
Broken links due to directory renaming from apps/www/** to sites/docs/**

### ISSUE THREAD

**Issue by GeoGeorgeous** [huntabyte/shadcn-svelte#1204]
### Change Type

Correction

### Proposed Changes

Hey! 

I've noticed that the directory `apps/www/**` was recently renamed to `sites/docs/**`, which has resulted in broken links across the site.

This affects the _Component Source_ links on component pages in `/docs`, as well as the _View Code_ links for examples.

For instance:

1. The _Component Source_ button for the Accordion component still leads to 
https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/registry/default/ui/accordion
instead of the correct
https://github.com/huntabyte/shadcn-svelte/tree/main/sites/docs/src/lib/registry/default/ui/accordion

2. The Tasks example _View Code_ link still points to 
https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/routes/(app)/examples/tasks
instead of the correct 
https://github.com/huntabyte/shadcn-svelte/tree/main/sites/docs/src/routes/(app)/examples/tasks

Hope it helps

**Comment by shyakadavis** [comment]
The correct previews are now live. I believe this can be closed.
