### ISSUE TITLE
Add Time-line (Vertical, Horizontal) 

### ISSUE THREAD

**Issue by FerielNot1** [huntabyte/shadcn-svelte#1205]
### Describe the feature

I am asking if you could implement some sort of component to display timeline similar to the separator with texts around it and maybe somehow to let it be more customizable.
Thanks

**Comment by huntabyte** [comment]
Hey there, if it isn't in the original shadcn/ui, it won't be added here. Thanks for understanding!

**Comment by marijuana-softwares-1** [comment]
something like the 
![Screenshot 2024-08-04 at 23-36-18 Formsnap   Superforms - shadcn-svelte](https://github.com/user-attachments/assets/b1c89d93-5e80-42e9-aacf-5c06f480941e)
