### ISSUE TITLE
Data Table - a combination of Pagination and Sort removes the sort property from the props object

### ISSUE THREAD

**Issue by robots4life** [huntabyte/shadcn-svelte#1209]
### Describe the bug

In a simple Data Table, when having pagination and sort enabled the the  `props`  object is missing the `sort` property, hence a condition to check for the `sort` property with the aim to show `ArrowUp` or `ArrowDowm` icons does not work.

Not using Shadcn-Svelte does not have the issue as can been see in this REPL.
[https://svelte.dev/repl/9b98604e674b482fa50ed1b8ab5fd1e2?version=4.2.18](https://svelte.dev/repl/9b98604e674b482fa50ed1b8ab5fd1e2?version=4.2.18)

### Reproduction

[https://github.com/robots4life/shadcn-svelte-data-table/tree/main](https://github.com/robots4life/shadcn-svelte-data-table/tree/main)

### System Info

```bash
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 24.07 GB / 31.23 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.14.1 - ~/.local/share/pnpm/pnpm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.182
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Closed in `shadcn-svelte@next` using TanStack Table.
