### ISSUE TITLE
Radix Svelte has paused development

### ISSUE THREAD

**Issue by JohnnyJTH** [huntabyte/shadcn-svelte#121]
Just wondering if this impacts this project...
https://github.com/radix-svelte/radix-svelte/blob/develop/ANNOUNCEMENT.md

**Comment by AdrianGonz97** [comment]
Hey @JohnnyJTH, please see this comment regarding `radix-svelte`: https://github.com/huntabyte/shadcn-svelte/issues/95#issuecomment-1595350269

**Comment by JohnnyJTH** [comment]
Oh great! Thank you.
