### ISSUE TITLE
#1203 Breaks paths to component source

### ISSUE THREAD

**Issue by ieedan** [huntabyte/shadcn-svelte#1210]
### Change Type

Correction

### Proposed Changes

After #1203 component source paths are broken.

For example in the [Command Docs](https://www.shadcn-svelte.com/docs/components/command) component source link (https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/registry/default/ui/command) is not longer valid and returns 404 after the rename.

**Comment by ieedan** [comment]
Corrected paths

```
# old
https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/registry/default/ui/
                                                     ^^^^^^^^
# new
https://github.com/huntabyte/shadcn-svelte/tree/main/sites/docs/src/lib/registry/default/ui/
                                                     ^^^^^^^^^^                       
```

**Comment by ieedan** [comment]
Maybe a deployment went wrong or something doing through the source it looks like the paths were corrected already

**Comment by ieedan** [comment]
![image](https://github.com/user-attachments/assets/330c23b2-09c9-43c1-887b-30a38e463283)

**Comment by shyakadavis** [comment]
Hello;

Related: #1204

**Comment by ieedan** [comment]
Not sure how I didn't see this I could've sworn I looked
