### ISSUE TITLE
Wrong Home and Line Chart icons in Blocks Dashboards

### ISSUE THREAD

**Issue by asdromundo** [huntabyte/shadcn-svelte#1212]
### Change Type

Cleanup (formatting, typos, etc.)

### Proposed Changes

The [Block code](https://shadcn-svelte.com/blocks) for some of the dashboards contain icons mislabeled (or not longer called that in lucide-svelte).

They can be updated their current name:

- LineChart -> [ChartLine](https://lucide.dev/icons/chart-line)
- Home -> [House](https://lucide.dev/icons/house)

![Captura de pantalla 2024-07-25 040408](https://github.com/user-attachments/assets/ff36e694-d0b0-4a10-be04-19a75f23f82b)

![image](https://github.com/user-attachments/assets/4b72216b-0f55-4808-bd4a-a50b408ab3f9)

ToDo:
Update House and ChartLine icons in dashboards:

- [ ]  [Dashboard 2](https://shadcn-svelte.com/blocks#dashboard-02)
- [ ]  [Dashboard 5](https://shadcn-svelte.com/blocks#dashboard-05)
- [ ]  [Dashboard 6](https://shadcn-svelte.com/blocks#dashboard-06)

**Comment by huntabyte** [comment]
Willing to accept a PR to update these in the project!
