### ISSUE TITLE
When using TypeScript, path generated still use JavaScript

### ISSUE THREAD

**Issue by Serpentarius13** [huntabyte/shadcn-svelte#1224]
### Describe the bug

Now, even with typescript: true in my components.json added components use .js extensions to reference $utils/ folder

### Reproduction

Enable Typescript and add any component

### System Info

```bash
...
```

### Severity

annoyance

**Comment by ieedan** [comment]
I believe this is just how Svelte works if you are referring to paths such as `import { cn } from "$lib/utils.js";`. You are still referring to a typescript file its just in its compiled javascript form. If this is a problem you could also use a path without the extension such as `$lib/utils`.

**Comment by AdrianGonz97** [comment]
As mentioned above, path imports that end with `.js` is expected, even when using typescript. I talk a little more about it here: https://github.com/huntabyte/shadcn-svelte/issues/951#issuecomment-2028194410
