### ISSUE TITLE
Cannot programmatically change values for things like tabs or dialogs

### ISSUE THREAD

**Issue by tyfiero** [huntabyte/shadcn-svelte#1236]
### Describe the bug

I cannot for the life of me figure out how to change a tab programmatically, the trigger must be clicked to change it. Is there any way to do this? I know melt UI lets us do this, I really need to figure this out.

### Reproduction

Assign the value to a svelte store. change the value. nothing happens

### System Info

```bash
macos
```

### Severity

annoyance

**Comment by shyakadavis** [comment]
Hey, @tyfiero 

You can `bind` to the `value` prop on your Root.

```svelte
<script lang="ts">
  import * as Tabs from "$lib/components/ui/tabs";
  import { writable } from 'svelte/store';
  import { Button } from "$lib/components/ui/button/index.js";

  const value = writable("account")
</script>
 
<Button on:click={() => value.set("account")}>Button</Button>

<Tabs.Root bind:value={$value} class="w-[400px]">
  <Tabs.List>
    <Tabs.Trigger value="account">Account</Tabs.Trigger>
    <Tabs.Trigger value="password">Password</Tabs.Trigger>
  </Tabs.List>
  <Tabs.Content value="account">
    Make changes to your account here.
  </Tabs.Content>
  <Tabs.Content value="password">Change your password here.</Tabs.Content>
</Tabs.Root>
```

**Comment by tyfiero** [comment]
Oh duh. I just need to bind the value 🤦🏻‍♂️

Thanks @shyakadavis !!!!
