### ISSUE TITLE
<Input type="file"> does not support bind:files

### ISSUE THREAD

**Issue by gwax** [huntabyte/shadcn-svelte#1240]
### Describe the bug

When using `<Input type="file" ... />` it is not possible to bind a superforms fileProxy using: `<Input type="file" bind:files={$myFileProxy} />` as is recommended by the superforms documentation for forms.

### Reproduction

Typescript error:
![image](https://github.com/user-attachments/assets/9b3d85bf-52a0-4c7d-a2ca-51a1cfdbd770)
![image](https://github.com/user-attachments/assets/54dbe482-926d-492c-839c-552956636c26)

And using the input does not update the value of the fileProxy store.

### System Info

```bash
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 1.05 GB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.12.0/bin/npm
    pnpm: 9.7.1 - ~/.nvm/versions/node/v20.12.0/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.5
  npmPackages:
    @sveltejs/kit: ^2.5.18 => 2.5.18 
    bits-ui: ^0.21.13 => 0.21.13 
    formsnap: ^1.0.1 => 1.0.1 
    lucide-svelte: ^0.408.0 => 0.408.0 
    svelte: ^4.2.18 => 4.2.18 
    sveltekit-superforms: ^2.16.1 => 2.16.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
You need to create a dedicated custom `FileInput` or similar until Svelte 5 where this problem doesn't exist anymore.
