### ISSUE TITLE
Tabs Like in the showcase website

### ISSUE THREAD

**Issue by 0x090909** [huntabyte/shadcn-svelte#1244]
### Prerequisites

- [X] This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.

### Describe the feature

![Screen Recording 2024-08-18 at 16 51 36](https://github.com/user-attachments/assets/82335310-c220-429e-a4ad-b265530e972a)

**Comment by Scooter1337** [comment]
What part of this does not exist yet? The https://www.shadcn-svelte.com/examples implementation is the exact same, no?

**Comment by huntabyte** [comment]
as @Scooter1337 mentioned, the example is there.

**Comment by huntabyte** [comment]
An example is a form of documentation. We don't intend on spoon feeding every possible variation or way of using every component. We believe developers can figure things out by exploring the examples and code base.
