### ISSUE TITLE
resizable component export typo

### ISSUE THREAD

**Issue by developedbyant** [huntabyte/shadcn-svelte#1252]
### Describe the bug

To match shadcn, the component resizable `src/lib/components/ui/resizable/index.ts` needs to export name.
Maybe it was typo writing (panel)
```ts
export {
	PaneGroup,
	Pane,
	Handle,
	//
	PaneGroup as ResizablePanelGroup,
	Pane as ResizablePanel,
	Handle as ResizableHandle,
};
```
Not
```ts
export {
	PaneGroup,
	Pane,
	Handle,
	//
	PaneGroup as ResizablePaneGroup,
	Pane as ResizablePane,
	Handle as ResizableHandle,
};
```

### Reproduction

Shadcn for react import items like this
```ts
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
```
We need to do the same
```ts
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "$lib/components/ui/resizable";
```

### System Info

```bash
macbook
```

### Severity

annoyance

**Comment by developedbyant** [comment]
Same thing for component (Carousel), there is not export as, only Root items are being exported

**Comment by huntabyte** [comment]
We call them `Pane` as that is what `paneforge` uses.
