### ISSUE TITLE
Menubar on Mobile📱 doesn't work correctly when Switching between Menus.

### ISSUE THREAD

**Issue by memestageceo** [huntabyte/shadcn-svelte#1268]
### Describe the bug

https://github.com/user-attachments/assets/97439505-087c-4912-a576-6591137f5d6c

I think this'll show it clearly. When a menu is already open & I click on the next menu, both of them just close.

The recording is from the official shadcn-svelte website.

I tested the corresponding shadcn react component, and that works fine. 

### Reproduction

Open the URL on a mobile phone and then trigger File open, then click on any other trigger.

https://shadcn-svelte.com/docs/components/menubar

### System Info

```bash
MSEdge, Chrome.
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
Fixed in `shadcn-svelte@next` / `bits-ui@next`
