### ISSUE TITLE
Uncaught TypeError in Slider component

### ISSUE THREAD

**Issue by trgsv** [huntabyte/shadcn-svelte#127]
### Current Behavior

Error occurs in several browsers.

### Expected Behavior

.

### Steps To Reproduce

1. Go to: https://www.shadcn-svelte.com/docs/components/slider
2. Open browser console
3. Move slider

**Comment by AdrianGonz97** [comment]
Strange, it seems like this bug came back #5

**Comment by AdrianGonz97** [comment]
It seems to be a Radix bug https://github.com/huntabyte/shadcn-svelte/issues/5#issuecomment-1565864812. As we'll be switching over to MeltUI soon, I expect this _may_ go away. We can keep this issue open in the mean time.

**Comment by trgsv** [comment]
MeltUI sounds very good. Looking forward to that!

**Comment by huntabyte** [comment]
Closed by #150
