### ISSUE TITLE
Combobox autocomplete breaks in Svelte 5.

### ISSUE THREAD

**Issue by memestageceo** [huntabyte/shadcn-svelte#1270]
### Describe the bug

[Shadcn-svelte Combobox](https://www.shadcn-svelte.com/docs/components/combobox) works in Svelte 4, but doesn't in Svelte 5. Tried with both, the code is same in both, the only different is svelte version.

I've created a repo for the same. The svelte 4 works well, svelte 5 fails - keeps adding new items when trying to filter lists

![image](https://github.com/user-attachments/assets/31486752-4a3a-498f-8a67-f567408cbfd2)

### Reproduction

Here's a repo. The svelte 4 version works. Svelte 5 fails - with both svelte 4 and svelte 5 syntax.

https://github.com/memestageceo/combobox-4v5.git

### Logs

```bash
no messages in console.
```

### System Info

```bash
Windows 11. Browsers: MSEdge, Chrome, Zen
```

### Severity

blocking an upgrade

**Comment by Egnus** [comment]
This seems to be happening directly on the dependency used for the combobox `cmdk-sv`
from this link: https://github.com/huntabyte/cmdk-sv/issues/92
you can find a workaround:
```svelte
<script>
let search = $state('')
</script>

<Command.Root>
  <Command.Input placeholder="Search framework..." bind:value={search} />
  {#key search}
    <Command.Group>
      {#each frameworks as framework}
        <Command.Item>
        ...
        </Command.Item>
      {/each}
    </Command.Group>
  {/key}
</Command.Root>
```

**Comment by huntabyte** [comment]
We're not addressing Svelte 5 issues until it is out of RC. We cannot control things that Svelte 5 breaks unfortunately.
