### ISSUE TITLE
Bad import line in carousel-next.svelte and carousel-previous.svelte

### ISSUE THREAD

**Issue by Lucho-git** [huntabyte/shadcn-svelte#1279]
### Describe the bug

	import {
		Button,
		type Props,
		type buttonVariants,
	} from "$lib/registry/default/ui/button/index.js";

As a manual installer of shadcn-svelte, I downloaded all the carousel files, however these file paths were erroring as the recommended shadcn-svelte setup is "$lib/components/ui/button/index.js"

Changing both of these files had it working.

### Reproduction

<--carousel-previous.svelte-->

<script lang="ts">
	import ArrowLeft from "lucide-svelte/icons/arrow-left";
	import type { VariantProps } from "tailwind-variants";
	import { getEmblaContext } from "./context.js";
	import { cn } from "$lib/utils.js";
	import {
		Button,
		type Props,
		type buttonVariants,
	} from "$lib/registry/default/ui/button/index.js";

	type $$Props = Props;

	let className: $$Props["class"] = undefined;
	export { className as class };
	export let variant: VariantProps<typeof buttonVariants>["variant"] = "outline";
	export let size: VariantProps<typeof buttonVariants>["size"] = "icon";

	const { orientation, canScrollPrev, scrollPrev, handleKeyDown } =
		getEmblaContext("<Carousel.Previous/>");
</script>

<Button
	{variant}
	{size}
	class={cn(
		"absolute h-8 w-8 touch-manipulation rounded-full",
		$orientation === "horizontal"
			? "-left-12 top-1/2 -translate-y-1/2"
			: "-top-12 left-1/2 -translate-x-1/2 rotate-90",
		className
	)}
	disabled={!$canScrollPrev}
	on:click={scrollPrev}
	on:keydown={handleKeyDown}
	{...$$restProps}
>
	<ArrowLeft class="h-4 w-4" />
	<span class="sr-only">Previous slide</span>
</Button>

<--carousel-next.svelte-->

<script lang="ts">
	import ArrowRight from "lucide-svelte/icons/arrow-right";
	import type { VariantProps } from "tailwind-variants";
	import { getEmblaContext } from "./context.js";
	import { cn } from "$lib/utils.js";
	import {
		Button,
		type Props,
		type buttonVariants,
	} from "$lib/registry/default/ui/button/index.js";

	type $$Props = Props;

	let className: $$Props["class"] = undefined;
	export { className as class };
	export let variant: VariantProps<typeof buttonVariants>["variant"] = "outline";
	export let size: VariantProps<typeof buttonVariants>["size"] = "icon";
	const { orientation, canScrollNext, scrollNext, handleKeyDown } =
		getEmblaContext("<Carousel.Next/>");
</script>

<Button
	{variant}
	{size}
	class={cn(
		"absolute h-8 w-8 touch-manipulation rounded-full",
		$orientation === "horizontal"
			? "-right-12 top-1/2 -translate-y-1/2"
			: "-bottom-12 left-1/2 -translate-x-1/2 rotate-90",
		className
	)}
	disabled={!$canScrollNext}
	on:click={scrollNext}
	on:keydown={handleKeyDown}
	{...$$restProps}
>
	<ArrowRight class="h-4 w-4" />
	<span class="sr-only">Next slide</span>
</Button>

### System Info

```bash
Windows 11
```

### Severity

annoyance

**Comment by huntabyte** [comment]
These are used internally since we have multiple styles; there's no great way for us to replace them across the board. We do so when you use the CLI, but for manual copy and paste you'll need to modify the paths yourself.
