### ISSUE TITLE
Can't bind a checkbox to a group

### ISSUE THREAD

**Issue by kryptus36** [huntabyte/shadcn-svelte#1280]
### Describe the bug

Svelte allows you to create an array from checkbox inputs:
https://learn.svelte.dev/tutorial/group-inputs

This is not possible with shadcn's checkbox.

### Reproduction

```
<Checkbox bind:group={myGroup} />
```
 simply doesn't work as group is not implemented.

### System Info

```bash
System:
    OS: Linux 6.6 Gentoo Linux
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 38.56 GB / 62.54 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 22.4.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.8.1 - ~/.npm-global/bin/npm
    pnpm: 9.9.0 - ~/.local/share/pnpm/pnpm
```

### Severity

annoyance

**Comment by shyakadavis** [comment]
Hi, @kryptus36 

Could you look into this: https://www.formsnap.dev/docs/recipes/checkbox-groups

Might help.

**Comment by huntabyte** [comment]
^ Checkboxs in Bits UI/shadcn-svelte aren't your standard checkboxes, so they can't take advantage of that Svelte 5 `bind:group` functionality (which isn't supported on components anyways).

**Comment by Stadly** [comment]
An alternative is to use Bits UI's [Checkbox.Group](https://www.bits-ui.com/docs/components/checkbox#group).

Maybe it should be exported from shadcn-svelte as well, similar to for example [DropdownMenu.CheckboxGroup](https://github.com/huntabyte/shadcn-svelte/pull/2389)?
