### ISSUE TITLE
Components with circular dependency breaks HMR

### ISSUE THREAD

**Issue by sacrosanctic** [huntabyte/shadcn-svelte#1281]
### Describe the bug

> If HMR is handled but it is within a circular dependency, a full reload will also happen to recover the execution order
> https://vitejs.dev/guide/troubleshooting.html#a-full-reload-happens-instead-of-hmr

For example, the [button component](https://github.com/huntabyte/shadcn-svelte/tree/main/sites/docs/src/lib/registry/new-york/ui/button) has a circular dependency.

### Reproduction

.

### System Info

```bash
.
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Fixed in @next
