### ISSUE TITLE
bun install break

### ISSUE THREAD

**Issue by nyssance** [huntabyte/shadcn-svelte#1290]
### Describe the bug

You are currently using an unsupported runtime. Only Node.js v18 or higher is officially supported. Continue at your own risk.

### Reproduction

macOS, just install bun by homebrew, no nodejs.
run
```shell
bunx shadcn-svelte@latest add accordion
```
Not only accordion, every components with the same issue.

### System Info

```bash
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1
    Memory: 66.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    bun: 1.1.29 - /private/tmp/bun-node-6d43b3662/bun
  Browsers:
    Chrome: 129.0.6668.60
    Safari: 18.1
  npmPackages:
    @sveltejs/kit: ^2.6.1 => 2.6.1 
    bits-ui: ^0.21.15 => 0.21.15 
    cmdk-sv: ^0.0.18 => 0.0.18 
    lucide-svelte: ^0.446.0 => 0.446.0 
    mode-watcher: ^0.4.1 => 0.4.1 
    svelte: ^5.0.0-next.260 => 5.0.0-next.260
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This is expected behavior. We don't develop/test for the bun; we develop/test for Node. If all works then there isn't an issue, just ignore the warning 😃
