### ISSUE TITLE
Dialog Content/Description: Forced wrong css text color

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#1293]
### Describe the bug

The [dialog docs code example](https://www.shadcn-svelte.com/docs/components/dialog) show that `<Dialog.Description>` should be used to wrap your dialog/modal content.
However, Dialog.Description aka `data-melt-dialog-description` forces `.text-muted-foreground`, which messes up any native text color expected from the application.

### Reproduction

Quickfix:
<Dialog.Description class="text-normal">

To fix: remove
`.text-muted-foreground` from  `[data-melt-dialog-description]` or rewrite so that  <Dialog.Content> can be used to place pure modal content.

It should be noted that trying to use <Dialog.Content> currently with content that is longer than the modal height, will make the modal content scroll to the middle when opening.

### System Info

```bash
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 6.38 GB / 40.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.7.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 128.1.69.168
    Chrome: 128.0.6613.138
    Safari: 15.6.1
  npmPackages:
    @sveltejs/kit: ^2.6.1 => 2.6.1 
    bits-ui: ^0.21.15 => 0.21.15 
    formsnap: ^1.0.1 => 1.0.1 
    lucide-svelte: ^0.446.0 => 0.446.0 
    mode-watcher: ^0.4.1 => 0.4.1 
    svelte: 5.0.0-next.260 => 5.0.0-next.260 
    sveltekit-superforms: ^2.19.0 => 2.19.0 
    vaul-svelte: ^0.3.2 => 0.3.2
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Not exactly true. `<Dialog.Description>` provides a description for the dialog. Any content that isn't the title or description, goes between the `Dialog.Header` and `Dialog.Footer`.
