### ISSUE TITLE
bind:value issue with Input on svelte 5

### ISSUE THREAD

**Issue by windfan** [huntabyte/shadcn-svelte#1302]
### Describe the bug

I know that shadcn-svelte's support on svelte 5 is not out yet. Just want to report an issue I'm encountering.
I was working with svelte 5(5.0.0-next.262) and shadcn-svelte's Form component.
In my testing, the value from Input is not bound to the properties in form data.
`<Input
     {...attrs}
    bind:value={$formData.email}
/>`
I have to switch to 
`<Input
     {...attrs}
    on:input={(e) => ($formData.email = e.currentTarget.value)}
/>`

### Reproduction

Create a form using shadcn-svelte's Form, with Input component with bind:value. I also use SuperDebug as well.

### System Info

```bash
"svelte": "^5.0.0-next.262",
Safari: Version 18.0 (20619.1.26.31.6)
```

### Severity

annoyance

**Comment by huntabyte** [comment]
https://github.com/user-attachments/assets/52d83e9f-cd8e-40f2-b069-26839c6eab42

Not able to reproduce this

**Comment by windfan** [comment]
Very strange.
![Screenshot 2024-10-06 at 7 58 07 PM](https://github.com/user-attachments/assets/70e15f0f-6a54-471e-b585-edc788302929)
In my testing cases, the bottom vanilla input always works.
However, the top input does not work on binding. When I type something in input, $formData.email is not updated. But if I manually update $formData.email somewhere else, the input is updated, which is a one-way street only.

Does it make a difference when the value in bind:value in the top one is light blue((property) HTMLInputAttributes.value?: any), but the bottom one is green color(no hover information)?

Could it be a Svelte 5 bug?

**Comment by huntabyte** [comment]
Perhaps, do you have a StackBlitz/repo with this reproduction so I can take a look?

**Comment by windfan** [comment]
somehow when I re-run npm run dev,  it started working again. I'm closing this issue for now and will investigate more. Thanks
