### ISSUE TITLE
Select component does not show focus ring

### ISSUE THREAD

**Issue by telcy** [huntabyte/shadcn-svelte#1306]
### Describe the bug

https://www.shadcn-svelte.com/docs/components/select

The select component does not show the focus ring when clicked. Focus via tabbing works.

### Reproduction

Go to https://www.shadcn-svelte.com/docs/components/select and click on the component

### System Info

```bash
Google Chrome 129
```

### Severity

annoyance

**Comment by ieedan** [comment]
As far as I can tell this follows the same behavior as `shadcn-ui` with minor differences in the way that focus is handled after selection.

https://ui.shadcn.com/docs/components/select

**Comment by demetrius-mp** [comment]
looks like in `next` it shows the focus ring (https://next.shadcn-svelte.com/docs/components/select)

**Comment by huntabyte** [comment]
Yes, this issue is resolved in next.
