### ISSUE TITLE
ESlint Error on $$Generic

### ISSUE THREAD

**Issue by GimpMaster** [huntabyte/shadcn-svelte#1311]
### Describe the bug

It looks like $$Generic is used but its never imported anywhere. I'm not even sure what it is.

### Reproduction

In the toggle-group.svelte you are using 	type T = $$Generic<"single" | "multiple">;

However $$Generic doesn't seem to be defined anywhere.

### System Info

```bash
svelte
```

### Severity

annoyance

**Comment by ieedan** [comment]
You can add the following to your ESlint config:
```jsonc
{
    '@typescript-eslint/no-unused-vars': [
        'error',
        {
            // allow $$Generic $$Events $$Props $$Slots
	    varsIgnorePattern: '^_|\\$\\$(Props|Events|Slots|Generic)$',
        },
    ],
}
```

**Comment by ieedan** [comment]
$$ Generic is used to create Generic components in Svelte

```ts
type T = $$Generic;
```

**Comment by huntabyte** [comment]
What @ieedan said ✅
