### ISSUE TITLE
Scroll Are scroll to bottom doesn't work

### ISSUE THREAD

**Issue by SilvianAchim** [huntabyte/shadcn-svelte#1316]
### Describe the bug

I've tried every way I could think of to trigger the scroll area to scroll to the bottom.

`<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import ScrollArea from '$lib/components/ui/scroll-area/scroll-area.svelte';
	import { ScrollArea as ScrollAreaPrimitive } from 'bits-ui';
	import { onMount, tick } from 'svelte';

	let messages: string[] = ['Initial message', 'Another message', 'Yet another message'];
	let scrollViewport: HTMLDivElement | undefined;

	const scrollToBottom = () => {
		if (scrollViewport) {
			scrollViewport.scrollTop = scrollViewport.scrollHeight;
		}
	};

	onMount(() => {
		scrollToBottom();
	});

	$: if (messages) {
		(async () => {
			await tick();
			scrollToBottom();
		})();
	}

	const addMessage = () => {
		messages = [...messages, `New message ${messages.length + 1}`];
	};
</script>

<div class="mx-auto w-full max-w-md space-y-4">
	<ScrollArea class="h-[300px] w-full rounded-md border p-4">
		<ScrollAreaPrimitive.Viewport el={scrollViewport}>
			<div>
				{#each messages as message, index}
					<div class="mb-4 last:mb-0">
						<p class="text-sm">{message}</p>
					</div>
				{/each}
			</div>
		</ScrollAreaPrimitive.Viewport>
	</ScrollArea>
	<div class="flex justify-between">
		<Button on:click={addMessage}>Add Message</Button>
		<Button on:click={scrollToBottom}>Scroll to End</Button>
	</div>
</div>`

Please let me know how to make this work.

### Reproduction

`<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import ScrollArea from '$lib/components/ui/scroll-area/scroll-area.svelte';
	import { ScrollArea as ScrollAreaPrimitive } from 'bits-ui';
	import { onMount, tick } from 'svelte';

	let messages: string[] = ['Initial message', 'Another message', 'Yet another message'];
	let scrollViewport: HTMLDivElement | undefined;

	const scrollToBottom = () => {
		if (scrollViewport) {
			scrollViewport.scrollTop = scrollViewport.scrollHeight;
		}
	};

	onMount(() => {
		scrollToBottom();
	});

	$: if (messages) {
		(async () => {
			await tick();
			scrollToBottom();
		})();
	}

	const addMessage = () => {
		messages = [...messages, `New message ${messages.length + 1}`];
	};
</script>

<div class="mx-auto w-full max-w-md space-y-4">
	<ScrollArea class="h-[300px] w-full rounded-md border p-4">
		<ScrollAreaPrimitive.Viewport el={scrollViewport}>
			<div>
				{#each messages as message, index}
					<div class="mb-4 last:mb-0">
						<p class="text-sm">{message}</p>
					</div>
				{/each}
			</div>
		</ScrollAreaPrimitive.Viewport>
	</ScrollArea>
	<div class="flex justify-between">
		<Button on:click={addMessage}>Add Message</Button>
		<Button on:click={scrollToBottom}>Scroll to End</Button>
	</div>
</div>`

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 9.04 GB / 31.95 GB
  Binaries:
    Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.7.0 
    bits-ui: ^0.21.16 => 0.21.16 
    cmdk-sv: ^0.0.18 => 0.0.18 
    lucide-svelte: ^0.414.0 => 0.414.0 
    svelte: ^4.2.7 => 4.2.19 
    svelte-radix: ^1.1.1 => 1.1.1 
    vaul-svelte: ^0.3.2 => 0.3.2
```

### Severity

annoyance

**Comment by ieedan** [comment]
The behavior here isn't very intuitive and there are a few things you have to do.

> [!NOTE]
> Keep in mind that all this can be figured out by looking at the `bits-ui` documentation

![Screenshot 2024-10-14 063649](https://github.com/user-attachments/assets/029de554-b1aa-4442-89d6-1a9f96c98454)

First of all in your `scroll-area.svelte` you need to add an `el` prop:

```svelte
<script lang="ts">
	import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
	import { Scrollbar } from "./index.js";
	import { cn } from "$lib/utils.js";

	type $$Props = ScrollAreaPrimitive.Props & {
		orientation?: "vertical" | "horizontal" | "both";
		scrollbarXClasses?: string;
		scrollbarYClasses?: string;
                // add the prop to the type
		el: HTMLDivElement
	};

	let className: $$Props["class"] = undefined;
	export { className as class };
	export let orientation = "vertical";
	export let scrollbarXClasses: string = "";
	export let scrollbarYClasses: string = "";
        
        // add the exported prop
	export let el: HTMLDivElement;
</script>

<ScrollAreaPrimitive.Root {...$$restProps} class={cn("relative overflow-hidden", className)}>
        <!-- bind to the el prop -->
	<ScrollAreaPrimitive.Viewport bind:el class="h-full w-full rounded-[inherit]">
		<ScrollAreaPrimitive.Content>
			<slot />
		</ScrollAreaPrimitive.Content>
	</ScrollAreaPrimitive.Viewport>
	{#if orientation === "vertical" || orientation === "both"}
		<Scrollbar orientation="vertical" class={scrollbarYClasses} />
	{/if}
	{#if orientation === "horizontal" || orientation === "both"}
		<Scrollbar orientation="horizontal" class={scrollbarXClasses} />
	{/if}
	<ScrollAreaPrimitive.Corner />
</ScrollAreaPrimitive.Root>
```

Then you can use the `el` prop to scroll the area like this:
```svelte
<script lang="ts">
    import { ScrollArea } from "$lib/components/ui/scroll-area";

    let element: HTMLDivElement;

    const scrollToBottom = () => {
        element.scrollTop = element.scrollHeight;
    }
</script>

<button on:click={scrollToBottom}>
    scrollToBottom
</button>
<ScrollArea bind:el={element}>
    <!-- scrollable content -->
</ScrollArea>
```

**Comment by SilvianAchim** [comment]
> The behavior here isn't very intuitive and there are a few things you have to do.
> 
> Note
> 
> Keep in mind that all this can be figured out by looking at the `bits-ui` documentation
> 
> ![Screenshot 2024-10-14 063649](https://private-user-images.githubusercontent.com/117548273/376221301-029de554-b1aa-4442-89d6-1a9f96c98454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDY0NDAsIm5iZiI6MTcyODkwNjE0MCwicGF0aCI6Ii8xMTc1NDgyNzMvMzc2MjIxMzAxLTAyOWRlNTU0LWIxYWEtNDQ0Mi04OWQ2LTFhOWY5NmM5ODQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTQyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmIxZGU1NTNjNGI2ZjI2ZTQ3ZDcyNjU4MWMyOTJjNjZhZDY1NTRiMTdkOWM1YWU3YTZhNzc1NjdiYzQ2Nzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FLGVuTPqMXrbxorRVo7e8bzIlLv9LPy4tpVRdbq0d1c)
> 
> First of all in your `scroll-area.svelte` you need to add an `el` prop:
> 
> ```svelte
> <script lang="ts">
> 	import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
> 	import { Scrollbar } from "./index.js";
> 	import { cn } from "$lib/utils.js";
> 
> 	type $$Props = ScrollAreaPrimitive.Props & {
> 		orientation?: "vertical" | "horizontal" | "both";
> 		scrollbarXClasses?: string;
> 		scrollbarYClasses?: string;
>                 // add the prop to the type
> 		el: HTMLDivElement
> 	};
> 
> 	let className: $$Props["class"] = undefined;
> 	export { className as class };
> 	export let orientation = "vertical";
> 	export let scrollbarXClasses: string = "";
> 	export let scrollbarYClasses: string = "";
>         
>         // add the exported prop
> 	export let el: HTMLDivElement;
> </script>
> 
> <ScrollAreaPrimitive.Root {...$$restProps} class={cn("relative overflow-hidden", className)}>
>         
> 	<ScrollAreaPrimitive.Viewport bind:el class="h-full w-full rounded-[inherit]">
> 		<ScrollAreaPrimitive.Content>
> 			<slot />
> 		</ScrollAreaPrimitive.Content>
> 	</ScrollAreaPrimitive.Viewport>
> 	{#if orientation === "vertical" || orientation === "both"}
> 		<Scrollbar orientation="vertical" class={scrollbarYClasses} />
> 	{/if}
> 	{#if orientation === "horizontal" || orientation === "both"}
> 		<Scrollbar orientation="horizontal" class={scrollbarXClasses} />
> 	{/if}
> 	<ScrollAreaPrimitive.Corner />
> </ScrollAreaPrimitive.Root>
> ```
> 
> Then you can use the `el` prop to scroll the area like this:
> 
> ```svelte
> <script lang="ts">
>     import { ScrollArea } from "$lib/components/ui/scroll-area";
> 
>     let element: HTMLDivElement;
> 
>     const scrollToBottom = () => {
>         element.scrollTop = element.scrollHeight;
>     }
> </script>
> 
> <button on:click={scrollToBottom}>
>     scrollToBottom
> </button>
> <ScrollArea bind:el={element}>
>     
> </ScrollArea>
> ```

Thank you so much! Sorry for the inconvenience!
