### ISSUE TITLE
Textarea not working with pre-filled data

### ISSUE THREAD

**Issue by sutharsha** [huntabyte/shadcn-svelte#1321]
### Describe the bug

Textarea is not working with pre-filled values. ie anything you type between the Textarea tags is coming blank. placeholder and typed values are reflecting but not preset values. 

### Reproduction

Add a text area, and type something inbetween the tags
<Textarea >something</Textarea> .
"something will not be visible"

### System Info

```bash
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1
    Memory: 257.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.1 - /opt/homebrew/bin/node
    npm: 10.8.1 - /opt/homebrew/bin/npm
    pnpm: 9.5.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.91
    Chrome Canary: 131.0.6772.0
    Safari: 18.0.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.27 
    bits-ui: ^0.21.16 => 0.21.16 
    lucide-svelte: ^0.441.0 => 0.441.0 
    svelte: ^4.2.7 => 4.2.19
```

### Severity

annoyance

**Comment by shyakadavis** [comment]
Hello, @sutharsha 

Textarea doesn't accept any children/slots. Just pass a normal value as you would a normal input.

**Comment by huntabyte** [comment]
What @shyakadavis and @reesebre82 said :)
