### ISSUE TITLE
Slider onValueCommit function

### ISSUE THREAD

**Issue by vthomas73** [huntabyte/shadcn-svelte#1325]
### Prerequisites

- [X] This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.

### Describe the feature

The [shacdn/ui slider](https://www.radix-ui.com/primitives/docs/components/slider#api-reference) has an onValueCommit function which is not available in the svelte version. 
This is interesting to trigger the committed value

**Comment by ieedan** [comment]
This would go to bits-ui since all the event handlers come from there:
https://github.com/huntabyte/bits-ui

**Comment by ieedan** [comment]
I will open a bits-ui issue for this

**Comment by ieedan** [comment]
https://github.com/huntabyte/bits-ui/issues/766

**Comment by huntabyte** [comment]
This is more of a `bits-ui` request and has been implemented in `bits-ui@next`

**Comment by VioPaige** [comment]
I ran into this just now, and since it is only implemented in bits-ui@next, it was not possible to use it in my project that still uses svelte 4. For anyone with that same issue, here was my solution (slider.svelte file):
```html
<script>
	import { Slider as SliderPrimitive } from "bits-ui";
	import { cn } from "$lib/utils.js";
	import { onMount } from "svelte";
	let className = undefined;
	export let value = [0];
	export { className as class };

	// custom patch for onValueCommit
	export let onValueCommit;
	let lastRegValue = value;

	onMount(() => {
		document.addEventListener("pointerup", () => {
			if (lastRegValue === value) return
			lastRegValue = value;

			if (onValueCommit) onValueCommit(value);
		});
	})
</script>

<SliderPrimitive.Root
	bind:value
	class={cn("relative flex w-full touch-none select-none items-center", className)}
	{...$$restProps}
	let:thumbs
>
	<span class="bg-secondary relative h-[.2rem] w-full grow overflow-hidden rounded-full">
		<SliderPrimitive.Range class="bg-primary absolute h-full" />
	</span>
	{#each thumbs as thumb}
		<SliderPrimitive.Thumb
			{thumb}
			class="border-primary bg-background ring-offset-background focus-visible:ring-ring block h-3 w-3 rounded-full border-2 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
		/>
	{/each}
</SliderPrimitive.Root>
```
(After which it's possible to simply pass an onValueCommit callback wherever you used the slider component)
