### ISSUE TITLE
next: Tasks example, previous dropdown menu not closing when switching between Task&Filtering buttons

### ISSUE THREAD

**Issue by derkan** [huntabyte/shadcn-svelte#1328]
### Describe the bug

When the Status button is clicked without closing the dropdown, and then the Priority button is clicked, the dropdown menu for Status remains open.

The bug can be observed at https://huntabyte-next.shadcn-svelte.pages.dev/examples/tasks :

![image](https://github.com/user-attachments/assets/e64df2f6-4353-44f2-8d04-05e4ab316cd0)

 

### Reproduction

When clicked on Status button without closing dropdown implicitly, click Priority button. Drowdown menu of Status is still open.

### System Info

```bash
MacOS, Brave
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This is a bug with bits-ui@next. I've opened an issue to track it: https://github.com/huntabyte/bits-ui/issues/784

**Comment by derkan** [comment]
Checked with latest at https://huntabyte-next.shadcn-svelte.pages.dev/examples/tasks  and it seems as https://github.com/huntabyte/bits-ui/issues/784 is closed, and you've updated deps.
