### ISSUE TITLE
select-scroll-up-button.svelte has <SelectPrimitive.ScrollDownButton> in "next" branch

### ISSUE THREAD

**Issue by charlie-roosen** [huntabyte/shadcn-svelte#1348]
### Describe the bug

I'm copy-and-pasting the code from the registry in the shadcn-svelte "next" branch to update my code to work with the bits-ui prerelease.

The "select-scroll-up-button.svelte" file currently has the source for the scroll DOWN button.

https://github.com/huntabyte/shadcn-svelte/blob/next/sites/docs/src/lib/registry/new-york/ui/select/select-scroll-up-button.svelte

### Reproduction

To reproduce, just look for "SelectPrimitive.ScrollDownButton".  The fix is to change it to "SelectPrimitive.ScrollUpButton".

https://github.com/huntabyte/shadcn-svelte/blob/next/sites/docs/src/lib/registry/new-york/ui/select/select-scroll-up-button.svelte

Clearly just a cut-and-paste issue that the linter isn't going to catch.

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 15.59 GB / 31.69 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/kit: ^2.7.3 => 2.7.3
    bits-ui: ^1.0.0-next.26 => 1.0.0-next.26
    mode-watcher: ^0.4.1 => 0.4.1
    svelte: ^5.1.2 => 5.1.2
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Nice catch. Thank you!

**Comment by charlie-roosen** [comment]
@huntabyte , the type of the props also needs changing: ScrollDownButtonProps.
