### ISSUE TITLE
Skeleton UI components

### ISSUE THREAD

**Issue by Rafi-Riday** [huntabyte/shadcn-svelte#136]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hei, can you add some features from `skeleton ui`? Like the `app shell`, `app rail`, `app bar`?
There are some structures and functions we always need. The `skeleton ui` looks fantastic but the main problem is performance.
I see anti component library is really greate for performance and I have complete control over the components I'm using.
Big fan of you hope you make it successful

### Some features from `skeleton ui`

https://www.skeleton.dev/components/app-bar
https://www.skeleton.dev/components/app-rail
https://www.skeleton.dev/components/app-shell
https://www.skeleton.dev/components/file-dropzone
https://www.skeleton.dev/components/paginators

**Comment by huntabyte** [comment]
Hey there @Rafi-Riday , this is a port of shadcn-svelte, so I want to keep it as aligned with the original as possible, so we will not be adding those components from Skeleton, however, you could always copy over their source code if you wanted it locally.
