### ISSUE TITLE
Failed to fetch registry from https://next.shadcn-svelte.com/registry

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#1368]
### Describe the bug

Running  npx  shadcn-svelte@next update

◇  Which components would you like to update?
│  avatar, badge, button, card, checkbox, command, context-menu, dialog, dropdown-menu, form, input, label, popover, radio-group, select, separator, sheet, skeleton, sonner, switch, table, tabs, utils
│
◇  Ready to update components? (Make sure you have committed your changes before proceeding!)
│  Yes
│
└  [CLI Error]: Failed to fetch registry from https://next.shadcn-svelte.com/registry.

### Reproduction

 npx  shadcn-svelte@next update

### System Info

```bash
System:
    OS: Windows 11 10.0.26100
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 4.64 GB / 31.91 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.12.2 - C:\ProgramData\chocolatey\bin\pnpm.EXE
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.26100.1882
```

### Severity

blocking an upgrade

**Comment by niemyjski** [comment]
I only get this when trying to upgrade utils

 Which components would you like to update?
│  utils
│
◇  Ready to update components? (Make sure you have committed your changes before proceeding!)
│  Yes
│
└  [CLI Error]: Failed to fetch registry from https://next.shadcn-svelte.com/registry.

**Comment by niemyjski** [comment]
Something is clearly going wrong tho, because none of my components are actually upgraded when I did them in batches

**Comment by huntabyte** [comment]
Ah, I don't think you can update utils like that @niemyjski. The update is for components only atm.

The `utils` have been dramatically reduced with the removal of svelte transitions in support of CSS/tailwind:

```ts
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}
```

**Comment by huntabyte** [comment]
Just noticed that `utils` is showing up as something you can update. We'll get this resolved.

**Comment by lecramr** [comment]
Getting the same Error trying to upgrade:

```
┌   shadcn-svelte  v1.0.0-next.0 
│
◇  Components to update:
│  accordion, alert, alert-dialog, aspect-ratio, avatar, badge, breadcrumb, button, calendar,
│  card, checkbox, collapsible, command, dialog, drawer, dropdown-menu, form, input,
│  label, pagination, popover, radio-group, scroll-area, select, separator, sheet, sidebar,
│  skeleton, sonner, switch, table, tabs, textarea, tooltip, utils
│
◇  Ready to update components? (Make sure you have committed your changes before proceeding!)
│  Yes
│
└  [CLI Error]: Failed to fetch registry from https://next.shadcn-svelte.com/registry.
```

https://next.shadcn-svelte.com/registry is also not found. It worked in the morning, pretty sure :D

**Comment by huntabyte** [comment]
Use `add` do not use `update`. @lecramr we are removing `update` because it does the same thing as add.
