### ISSUE TITLE
svelte 5: update all error

### ISSUE THREAD

**Issue by zhihengGet** [huntabyte/shadcn-svelte#1370]
### Describe the bug

npx shadcn-svelte@next update --all 

Exception in PromiseRejectCallback:
file:///C:/Users/nicej/AppData/Local/npm-cache/_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:65

### Reproduction

npx shadcn-svelte@next update --all 

### Logs

```bash
Exception in PromiseRejectCallback:

/_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:65

RangeError: Maximum call stack size exceeded

│
└  RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at Oe (/28febf0521d8db2e/node_modules/shadcn-
svelte/dist/index.js:65:1826)

    at Oe (file:///C:/Users/nicej/AppData/Local/npm-cache/_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:65:2023)RangeError: Maximum call stack size exceeded

Exception in PromiseRejectCallback:
... /_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:65
```

### System Info

```bash
win11
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Just run `add` instead of `update`, they basically do the exact same thing! We're going to nuke the `update` command soon.
