### ISSUE TITLE
`npx shadcn-svelte` init overwrites existing files in project

### ISSUE THREAD

**Issue by eike-heimpel** [huntabyte/shadcn-svelte#139]
### Current Behavior

Hey team,

Using the components for the first time, thanks for making this happen! I stumbled upon it while working on a project already and running `npx shadcn-svelte init` caused some issues for me. Most importantly, it overwrites the lib/utils.ts file, which was unexpected. 

It also overwrote my custom tailwind colors, which is less surprising, but still not optimal imo. Not sure if it is possible, but maybe it could leave the existing ones in just so the code on an existing project does not instantly break. 

### Expected Behavior

I think it would be great if it could be made easier and safer to run on an existing project. 

### Steps To Reproduce

On a project with existing `src/lib/utils.js` and/or `tailwind.config.js`, running `npx shadcn-svelte` overwrites existing functions/properties. 

It looks like it does not simply overwrite everything, e.g. my `svelte.config.js` has some old and new pieces.

**Comment by eike-heimpel** [comment]
I understand that the manual process would help me avoid/be aware of these issues, so maybe it is more a feature request than a bug to make the installer be more compatible with existing files.

**Comment by huntabyte** [comment]
I'm open to the idea of this, if someone has the cycles and wants to take on that challenge. We already have some AST walkers and such in the CLI package, it'd just be a matter of getting it right and covering all possibilities, or not doing it at all.

**Comment by Benjamoon** [comment]
What if, if the config files are found to not be fresh, we duplicate them and add a ".old" suffix and provide a message explaining this?

If that sounds good, id be more than happy to try and implement it.

**Comment by huntabyte** [comment]
I'll defer to @AdrianGonz97 on this one, but I don't feel good about the .old idea, as what would be our source of truth for a "fresh" tailwind config?

When the file is replaced inside of an existing git repo you can diff the changes to see what of yours was removed and revert as needed, or take the manual approach.

--

The easy approach would be to enable the opt out of certain files being overwritten or touched at all.

The optimal approach though is to gracefully insert the scn tailwind configs into an already existing config. It's something we for sure want to do it's just not high up there on the priority list (behind supporting non-TS projects).

**Comment by huntabyte** [comment]
Closing as not planned for the time being.
