### ISSUE TITLE
Pagination : Cannot use `{@render children(...)}` if the parent component uses `let:` directives. Consider using a named snippet instead

### ISSUE THREAD

**Issue by YashKorat17** [huntabyte/shadcn-svelte#1392]
### Describe the bug

Cannot use `{@render children(...)}` if the parent component uses `let:` directives. Consider using a named snippet instead

### Reproduction

Cannot use `{@render children(...)}` if the parent component uses `let:` directives. Consider using a named snippet instead

### System Info

```bash
Cannot use `{@render children(...)}` if the parent component uses `let:` directives. Consider using a named snippet instead
```

### Severity

annoyance

**Comment by shyakadavis** [comment]
@YashKorat17 I think the `let:` directive won't work. Consider using [snippets](https://svelte.dev/docs/svelte/snippet) instead.

**Comment by YashKorat17** [comment]
It's occurs in pagination file.

**Comment by shyakadavis** [comment]
Mind sharing a small reproduction?

**Comment by YashKorat17** [comment]
<Pagination.Root {count} perPage={10} class="w-min">
			{#snippet children({ pages, currentPage }: { pages: any; currentPage: number })}
				<Pagination.Content>
					<Pagination.Item>
						<Pagination.PrevButton>
							<Icons.chevronLeft class="h-4 w-4" />
							<span class="hidden sm:block">Previous</span>
						</Pagination.PrevButton>
					</Pagination.Item>
					{#each pages as page (page.key)}
						{#if page.type === 'ellipsis'}
							<Pagination.Item>
								<Pagination.Ellipsis />
							</Pagination.Item>
						{:else}
							<Pagination.Item>
								<Pagination.Link {page} isActive={currentPage === page.value}>
									{page.value}
								</Pagination.Link>
							</Pagination.Item>
						{/if}
					{/each}
					<Pagination.Item>
						<Pagination.NextButton>
							<span class="hidden sm:block">Next</span>
							<Icons.chevronRight class="h-4 w-4" />
						</Pagination.NextButton>
					</Pagination.Item>
				</Pagination.Content>
			{/snippet}
		</Pagination.Root>

**Comment by shyakadavis** [comment]
Afraid this isn't a repro. And for what it's worth, didn't run into an error using your shared snippet.

**Comment by huntabyte** [comment]
Make sure you are using `bits-ui@next`. Once you provide a reproduction I will reopen this issue.

**Comment by jamesepirus** [comment]
I have the same issue, and I have "bits-ui": "^1.0.0-next.46",
