### ISSUE TITLE
`<Collapsible />` is not applying animations

### ISSUE THREAD

**Issue by demetrius-mp** [huntabyte/shadcn-svelte#1398]
### Describe the bug

Expanding/collapsing the Content will happen without animation
pretty sure is because of https://next.bits-ui.com/docs/components/collapsible#svelte-transitions

### Reproduction

the docs https://next.shadcn-svelte.com/docs/components/collapsible

click the expand/collapse button and you will see it has no animation

### System Info

```bash
no need, check the docs
```

### Severity

annoyance

**Comment by trueight** [comment]
@demetrius-mp i think the docs do not use animations in this component, just like the [original](https://ui.shadcn.com/docs/components/collapsible) one

but you can add them to your project, as shown in the bits-ui documentation

**Comment by demetrius-mp** [comment]
Ur right, its just that in the previous version it had animations, but i checked shadcn collapsible and it does not have animations too

Gonna close this one

**Comment by demetrius-mp** [comment]
Yeah, i think so, gonna reopen them

**Comment by huntabyte** [comment]
Nah it's not a bug. It's aligned with shadcn/ui. Not sure why we had animations on the first one, but you can add them if you wish.

**Comment by HuakunShen** [comment]
How to make it animate? 
In the docs I saw only svelte transition
https://next.bits-ui.com/docs/components/collapsible#api-reference
