### ISSUE TITLE
The Select component shows outdated docs.

### ISSUE THREAD

**Issue by pacosw1** [huntabyte/shadcn-svelte#1399]
### Change Type

Correction

### Proposed Changes

The [docs for select](https://next.shadcn-svelte.com/docs/components/select) show invalid usage of the component.

I added the select component with the CLI but there is no exported type for Select.Value like suggested in the usage. I checked the repo. The previous version does include it but not the next version

New version without the Value type: https://github.com/huntabyte/shadcn-svelte/blob/next/sites/docs/src/lib/registry/new-york/ui/select/index.ts

Old version that includes it https://github.com/huntabyte/shadcn-svelte/blob/main/sites/docs/src/lib/registry/new-york/ui/select/index.ts

**Comment by shyakadavis** [comment]
Was actually about to open a P.R fixing this. Should be only one line removed.

**Comment by pacosw1** [comment]
Cool I was just about to use it, but didn't know how it worked.

After some thinkering I saw that type is no longer required, but I thought it was broken.
