### ISSUE TITLE
next: Task example Select should have `allowDeselect={false}`

### ISSUE THREAD

**Issue by joleeee** [huntabyte/shadcn-svelte#1401]
### Describe the bug

If you pick the start value from a Select it will the first time do a `onValueChange` returning "", but it only seems to do so if the `Select.Item`'s value is a stringified integer, e.g. `12` but not `a12`.

My observations may not be correct but you can see it yourselves at https://next.shadcn-svelte.com/examples/tasks

https://github.com/user-attachments/assets/985bf359-330a-4989-bfd4-52a53a2a472d

### Reproduction

Go to https://next.shadcn-svelte.com/examples/tasks, click Rows per page = 10

### System Info

```bash
It happens on the official website aswell
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
That is the correct value (an empty string) when you select it. The issue is this specific select in the example should have `allowDeselect` set to `false` as you shouldn't be able to deselect an option altogether.

**Comment by joleeee** [comment]
Makes sense! I discovered it through the data table example, so it's also an issue there

**Comment by huntabyte** [comment]
Which `Select` in that example is causing an issue @joleeee ?

**Comment by joleeee** [comment]
My bad, I misremembered. It must've been from the .svelte files I found for the task example.
