### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by dheerajpg** [huntabyte/shadcn-svelte#142]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

is it possible to add rich text editor component, I guess it's useful for many website where there's custom user input is necessary 

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

**Something like this**

<img width="694" alt="Screenshot 2023-07-12 at 10 49 05 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/70167116/70640ed0-6dde-4a6c-aa4e-121cd8072c41">

**Comment by huntabyte** [comment]
Hey @dheerajpg , we aren't going to be adding thing that the original `shadcn/ui` doesn't have, as we want to stay tightly aligned as a port. If this comes up in the future and shad decides to add something similar, we will do the same!
