### ISSUE TITLE
Ability to provide a customised bits.ui Close Button

### ISSUE THREAD

**Issue by stefa168** [huntabyte/shadcn-svelte#1433]
### Prerequisites

- [X] This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.

### Describe the feature

Hi, I have been working with Dialogs a lot recently, and the current implementation lacks the possibility to provide a custom bits.ui Close button at the top right of the dialog.

A similar issue has been already presented on the original shadcn repo (shadcn-ui/ui#1871).
I'd implement such a change myself, however the current wrapper around bits.ui is a bit out of my league, especially now that Svelte5 has been released and snippets are becoming more and more used.

Is there any way to solve this issue in an elegant way?

**Comment by huntabyte** [comment]
You can edit the component yourself, the code is yours 😃 as was determined in the original issue you linked. If it is removed there it will be removed here but not until then 😃
