### ISSUE TITLE
[Sheet] Click event handlers are triggered by pressing Sheet.Trigger

### ISSUE THREAD

**Issue by Inovvia** [huntabyte/shadcn-svelte#1434]
### Describe the bug

Basically I want to execute functions inside the sheet overlay but what happens is they get executed immediately.
In my example code i have buttons but they do not execute the function when pressed, but are executed immediately when pressing the sheet trigger.

ER: Events are not triggered
AR: Events are triggered.

### Reproduction

https://stackblitz.com/edit/github-qu3ne7-fqgmgx?file=src%2Froutes%2F%2Blayout.svelte

If that doesn't work or the link expires
```
<script>
	import '../app.pcss';
	import * as Sheet from '$lib/components/ui/sheet/';
</script>
<Sheet.Root>
		<Sheet.Trigger>Open</Sheet.Trigger>
		<Sheet.Content>
			<Sheet.Header>
				<Sheet.Title>Are you sure absolutely sure?</Sheet.Title>
				<Sheet.Description>
					This action cannot be undone. This will permanently delete your account and remove your
					data from our servers.
				</Sheet.Description>
				<button onclick={alert("alerted")}>Alert me</button>

			</Sheet.Header>
		
		</Sheet.Content>
	</Sheet.Root>
<slot />
```

### Logs

```bash
N/A
```

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 42.46 GB / 63.92 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.4 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.0 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Severity

annoyance

**Comment by huntabyte** [comment]
You are using svelte 4 in that stackblitz. In Svelte 4 you need to use `on:click` not `onclick`

**Comment by Inovvia** [comment]
Sorry I cannot replicate this on stackblitz on svelte 5, :((


However I can replicate in on my private repo.

Here is my package json if it might help

{
	"name": "frontend",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --check . && eslint .",
		"format": "prettier --write ."
	},
	"devDependencies": {
		"@sveltejs/adapter-node": "^5.2.6",
		"@sveltejs/kit": "^2.5.27",
		"@sveltejs/vite-plugin-svelte": "^4.0.0",
		"@tailwindcss/typography": "^0.5.14",
		"@types/eslint": "^9.6.0",
		"autoprefixer": "^10.4.20",
		"bits-ui": "^1.0.0-next.39",
		"clsx": "^2.1.1",
		"eslint": "^9.0.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-svelte": "^2.45.1",
		"formsnap": "^1.0.1",
		"globals": "^15.0.0",
		"lucide-svelte": "^0.452.0",
		"mode-watcher": "^0.4.1",
		"prettier": "^3.1.1",
		"prettier-plugin-svelte": "^3.2.6",
		"prettier-plugin-tailwindcss": "^0.6.5",
		"svelte": "^5.0.0",
		"svelte-check": "^4.0.0",
		"svelte-sonner": "^0.3.28",
		"sveltekit-superforms": "^2.20.0",
		"tailwind-merge": "^2.5.4",
		"tailwind-variants": "^0.2.1",
		"tailwindcss": "^3.4.9",
		"typescript": "^5.5.0",
		"typescript-eslint": "^8.0.0",
		"vite": "^5.4.4",
		"zod": "^3.23.8"
	},
	"type": "module",
	"dependencies": {
		"dotenv": "^16.4.5",
		"pocketbase": "^0.22.0-rc2"
	},
	"optionalDependencies": {
		"@rollup/rollup-linux-x64-gnu": "^4.24.0"
	}
}

**Comment by Inovvia** [comment]
I even tried reinstalling my node modules.

**Comment by huntabyte** [comment]
It doesn't help, unfortunately. Once you provide a reproduction with Svelte 5 I can reopen this issue, but gonna close it until then.

**Comment by Inovvia** [comment]
Must be a bug in svelte or one of my old packages! 

I deleted my package-lock.json and reinstalled everything now everything works perfectly.

Let me know you need a repro for that so I can create one.

**Comment by huntabyte** [comment]
Awesome!

**Comment by Inovvia** [comment]
Here is a short video of the error!

It's actually weird that I can only reproduce it at the moment when using touch/taps!


Repro link:  https://stackblitz.com/~/github.com/Inovvia/shadcn-repro-sheet


https://github.com/user-attachments/assets/69ca4560-e313-4675-8dc3-9e1bb37c5f29
