### ISSUE TITLE
v5 Migration

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#1437]
### Change Type

Addition

### Proposed Changes

Thx for proving v.5 svelte support !

Please add a migration page so we know what needs to be done to upgrade.

**Comment by skylerknight** [comment]
I had to manually install `bits-ui@next` with the latest version for anyone else having issues with the installation process

**Comment by MentalGear** [comment]
Very understandable, thank you again for your amazing work!
Let's collect migration feedback in this issue and then fill a docs page with it as general tips.

**Comment by ieedan** [comment]
So far here's what I have identified:

1. migrate components with `shadcn-svelte@next add` (or update once it's fixed) also be aware of components that have custom code as you will need to reimplement any of that yourself
2. upgrade dependencies (list below update with full)
    - `bits-ui` 
3. remove dependencies (list below update with full)
    - cmdk-sv
    - svelte-headless-table
4. run `npx sv migrate svelte-5` to migrate other components

**Comment by jakobpesch** [comment]
You can also use both versions in your project and migrate only some components using npm aliases. It is a bit tedious and you gotta be careful to import from the correct version of `bits-ui`, but if you have a big project and don't want to do a huge migration, this could be an alternative.

**Comment by ieedan** [comment]
I will work on an draft PR this morning with the initial things we discussed here I will reference this issue when I open it so we can continue discussion there.

**Comment by ieedan** [comment]
[Preview Documentation](https://ieedan-migration-instruction.shadcn-svelte.pages.dev/docs/migration/svelte-5)

Let me know what you think!

**Comment by jacob-winkler** [comment]
> [Preview Documentation](https://ieedan-migration-instruction.shadcn-svelte.pages.dev/docs/migration/svelte-5)
> 
> Let me know what you think!

I just used this to migrate. The guide is mostly great, well done and thank you!!

The one thing I noticed is the suggestion to use `npx  shadcn-svelte@next update`. This command did nothing after I ran and selected the components I wanted to update. I instead ran `npx  shadcn-svelte@next add` and selected the components I wanted to "install" which then overwrote my existing components

**Comment by volstas** [comment]
I'm having issues with form. 
E.g. form-description.svelte is failing with:

`Property 'ref' does not exist on type '{ id?: string | undefined; asChild?: boolean | undefined; el?: HTMLDivElement | undefined; } & HTMLAttributes<HTMLDivElement>'`

Then form-element-field.svelte doesn't complain about ref because type has added `WithElementRef<HTMLAttributes<HTMLDivElement>> `

but it does complain in the snippet, with `Binding element 'constraints' implicitly has an 'any' type.` and the @render is throwing Expected 0 arguments, but got 1.

I tried also upgrading formsnap@next but it didn't really help.

What am I missing?

**Comment by shubhamkumar13** [comment]
> I had to manually install `bits-ui@next` with the latest version for anyone else having issues with the installation process

Thank you so much, Tauri right now has this same issue.
