### ISSUE TITLE
Table footer uses wrong color combination

### ISSUE THREAD

**Issue by wiesson** [huntabyte/shadcn-svelte#1440]
### Describe the bug

The table footer uses `bg-muted/50` with `text-primary-foreground` which is barely visible. (See here https://github.com/huntabyte/shadcn-svelte/blob/next/sites/docs/src/lib/registry/default/ui/table/table-footer.svelte#L16) 

I have checked shadcn-ui and we have a different class here:

```HTML
border-t bg-muted/50 font-medium [&>tr]:last:border-b-0
```

See https://github.com/shadcn-ui/ui/blob/2c043e709fe0175309d1e8e58f16d20fe841236a/apps/www/registry/default/ui/table.tsx#L46C8-L46C63

If `text-primary-foreground` is intended, it's not working, otherwise I'm happy to submit a quick PR to fix it

### Reproduction

https://play.tailwindcss.com/A8b5TqNBW5

### System Info

```bash
System:
    OS: macOS 15.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 785.16 MB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /usr/local/bin/npm
    bun: 1.1.34 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.1
  npmPackages:
    @sveltejs/kit: ^2.7.4 => 2.7.4 
    bits-ui: 1.0.0-next.39 => 1.0.0-next.39 
    lucide-svelte: ^0.454.0 => 0.454.0 
    mode-watcher: ^0.4.1 => 0.4.1 
    svelte: 5.1.9 => 5.1.9 
    svelte-radix: ^2.0.1 => 2.0.1 
    svelte-sonner: ^0.3.28 => 0.3.28 
    vaul-svelte: 1.0.0-next.1 => 1.0.0-next.1 
```

### Severity

super annoyance

**Comment by huntabyte** [comment]
As long as it is aligned with the original [shadcn/ui](https://github.com/shadcn-ui/ui) then I am open to PRs!
