### ISSUE TITLE
tailwindcss-animate does not get added when upgrading Dialog to @next

### ISSUE THREAD

**Issue by MiraiSubject** [huntabyte/shadcn-svelte#1443]
### Describe the bug

Dialog does not animate when running `pnpm dlx shadcn-svelte@next add dialog` on a project that was previously using a pre-next version of shadcn-svelte. A new shadcn-svelte project initialised with `pnpm dlx shadcn-svelte@next init` includes the necessary `tailwindcss-animate` dependency.

I expect when running `pnpm dlx shadcn-svelte@next add dialog` on a pre-next project that the `tailwindcss-animate` also gets installed when agreeing to install components and dependencies. 

The usecase here was using `shadcn-svelte@latest` in an existing svelte 5 project and now in the process of migrating the shadcn components to their `@next` versions

### Reproduction

```bash
pnpm dlx sv create
pnpm dlx sv add tailwindcss
pnpm dlx shadcn-svelte@latest init
pnpm dlx shadcn-svelte@latest add dialog
pnpm dlx shadcn-svelte@next add dialog
```

Observe here that `tailwindcss-animate` does not get installed (+ added to the tailwind.config.ts file), and only bits-ui gets upgraded: https://github.com/MiraiSubject/shadcn-dialog-repro/commit/982b87b8a7ce47949dd249723b76acc2bc723ec3

### System Info

```bash
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.58 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/Library/pnpm/node
    npm: 10.8.2 - ~/Library/pnpm/npm
    pnpm: 9.0.6 - ~/Library/pnpm/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.1
    Safari Technology Preview: 18.0
  npmPackages:
    @sveltejs/kit: ^2.7.3 => 2.7.3 
    bits-ui: 1.0.0-next.40 => 1.0.0-next.40 
    cmdk-sv: ^0.0.18 => 0.0.18 
    mode-watcher: ^0.4.1 => 0.4.1 
    svelte: ^5.1.4 => 5.1.4 
    svelte-radix: ^1.1.1 => 1.1.1 
    svelte-sonner: ^0.3.28 => 0.3.28 
    vaul-svelte: ^0.3.2 => 0.3.2
```

### Severity

annoyance

**Comment by huntabyte** [comment]
You need to `init` with `shadcn-svelte@next init` not `@latest`

**Comment by MiraiSubject** [comment]
> You need to `init` with `shadcn-svelte@next init` not `@latest`.

The `@latest` init there was purely to demonstrate a project that migrates from latest to next. Unless you mean a consumer should _re_-init using `@next`.

> We already have marked to update tailwind config and such on an as-needed basis in the next release but we haven't gotten to it just yet.

Sounds good! That solves it for me.
