### ISSUE TITLE
Svelte 5 runes mode compatibility

### ISSUE THREAD

**Issue by Mr-EmPee** [huntabyte/shadcn-svelte#1444]
### Describe the bug

The dependency "lucide-icons" is causing issues when runes mode is activated.

https://github.com/lucide-icons/lucide/issues/2312

The fixes are using a workaround or waiting for a next major release of the library.

### Reproduction

Add to the config inside svelte.config.js
```js
compilerOptions: {
  runes: true
},
```

### System Info

```bash
System:
    OS: Linux 6.10 Fedora Linux 40 (Forty)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.26 GB / 15.36 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v20.17.0/bin/npm
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.7.4 
    bits-ui: ^1.0.0-next.39 => 1.0.0-next.39 
    lucide-svelte: ^0.454.0 => 0.454.0 
    svelte: ^5.0.0 => 5.1.9
```

### Severity

annoyance

**Comment by huntabyte** [comment]
As you mentioned, this is an issue with `lucide-svelte` and not this project. Closing this issue here.
