### ISSUE TITLE
For Label, the Usage section doesn't match the Preview

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/shadcn-svelte#145]
### Change Type

Cleanup (formatting, typos, etc.)

### Proposed Changes

The Preview is "Accept terms and conditions".

The Usage shows: "Your email address"

For consistency, I assume these are intended to match.

**Comment by huntabyte** [comment]
They are actually not intended to match! Usage is more of a general quick overview of component use, whereas the example component's code is under the 'Code' tab at the top!
