### ISSUE TITLE
Hovercard behavior changed with svelte v5 migration

### ISSUE THREAD

**Issue by jacob-winkler** [huntabyte/shadcn-svelte#1450]
### Describe the bug

If I quickly drag my mouse over many `HoverCard.Trigger` components, then all of the "touched" triggers will display their `HoverCard.Content`, even though my mouse is no longer hovering over the triggers.

### Reproduction

```svelte
<script lang="ts">
    import * as Card from '$lib/components/ui/card';
    import * as HoverCard from '$lib/components/ui/hover-card';
    
    let numbers = [1,2,3,4,5];
</script>

{#each numbers as number}
    <HoverCard.Root>
        <HoverCard.Trigger>
            <Card.Root>
                <Card.Title class="h-24">{number}</Card.Title>
            </Card.Root>
        </HoverCard.Trigger>
        <HoverCard.Content class="w-auto">
            <Card.Title class="pb-2">TEST HOVER CONTENT {number}</Card.Title>
        </HoverCard.Content>
    </HoverCard.Root>
{/each}	
```

### System Info

```bash
System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 3.18 GB / 31.01 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
  Browsers:
    Brave Browser: 130.1.71.121
    Chrome: 124.0.6367.155
  npmPackages:
    @sveltejs/kit: ^2.7.2 => 2.7.2 
    bits-ui: ^1.0.0-next.45 => 1.0.0-next.45 
    lucide-svelte: ^0.453.0 => 0.453.0 
    svelte: ^5.0.0 => 5.0.5
```

### Severity

blocking an upgrade

**Comment by ieedan** [comment]
https://stackblitz.com/edit/github-bnmjm7?file=src%2Froutes%2F%2Bpage.svelte here's a reproduction really not sure how far this goes down the chain.

**Comment by jacob-winkler** [comment]
> https://stackblitz.com/edit/github-bnmjm7-nhztbb?file=src%2Froutes%2F%2Bpage.svelte here's a reproduction really not sure how far this goes down the chain.
> 
> Since its reproducible with `bits-ui` only it should probably go there: https://stackblitz.com/edit/github-bnmjm7-p2msgy?file=src%2Froutes%2F%2Bpage.svelte

Thanks for digging in, I'll see if an issue already exists there and if not, will create one.

**Comment by jacob-winkler** [comment]
Related issue in the bits-ui repo
https://github.com/huntabyte/bits-ui/issues/888

**Comment by huntabyte** [comment]
Fixed in the latest release of `bits-ui@next`

**Comment by jacob-winkler** [comment]
> Fixed in the latest release of `bits-ui@next`

Awesome, thank you for the speedy response. The fix looks good for me locally after updating bits-ui@next :+1: :rocket:
