### ISSUE TITLE
Chat component

### ISSUE THREAD

**Issue by wighawag** [huntabyte/shadcn-svelte#1452]
### Prerequisites

- [X] This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.

### Describe the feature

A chat component / example would be useful

I am not sure if it fit your pre-requisites as this is not part of shadcn/ui core but it is part of shadcn ecosystem:   https://github.com/jakobhoeg/shadcn-chat

**Comment by huntabyte** [comment]
It won't be added here if it is not a part of shadcn/ui core!
