### ISSUE TITLE
npx shadcn-svelte@next init 'tailwind.config.mjs' error "tailwindcssAnimate is not defined"

### ISSUE THREAD

**Issue by joshmitch2000** [huntabyte/shadcn-svelte#1458]
### Describe the bug

When running the shadcn-svelte init command for the "next" version, (npx shadcn-svelte@next init), it adds the following inside the tailwind config file:
```javascript
plugins: [tailwindcssAnimate]
``` 
This causes a runtime error as "tailwindcssAnimate" is not defined.

<img width="1261" alt="Screenshot 2024-11-07 at 2 30 10 pm" src="https://github.com/user-attachments/assets/bbc58501-a5e6-44a6-b3fa-9a5d4eff49e0">

**_Proposed fix_** - update `TAILWIND_WITH_VARIABLES` inside https://github.com/huntabyte/shadcn-svelte/blob/next/packages/cli/src/utils/templates.ts from:
```typescript
//...
plugins: [tailwindcssAnimate] // @line 117
```
**TO**
```typescript
//...
plugins: [require('tailwindcss-animate')] // @line 117
``` 

### Reproduction

Install latest version of shadcn-svelte for astro via https://next.shadcn-svelte.com/docs/installation/astro

### System Info

```bash
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M2
    Memory: 59.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 130.0.6723.92
    Chrome Canary: 132.0.6823.1
    Edge: 130.0.2849.68
    Safari: 18.0.1
  npmPackages:
    bits-ui: ^1.0.0-next.46 => 1.0.0-next.46 
    svelte: ^5.1.11 => 5.1.11 
    vaul-svelte: ^1.0.0-next.2 => 1.0.0-next.2
```

### Severity

blocking an upgrade

**Comment by ieedan** [comment]
Generally you get linting errors when you use require in that way. All you need to do is `npm install`. Please confirm that the `tailwindcss-animate` package was added to your `package.json`. If it wasn't added on `init` I can get a PR working for that.

**Comment by joshmitch2000** [comment]
Oh yeah good point and thanks for your reply.
It looks like it is getting added to the `package.json` on running init however it's not getting imported into `tailwind.config.mjs` and hence the runtime error.

**Comment by ieedan** [comment]
Last I checked it completely overwrote the config. Let me look into this in a bit.

**Comment by ieedan** [comment]
Just ran it it seems to overwrite this config without any issues make sure you are running

```
npx shadcn-svelte@next init
```

**Comment by rudiv** [comment]
For me, it's adding `import tailwindcssAnimate from "tailwindcss-animate";` to the top of the file no issue, not sure why it wouldn't be there.

Instead, I'm getting:

```
TS1259: Module ... can only be default-imported using the esModuleInterop flag

index.d.ts(3, 1): This module is declared with export =, and can only be used with a default import when using the esModuleInterop flag```

Suppressing this with a `@ts-expect-error` right now, but does seem that library isn't maintained.

**Comment by ieedan** [comment]
> For me, it's adding `import tailwindcssAnimate from "tailwindcss-animate";` to the top of the file no issue, not sure why it wouldn't be there.
> 
> Instead, I'm getting:
> 
> ```
> TS1259: Module ... can only be default-imported using the esModuleInterop flag
> 
> index.d.ts(3, 1): This module is declared with export =, and can only be used with a default import when using the esModuleInterop flag
> ```
> 
> Everything works fine apart from the red squiggly, so just suppressing this with a `@ts-expect-error` right now, but does seem that library isn't maintained.
> 
> Mainly putting this here not to report an issue (I don't feel that it warrants that), but if anyone else with default SK setup sees a red squiggly when searching.

This sounds like an issue with tsconfig but if you can create a repro I can take a look!

**Comment by rudiv** [comment]
In all honesty I've just checked the tsconfig and `esModuleInterop` is true. I think it's my IDE being a little stupid, changed it to `@ts-ignore` instead.

**Comment by ieedan** [comment]
> In all honesty I've just checked the tsconfig and `esModuleInterop` is true. I think it's my IDE being a little stupid, changed it to `@ts-ignore` instead.

Maybe need to restart ts server?

**Comment by joshmitch2000** [comment]
> Just ran it it seems to overwrite this config without any issues make sure you are running
> 
> ```
> npx shadcn-svelte@next init
> ```

I've run this again and all seems okay. I'm not sure what I did the first time around my mistake (I'm just new haha)

Thank you for looking into it anyway :)
