### ISSUE TITLE
App crashes: Cannot find package 'tailwind-variants'

### ISSUE THREAD

**Issue by joshdavham** [huntabyte/shadcn-svelte#1459]
### Describe the bug

I'm developing a Sveltekit app with Firebase Hosting and just added shadcn-svelte to it. Everything was working fine with the local emulators and I even did a local build and previewed it to verify things were working, but it crashes when I deploy to firebase. Also, to be sure, it was deploying and working totally fine in production before this. It was only after adding shadcn-svelte that this issue arose.

Looking at the logs, I get:

> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tailwind-variants' imported from /workspace/chunks/index3.js
>     at packageResolve (node:internal/modules/esm/resolve:854:9)
>     at moduleResolve (node:internal/modules/esm/resolve:927:18)
>     at defaultResolve (node:internal/modules/esm/resolve:1169:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
>     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
>     at link (node:internal/modules/esm/module_job:95:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }

### Reproduction

To reproduce, I'd follow the [installation](https://shadcn-svelte.com/docs/installation/sveltekit) instructions for shadcn-svelte, create a simple shadcn-svelte button on `source/routs/+page.svelte`and deploy the app on firebase hosting. Make sure to also run the following before deploying the first time: `firebase experiments:enable webframeworks`

### Logs

```bash
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tailwind-variants' imported from /workspace/chunks/index3.js
>     at packageResolve (node:internal/modules/esm/resolve:854:9)
>     at moduleResolve (node:internal/modules/esm/resolve:927:18)
>     at defaultResolve (node:internal/modules/esm/resolve:1169:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
>     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
>     at link (node:internal/modules/esm/module_job:95:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
```

### System Info

```bash
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 104.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.8.3 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 130.0.6723.93
    Edge: 130.0.2849.68
    Safari: 18.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.8.0
    bits-ui: ^0.21.16 => 0.21.16
    svelte: ^5.0.0 => 5.1.11
```

### Severity

blocking all usage of shadcn-svelte

**Comment by joshdavham** [comment]
@ieedan 

> Import tailwind-variants as a dev dependency.

Yup. It was, but I still got the above issue.

> Also what version of the cli are you using I think this should be fixed in later versions.

Here's what my package.json looked like:

> {
> 	"name": "redacted",
> 	"version": "0.0.1",
> 	"type": "module",
> 	"scripts": {
> 		"dev": "vite dev",
> 		"build": "vite build",
> 		"preview": "vite preview",
> 		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
> 		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
> 		"format": "prettier --write .",
> 		"lint": "prettier --check . && eslint ."
> 	},
> 	"devDependencies": {
> 		"@sveltejs/adapter-auto": "^3.0.0",
> 		"@sveltejs/kit": "^2.0.0",
> 		"@sveltejs/vite-plugin-svelte": "^4.0.0",
> 		"@types/eslint": "^9.6.0",
> 		"autoprefixer": "^10.4.20",
> 		"bits-ui": "^0.21.16",
> 		"clsx": "^2.1.1",
> 		"eslint": "^9.7.0",
> 		"eslint-config-prettier": "^9.1.0",
> 		"eslint-plugin-svelte": "^2.36.0",
> 		"globals": "^15.0.0",
> 		"prettier": "^3.3.2",
> 		"prettier-plugin-svelte": "^3.2.6",
> 		"prettier-plugin-tailwindcss": "^0.6.5",
> 		"svelte": "^5.0.0",
> 		"svelte-check": "^4.0.0",
> 		"tailwind-merge": "^2.5.4",
> 		"tailwind-variants": "^0.2.1",
> 		"tailwindcss": "^3.4.9",
> 		"typescript": "^5.0.0",
> 		"typescript-eslint": "^8.0.0",
> 		"vite": "^5.0.3"
> 	},
> 	"dependencies": {
> 		"firebase": "^10.0.0"
> 	}
> }

I was using shadcn-svelte@latest because I was having even bigger problems with shadcn-svelte@next (on:click wasn't working for <Button>).

Anyways, I decided to switch my project to [flowbite-svelte](https://flowbite-svelte.com/) and it's working just fine deployed on firebase with no issues. I don't think I'll use shadcn-svelte for the time being as it seems like it's a bit too unstable for me at the moment.

Given the above, would you like me to leave this issue up or close it? I think the bug I encountered is legit, but I won't be spending any more time trying to fix it.

**Comment by ieedan** [comment]
on:click won't work on next because the new handlers in svelte 5 are onclick

**Comment by ieedan** [comment]
I really know nothing about deploying on firebase but if you are getting that error it's because it cannot find the dependency since it's not installed you'd get a similar error anywhere you deploy it. Normally that doesn't happen if everything is a devDependency with the way that Svelte bundles dependencies.

**Comment by huntabyte** [comment]
This is out of the scope of the project. Ensure it is installed as a `devDependency` as @ieedan mentioned.

**Comment by joshdavham** [comment]
> Ensure it is installed as a devDependency as ieedan mentioned.

Just for the record, it was. See the `package.json` [here](https://github.com/huntabyte/shadcn-svelte/issues/1459#issuecomment-2463156286)

**Comment by vpusher** [comment]
I observe the behavior described by @joshdavham too (for some other deps of `bits-ui`, .eg. `floating-ui/dom`) when deployed on Firebase hosting (which does not have an official support through SvelteKit adapter). My guess is that the issue is somewhere inside of the deployment component of `firebase-tools` which does not embed `devDependencies` and its sub-dependencies in the `node_modules` folder when building the docker image for Cloud Run.

Quick and dirty workaround is to also declare the "not found" deps under `dependencies`, or their parent. In my case, `bits-ui` directly to cover them all.
