### ISSUE TITLE
Input.svelte should handle type="number" correctly

### ISSUE THREAD

**Issue by proof-llc** [huntabyte/shadcn-svelte#146]
### Current Behavior

<Input type="number"> should have value of type number - not string. it appears that it's a string.

### Expected Behavior

we want the value to be of type number

### Steps To Reproduce

1. npx shadcn-svelte add input

### More Information

one solution that worked for me was to add the following to Input.svelte but perhaps you can think of a less hacky approach:

```ts
export let type: HTMLInputAttributes['type'];
export let value: HTMLInputAttributes['value'] = undefined;

{#if type === 'number'}
    <input
        bind:value
        type="number"
        ....
    />
{:else}
    <input
        bind:value
        ....
    />
{/if}
```

**Comment by huntabyte** [comment]
Does this issue still occur?
