### ISSUE TITLE
Accordion height not animating

### ISSUE THREAD

**Issue by skylerknight** [huntabyte/shadcn-svelte#1469]
### Describe the bug

Accordion height does not animate when opening using the latest `@next` version and `bits-ui@next`

---

NOTE: It appears that in the tailwindcss config the incorrect variable is being used for the animation height.

It's initially using `var(--radix-accordion-content-height)`
But needs to be updated to `var(--bits-accordion-content-height)`

### Reproduction

1. Install the latest version of shadcn-svelte@next (Svelte 5)

2. Install the latest version of bits-ui@next

3. Install the accordion component `npx  shadcn-svelte@next add accordion`

4. Observe that it does not animate when opening

### System Info

```bash
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 120.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    npm: 10.9.0 - /usr/local/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    bun: 1.1.3 - ~/.bun/bin/bun
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.7.4 
    bits-ui: 1.0.0-next.46 => 1.0.0-next.46 
    lucide-svelte: ^0.454.0 => 0.454.0 
    mode-watcher: ^0.4.1 => 0.4.1 
    svelte: ^5.0.0 => 5.1.9
```

### Severity

annoyance

**Comment by ieedan** [comment]
Please run `npx shadcn-svelte@next -v` the latest version should be `1.0.0-next.1` I don't see this issue using the latest version. If you need to update the config you can run `npx shadcn-svelte@next init`.

**Comment by skylerknight** [comment]
Aha,

Will try that. Thanks!
