### ISSUE TITLE
Dependency conflict: svelte-radix requires Svelte 5 while project uses Svelte 4

### ISSUE THREAD

**Issue by onursoyer** [huntabyte/shadcn-svelte#1473]
### Describe the bug

When attempting to install the accordion component using shadcn-svelte (v0.14.0), the installation fails due to a dependency conflict. The project is using Svelte 4.2.19, but svelte-radix@2.0.1 requires Svelte 5.0.0 as a peer dependency, causing an npm ERESOLVE error.

### Reproduction

# Environment setup
npm create svelte@latest my-app
cd my-app
npm install

# Attempt to add shadcn-svelte accordion component
npx shadcn-svelte@latest add
# Select 'accordion' component
# Choose 'Yes' for overwriting components
# Choose 'Yes' for installing dependencies

### Logs

```bash
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error 
npm error While resolving: app@0.0.1
npm error Found: svelte@4.2.19
npm error node_modules/svelte
npm error   dev svelte@"^4.2.19" from the root project
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^5.0.0" from svelte-radix@2.0.1
npm error node_modules/svelte-radix
npm error   dev svelte-radix@"*" from the root project
```

### System Info

```bash
System:
    OS: Linux 6.11 Fedora Linux 41 (Workstation Edition)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 20.51 GB / 46.75 GB
    Container: Yes
    Shell: 5.2.32 - /bin/bash
  Binaries:
    Node: 22.4.1 - /usr/bin/node
    npm: 10.8.1 - /usr/bin/npm
  Browsers:
    Chrome: 130.0.6723.116
  npmPackages:
    @sveltejs/kit: ^2.7.2 => 2.7.2 
    bits-ui: ^0.21.16 => 0.21.16 
    cmdk-sv: ^0.0.17 => 0.0.17 
    formsnap: ^1.0.1 => 1.0.1 
    lucide-svelte: ^0.394.0 => 0.394.0 
    mode-watcher: ^0.3.1 => 0.3.1 
    shadcn-svelte: ^0.14.0 => 0.14.0 
    svelte: ^4.2.19 => 4.2.19 
    svelte-radix: ^1.1.1 => 1.1.1 
    svelte-sonner: ^0.3.28 => 0.3.28 
    sveltekit-superforms: ^2.20.0 => 2.20.0
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Once we merge `next` with `main`, we'll be pinning the versions of the deps. If someone wants to submit a PR to `main` to pin radix-svelte to a version with Svelte 4 support I'll gladly merge.

**Comment by ieedan** [comment]
> Once we merge `next` with `main`, we'll be pinning the versions of the deps. If someone wants to submit a PR to `main` to pin radix-svelte to a version with Svelte 4 support I'll gladly merge.

I can probably make one but I don't think I can properly dedicate any time until Tuesday.
