### ISSUE TITLE
Confusing installation instructions

### ISSUE THREAD

**Issue by Creative-Difficulty** [huntabyte/shadcn-svelte#148]
### Change Type

Correction

### Proposed Changes

In the installation docs (https://www.shadcn-svelte.com/docs/installation) under "New Project" at step 1 ("Run the CLI") it says "Use the SvelteKit CLI to create a new project. Support for Svelte v4 is coming soon, we are just waiting for our dependencies to be updated.", however the command below it uses svelte(-kit) >v4 (npm create svelte@v4.2.0 my-app). This is very confusing, also in the project setup, when running "npm create svelte@v4.2.0 my-app" a warning appears, saying trhat svelte >v4 isnt supported.

**Comment by huntabyte** [comment]
Closed by #150
