### ISSUE TITLE
How to make Dialog controlled?

### ISSUE THREAD

**Issue by aaron-barbieriaghib** [huntabyte/shadcn-svelte#149]
I know i can do <Dialog {open}> but I can't set open=false when the user manually closes it which means future opens via the trigger fail. Am i missing something?

**Comment by Creative-Difficulty** [comment]
I do it like this:
```svelte
<Dialog open={true}>
```

**Comment by huntabyte** [comment]
^ this exact method should work now! You can `bind:open={someVariable}` as well to track the state elsewhere.
