### ISSUE TITLE
next: Render issue when bind:open on Select.Root

### ISSUE THREAD

**Issue by robinbraemer** [huntabyte/shadcn-svelte#1534]
### Describe the bug

The Select component is not rendering correctly when using `bind:open`.

### Reproduction

```svelte
<Select.Root
	bind:open={selectRegionOpen}
	type="single"
	value={cluster.regionId}
	onValueChange={(value) => handleRegionChange(cluster.id, value)}
>
```

![image](https://github.com/user-attachments/assets/661d7753-8016-48f0-957e-32cbaace0fda)

---

Without `bind:` it renders as expected.

![image](https://github.com/user-attachments/assets/78054f65-0662-4d4f-9c29-34a5b4ecfc0c)

```svelte
<Select.Root
	open={selectRegionOpen}
	type="single"
	value={cluster.regionId}
	onValueChange={(value) => handleRegionChange(cluster.id, value)}
>
```

### System Info

```bash
Versions:

- https://github.com/huntabyte/shadcn-svelte/tree/8b0c6d29935f6192b87f6ed5c09cbc12d436873b
- "bits-ui": "1.0.0-next.67"
```

### Severity

annoyance

**Comment by huntabyte** [comment]
I need a minimal reproduction to debug, a snippet of the `Select.Root` component won't suffice as I'm not able to reproduce by simply binding
