### ISSUE TITLE
Fix automatic zoom in on Safari/iOS when focusing textarea or input

### ISSUE THREAD

**Issue by waedi** [huntabyte/shadcn-svelte#1548]
### Describe the bug

Safari on iOS zooms in when the user focuses an <input> or <textarea> with font-size smaller than 16px. After the focus is lost Safari does not zoom out again. This can leave the website in a weird looking state.

When looking for solutions I only found pretty ugly hacks and it made me wonder if this issue happens with shadcn too or how they solved it. Turns out they changed from "text-sm" to "text-base md:text-sm" for Input and Textarea in [this commit](https://github.com/shadcn-ui/ui/commit/13c97acf9f6db4b3e89ec8943b6d4463dc575f85#diff-bccc7161022356d1158e1a6412faf48bbe0c296d0b2aa6146418e9dc582c8901R7)

So I propose to implement this change to solve the issue and also align the behavior of shadcn-svelte with shadcn in this regard.
I can create a PR for this, if that's ok.

### Reproduction

Not really needed I guess as this happens with every Input and Textarea on iOS & Safari

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    Memory: 13.40 GB / 31.34 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.4 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (131.0.2903.51)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    svelte: ^5.10.0 => 5.10.0
```

### Severity

annoyance

**Comment by ieedan** [comment]
Glad they addressed this! I can open a PR in a bit.
