### ISSUE TITLE
Tooltip (next) position broken when wrapped with tailwind's @container

### ISSUE THREAD

**Issue by juanpujol** [huntabyte/shadcn-svelte#1576]
### Describe the bug

Implementing a Tooltip wrapped on a div with the class @container from Tailwind breaks the tooltip content position. Found this while migrating, this works on the current version of shadcn-svelte.

### Reproduction

Install the tailwind component https://github.com/tailwindlabs/tailwindcss-container-queries

Wrap the tooltip on a div with the class `@container`

<div class="@container">
  <Tooltip.Provider>
    <Tooltip.Root>
      <Tooltip.Trigger>
        <p class="font-bold">Test</p>
      </Tooltip.Trigger>
      <Tooltip.Content>Test</Tooltip.Content>
    </Tooltip.Root>
  </Tooltip.Provider>
</div>

### System Info

```bash
System:
    OS: macOS 15.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 317.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: 9.14.2 - ~/Library/pnpm/pnpm
    bun: 1.1.40 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 131.1.73.104
    Chrome: 131.0.6778.85
    Safari: 18.2
  npmPackages:
    @sveltejs/kit: ^2.15.0 => 2.15.0 
    bits-ui: ^1.0.0-next.74 => 1.0.0-next.74 
    formsnap: ^2.0.0 => 2.0.0 
    lucide-svelte: ^0.469.0 => 0.469.0 
    mode-watcher: ^0.5.0 => 0.5.0 
    svelte: ^5.15.0 => 5.15.0 
    svelte-radix: 2.0.1 => 2.0.1 
    svelte-sonner: ^0.3.28 => 0.3.28 
    sveltekit-superforms: ^2.22.1 => 2.22.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Ensure to wrap the `Tooltip.Content` in `Tooltip.Portal`.

**Comment by juanpujol** [comment]
@huntabyte thank you for the reply. I'm sorry, but i must be doing something wrong. I don't see the Porta component on the Tooltip module.

<img width="365" alt="SCR-20241229-rsow" src="https://github.com/user-attachments/assets/57bdb218-3019-44f4-abd5-d99aa9a13c07" />

Is there any documentation on this kind of case that you could share? 

Thank you.

**Comment by huntabyte** [comment]
It should be inside of the `Tooltip.Content`, is it not there already? @juanpujol

**Comment by juanpujol** [comment]
Thank you. Added wrapped the content component within the portal on `tooltip-content.svelte` like this and it worked:

```svelte
<script lang="ts">
  import { cn } from "$lib/utils/ui";
  import { Tooltip as TooltipPrimitive } from "bits-ui";

  let {
    ref = $bindable(null),
    class: className,
    sideOffset = 4,
    ...restProps
  }: TooltipPrimitive.ContentProps = $props();
</script>

<TooltipPrimitive.Portal>
  <TooltipPrimitive.Content
    bind:ref
    {sideOffset}
    class={cn(
      "bg-foreground text-background animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 overflow-hidden rounded-md px-3 py-1.5 text-xs",
      className,
    )}
    {...restProps}
  />
</TooltipPrimitive.Portal>
```

I must have made a mistake while migrating this component.

Thank you 🙏

**Comment by huntabyte** [comment]
Awesome to hear!

**Comment by Verde19** [comment]
Thanks @juanpujol, that worked.

However, I had the same issue, and it looks like [the source code itself doesn't include the portal](https://github.com/huntabyte/shadcn-svelte/blob/main/sites/docs/src/lib/registry/default/ui/tooltip/tooltip-content.svelte).

Another solution would be to export the Portal in the index.ts file (only Root, Trigger and Provider are there now) and wrap in the content manually every time you use it.

In any case, I think this needs a fix.

**Comment by huntabyte** [comment]
This is something we'll fix on our end @Verde19
