### ISSUE TITLE
Misplaced `className` in `buttonVariants`

### ISSUE THREAD

**Issue by frirasyidi** [huntabyte/shadcn-svelte#1582]
### Describe the bug

The `className` is currently placed in `buttonVariants` instead of `cn` function.

Current:
```ts
<ButtonPrimitive.Root
	{builders}
	class={cn(buttonVariants({ variant, size, className }))}
                                                  ^
	// more codes here…
>
```

Should be:
```ts
<ButtonPrimitive.Root
	{builders}
	class={cn(buttonVariants({ variant, size }), className)}
                                                     ^

	// more codes here…
>
```

### Reproduction

The easiest way to find the issue is by using Typescript error on the [Button.svelte file](https://github.com/huntabyte/shadcn-svelte/blob/main/sites/docs/src/lib/registry/new-york/ui/button/button.svelte).

### System Info

```bash
Not available
```

### Severity

annoyance

**Comment by opensas** [comment]
I still get the same error

These are the steps I took:

```shell
$ px sv create shadcn-error
┌  Welcome to the Svelte CLI! (v0.6.10)
◇  Which template would you like?
│  SvelteKit minimal
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint
◇  Which package manager do you want to install dependencies with?
│  pnpm

$ pnpm dlx shadcn-svelte@latest init

$ pnpm dlx shadcn-svelte@latest add button

$ pn check

> shadcn-error@0.0.1 check /home/sas/devel/apps/dgiit/proyectos/tmp/shadcn-error
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json

====================================
Loading svelte-check in workspace: /home/sas/devel/apps/dgiit/proyectos/tmp/shadcn-error
Getting Svelte diagnostics...

/home/sas/devel/apps/dgiit/proyectos/tmp/shadcn-error/src/lib/components/ui/button/button.svelte:18:44
Error: Type 'string | ClassArray | ClassDictionary | null | undefined' is not assignable to type 'ClassNameValue'.
  Type 'ClassArray' is not assignable to type 'ClassNameValue'.
    Type 'ClassValue[]' is not assignable to type 'ClassNameArray'.
      Type 'ClassValue' is not assignable to type 'ClassNameValue'.
        Type 'number' is not assignable to type 'ClassNameValue'. (ts)
        {builders}
        class={cn(buttonVariants({ variant, size, className }))}
        type="button"


====================================
svelte-check found 1 error and 0 warnings in 1 file
 ELIFECYCLE  Command failed with exit code 1.
 ```
 
 should I create a new issue?
 
 this is the package.json file:
 
 ```json
 $ cat package.json 
{
        "name": "shadcn-error",
        "private": true,
        "version": "0.0.1",
        "type": "module",
        "scripts": {
                "dev": "vite dev",
                "build": "vite build",
                "preview": "vite preview",
                "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
                "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
                "lint": "eslint . && prettier --check .",
                "format": "prettier --write ."
        },
        "devDependencies": {
                "@eslint/compat": "^1.2.3",
                "@sveltejs/adapter-auto": "^3.0.0",
                "@sveltejs/kit": "^2.0.0",
                "@sveltejs/vite-plugin-svelte": "^4.0.0",
                "autoprefixer": "^10.4.20",
                "bits-ui": "^0.22.0",
                "clsx": "^2.1.1",
                "eslint": "^9.7.0",
                "eslint-config-prettier": "^9.1.0",
                "eslint-plugin-svelte": "^2.36.0",
                "globals": "^15.0.0",
                "prettier": "^3.3.2",
                "prettier-plugin-svelte": "^3.2.6",
                "prettier-plugin-tailwindcss": "^0.6.5",
                "svelte": "^5.0.0",
                "svelte-check": "^4.0.0",
                "tailwind-merge": "^2.6.0",
                "tailwind-variants": "^0.3.0",
                "tailwindcss": "^3.4.9",
                "typescript": "^5.0.0",
                "typescript-eslint": "^8.0.0",
                "vite": "^5.4.11"
        }
}
```

**Comment by ieedan** [comment]
Use @next instead of @latest.

This should probably be fixed on main as well though.

**Comment by opensas** [comment]
thanks, I'm using next and no problem so far

btw, how are w suppossed to step out of next, when what is currently next becomes the default version?

**Comment by nela** [comment]
The bug still persists on @latest. Using @next, I get an import error from bits-ui, in button/index.ts.

`Module '"bits-ui"' has no exported member 'WithElementRef'.`

**Comment by bigjangmon** [comment]
There's a temporary workaround to fix the `not assignable to type 'ClassNameValue'.` error while keeping the `className` placed inside the `variants` function call.

You can fix this by telling TypeScript that these types are compatible. Create a declaration file in your project:

```typescript
// src/types.d.ts
import type { ClassValue as ClsxClassValue } from 'clsx';

declare module 'tailwind-merge' {
  // Make ClassNameValue compatible with clsx's ClassValue
  export type ClassNameValue = ClsxClassValue;
}
```

This uses declaration merging to align the types, allowing `tailwind-merge` (used by `cn` and `tailwind-variants`) to accept the `ClassValue` from the `className` prop directly.
