### ISSUE TITLE
cannot reproduce the results from docs after fresh installation

### ISSUE THREAD

**Issue by kiran-4444** [huntabyte/shadcn-svelte#1583]
### Describe the bug

Hi, I'm trying shadcn-svelte for the first time. I followed everything from https://shadcn-svelte.com/docs/installation/sveltekit but the `<Button>` isn't getting any styles, it's just a simple HTML `Button` without any styles. But I've expected the Button to have some styles and look better. 

![image](https://github.com/user-attachments/assets/71f86800-c36c-42ae-96c6-0e2eade5bab3)

### Reproduction

I followed the installation docs.

### System Info

```bash
~/Documents/my-app npx envinfo --system --npmPackages svelte,shadcn-svelte,bits-ui,vaul-svelte,sveltekit-superforms,@sveltejs/kit,mode-watcher,formsnap,cmdk-sv,svelte-radix,lucide-svelte,svelte-sonner --binaries --browsers

  System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 112.86 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.7.6 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
    bun: 1.1.42 - ~/.nvm/versions/node/v18.18.0/bin/bun
  Browsers:
    Safari: 17.6
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.15.1 
    bits-ui: ^1.0.0-next.74 => 1.0.0-next.74 
    lucide-svelte: ^0.469.0 => 0.469.0 
    svelte: ^5.0.0 => 5.16.0 

```
```


### Severity

annoyance

**Comment by ieedan** [comment]
A reproduction would be helpful here. More than likely it is an issue with tailwind.

**Comment by huntabyte** [comment]
Yeah, you likely are not importing the `app.css` to your layout is what it looks like to me!
