### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by ftognetto** [huntabyte/shadcn-svelte#166]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hello, congrats for the new release, you did an awesome work, thank you!
is already possibile to use the form components as in the example? https://www.shadcn-svelte.com/examples/forms

Thank you

### What type of pull request would this be?

Guide

**Comment by huntabyte** [comment]
It's still in "preview" at the moment as I work through some of the final details, but you're more than welcome to copy the code from those which can be found [here](https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/registry/new-york/ui/super-form)

Closing this issue as the same thing is being tracked here: #42
