### ISSUE TITLE
Card.Title $$Props mismatch

### ISSUE THREAD

**Issue by nbeerten** [huntabyte/shadcn-svelte#168]
### Current Behavior

Card.Title has this as $$props:
```ts
type $$Props = HTMLAttributes<HTMLHeadingElement> & {
    level?: HeadingLevel;
};
```
and this as exported prop:
```ts
export let tag: $$Props["level"] = "h3";
```

### Expected Behavior

`level` and `tag` are the same.

### Steps To Reproduce

1. Using component Card.Title with default everything

**Comment by huntabyte** [comment]
Thanks for catching this!
