### ISSUE TITLE
Error: Failed to fetch components

### ISSUE THREAD

**Issue by michal-weglarz** [huntabyte/shadcn-svelte#172]
### Current Behavior

When I'm trying to install a component using a command shown directly on a corresponding page in the documentation, I get the following error:
```
Error: Failed to fetch components from https://shadcn-svelte.com/api/components
```

<img width="991" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/37783495/699ca905-7139-4439-be2b-29c3c6cf4dd7">

It happens for all the components I've tried, e.g.:
```
npx shadcn-svelte add skeleton
```

However, when I add `@latest` to it, then it works fine:
```
npx shadcn-svelte@latest add skeleton
```

### Expected Behavior

I expect a component to be installed properly, using the command shown on a corresponding documentation page.

### Steps To Reproduce

1. Go to a component page, e.g. Skeleton.
2. Copy a command from the installation instruction.
3. Use the command in your terminal.
4. See the error. 

### More Information

Using Node.js v18.12.1

**Comment by AdrianGonz97** [comment]
Thanks for raising an issue! This is because we no longer use an API endpoint to fetch the component registry. As a result, previous versions of the CLI will no longer work. 

I've created a PR to fix the installation instructions so that users will use the `@latest` version.
