### ISSUE TITLE
Select component, flickering outline and difference in animation than the react version

### ISSUE THREAD

**Issue by subhendupsingh** [huntabyte/shadcn-svelte#176]
### Current Behavior

https://github.com/huntabyte/shadcn-svelte/assets/5727516/f27d0ee9-1dd9-435a-951d-9f1f1aa627ae

Here on the left side, we have shadcn-svelte and on the right side, we have the react version. In the shadcn-svelte, when the select is clicked, the outline flickers. Also, the animation of the dropdown is not as smooth as the one on the right side.

### Expected Behavior

1. The outline should appear once the item is selected.
2. Animation should match the one in the react version.

### Steps To Reproduce

In the documentation, click on the select component to see the flicker of the outline.

**Comment by huntabyte** [comment]
Thank you @subhendupsingh!

**Comment by huntabyte** [comment]
Hey @subhendupsingh can you confirm if this is resolved with the latest updates to `bits-ui` and `shadcn-svelte`?

**Comment by subhendupsingh** [comment]
Just checked on `shadcn-svelte`, works as expected. Thanks!
I can't seem to find the component on the bits-ui page though!

**Comment by huntabyte** [comment]
Yeah, I'm working with a designer on getting some examples designed for it! Should be soon!
