### ISSUE TITLE
Dialog box trigger inside Dropdown Item is not working

### ISSUE THREAD

**Issue by theetherGit** [huntabyte/shadcn-svelte#177]
### Current Behavior

I have a actions in data-table, which is as your example a dropdown and inside that drop down i have added my dialog component but it's able to trigger it on click.

Example source code:

<script lang="ts">
    import * as DropdownMenu from "../../ui/dropdown-menu";
    import * as Dialog from "../../ui/dialog";
    import { Input } from "../../ui/input";
    import { Label } from "../../ui/label";
    import { Button } from "../../ui/button";
    import { MoreHorizontal } from "lucide-svelte";
    export let data: string;
</script>

<DropdownMenu.Root>
    <DropdownMenu.Trigger asChild let:builder>
        <Button variant="ghost" builders={[builder]} class="h-8 w-8 p-0">
            <span class="sr-only">Open menu</span>
            <MoreHorizontal class="h-4 w-4" />
        </Button>
    </DropdownMenu.Trigger>
    <DropdownMenu.Content>
        <DropdownMenu.Group>
            <DropdownMenu.Label>Update Order</DropdownMenu.Label>
            <DropdownMenu.Item>
                <div class="text-sm px-2 py-1.5">
                    <Dialog.Root>
                        <Dialog.Trigger>
                            Mark ad Delivered
                        </Dialog.Trigger>
                        <Dialog.Content class="sm:max-w-[425px]">
                            <Dialog.Header>
                                <Dialog.Title>Edit profile</Dialog.Title>
                                <Dialog.Description>
                                    Make changes to your profile here. Click save when you're done.
                                </Dialog.Description>
                            </Dialog.Header>
                            <div class="grid gap-4 py-4">
                                <div class="grid grid-cols-4 items-center gap-4">
                                    <Label class="text-right">Name</Label>
                                    <Input id="name" value="Pedro Duarte" class="col-span-3" />
                                </div>
                                <div class="grid grid-cols-4 items-center gap-4">
                                    <Label class="text-right">Username</Label>
                                    <Input id="username" value="@peduarte" class="col-span-3" />
                                </div>
                            </div>
                            <Dialog.Footer>
                                <Button type="submit">Save changes</Button>
                            </Dialog.Footer>
                        </Dialog.Content>
                    </Dialog.Root>
                </div>
            </DropdownMenu.Item>
            <DropdownMenu.Item on:m-click={() => console.log(data)}>
                Add remark
            </DropdownMenu.Item>
        </DropdownMenu.Group>
        <DropdownMenu.Separator />
        <DropdownMenu.Item>View customer</DropdownMenu.Item>
    </DropdownMenu.Content>
</DropdownMenu.Root>

### Expected Behavior

I expect it to open my dialog

### Steps To Reproduce

Add all required components to your project used in above provided example. And you can copy paste it to check the behavoiur.

### More Information

It sometimes opens but never closes with close option and others.

Same kind of behavior with alert dialog too.

**Comment by huntabyte** [comment]
In this case, you'll want to ensure the `DropdownMenu` is inside the `Dialog.Root`, then you should be able to trigger it.

**Comment by theetherGit** [comment]
I think we should add this for example till come with something.

**Comment by huntabyte** [comment]
> I think we should add this for example till come with something.

Edited my comment above ^ @theetherGit

**Comment by theetherGit** [comment]
> > I think we should add this for example till come with something.
> 
> Edited my comment above ^ @theetherGit

Me too

**Comment by theetherGit** [comment]
@huntabyte it's working. I'll use it at more place and look into sheets and action-dialog too. If it's all clear i'll close this one.

**Comment by huntabyte** [comment]
Great to hear!

**Comment by theetherGit** [comment]
Dialog, sheets and action-alerts are working with this.
