### ISSUE TITLE
Data Table Component "breaks" documentation page layout in mobile view

### ISSUE THREAD

**Issue by oscaroox** [huntabyte/shadcn-svelte#178]
### Current Behavior

[screen-capture.webm](https://github.com/huntabyte/shadcn-svelte/assets/6206624/77288653-1961-4ab2-9d42-d7e32eca47e8)

Tried Chrome browser versions:
Chrome: 116.0.5845.97
Chrome Android: 116.0.5845.92

Unlike other components, the Data Table Component seems to be affecting the layout of the documentation page in mobile view. No such issues observed with Firefox browser and Firefox Android.

### Expected Behavior

Data Table Component should preserve docs layout on mobile across Chrome, Firefox, and various devices.

### Steps To Reproduce

use one of the listed browser in the description to view the Datatable component.

**Comment by huntabyte** [comment]
Good catch! Thank you!
