### ISSUE TITLE
Select name attr not applying to Select.Root

### ISSUE THREAD

**Issue by paulrichan** [huntabyte/shadcn-svelte#188]
### Current Behavior

Select.Root is not correctly applying the name attribute to be used in form actions.

### Expected Behavior

Using a name attribute on a raw select html tag does work with form actions in getting the correct value. 

### Steps To Reproduce

1. Use the Select component
2. Apply the name attribute to Select.Root
3. Submit a form and log the form data with a .get(attrbuteName)
4. Value is null

### More Information

![image](https://github.com/huntabyte/shadcn-svelte/assets/75490402/77e99569-fc0e-49ae-b050-29a2574d5dc7)

Raw html select tag result:
![image](https://github.com/huntabyte/shadcn-svelte/assets/75490402/34560bfe-f6c3-4ddc-9323-1a4495357cd3)

Shadcn-Svelte select tag result:
![image](https://github.com/huntabyte/shadcn-svelte/assets/75490402/0436500a-a600-47c5-8ec1-499c22b54f3b)

**Comment by huntabyte** [comment]
You need to add the input as well.

`<Select.Input />`

**Comment by paulrichan** [comment]
My apologies, I should have looked into the documentation a little more! Appreciate this effort a ton.

**Comment by huntabyte** [comment]
No worries, the docs are pretty scarce at the moment! I anticipated these issues would arise, just wanted you to know that I'm working on it :)
