### ISSUE TITLE
Checkbox is not submitted with form

### ISSUE THREAD

**Issue by chientrm** [huntabyte/shadcn-svelte#189]
### Current Behavior

Checkbox is not submitted with form.

### Expected Behavior

formData value for `rememberMe`.

### Steps To Reproduce

```html
<form method='POST'>
    <div class="flex items-center space-x-2">
      <Checkbox id="rememberMe" name="rememberMe" checked />
      <Label for="rememberMe">Remember me</Label>
    </div>
</form>
```

**Comment by huntabyte** [comment]
I'm working on the optimal way to handle this, but at the moment, you can do the following as a temp solution until something is pushed to `bits`. Apologies about that.

```svelte
<script lang="ts">
	import { Checkbox } from '$lib/components/ui/checkbox'
	let checkboxValue = true
</script>


<form method='POST'>
	<div class="flex items-center space-x-2">
	  	<Checkbox id="rememberMe" bind:checked={checkboxValue} />
		<input hidden name="rememberMe" value={checkboxValue} />
	  	<Label for="rememberMe">Remember me</Label>
    </div>
</form>
```

**Comment by huntabyte** [comment]
Should an input automatically be included with the `<Checkbox />` component? At the moment I don't see why not, but unsure if I'm missing any implications here.

The alternative is to add a hidden input when you need one.

**Comment by chientrm** [comment]
> 

Yes it is.

The hidden input is a viable solution but a native `input` element is better so that would comply with SvelteKit's Progressive Enhancement.

**Comment by chientrm** [comment]
> Should an input automatically be included with the `<Checkbox />` component? At the moment I don't see why not, but unsure if I'm missing any implications here.
> 
> The alternative is to add a hidden input when you need one.

Same bug with `<Switch />` 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by huntabyte** [comment]
We're not going to be converting the switch/checkbox into primitive `<input type="checkbox" />`.

You're more than welcome to apply the styles and implement them yourself if you want, but the method I showed previously is how it's going to remain for the time being.

**Comment by aldo-roman** [comment]
Hello @huntabyte With the current implementation, the `<Checkbox>` component is no usable on its own on a form, whereas the other components (such as `<Input>`) are.

Could we revisit this decision and add the `<input type="hidden" />` as part of the checkbox? I don't think there is a need to convert it to `<input type="checkbox" />`.

Thanks!

**Comment by DePasqualeOrg** [comment]
I've migrated to Svelte 5 and am having trouble with the checkbox. Do we still need a shadow checkbox in the latest version? How can we access the `checked` value in the latest version?

**Comment by baderj** [comment]
Yes you still need to manually add the hidden input. Fortunately, you can just edit `checkbox.svelte` and get a Checkbox that automatically works with forms. Just add a hidden `input` whenever the prop `name` is set on `Checkbox`. Note that you need to remove `name` from the `restProps` so name is not added to the checkbox component (forms only allow each name to appear once). 


```svelte
<script lang="ts">
	import { Checkbox as CheckboxPrimitive } from 'bits-ui';
	import CheckIcon from '@lucide/svelte/icons/check';
	import MinusIcon from '@lucide/svelte/icons/minus';
	import { cn, type WithoutChildrenOrChild } from '$lib/utils.js';

	let {
		ref = $bindable(null),
		checked = $bindable(false),
		indeterminate = $bindable(false),
		name,
		class: className,
		...restProps
	}: WithoutChildrenOrChild<CheckboxPrimitive.RootProps> = $props();
</script>

{#if name}
	<input type="hidden" {name} value={checked} />
{/if}
<CheckboxPrimitive.Root
	bind:ref
	data-slot="checkbox"
	class={cn(
		'peer flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input shadow-xs transition-shadow outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground dark:bg-input/30 dark:aria-invalid:ring-destructive/40 dark:data-[state=checked]:bg-primary',
		className
	)}
	bind:checked
	bind:indeterminate
	{...restProps}
>
	{#snippet children({ checked, indeterminate })}
		<div data-slot="checkbox-indicator" class="text-current transition-none">
			{#if checked}
				<CheckIcon class="size-3.5" />
			{:else if indeterminate}
				<MinusIcon class="size-3.5" />
			{/if}
		</div>
	{/snippet}
</CheckboxPrimitive.Root>
```
