### ISSUE TITLE
Weird behavior of input box inside dialog.

### ISSUE THREAD

**Issue by huntabyte** [huntabyte/shadcn-svelte#201]
### Discussed in https://github.com/huntabyte/shadcn-svelte/discussions/183

<div type='discussions-op-text'>

<sup>Originally posted by **theetherGit** August 21, 2023</sup>

https://github.com/huntabyte/shadcn-svelte/assets/71087863/9486f316-d156-4801-94bb-1b03e0aeb829

As you can see above when a input is in focus and i move cursor over it, text get selected automatically that's not a expected behavior.</div>

**Comment by theetherGit** [comment]
@huntabyte i found little bit more issues. And it really hard to keep with them. I think it's better to share repo access with you or showcase all the issues anywhere?

**Comment by theetherGit** [comment]
One more addition 

https://github.com/huntabyte/shadcn-svelte/assets/71087863/75699671-6eeb-45e2-8f5f-fde8c76763df

When a dialog box is open and press spacebar it get closed. Nothing just closes it self only in dialog box.

https://github.com/huntabyte/shadcn-svelte/assets/71087863/cf8f7352-d379-4aa9-97ab-1b845d90b6b0

In this i'm pressing spacebar and it's not taking it as input.

**Comment by huntabyte** [comment]
> @huntabyte i found little bit more issues. And it really hard to keep with them. I think it's better to share repo access with you or showcase all the issues anywhere?

@theetherGit thanks for pointing these out! We are working on all of these as we speak! If you wouldn't mind opening an individual issue for each so we can resolve them each!

**Comment by huntabyte** [comment]
No worries at all! Is this issue good to close? @theetherGit

**Comment by theetherGit** [comment]
yes not just this one other too i have created them in issue too.
