### ISSUE TITLE
AlertDialog trigger is not clickable

### ISSUE THREAD

**Issue by leonardodipace** [huntabyte/shadcn-svelte#207]
### Current Behavior

I copied the AlertDialog [example from the docs](https://www.shadcn-svelte.com/docs/components/alert-dialog) and I'm not able to click on the "Show Dialog" button to open the dialog

### Expected Behavior

After clicking the "Show Dialog" button, the AlertDialog should appear, but the cursor is unable to reach the button.

### Steps To Reproduce

1. Copy the [example code from the docs](https://www.shadcn-svelte.com/docs/components/alert-dialog)
2. Run `npm run dev`
3. Click on the Show Dialog button

### More Information

After opening the DevTools, I noticed a fixed div covering the button (and the whole page) and it looks like it's coming from the AlertDialog overlay:
![image](https://github.com/huntabyte/shadcn-svelte/assets/63299726/53a9b4c3-385e-4ff0-9209-c3a7699f29a9)

**Comment by huntabyte** [comment]
Hey there @leonardodipace , thanks for pointing this out! Please update `bits-ui` to latest (0.0.33) and this issue should be resolved! Let me know if it isn't!

**Comment by leonardodipace** [comment]
Updating `bits-ui` fixed the bug, thanks!
