### ISSUE TITLE
Select broken with latest lucide-svelte

### ISSUE THREAD

**Issue by saturnonearth** [huntabyte/shadcn-svelte#231]
### Current Behavior

ChevronDown is broken via Select Component with latest `lucide-svelte` v0.270.0

### Expected Behavior

Proper importing from Lucide

### Steps To Reproduce

Install latest lucide-svelte and try Select component.

**Comment by Rykuno** [comment]
Solution for anyone looking at this atm is to just roll back to `v0.269.0` btw

**Comment by eric-naguras** [comment]
Same problem. For now replaced lucide-svelte ChevronDown with another icon library (iconify)  as a work-around. 
I hope this gets fixed. Excellent UI package. I like it a lot so far.
```
// import { ChevronDown } from "lucide-svelte";
import Icon from '@iconify/svelte';

<div>
     <!-- <ChevronDown class="h-4 w-4 opacity-50" /> -->
     <Icon icon="mdi:chevron-down" class="h-4 w-4 opacity-50" />
</div>

```

**Comment by saturnonearth** [comment]
This appears to be an issue with Lucide, see
https://github.com/lucide-icons/lucide/issues/1536

I wonder if it's better to just use the raw SVG's of the icons currently in the library as opposed to relying on Lucide as a dependency? The less dependencies the better?

**Comment by huntabyte** [comment]
> The less dependencies the better?

Not always true, nor efficient.

For now, roll `lucide-svelte` back to the last working version `v0.269.0`, and I'll close this issue once it's resolved on the lucide end.

**Comment by huntabyte** [comment]
Issue closed by https://github.com/lucide-icons/lucide/pull/1548 which fixes the bug introduced into Lucide svelte!

Thanks!
