### ISSUE TITLE
Link to view example code for playground are broken.

### ISSUE THREAD

**Issue by HubbeDev** [huntabyte/shadcn-svelte#246]
### Change Type

Correction

### Proposed Changes

The link to view source code at https://www.shadcn-svelte.com/examples/playground are broken and gives 404.

They are currently leading to https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/apps/www/app/examples/playground

Update link to https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/routes/examples/playground

**Comment by huntabyte** [comment]
Hey thanks for pointing that out, feel free to open a PR if you have the time!
