### ISSUE TITLE
Can't find module @/registry/default/ui/button

### ISSUE THREAD

**Issue by kissecx** [huntabyte/shadcn-svelte#251]
### Current Behavior

Hi,

first of all I'm new to svelte and new to shadcn-ui so please be patient 😄 

I followed the instructions for installing shadcn-ui for svelte with creating a new project .
I've set the aliases for components and lib which worked well.

Unfortunately the components which should be located in @/registry ... couldn't be found.

![image](https://github.com/huntabyte/shadcn-svelte/assets/133776547/3b4c8693-f481-4d0a-a032-28778816192f)

Another beginner question: My components folder is empty after install shadcn with the usage of npx cmd. This isn't the expecated behaviour right?

Anyways appreciating your efforts guys!

### Expected Behavior

-

### Steps To Reproduce

1.  Installed shadcn while using the "New project" instructions
2. Tried to copy the auth-form component of https://www.shadcn-svelte.com/examples/authentication

**Comment by huntabyte** [comment]
Hey there @kissecx, those are aliases I'm using internally for the docs. You'll want to update those to be whatever alias you set!

For example, if you set the alias to be `$lib/components`, then you'd update those imports to:
`from "$lib/components/ui/button"`
