### ISSUE TITLE
AlertDialog Button Not Submit on:keydown

### ISSUE THREAD

**Issue by yomp-admin** [huntabyte/shadcn-svelte#257]
### Current Behavior

 When I use the Tab to select any button on the dialog, if I press enter nothing is working yet onclick event is firing correctly.

### Expected Behavior

When I use the tab key for selection, on Enter keydown I expect the button to execute a function. 

### Steps To Reproduce

<AlertDialog.Footer>
    <AlertDialog.Cancel>Cancel</AlertDialog.Cancel>
    <AlertDialog.Action on:click={() => console.log('button clicked')} on:keydown={e=>e.key==='Enter' && console.log('button clicked')}>
        Continue
    </AlertDialog.Action>
</AlertDialog.Footer>

**Comment by DevilWarrior** [comment]
Hi there, this is still happening to me on:

"bits-ui": "^0.18.0"
"svelte": "^4.2.7",
"@sveltejs/kit": "^2.0.0",

AlertDialog action on:click is triggered properly when using the mouse but navigating with TAB and pressing enter does close the dialog but it doesn't trigger the click event.

**Comment by cedricd-campfire** [comment]
Hello

I have the same issue.

I'm using:

"bits-ui": "^0.21.13",
"svelte": "^4.2.18",

I found a workaround, but it doesn't feel right to use it like this.

```js
<AlertDialog.Action asChild let:builder>
    <div use:builder.action {...builder}>
        <Button
            {...builder}
            on:click={onSaveComment}
            on:keydown={(e) => e.key === "Enter" && onSaveComment(e)}
            >Save
        </Button>
    </div>
</AlertDialog.Action>
```
            
            
Isn't it meant to work like this?

```js
<AlertDialog.Action
    on:confirm={onSaveComment}
    on:click={onSaveComment}
    on:keydown={(e) => e.key === "Enter" && onSaveComment(e)}
    >Save
</AlertDialog.Action>
```


Or a custom event would be even better, in order to not forget about one of the 2 events:

```js
<AlertDialog.Action
    on:confirm={onSaveComment}
    >Save
</AlertDialog.Action>
```
