### ISSUE TITLE
Select value binding

### ISSUE THREAD

**Issue by wingi11** [huntabyte/shadcn-svelte#261]
### Current Behavior

When we want to bind the selected value to a store/variable the object with value and label is bound.

It is also noticeable on the examples page: https://www.shadcn-svelte.com/examples/forms. If you change a select form field an error gets displayed that it expects a string but received an object (`Expected string, received object`).

### Expected Behavior

Add the option to bind the value (`bind:value={}`).

### Steps To Reproduce

Use the select component and try to bind selected:
```svelte
    <Select.Root bind:selected={value}>
      <Select.Trigger class="w-[180px]">
        <Select.Value />
      </Select.Trigger>
      <Select.Content>
        <Select.Item value="optiona">a</Select.Item>
        <Select.Item value="optionb">b</Select.Item>
      </Select.Content>
    </Select.Root>
```

### More Information

Is this already on the radar with the superforms integration or is there already a way to directly bind the selected option value?

**Comment by huntabyte** [comment]
This is handled better in the recently released forms integration. There is no intention of being able to `bind:value` at this point in time due to synchronization with the label on SSR.

**Comment by Skylli202** [comment]
Hi,

Then how are we supposed to bind the select value to our component prop to react on a chance of the selected value ? 

In my case, I am not even in a `HTMLFormElement`.

**Comment by fen89** [comment]
> Hi,
> 
> Then how are we supposed to bind the select value to our component prop to react on a chance of the selected value ?
> 
> In my case, I am not even in a `HTMLFormElement`.
> 
> My main issue is that `select` is an object with 3 properties, so I `bind:selected={foo}` and I do a reactive statement `$: value = foo.value`. Would be neat to just do `bind:value`.

I am having the exact same issue. A simple bind:value would be the best in this case. 

Because for every select to create a wrapper function and use it like this is cumbersome and errorprone, because I need to type everything as any:

```svelte
<script>
        let filters: { timeRange: 'today' | 'week' | 'month' | 'quarter' } = {
            timeRange: 'today'
        };
	const timeRangeOptions = [
		{ text: 'Heute', value: 'today' },
		{ text: 'Woche', value: 'week' },
		{ text: 'Monat', value: 'month' },
		{ text: 'Quartal', value: 'quarter' }
	];

	function handleFiltersChange() {
		dispatch('filtersChange', filters);
	}

	function setTimeRange(range: any) {
		filters.timeRange = range;
	}
</script>

<Select.Root onSelectedChange={(v)=> {
	handleFiltersChange();
	setTimeRange(v?.value);
}}>
    [...]
</Select.Root>
```

Another option is still cumbersome and errorprone:

```svelte
<script>
function getSelectOptionValue(selectOption: { value: unknown } | undefined): any {
	return selectOption?.value as any;
}
</script>

<Select.Root onSelectedChange={(v) => {
	filters.timeRange = getSelectOptionValue(v);
}}>
[...]
</Select.Root>

```
