### ISSUE TITLE
Adding the form component doesn't replace `@/utils` with `config.aliases.utils`

### ISSUE THREAD

**Issue by tmadge** [huntabyte/shadcn-svelte#263]
### Current Behavior

A few of the new form components reference `@/utils` instead of `$lib/utils` which don't get replaced with `config.aliases.utils` by the CLI.

For example:
`form-description.svelte`
https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/default/ui/form/form-description.svelte#L3

### Expected Behavior

`@/utils` should be replaced with `config.aliases.utils` from `components.json`.

### Steps To Reproduce

1. Install shadcn-svelte  
    https://www.shadcn-svelte.com/docs/installation#new-project
2. Add the form components  
    ```
    npx shadcn-svelte@latest add form
    ```
3. Open `components/ui/form-description.svelte` and see `import { cn } from "@/utils";`

**Comment by tmadge** [comment]
Is it worth updating `transformImport` to replace both `$lib/utils` and `@/utils` to catch this from happening again in the future?

**Comment by AdrianGonz97** [comment]
@tmadge Not sure if that would be the best approach. While it would cover the accidental case of using `@/utils`, I would also have to add cases for the relative paths as well. Instead, I think the best way to go about it would be to maintain this pattern of only using `$lib/utils` in the registry code and probably add an eslint rule to catch these errors in CI.
