### ISSUE TITLE
[Question] How to use in a monorepo?

### ISSUE THREAD

**Issue by hugotox** [huntabyte/shadcn-svelte#266]
Hello!

I'm trying to set up a component library with `shadcn-svelte` in a monorepo (turborepo). 

I'll use my component library in 2 different apps:
```
/apps
  /admin 
  /portal
/packages
  /ui
    /src
      /lib
        /components
          /ui
```
I'm using the svelte package template to build the `ui` package, and I'm able to import the components in my apps, but none of the styles are applied.
I have tried copying and pasting the `app.css` and the `tailwind.config.js` from the `ui` package into each of the apps, with no luck.

Any advice how to properly set up a component lib in a monorepo? 

Thanks a lot for this great project!!

**Comment by huntabyte** [comment]
I'll defer to @multiplehats on this one as I believe he's done something similar in the past.

**Comment by hugotox** [comment]
Thank you! All working as expected now!
