### ISSUE TITLE
Form select not showing value

### ISSUE THREAD

**Issue by ftognetto** [huntabyte/shadcn-svelte#269]
### Current Behavior

When I save the form and the page reload the select are showing the placeholder value instead of the value saved.
If I save again I get the correct value in action, so it's only a matter of ui.

### Expected Behavior

I would expect that if the select has a value, that value would be shown instead of the placeholder

### Steps To Reproduce

Using the select in this way it works

```
<FormField {config} name="startHour" let:value>
				<FormItem>
					<FormSelect>
						<FormSelectTrigger placeholder={value || 'HH'} />
						<FormSelectContent>
							<FormSelectItem value="8">08</FormSelectItem>
							<FormSelectItem value="9">09</FormSelectItem>
							<FormSelectItem value="10">10</FormSelectItem>
							<FormSelectItem value="11">11</FormSelectItem>
							<FormSelectItem value="12">12</FormSelectItem>
							<FormSelectItem value="13">13</FormSelectItem>
							<FormSelectItem value="14">14</FormSelectItem>
							<FormSelectItem value="15">15</FormSelectItem>
							<FormSelectItem value="16">16</FormSelectItem>
							<FormSelectItem value="17">17</FormSelectItem>
							<FormSelectItem value="18">18</FormSelectItem>
							<FormSelectItem value="19">19</FormSelectItem>
							<FormSelectItem value="20">20</FormSelectItem>
						</FormSelectContent>
					</FormSelect>
					<FormValidation />
				</FormItem>
			</FormField>
```
With let:value and placeholder showing value

**Comment by huntabyte** [comment]
Thanks for raising this issue! Will investigate!

**Comment by huntabyte** [comment]
Okay so because the `Select` component has no way of knowing what the label for the selected value is, due to SSR and conditional rendering of the items when the menu is open, you'll need to setup a way to grab the appropriate label for what the value is and apply it.

Here's an example implementation you can follow:
https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/routes/examples/forms/account/account-form.svelte

**Comment by ftognetto** [comment]
Ok, Thank you!

Is it the same thing to use let:value instead of let:attrs?

Like this

```
<Form.Field {config} name="language" let:value>
			<Form.Label>Language</Form.Label>
			<Form.Select selected={{ value, label: languages[value] }}>
				<Form.SelectTrigger
					placeholder="Select language"
					class={cn(
						"w-[200px] justify-between",
						!value && "text-muted-foreground"
					)}
				/>
				<Form.SelectContent class="h-52 overflow-y-auto">
					{#each Object.entries(languages) as [value, lang]}
						<Form.SelectItem {value}>
							{lang}
						</Form.SelectItem>
					{/each}
				</Form.SelectContent>
			</Form.Select>
			<Form.Description>
				This is the language that will be used in the dashboard.
			</Form.Description>
			<Form.Validation />
		</Form.Field>
```

**Comment by tmadge** [comment]
@ftognetto it looks like `let:value` and `attrs.input.value` are the same, so either should work.
