### ISSUE TITLE
Alignment of buttons containing an icon

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/shadcn-svelte#271]
### Current Behavior

Experimenting with the buttons from the docs, I noticed that buttons containing an icon have their positioning changed slightly (to become higher). 

Default:
<img width="996" alt="Screenshot 2023-09-07 at 11 38 54 AM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/ba576488-91c1-48a4-999d-73c04a9743db">

Experimenting shows it's the height of the icon that influences this, up to a certain value, beyond which the visual size of the icon no longer changes: 
<img width="967" alt="Screenshot 2023-09-07 at 11 39 30 AM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/f6c73602-308f-4440-a9bf-8f10e9312f40">

Easiest solution is to wrap all icons in a container and use flex to align items: 
<img width="996" alt="Screenshot 2023-09-07 at 11 41 30 AM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/9b48abc9-89f7-4690-950a-f305a9adee5f">

But I'm curious if it might be possible to address icon styling, in order to make it easier for other devs out of the box. I don't know a solution offhand to achieve this, so wanted to open this for discussion. Any ideas?

### Expected Behavior

I would expect all buttons to have same vertical alignment. 

### Steps To Reproduce

Just add buttons from the docs:

```svelte
<script>
	import { Button } from '$lib/components/ui/button';
	import { Mail } from 'lucide-svelte';
	import { ChevronRight } from 'lucide-svelte';
	import { Loader2 } from 'lucide-svelte';
</script>

	<div class="flex items-center">
		<Button>Button</Button>
		<Button variant="secondary">Button</Button>
		<Button variant="outline">Button</Button>
		<Button variant="ghost">Button</Button>
		<Button variant="link">Button</Button>
		<Button variant="destructive">Button</Button>
		<Button>
			<Mail class="mr-2 h-4 w-4" />
			Login with Email
		</Button>

		<Button disabled>
			<Loader2 class="mr-2 h-4 w-4 animate-spin" />
			Please wait
		</Button>

		<Button variant="outline" size="icon">
			<ChevronRight className="h-4 w-4" />
		</Button>
	</div>
```

**Comment by Scooter1337** [comment]
This is very weird behaviour, can't really find any other topics that discuss it online.
For some reason, the SVG (or its child nodes) changes the offsetTop property from 3px to 0px.

If you use a 4x4 svg then another (temporary) fix is adding relative and top-[3px] to the button class:
```
<Button class="relative top-[3px]">
	<Mail class="mr-2 h-4 w-4" />
	Login with Email
</Button>
```
