### ISSUE TITLE
Add `whitespace-nowrap` to buttons by default

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/shadcn-svelte#272]
### Current Behavior

At constrained screen sizes, button text wraps in a way that I don't think devs will ever intend.

<img width="712" alt="Screenshot 2023-09-07 at 11 55 08 AM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/9cd9e4c3-cc75-4e9a-85ea-2938d7f1f7dd">

Could fix by adding `whitespace-nowrap` by default to buttons.

<img width="736" alt="Screenshot 2023-09-07 at 11 59 57 AM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/3dc04c8d-e36c-4f12-82a4-82bbc3641bd3">

### Expected Behavior

Button text should remain on one line. 

### Steps To Reproduce

Add a bunch of stuff to the same line, including a button with more than one word, and then resize browser viewport to be small horizontally.

**Comment by HubbeDev** [comment]
I could take a look at this.
