### ISSUE TITLE
Improve CLI output

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/shadcn-svelte#273]
### Current Behavior

As a new user, adding a component shows me:

<img width="568" alt="Screenshot 2023-09-07 at 12 09 15 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/b33d7a4b-3b32-41f5-81fa-1d9421e1d84a">

Based on the yellow text, my first thought was that it found a conflict and was going to overwrite something, but that it just wasn't telling me what it knew something would be overwritten.

But it actually was not going to overwrite any existing files within my project and was scary for no reason.

When I ran it twice, so that it would actually overwrite existing files, the CLI is smart enough to detect this and show a different warning:
<img width="609" alt="Screenshot 2023-09-07 at 12 09 26 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/50032291/f915b3cd-4aa8-48dd-9b2a-68125d4a31d5">

### Expected Behavior

I think this could be made friendly and more useful with a few tweaks:

1. I would expect to never see the first 2 yellow lines. They're scary for no benefit given the CLI can know if there will be conflicts.

2. I would expect the CLI to detect if files exist on disk that would conflict--which it does already--and only to warn me in that case. It would be beneficial if this text also guided devs where in the file structure they can look to find the conflict:

    ```
    Component already exists at $lib/components/ui/button/
    Use --overwrite to overwrite.
    ```

3. When successfully installing, the text would be more helpful if it told devs what changed in their project so they know where to look, for example:

    ```
    ✔ Ready to install components and dependencies. Proceed? … yes
    ⠋ Installing components...

    ✔ Done. Installed at $lib/components/ui/button/
    ```

### Steps To Reproduce

-

**Comment by huntabyte** [comment]
Nice catch @jasongitmail, thanks for raising the issue!

**Comment by skoriop** [comment]
Hi, I'd like to work on this if it's still up :)

**Comment by huntabyte** [comment]
You got it! @skoriop

**Comment by TheComputerM** [comment]
> Hi, I'd like to work on this if it's still up :)

I am up for you bby

**Comment by HubbeDev** [comment]
@skoriop @huntabyte how is the status on this? 

I got some time over next week. Could take a look at it if not started.
