### ISSUE TITLE
Nesting context menus. Triggers both.

### ISSUE THREAD

**Issue by HubbeDev** [huntabyte/shadcn-svelte#274]
### Current Behavior

Hi, 

If i have 2 nested context menus and click on the nested trigger element. Both is openening and the parent/outer context menu is overlaying the nested one.

```svelte
<ContextMenu.Root >
        <ContextMenu.Trigger>
                <div>
                        {#if components}
                                {#each components as component}
                                        <div>
                                                <ContextMenu.Root>
                                                        <ContextMenu.Trigger  >
                                                                {component.text}
                                                        </ContextMenu.Trigger>
                                                        <ContextMenu.Content>
                                                                <ContextMenu.Item>Inner context menu item</ContextMenu.Item>
                                                        </ContextMenu.Content>
                                                 </ContextMenu.Root>
                                        </div>
                                {/each}
                        {/if}
                </div>
        </ContextMenu.Trigger>  
        <ContextMenu.Content>
                <ContextMenu.Item>Outer context menu itex</ContextMenu.Item>
        </ContextMenu.Content>
</ContextMenu.Root>
```

### Expected Behavior

If nested trigger element is clicked only that context menu should open.

### Steps To Reproduce

1.  Add 1 context menu components
2.  Add another one inside the first trigger.

### More Information

I do not know if this is a bug or just how it is intendet to be. Maby im just missing something.

**Comment by huntabyte** [comment]
Why is that nested menu inside of the main menu's trigger?

**Comment by HubbeDev** [comment]
@huntabyte Thanks for your answere. The thing im trying to do is wrapping a fullscreen div with the context menu. When clicking inside the div it should trigger the context menu. 

But if you click any element inside the div for example another h1. it should trigger another context menu. Maby im just overtinking this and it could be done with just 1 context menu and conditionaly check wich items to show in the actually popup.

**Comment by HubbeDev** [comment]
@huntabyte I think i was too tired yesterday when i tried this. Got everything working before when i got home from work. Thank you for the time to check this out.

**Comment by domw95** [comment]
I am trying to achieve separate context menus for nested components as outlined in the image above.  What changes need to be made to the example at the top to get this to work?
