### ISSUE TITLE
Feature Request: Datepicker

### ISSUE THREAD

**Issue by theetherGit** [huntabyte/shadcn-svelte#287]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I'm using shadcn in my svelte project and it needs a date picker and date range picker. I tried with other libraries also looked with headless but UI mixmatch issues with my own implementations.

Can we expect a Datepicker sooner?

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
Yeah! As soon as the calendar is ready to go in Melt UI we will have a date picker.

**Comment by buhodev** [comment]
> I think it's going to take some time

Now there's a [PR](https://github.com/melt-ui/melt-ui/pull/527) :)

**Comment by huntabyte** [comment]
Will be implemented in bits-ui once https://github.com/melt-ui/melt-ui/pull/527 is complete, and then brought here.

**Comment by raiyansarker** [comment]
Is there any update?

**Comment by raiyansarker** [comment]
> Will be implemented in bits-ui once [melt-ui/melt-ui#527](https://github.com/melt-ui/melt-ui/pull/527) is complete, and then brought here.

the pr is merged btw!

**Comment by theetherGit** [comment]
https://github.com/huntabyte/bits-ui/pull/171 please check this.

**Comment by Creative-Difficulty** [comment]
@huntabyte Is a time picker coming to the date picker? imo its essential for many (including my) use case.
