### ISSUE TITLE
AlertDialog.Action not executing callbacks

### ISSUE THREAD

**Issue by amirbenasr** [huntabyte/shadcn-svelte#288]
### Current Behavior

`<AlertDialog.Action
										on:click={(e) => {
											alert("hello svelte");
										}}>Delete</AlertDialog.Action
									>`

simply not executing, as a workaround, i simply exported a callback and attached to the alertDialog action component!

### Expected Behavior

on:click, should simply fire my code before dismissing the alert dialog

### Steps To Reproduce

Using AlertDialog.Root Component, and attaching on:click event to the AlertDialog.Action component

**Comment by huntabyte** [comment]
What version of `bits-ui` are you running?

**Comment by amirbenasr** [comment]
"bits-ui": "^0.5.7",

**Comment by huntabyte** [comment]
Make sure that you're forwarding the `on:click` and `on:keydown` within the `$lib/components/ui/alert-dialog-action.svelte` file!

So it should look something like this:

```svelte
<AlertDialogPrimitive.Action
	class={cn(buttonVariants(), className)}
	{...$$restProps}
	on:click
	on:keydown>
```

**Comment by huntabyte** [comment]
Did this resolve the issue for you? @amirbenasr
