### ISSUE TITLE
There's no mention anywhere in the docs on how to use the Arrow component for floating elements

### ISSUE THREAD

**Issue by buhodev** [huntabyte/shadcn-svelte#290]
### Change Type

Addition

### Proposed Changes

It would be nice if there were a place in the docs that references how to use arrows on floating elements. Also, it would be great if the CLI added an Arrow component (e.g. `menubar-arrow.svelte`) along the components that have floating elements. I checked bits-ui and there's indeed the component, but the CLI doesn't generate it. Thanks for building `bits-ui` and `shadcn-svelte` :heart:

**Comment by huntabyte** [comment]
The arrow component isn't a part of shadcn-svelte, since it's not a part of the original (to my understanding). I'll look into how to use it with the current setup though!
