### ISSUE TITLE
Form component. How to set value an input field

### ISSUE THREAD

**Issue by alexanderscpo** [huntabyte/shadcn-svelte#291]
### Change Type

Addition

### Proposed Changes

If you could describe how I can change the value of the input given an event. I tried using event.target.value, but it didn't work for me because the value is tied to the store. And outside the FormInput component, I cannot call setValue.
```
const changeValue = (event) => {
   event.target.value = 'custom value' // not work
}
<Form.Root {schema} {form} let:config>
  <Form.Field {config} name="email">
    <Form.Item>
      <Form.Label />
      <Form.Input on:input={changeValue/>
      <Form.Description />
      <Form.Validation />
    </Form.Item>
  </Form.Field>
</Form.Root>
```

**Comment by huntabyte** [comment]
If you want to handle the input yourself, you shouldn't be using the `<Form.Input />` but instead using a regular `<Input />` and handling it that way.

**Comment by huntabyte** [comment]
You can reference the [Formsnap docs](https://formsnap.dev) to see the different ways you can update the value outside of the default behavior.

**Comment by alexanderscpo** [comment]
Thank you, I'll check it out 😁
