### ISSUE TITLE
Theme customize style tooltip wrong library

### ISSUE THREAD

**Issue by HubbeDev** [huntabyte/shadcn-svelte#293]
### Change Type

Cleanup (formatting, typos, etc.)

### Proposed Changes

The info tooltip at [Theme showcase ](https://www.shadcn-svelte.com/themes) says "The Default style has larger inputs, uses lucide-react for icons." Should be lucide-svelte?

**Comment by huntabyte** [comment]
That is correct! Thanks for catching it!

**Comment by huntabyte** [comment]
Closed by #296
