### ISSUE TITLE
Form(Preview) doesn't support default values

### ISSUE THREAD

**Issue by callmeberzerker** [huntabyte/shadcn-svelte#295]
### Current Behavior

No default values are being rendered by default.

### Expected Behavior

Default values are being rendered.

### Steps To Reproduce

1. create brand new svelte-kit project and follow the installation instructions in the shadcn-svelte 
2. add the Form component(s)
3. copy-paste the code from the sample profile form

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/github-zxmrcw?file=src%2Froutes%2F%2Bpage.svelte

### More Information

I copied [this form](https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/routes/examples/forms/profile-form.svelte) into my project and basically no `.default()` values are being rendered.

I am well aware that the `default()` values (for the `website` for instance) somehow work on [https://www.shadcn-svelte.com/examples/forms](https://www.shadcn-svelte.com/examples/forms). 

Anyone has any idea?

**Comment by huntabyte** [comment]
When looking at your reproduction it appears that the default values are in fact displaying, can you clarify?

**Comment by callmeberzerker** [comment]
Yeah, I figured it out - I think I totally didn't figure out how the form library works. My initial code (which I hence modified and corrected) was as below. The commented code is an example of making it work with default values. Interesting bit is that if you export the last commented line and add `export` keyword (ie. `export let form = superValidateSync(formSchema)`) it stops working again - and I assumed that the `formSchema` (zod) was enough to render out the default values. :) Anyhow considering this resolved.

```
	let form: SuperValidated<FormSchema>;
	//  let form = defaultValues(formSchema);
	//  let form = superValidateSync(formSchema);
```
