### ISSUE TITLE
How do i update to a newer version

### ISSUE THREAD

**Issue by Creative-Difficulty** [huntabyte/shadcn-svelte#298]
### Current Behavior

Updating is kind of a pain in the a$$, as i have to create a new branch, delete all files in the branch, reinstall svelte and shadcn etc. and then copy my routes and other files over from another branch.

### Expected Behavior

A command line flag when installing shadcn-svelte would be very useful, or an entirley new command in the CLI(`npx shadcn-svelte@latest init --update`, or `npx shadcn-svelte@latest update`).

### Steps To Reproduce

-

**Comment by ftognetto** [comment]
I usually use `npx shadcn-svelte@latest add button --overwrite` (I took as an example the button component)
If I previously edited button component somehow (eg changing background color), check with git diff and redo the changes on the new installed component.
But I do agree It's a price to pay for having the components installed directly in your code instead of having an npm package. Also on original shadcn library there is the same problem

**Comment by Creative-Difficulty** [comment]
Good solution, however, with this method the `utils.ts` is still not updated, which was the culprit of many errors and hours wasted in my case. An update would be nice @huntabyte

**Comment by yomp-admin** [comment]
Yah I would also want this.

**Comment by huntabyte** [comment]
We could possibly add an `update utils` which would overwrite your existing utils with the latest one, but that's as far as it'd go at this point in time.

**Comment by Creative-Difficulty** [comment]
> We could possibly add an `update utils` which would overwrite your existing utils with the latest one, but that's as far as it'd go at this point in time.

That would be very cool

**Comment by DePasqualeOrg** [comment]
I'm getting this error when I run the update command:

```
$ npx shadcn-svelte@latest update --all
Running the following command will overwrite existing files.
Make sure you have committed your changes before proceeding.


FetchError: request to https://shadcn-svelte.com/registry/styles/default/textarea.json failed, reason: write EPROTO C05ED3DE01000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:355:

    at ClientRequest.<anonymous> (file:///Users/anthony/.npm/_npx/a9116f6e444a1e9e/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:515:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:515:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO',
  erroredSysCall: 'write'
}
Failed to fetch tree from registry.

```

**Comment by Skylli202** [comment]
@huntabyte I worked on this issue this evening. Please find my work in the PR #578.
