### ISSUE TITLE
Memory leak with email validation in zod forms

### ISSUE THREAD

**Issue by callmeberzerker** [huntabyte/shadcn-svelte#300]
### Current Behavior

The browser tab hangs and crashes

### Expected Behavior

Email validation works 

### Steps To Reproduce

1. basically start writing in the email field with characters and browser tab will grind to a halt (enter at least 50 characters)

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/github-zxmrcw?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte

### More Information

I did some testing and this _only_ happens when validating the _email_ constraint -> and I have no running hypothesis why is that the case.

**Comment by huntabyte** [comment]
Interesting 🤔, thanks for raising this issue, I'll look into it!

**Comment by huntabyte** [comment]
Closing this as it's an issue with Zod itself, rather than `shadcn-svelte` or `formsnap` - see: https://github.com/colinhacks/zod/issues/2580

You can find some example workarounds in this issue here in the meantime: https://github.com/colinhacks/zod/issues/2609

**Comment by callmeberzerker** [comment]
Thank you so much!
