### ISSUE TITLE
The examples in "Toggle" component always shows the code even when the tabs is in preview

### ISSUE THREAD

**Issue by rifandani** [huntabyte/shadcn-svelte#310]
### Change Type

Correction

### Proposed Changes

The code in examples should only be displayed when the tabs "code" is selected like in other pages.

Screenshots:

<img width="681" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/57568218/295c24a1-1e92-4f73-b81b-8fab56196127">

**Comment by huntabyte** [comment]
Thanks for raising this!
