### ISSUE TITLE
Input Element ignores number types and returns strings

### ISSUE THREAD

**Issue by fen89** [huntabyte/shadcn-svelte#312]
### Current Behavior

```svelte
<script lang="ts">
let text = 'Hello world!';
let number = 1;

$: console.log({ text: text, number: number });
</script>

<Input type="text" bind:value={text} />
<Input type="number" bind:value={number} />
```

![svelte-input](https://github.com/huntabyte/shadcn-svelte/assets/4036376/a529f75c-e4ee-4d31-ad34-033ecdd88d0e)

### Expected Behavior

I expect to get a string value on the `string` value and number value on the `number` value.

### Steps To Reproduce

1. Use Input Component
2. Pass in `type=number`
3. Check return type of `value` which is a string instead of a number 

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/vitejs-vite-ffby8e?file=src%2FApp.svelte

### More Information

According to Rich Harris in this [Stackoverflow Thread](https://stackoverflow.com/questions/57392773/error-type-attribute-cannot-be-dynamic-if-input-uses-two-way-binding) it is possible to get numbers correctly returned from an input component .

I added a second version of the input component inside the Stackblitz to show that it is indeed possible.

Please let me know if you need any further information.

**Comment by lucien-neuhoff** [comment]
Same issue on `Select` where the value is a number

**Comment by huntabyte** [comment]
Are we thinking this fix should be a part of the input component by default? I'm just trying to think of the implications of setting the value like that and then dispatching the same `on:input` event so that it can be handled by the dev.

Interested in hearing thoughts on this

**Comment by fen89** [comment]
@huntabyte I would tend to break the input component instead into smaller components for specific use cases, e.g. instead of one big input component handling all cases I would prefer having multiple ones for specific purposes (InputText, InputNumber, etc). 

> Are we thinking this fix should be a part of the input component by default? I'm just trying to think of the implications of setting the value like that and then dispatching the same event so that it can be handled by the dev.

The problem with the fix above is indead as you said that we would just blew up that one Input component with implicit logic for special cases. There are two possible solutions to this which came to my mind: 

1. Leave as is, maybe provide something in the docs to tell people that if they need e.g. a `NumberInput `that they should wrap the normal `Input` in a custom component and maybe show a small code example on how to do that.
2. Create more custom components: Breaking the input component into smaller components for specific use cases, e.g. instead of one big input component handling all cases having multiple ones for specific purposes (InputText, InputNumber, etc). 

The more I think about it, the more I tend to solution 1, because it would keep the components as shallow as they are now, and it is easy to put a custom wrapper component in a solution over it.

**Comment by AristideBH** [comment]
The fix gave resolved the type issue I had using the form component with a number field.
Had a `z.number()` in my form schema, which triggerred a validation error upon form edit.

Thansk @fen89 !
