### ISSUE TITLE
Checkbox Check is off-centered

### ISSUE THREAD

**Issue by wlockiv** [huntabyte/shadcn-svelte#313]
### Current Behavior

The checkbox check is slightly off-center.

<img width="435" alt="Screenshot 2023-09-21 at 8 51 41 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/29662637/f8caa768-161b-4869-ada7-577a26546b73">

### Expected Behavior

The checkbox check is smack in the middle of the box itself.

<img width="480" alt="Screenshot 2023-09-21 at 8 52 03 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/29662637/aaebdbcf-780d-4455-ac39-924dbde591fe">

### Steps To Reproduce

Add this component to a page and check it, or set it to be. checked programatically.

### More Information

I was able to get this centered up by adding tw class `box-content` to the `CheckboxPrimitive.Root` component, and changing all of the `h-4 w-4` classes to `h-3.5 w-3.5` in order to preserve the height of the checkbox.

**Comment by wlockiv** [comment]
If the proposed approach in `More Information` is alright, I volunteer as tribute.

**Comment by huntabyte** [comment]
Sounds good to me! @wlockiv thanks!
