### ISSUE TITLE
Insert/append instead of replace files (tailwind & app.css / app.postcss) file 

### ISSUE THREAD

**Issue by MarArMar** [huntabyte/shadcn-svelte#319]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

During the setup, I believe it would be possible to replace & insert into the files instead of replacing them

The app.css / app.postcss looks easier to do

Basically something like
1) Remove in the file the existing
"@tailwind base;
@tailwind components;
@tailwind utilities;
"
2) Add at the top of the file the content shadcn-svelte needs to have

Would be ok in most cases

For the tailwind.css config, might be trickier but I believe someone could try : 

1) Import the existing config as an object

2) Assign the new values (can alert at that point : were values only appended or some values replaced ? in the latter case maybe the user should see them, but I guess on clean installs this shouldn't happen)

3) Write the new file

You could even in the CLI try the assignment & then tell the user "values will be appended but all your existing values will be kept" or "some values will be replaced, make sure to keep a copy of your file"

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
There are a ton of variables at play here that introduces a lot of complexity for minor gain. What if the user already has some of those properties defined, are we expected to overwrite them? leave them alone? also considering both TS & JS are possible, or .css or .postcss.

**Comment by huntabyte** [comment]
Closing as not planned at the moment
