### ISSUE TITLE
Alert not rendering properly in Firefox

### ISSUE THREAD

**Issue by jamincan** [huntabyte/shadcn-svelte#320]
### Current Behavior

SVG icons in the alert are being rendered over the text in Firefox.

![image](https://github.com/huntabyte/shadcn-svelte/assets/1579623/145f7925-9789-446b-94a6-8cc2f6286cc1)

### Expected Behavior

The text should be shifted right to fit the icons on the left as seen in Chrome.

![image](https://github.com/huntabyte/shadcn-svelte/assets/1579623/d96329da-6ef0-43bc-ade4-fc1342549745)

### Steps To Reproduce

This is demonstrated on the shadcn website in the above screenshots using version 117 of Firefox.

### More Information

Looking at the inspector in chrome, the classes on the div containing the alert show up as expected from the code:
![image](https://github.com/huntabyte/shadcn-svelte/assets/1579623/be5fb12f-cafe-43aa-bbc9-fe7f85bb199f)

On firefox, however, a lot of them seem to be missing with a weird garbled class shown:
![image](https://github.com/huntabyte/shadcn-svelte/assets/1579623/bcf031ed-81f9-4ea5-867b-1c4d9a68b1cc)

Nevertheless, I would expect the [&:has(svg)]:pl-11 to have an effect that seems to be missing.

**Comment by huntabyte** [comment]
Firefox support for `has` is still in the works.
