### ISSUE TITLE
Issue in build:registery step of `pnpm dev` & `pnpm build` scripts

### ISSUE THREAD

**Issue by wlockiv** [huntabyte/shadcn-svelte#321]
### Current Behavior

When I run `pnpm run dev` in the root directory of the repo, the build fails with the following error:

```bash
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: ENOENT: no such file or directory, open '/shadcn-svelte/apps/www/src/lib/registry/default/example/data-table-actions.svelte'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/shadcn-svelte/apps/www/src/lib/registry/default/example/data-table-actions.svelte'
}

Node.js v18.17.1
/shadcn-svelte/apps/www:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  www@0.0.4 build:registry: `tsx scripts/build-registry.ts`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

```

### Expected Behavior

The project's development build succeeds and a development server is started.

### Steps To Reproduce

1. Clone the repo
2. `cd` into the local repo
3. run `pnpm i`
4. run `pnpm dev`
5. the build will fail with the error outlined in `Current Behavior`

### More Information

This is blocking my work on #313 , and it looks like this blocked someone else on [discord](https://discord.com/channels/1025195801095458887/1145753313955041310/1145753313955041310). 

So I think what's happening here is that the `crawlExample` function in `apps/www/scripts/registry.ts` finds files in child folders (`data-table/data-table-actions.svelte`), but then line 63 has `getDependencies` look at the `rootDir` + `filename.svelte`, when really it should be looking at `rootDir` + `subDir` + `filename.svelte`. When I logged `dirent` to the console, it _does_ have a `path` field on it which has the entire path of the file's directory, but TS doesn't seem to recognize that field (property `path` does not exist on type `dirent`).

**Comment by wlockiv** [comment]
I think I can tackle this one, but I'd like some input from someone with more experience here than me. I'm not entirely sure I understand _all_ of the reasons for this registry workflow. 

I think there are two ways to fix:

1. Use the `path` field on the `dirent` object in lieu of `rootPath`. So line 63 in `apps/www/scripts/registry.ts` would be:
```ts
await getDependencies(join(dirent.path as string, dirent.name))
```

2. Move components out of subfolders, then set `recursive` on line 50 to false. Components in subfolders wouldn't be found any longer. I'm not sure the contents of `/data-table/*` need to be "registered" anyway?

If either of these work, I volunteer as tribute.

**Comment by huntabyte** [comment]
I think first we should identify what is causing this to happen on a couple of machines but not all of the others that have been contributing. I see the error and see what you're saying about the path being incorrect in the output, but the path _is_ correct on both my Windows & Mac machines, as well as others apparently.

As long as the fix isn't a "fix it for me break it for you", then I'm all for it. @AdrianGonz97 wrote the CLI, so I'll defer to him for guidance on this.

**Comment by HubbeDev** [comment]
@huntabyte @wlockiv I noticed this error aswell when i forked the repo on my older macbook pro 2013. Havent had the time yet to make any investigations on it tho.

**Comment by wlockiv** [comment]
Yea I just tried to see if I could get this running on Codespaces as well and I ran into the same issue w/ the build step

**Comment by AdrianGonz97** [comment]
@wlockiv Thanks for raising the issue! I'm unable to replicate this problem, but I've pushed a fix as part of #327 that _I think_ should do the trick (mainly disabling off the `recursive` arg as you suggested, which we don't really need anymore). When you get a chance, please test out my PR and see if it works as expected.

**Comment by wlockiv** [comment]
@AdrianGonz97 you're a legend! I'll check it out now.

**Comment by wlockiv** [comment]
@AdrianGonz97 this works both on my local machine, and it also worked on a vanilla GH Codespace.

Huzzah!! 🎉🥳
