### ISSUE TITLE
Hover Card component's hovering breaks when highlighting text

### ISSUE THREAD

**Issue by thijserven** [huntabyte/shadcn-svelte#323]
### Current Behavior

When I hover over the trigger element while highlighting text the card will open as normal but won't close when I move the mouse away from the card or the trigger. Afterwards this behaviour keeps continuing even when I don't have any text highlighted. Only when I refresh the page it resets and behaves as expected.

### Expected Behavior

When I hover over the trigger, the card should open. When the mouse leaves the card or the trigger, the card should close.

### Steps To Reproduce

This can actually be easily reproduced with the example on: https://www.shadcn-svelte.com/docs/components/hover-card

1. Highlight the text "@sveltejs"
2. Hover over the text "@sveltejs"
3. The card will pop up as normal
4. When moving the mouse away from the card or the trigger the card won't close
5. Click outside of the card or trigger to close the card
6. Now repeat the process starting from step 2 and see that the card won't close anymore when the mouse leaves the card or trigger

### Link to Reproduction / Stackblitz

https://www.shadcn-svelte.com/docs/components/hover-card

**Comment by huntabyte** [comment]
Are you able to reproduce this here as well?
https://melt-ui.com/docs/builders/link-preview

If so we'll need to open an issue there. I know it's not supposed to close when you select text _within_ the hover card by design, but it seems as though your repro causes that functionality to misbehave.

**Comment by thijserven** [comment]
@huntabyte Yes I'm able to reproduce it on https://melt-ui.com/docs/builders/link-preview as well.

**Steps to reproduce:**

1. Mouse over the button with the ice cream icon, the popup appears (as it should).
2. If you highlight any text inside of the popup and move the mouse away from the popup, the popup won't close (as it should since there is text highlighted).
3. If you click outside of the popup in order to close it (since it would disable the text highlight, thus allowing the popup to close since there's no text highlighted anymore and the mouse is outside of the popup) the popup closes (as it should).
4. **Here is where the bug happens**: Now when I hover over the button with the ice cream icon again the popup appears (as it should). But when I move the mouse away from the popup (and remember I haven't highlighted any text inside the popup now) it won't close.

**Comment by huntabyte** [comment]
Thank you! @thijserven, this issue will be blocked until we resolve it at the Melt level!
