### ISSUE TITLE
Add boolean property to textarea to turn on auto-growing

### ISSUE THREAD

**Issue by Evertt** [huntabyte/shadcn-svelte#325]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Well I guess we all know what I'm talking about right? Some textarea inputs on the web automatically become taller when you start to type more lines than its initial height can show. It'd be nice if the textarea in this project had an option to do something similar.

### What type of pull request would this be?

Enhancement

(What's the difference between a new feature and an enhancement?)

**Comment by huntabyte** [comment]
I guess a new feature would be something from scratch, where as an enhancement would be improving an existing component/feature, but not 100% sure 😂

How do you think this would be implemented? I think this is a solid feature, so if you're down for implementing it I can assign the issue to you!

**Comment by Evertt** [comment]
You're not using storybooks right? Or am I supposed to be looking at another repo for that?

Maybe that's a stupid question. The thing is, I'm currently working on this and I'm noticing that I find it hard to make certain UX decisions. Such as:

* If the user has made the textarea grow by adding lines, and they then remove those lines again, should the textarea shrink back? Or should it stay at the maximum size it had reached so far?
* If the user starts to manually resize the textarea, and then starts typing again, what should we do? Should we resize the textarea immediately again to what the code would've otherwise done? Should we stop resizing the textarea? Should we only allow for growth, but no longer for shrinkage?
* Or should we say that when `autoGrow` is enabled, the manual resize feature gets turned off?

If these components came with storybooks and I knew where to find them, then I could just give you all the variations I can think of, and then you can maybe choose which one you think makes the most sense.

**Comment by huntabyte** [comment]
Hey @Evertt, after thinking about this, maybe it's not a _great_ idea to add as part of the lib, just due to the (potentially) unnecessary complexity it adds for those who don't need the feature.

However, if you wanted to add an example to the docs demonstrating how to accomplish this, that would be awesome!

**Comment by mattf96s** [comment]
I think an autosizing text-area is going to be natively supported [soon](https://twitter.com/jh3yy/status/1714275910172791211).

**Comment by huntabyte** [comment]
I saw this as well @mattf96s! Will be incredible!

In the meantime, I'm going to close this issue, but feel free to add an example if you wish @Evertt!
