### ISSUE TITLE
Card on:click functionality

### ISSUE THREAD

**Issue by sakgoyal** [huntabyte/shadcn-svelte#329]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Can we get support for being able to click on cards?

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
I don't think this is something I will add by default to the project, as then we'd have to get into ensuring the proper `role` is set if the card is going to act as a button, however, the beauty is that you can easily add/forward your own `on:click` from the card element within your card component!
