### ISSUE TITLE
Current implementation of `hsl` doesn't inject `alpha value` when using an opacity modifier

### ISSUE THREAD

**Issue by shyakadavis** [huntabyte/shadcn-svelte#333]
### Current Behavior

Currently, if I wanted to style something using opacity modifiers, it would not work.

For example:
```svelte
<button class="... border-primary/20 bg-primary/10 ...">
	Reduced Opacity
</button>
```

If you do that, then the semblance of reduced opacity isn't applied.

### Expected Behavior

I should be able to control the opacity of colours using the colour opacity modifier.

e.g.
```svelte
<button class="bg-sky-500/100 ..."></button>
<button class="text-sky-500/75 ..."></button>
<button class="border-sky-500/50 ..."></button>
```

### Steps To Reproduce

1. Pick any component whatsoever, say, a button.
2. Try giving it a background of `bg-indigo-500/50`.
3. That style won't be applied.

I tried implementing a fix locally, and all worked as expected.
The fix is relatively straight forward, and I volunteer to work on this issue.

### More Information

The reason is that the current definition of colours in the configuration file doesn't inject the special `<alpha-value>` placeholder that Tailwind will use to inject the alpha value when using an opacity modifier

**Comment by huntabyte** [comment]
Sounds good to me!
