### ISSUE TITLE
`<Input type="file" />` has unreadable text in dark mode

### ISSUE THREAD

**Issue by phenomen** [huntabyte/shadcn-svelte#338]
### Current Behavior

`<Input type="file" />` has a black "Choose file" label on a black background, making it unreadable.

![chrome_TchH7pw6KC](https://github.com/huntabyte/shadcn-svelte/assets/138311/b0907d5e-e6ca-4d0e-a37b-d599b8ee60eb)

### Expected Behavior

Here is how it looks in `shadcn-ui/ui`:

![image](https://github.com/huntabyte/shadcn-svelte/assets/138311/5326fdc2-7c32-4386-85d6-68c44b7742b6)

### Steps To Reproduce

1. https://www.shadcn-svelte.com/docs/components/input#file
2. Toggle dark mode

**Comment by HubbeDev** [comment]
@phenomen @huntabyte Looks fine on my end. Tested in Arc and safari.

<img width="661" alt="file-input-dark-mode" src="https://github.com/huntabyte/shadcn-svelte/assets/57641199/b3e6c422-4788-44bb-9699-8b17b0f7f406">

**Comment by huntabyte** [comment]
What browser are you using @phenomen?

**Comment by phenomen** [comment]
> What browser are you using @phenomen?

Google Chrome 118
Can still reproduce it here https://www.shadcn-svelte.com/docs/components/input#file

**Comment by fen89** [comment]
> > What browser are you using @phenomen?
> 
> Google Chrome 118 Can still reproduce it on `shadcn-svelte` docs here https://www.shadcn-svelte.com/docs/components/input#file Not reproducible on the original `shadcn/ui` https://ui.shadcn.com/docs/components/input#file
> 
> And it's not just docs, it happens in my app with `shadcn-svelte` too.

I can confirm this behavior, happen on my side as well (reproduced in  Chrome v117, Firefox v118) :

 Chrome v117

![file-dark-mode](https://github.com/huntabyte/shadcn-svelte/assets/4036376/1a6e251d-7061-4c5e-9f6c-3c45da0675e7)

If we remove all styles from the inputs on both shadcn-svelte and original shadcn, they both differ:

```html
<input class="" id="picture" type="file">
```

in original shadcn:
![image](https://github.com/huntabyte/shadcn-svelte/assets/4036376/929e893e-6841-43d8-9b81-47a12b925078)

in shadcn-svelte:
![image](https://github.com/huntabyte/shadcn-svelte/assets/4036376/b1a76e63-d13d-40e6-895c-14b25e6b6db2)

**Comment by HubbeDev** [comment]
@phenomen @huntabyte I just noticed the same behavour on my other computer. In Arc same version and same os version. Its kinda weird.

**Comment by HubbeDev** [comment]
@huntabyte I made a pullrequest for a fix.

But i noticed while doing some debugging based on @fen89 comment. 

the original shadcn-ui website gets a style attribute
```
style attribute {
    color-scheme: dark;
}
```

I could not se that this one is generated on the svelte version.

**Comment by huntabyte** [comment]
Interesting. I know we do light/dark modes a bit differently as they're using a StyleProvider, is that attribute a requirement, or does your fix suffice?

**Comment by HubbeDev** [comment]
@huntabyte i think my fix is sufficient for now. But maby adding the color-scheme functionality  to a todo list / future features would be a good idé. Its telling the browser what base styles to apply to elements. So its no problem if the elements have it owns styles by css. 

The problem here was that the browser didn't understand that the site is in dark mode. So it applied the black text as default. color-scheme: dark would  have changed the color to white by its self without needed a extra class for it.

**Comment by huntabyte** [comment]
Okay, this shouldn't be too difficult to add. We'll just need to extend the light switch to also handle that as well!

**Comment by markmansur** [comment]
I'm still seeing this issue on Chrome `v122.0.6261.94`

**Comment by lolzivkovic** [comment]
It appears that the issue is specifically related to the "new-york" style component. In my testing, the problem only occurs when using the "new-york" style.

**Comment by StevenStavrakis** [comment]
I am using default styles on Arc and am getting this issue. I saw it white once, but it's finicky.
