### ISSUE TITLE
Dialog: closeOnSubmit

### ISSUE THREAD

**Issue by pietz** [huntabyte/shadcn-svelte#342]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I use a form in my Dialog component and pressing Submit sends the form. I would also like to close the dialog when that happens. Is there a parameter for that?

### What type of pull request would this be?

Enhancement

**Comment by paul-brenner** [comment]
I've been using [this](https://github.com/huntabyte/shadcn-svelte/discussions/304#discussioncomment-7063934) solution until this is implemented and it works well.

**Comment by huntabyte** [comment]
There won't be a prop for this. You can `bind:open` to the dialog and programmatically set it to `false` once the form is submitted.
