### ISSUE TITLE
Website UX Bug: Examples route scroll resets to the top on tab navigation

### ISSUE THREAD

**Issue by akifisitan** [huntabyte/shadcn-svelte#345]
### Current Behavior

Navigating through the tabs (Dashboard/Cards/Playground/Music/Authentication/Forms in the examples route resets the scroll to the top each time a new tab is accessed. 

### Expected Behavior

The scroll height should be kept when switching through tabs.

### Steps To Reproduce

1. Go to https://www.shadcn-svelte.com/examples/dashboard
2. Scroll down a bit to see the contents of the Dashboard tab
3. Click on any of the tabs (Dashboard/Cards/Playground/Music/Authentication/Forms

### More Information

Thank you for your efforts on the port, been using it frequently in my projects. Just wanted to inform about this bug as it has been a bit annoying when switching through the different tabs when viewing examples. Keep up the great work!

**Comment by akifisitan** [comment]
https://github.com/huntabyte/shadcn-svelte/assets/102677971/8331a388-88e6-4a32-b389-c80460f3fef5

**Comment by HubbeDev** [comment]
@huntabyte  I could take a look at this later today if i get some time over after work.

**Comment by huntabyte** [comment]
Closed by #355
