### ISSUE TITLE
Avatar not updating

### ISSUE THREAD

**Issue by ftognetto** [huntabyte/shadcn-svelte#347]
### Current Behavior

If I change image on avatar component after it has already loaded it doesn't update

### Expected Behavior

Should update image 

### Steps To Reproduce

I'll try to add a repro this evening but the steps are

load avatar with src=img1

then programmatically change the src to img2

the image doesn't change

**Comment by huntabyte** [comment]
This was an issue with bits-ui and has been resolved in `v0.6.2`. Update that package and you'll be good to go.

https://github.com/huntabyte/bits-ui/pull/130

**Comment by ftognetto** [comment]
Oh sorry for the duplicate, thank you !
