### ISSUE TITLE
Custom form errors do not reach the <Form.Validation /> component

### ISSUE THREAD

**Issue by StevenStavrakis** [huntabyte/shadcn-svelte#350]
### Current Behavior

I have a sign in form. When a user inputs an email that is not in the database it will throw an error. That error should propagate to the email field's validation component. A custom error is set with `setError` from superforms, but it doesn't seem to make a difference. When the error is handled with HTML from the $errors store, it works. It appears the the error doesn't make it to the validation component.

### Expected Behavior

I would expect the error to show up in the validation component.

### Steps To Reproduce

1. Create a form
2. In a server action, handle a custom error
3. Use and return `setError` to set a custom error on the email field
4. Submit the form and induce the error
5. Validation component doesn't change.

**Comment by huntabyte** [comment]
I'm not able to reproduce this. When I return `setError(form, 'username', 'some custom message')` it is populated on the input.

Can you provide a reproduction stackblitz/repo?

**Comment by sammynave** [comment]
@huntabyte I'm having this issue as well but it only happens when I submit the form with the enter key. Clicking the submit button seems fine. Here's a [minimal repro](https://github.com/sammynave/shadcn-svelte-repro) and gif of what I'm experiencing. 

![repro](https://github.com/huntabyte/shadcn-svelte/assets/751410/c0edb1a7-f86a-4063-881e-3cd0b8bb82f6)

**Comment by huntabyte** [comment]
If you update to the latest version of formsnap, are you still able to reproduce this?

**Comment by sammynave** [comment]
@huntabyte yes, sorry to say that it's still happening with `formsnap` at `0.4.0`.

**Comment by huntabyte** [comment]
I'm no longer able to reproduce this @sammynave 

https://github.com/huntabyte/shadcn-svelte/assets/64506580/3289748a-ab34-405e-92b2-bceed2e42345



Here's a modified version of your repro - updated bits-ui (shouldn't be related) and superforms to 1.9.

https://stackblitz.com/edit/github-gpelpt

**Comment by huntabyte** [comment]
Can you provide me with a reproduction example if you're still experiencing issues @sammynave? https://shadcn-svelte.com/repro

**Comment by huntabyte** [comment]
Feel free to reopen the issue if this persists and you can provide a reproduction!
