### ISSUE TITLE
SelectInput value is set to "[object Object]"

### ISSUE THREAD

**Issue by hugotox** [huntabyte/shadcn-svelte#351]
### Current Behavior

I noticed when using the `SelectInput` component, its value is always `"[object Object]"`. I thought something was wrong with my implementation, but checking the [docs page](https://www.shadcn-svelte.com/docs/components/select) and it has the same issue.

This is problematic when using the select to submit a form.

<img width="1143" alt="Screenshot 2023-10-14 at 4 14 34 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/1758062/b3293405-4a48-4077-8d57-f7eec038891b">

### Expected Behavior

The `SelectInput` value should be set to the actual selected value

### Steps To Reproduce

Follow the instructions from the first example from the docs page https://www.shadcn-svelte.com/docs/components/select

**Comment by huntabyte** [comment]
Thanks @hugotox, this was recently patched in Melt UI so I will update bits to reflect that as well before the end of this weekend!

**Comment by huntabyte** [comment]
This is fixed with the latest version of `bits-ui`!
