### ISSUE TITLE
Can't set default value of Select component

### ISSUE THREAD

**Issue by PaulDotterer** [huntabyte/shadcn-svelte#361]
### Change Type

Addition

### Proposed Changes

I have been migrating my project to your library and it's been awesome so far.
But im currently stuck  and can't seem to figure out how to assign a default value to the Select component.

I have tried anything i can think of but nothing works.

Example:
```svelte

<Select.Root value="light"> <-- does not work
  <Select.Trigger value="light"> <-- does not work
    <Select.Value placeholder="Theme" />
    <Select.Value placeholder="Theme">light</Select.Value> <-- adding value does not work
  </Select.Trigger>
  <Select.Content value="light"> <-- does not work
    <Select.Item value="light" selected>Light</Select.Item> <-- adding selected does not work
    <Select.Item value="dark">Dark</Select.Item>
    <Select.Item value="system">System</Select.Item>
  </Select.Content>
</Select.Root>
```

When examining [bits-ui/select](https://www.bits-ui.com/docs/components/select) there should be a value prop, but as far as i could see in the component itself, it does not expose a value prop.

So i have basically tried adding a default value to every place i can imagine and none of the values apply. What am i doing wrong here, or is there just no way to set a default value?

Any guidance is much appreciated!

**Comment by HubbeDev** [comment]
@PaulDotterer 

Try this: 

```svelte
	const fruits = [
		{ value: "apple", label: "Apple" },
		{ value: "grapes", label: "Grapes" },
	      ...
	];

	let selected = { value: "grapes", label: "Grapes" };

	$: console.log(selected);
</script>

<Select.Root bind:selected >
....
```

@huntabyte Maby this should be updated to be able to select default value without needing to specify the label?

**Comment by PaulDotterer** [comment]
> @PaulDotterer
> 
> Try this:
> 
> ```svelte
> <script>
>       let selected = { value: "light", label: "Light" };
>       
>       $: console.log(selected);
> </script>
> <Select.Root bind:selected>
>   <Select.Trigger >
>     <Select.Value placeholder="Theme" />
>   </Select.Trigger>
>   <Select.Content>
>     <Select.Item value="light">Light</Select.Item>
>     <Select.Item value="dark">Dark</Select.Item>
>     <Select.Item value="system">System</Select.Item>
>   </Select.Content>
> </Select.Root>
> 
> ....
> ```
> 
> @huntabyte Maby this should be updated to be able to select default value without needing to specify the label?

Thank you!
Worked like a charm, ill close this issue :)

**Comment by PaulDotterer** [comment]
Ill have to reopen this issue because when i use the same logic on the Form component, the selected value gets set to undefined. Do i have to do it a different way when using it in a Form?

**Comment by huntabyte** [comment]
Looking into this @PaulDotterer!

**Comment by PaulDotterer** [comment]
@huntabyte thank you very much for your time!
I was beeing a really big dumb dumb...
I never returned a form object from my +page.server.js file.
However, your example set me on the right path and my selects now are working as they should.

Thank you both very much for your time!

**Comment by niemyjski** [comment]
How do you bind without a key value pair? Display name is just for display.

**Comment by PaulDotterer** [comment]
> How do you bind without a key value pair? Display name is just for display.

As of now, it's not possible. Or at least I cloud not figure it out. You have to bind using Key value pairs. I was facing the same issue as in your quoted issue. It does not behave how someone would expect a regular select component to behave. This and a couple of other reasons are why I decided to stop porting so shading-svelte and stick with Skeleton for now.

**Comment by niemyjski** [comment]
We could probably use a writable with subscribe to update exported selected prop?

**Comment by PaulDotterer** [comment]
There is actually no binding needed. If you provide the "default" values it will work as expected. But you still need to provide a name and a value as a dict. But setting a store with a subscription also works.

**Comment by ak4zh** [comment]
> Hey @PaulDotterer, with the `Form` components, you do have to do it differently due to the way it is intertwined with `sveltekit-superforms`. It works the same as setting default values works with superforms, here's a modified example of the [Account Form Example](https://shadcn-svelte.com/examples/forms/account) with a default value set. Notice the `.default` bit of the zod schema.
> 
> ```svelte
> <script lang="ts" context="module">
> 	import { z } from "zod";
> 
> 	const languages = {
> 		en: "English",
> 		fr: "French",
> 		de: "German",
> 		es: "Spanish",
> 		pt: "Portuguese",
> 		ru: "Russian",
> 		ja: "Japanese",
> 		ko: "Korean",
> 		zh: "Chinese"
> 	} as const;
> 
> 	type Language = keyof typeof languages;
> 
> 	export const accountFormSchema = z.object({
> 		name: z
> 			.string({
> 				required_error: "Required."
> 			})
> 			.min(2, "Name must be at least 2 characters.")
> 			.max(30, "Name must not be longer than 30 characters"),
> 		// Hack: https://github.com/colinhacks/zod/issues/2280
> 		language: z
> 			.enum(Object.keys(languages) as [Language, ...Language[]])
> 			.default("en")
> 	});
> 
> 	export type AccountFormSchema = typeof accountFormSchema;
> </script>
> 
> <script lang="ts">
> 	import * as Form from "@/registry/new-york/ui/form";
> 	import type { SuperValidated } from "sveltekit-superforms";
> 	import { cn } from "@/utils";
> 
> 	export let data: SuperValidated<AccountFormSchema>;
> </script>
> 
> <Form.Root
> 	method="POST"
> 	class="space-y-8"
> 	let:config
> 	schema={accountFormSchema}
> 	form={data}
> 	debug={true}
> >
> 	<Form.Item>
> 		<Form.Field name="name" {config}>
> 			<Form.Label>Name</Form.Label>
> 			<Form.Input placeholder="Your name" />
> 			<Form.Description>
> 				This is the name that will be displayed on your profile and in
> 				emails.
> 			</Form.Description>
> 			<Form.Validation />
> 		</Form.Field>
> 	</Form.Item>
> 	<Form.Item>
> 		<Form.Field {config} name="language" let:attrs>
> 			{@const { value } = attrs.input}
> 			<Form.Label>Language</Form.Label>
> 			<Form.Select selected={{ value, label: languages[value] }}>
> 				<Form.SelectTrigger
> 					placeholder="Select language"
> 					class={cn(
> 						"w-[200px] justify-between",
> 						!attrs.input.value && "text-muted-foreground"
> 					)}
> 				/>
> 				<Form.SelectContent class="h-52 overflow-y-auto">
> 					{#each Object.entries(languages) as [value, lang]}
> 						<Form.SelectItem {value}>
> 							{lang}
> 						</Form.SelectItem>
> 					{/each}
> 				</Form.SelectContent>
> 			</Form.Select>
> 			<Form.Description>
> 				This is the language that will be used in the dashboard.
> 			</Form.Description>
> 			<Form.Validation />
> 		</Form.Field>
> 	</Form.Item>
> 	<Form.Button>Update account</Form.Button>
> </Form.Root>
> ```
> 
> I hope this helps! I will further explore possibilities with select not requiring a label in the near future!

This works when you have a default value in zod schema. But how to handle it when you want to create a edit profile form sort of thing where the data comes from database. So I provided the values as `<Form.Select selected={{ value, label: languages[value] }}>` and the value shows correctly selected in the UI w=but when form is submitted it still takes the schema default or `undefined` if no default is defined in shema. It only works if you manually change the select value from UI.

**Comment by rjalexa** [comment]
Thank you all ! :)

**Comment by jdgamble555** [comment]
@huntabyte - Could the `selected` feature be added to Svelte 5 version?

Thanks!

J

**Comment by dhndmn** [comment]
I was struggling with this for **_days_** and just got it working! I am using the Select component within a vanilla form - no Form component. None of the above approaches were working for me and the saved value was being cleared on reload. What ended up working was combining @HubbeDev's script tag with @huntabyte's 'Select selected=' suggestion. Values now saving to db and persisting on reload. Thank you all!

`
<script>
      let selected = { value: "light", label: "Light" };
      
      $: console.log(selected);
</script>
...
<Select.Root selected={selected}>
...
`

**Comment by lmzses** [comment]
I don't know if this still helpful but I just faced the same and I found an easier workaround. 

	<div class="space-y-2">
		<Label class="text-sm">Notification Sound</Label>
		<Select
			selected={{
				value: preferences.notificationSound,
				label: capitalizeFirstLetter(preferences.notificationSound)
			}}
			onSelectedChange={(value: { value: string; label: string }) =>
				updatePreference('notificationSound', value.value)}
		>
			<SelectTrigger class="w-full">
				<SelectValue placeholder="Select sound" />
			</SelectTrigger>
			<SelectContent>
				<SelectItem value="default">Default</SelectItem>
				<SelectItem value="chime">Chime</SelectItem>
				<SelectItem value="bell">Bell</SelectItem>
				<SelectItem value="melody">Melody</SelectItem>
			</SelectContent>
		</Select>
	</div>

Since the select property expects an object(Value and Label), I built mines using the data I have. I did it because I have several fields and doing the mentioned ways seemed too complicated or didn't fit my needs.

**Comment by xucian** [comment]
> I don't know if this still helpful but I just faced the same and I found an easier workaround.
> 
> ```
> <div class="space-y-2">
> 	<Label class="text-sm">Notification Sound</Label>
> 	<Select
> 		selected={{
> 			value: preferences.notificationSound,
> 			label: capitalizeFirstLetter(preferences.notificationSound)
> 		}}
> 		onSelectedChange={(value: { value: string; label: string }) =>
> 			updatePreference('notificationSound', value.value)}
> 	>
> 		<SelectTrigger class="w-full">
> 			<SelectValue placeholder="Select sound" />
> 		</SelectTrigger>
> 		<SelectContent>
> 			<SelectItem value="default">Default</SelectItem>
> 			<SelectItem value="chime">Chime</SelectItem>
> 			<SelectItem value="bell">Bell</SelectItem>
> 			<SelectItem value="melody">Melody</SelectItem>
> 		</SelectContent>
> 	</Select>
> </div>
> ```
> 
> Since the select property expects an object(Value and Label), I built mines using the data I have. I did it because I have several fields and doing the mentioned ways seemed too complicated or didn't fit my needs.

much love. was already struggling for 1h to find a solution
