### ISSUE TITLE
Missing "Tasks" from examples

### ISSUE THREAD

**Issue by HubbeDev** [huntabyte/shadcn-svelte#362]
### Change Type

Addition

### Proposed Changes

Now that we have the DataTable/table component ready. We should add the tasks example that exsists on the original shadcn-ui website.
https://ui.shadcn.com/examples/tasks

PS... I could take this one when i have some time over.

**Comment by huntabyte** [comment]
Yeah I haven't gotten to this yet as we're missing the combobox which as soon as I finish the CMDK for svelte will be added :)

But feel free to get everything else in place in a PR if you want so that once the combobox is ready we can just pop it in and publish!

**Comment by HubbeDev** [comment]
Aha perfect.

Absolutely. Will take a look at it when I get time over. 

No worries just glad to contribute :)

**Comment by HubbeDev** [comment]
Closing this as its fixed with #372
