### ISSUE TITLE
feature: Write all installed components to components.json

### ISSUE THREAD

**Issue by Creative-Difficulty** [huntabyte/shadcn-svelte#363]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

In my opninion it's very tiring to always install all the components manually, so i have a proposal. I think it's good idea to write al components to `components.json`like this: 
```json

{
	"$schema": "https://shadcn-svelte.com/schema.json",
	"style": "default",
	"tailwind": {
		"config": "tailwind.config.js",
		"css": "src/app.postcss",
		"baseColor": "slate"
	},
	"aliases": {
		"components": "$lib/components",
		"utils": "$lib/utils"
	},
        "components": [
                "button",
                "accordion"
        ]
}

```

Or even with versioning, that way older projects don't get fked over by breaking changes:
```json

{
	"$schema": "https://shadcn-svelte.com/schema.json",
	"style": "default",
	"tailwind": {
		"config": "tailwind.config.js",
		"css": "src/app.postcss",
		"baseColor": "slate"
	},
	"aliases": {
		"components": "$lib/components",
		"utils": "$lib/utils"
	},
        "components": {
                "button": "0.2.1",
                "accordion": "3.29"
        }
}

```
I think the package.json could be used as inpiration.
We could maybe even implement a lockfile someday.

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
What do you mean by installing all the components manually? Can you not select multiple at once/select all?

Curious to know how you think the 'installed components' would be used!

As for the version control / package.json thing, that's not going to happen. It sounds cool in theory, but in reality it's a nightmare and impractical.

**Comment by Creative-Difficulty** [comment]
Case closed
