### ISSUE TITLE
How to update shadcn-svelte library

### ISSUE THREAD

**Issue by amirbenasr** [huntabyte/shadcn-svelte#366]
### Change Type

Addition

### Proposed Changes

I'd love to see a direct instruction, on how to update the shadcn-svelte library in the documentation

**Comment by ollema** [comment]
@amirbenasr have you seen this chapter? https://www.shadcn-svelte.com/docs/cli#update

**Comment by huntabyte** [comment]
As @ollema mentioned, we have documentation on updating the components using the CLI. You can also manually copy and paste them if you'd like.

A large majority of updates come from `bits-ui` (the underlying primitives), which is distributed via npm and can be upgraded using your package manager of choice!

**Comment by amirbenasr** [comment]
thank you all, yes didn't notice that part !
