### ISSUE TITLE
hover-card transition delay

### ISSUE THREAD

**Issue by bennettcolecohen** [huntabyte/shadcn-svelte#369]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, it seems like the hover-card component has a significant delay. I think the default is far too slow, and would love controls ( or instructions ) on how to reduce it. I went into the flyAndScale function and lib/utils.ts and saw that the delay was already set to 0 so I'm not too sure where else to fix it :( 

I'm not sure if this is a new feature or maybe just better documentation on it, but hoping to figure out how to make the hover animation take effect sooner. 

Thank you

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
Use the `openDelay` and `closeDelay` props on the `HoverCard.Root`

https://bits-ui.com/docs/components/link-preview
