### ISSUE TITLE
Form checkboxes not properly binding checked prop

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/shadcn-svelte#373]
### Current Behavior

I have 2 `Form`s, separated in 2 `Tabs`. I have the same checkbox & submit buttons duplicated into each form.

When using a regular `Checkbox`, I can `bind:` their `checked` prop and thus make them share the same state. However, this behavior no longer works with a `Form.Checkbox`.

### Expected Behavior

The `bind:checked={sharedBoolean}` to actually work on `Form.Checkbox` to actually work and update its value when the boolean changes.

### Steps To Reproduce

1. Create 2 `Tabs` (I don't think it's even mandatory, just use 2 separate `Form`s on the same page)
2. Put a `Form` in each one with at least one `Form.Checkbox` (+ `Checkbox.Label`) and a `Form.Button`
3. Add `bind:checked={myVar}` on both `Form.Checkbox`es
4. Add a `let myVar = false;` on top of the file
5. Tick one of the checkboxes, notice the other one doesn't get ticked too

`myVar` doesn't even change: on page load, `$: console.log(myVar);` logs `false`, then `undefined` right after, then nothing anymore despite the ticks/unticks.

**Comment by huntabyte** [comment]
The `Form.Checkbox` has different behavior than the `Checkbox` due to how it has to remain in sync with superforms. I will do some experimenting to see if I can make it work the way you are describing!

**Comment by WarningImHack3r** [comment]
Great! Thanks for your hard work :)

**Comment by huntabyte** [comment]
Yeah @WarningImHack3r after investigating it further it seems this would not be possible as we'd have multiple bindings on the input (one for superforms and one for the prop).

Instead, if you want access to the `checked` state of the checkbox, you should use the "controlled" Formsnap option which was recently added as then you can simply use `$form.whatever` to get access to that state across multiple components.

See: https://github.com/huntabyte/formsnap/pull/83 for more details on this one!

**Comment by WarningImHack3r** [comment]
@huntabyte that sounds good on paper as I've managed to get my controlled forms and reactive values working, however, I hurt a problem: how can I avoid a cyclic dependency loop? Here is what I'm doing:
```ts
const form1 = superForm(data.form1, {
	validators: form1Schema // is this even useful?
});
const form2 = superForm(data.form2, {
	validators: form2Schema // same, both already in markup
});
const { form: form1Config } = form1;
const { form: form2Config } = form2;
```
and in the markup:
```svelte
<Form.Root
	method="POST"
	action="?/form1" <!-- or "?/form2" -->
	form={form1} <!-- or form2 -->
	schema={form1Schema} <!-- or form2Schema -->
	controlled
	let:config
>
```
But this creates a cyclic dependency if I want to mimic `bind:checked={myVar}`:
```ts
$: $form1Config.myCheckbox = $form2Config.myCheckbox;
$: $form2Config.myCheckbox = $form1Config.myCheckbox;
```
How can I prevent this by mimicking the `bind:` behavior using your `controlled` solution?
