### ISSUE TITLE
Dark mode radix-icons-svelte not installed from cli

### ISSUE THREAD

**Issue by DigitalOutbreak** [huntabyte/shadcn-svelte#379]
### Change Type

Addition

### Proposed Changes

for the dark mode docs i tried doing new york style but its asking to import from radix-icons-svelte. but the cli only installed the lucide-svelte

**Comment by huntabyte** [comment]
Hey @DigitalOutbreak , what style did you choose when running the `init` command with the cli? It should also be displayed inside your `components.json` file.

**Comment by DigitalOutbreak** [comment]
youre right i installed it as default thank you!
