### ISSUE TITLE
Date range picker

### ISSUE THREAD

**Issue by manish-butterpaper** [huntabyte/shadcn-svelte#383]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hi @huntabyte, John built an awesome date range picker for React Shancn. Just wanted to add this to our backlog. This is one of the most used components for dashboards after Combobox, and would be amazing if we can port this into Svelte.

https://date-range-picker-for-shadcn-demo.vercel.app/

Thanks for the amazing port!!

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://date-range-picker-for-shadcn-demo.vercel.app for Demo and https://github.com/johnpolacek/date-range-picker-for-shadcn for GitHub.

**Comment by huntabyte** [comment]
Thank you! 

See #287
