### ISSUE TITLE
tailwind.config.ts deleted after init

### ISSUE THREAD

**Issue by LifeGlitch** [huntabyte/shadcn-svelte#384]
### Current Behavior

Hello,

I'm using sveltekit with tailwindcss with a tailwind.config.ts config file and want to init shadcn-svelte via `bunx shadcn-svelte@latest init`. With that done my tailwind.config.ts gets deleted and not modified. But it works fine with a tailwind.config.js.

### Expected Behavior

tailwind.config.ts should be modified and not deleted.

### Steps To Reproduce

1. Using existing sveltekit with tailwindcss project
2. run `bunx shadcn-svelte@latest init`
3. go through the questions, doesn't matter what you chose but please use the correct path and file names
4. watch your tailwind.config.ts disappearing magically
5. don't hand clap...do facepalm
6. :)

**Comment by huntabyte** [comment]
Right now we only have a `.js` template defined, so we replace whatever you have at the start with that template. We need another template for TS and to detect if the path ends with `.ts` or `.js/.cjs` and respond accordingly. Not going to add a `.cjs` template, that will always be replaced by `.js`

**Comment by huntabyte** [comment]
Yeah this isn't something that I think is worth the squeeze tbh, considering it overwrites the file anyways. If you want to use `.ts` you're more than welcome to modify it after initializing.

Reference: https://github.com/shadcn-ui/ui/pull/1743
