### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by ryoppippi** [huntabyte/shadcn-svelte#386]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

https://ui.shadcn.com/docs/components/navigation-menu

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
Once added to melt it will be added here. Closing for the time being as no reason in keeping an issue for obvious things that are in progress.

**Comment by LBF38** [comment]
For reference purposes: https://github.com/melt-ui/melt-ui/issues/572
