### ISSUE TITLE
AlertDialog Inside of DropdownMenu.Content is not closing

### ISSUE THREAD

**Issue by zomchak-code** [huntabyte/shadcn-svelte#390]
### Current Behavior

The dialog is not closing

### Expected Behavior

The dialog closes

### Steps To Reproduce

1. Using this beautiful peace of code:

```
<script lang="ts">
  import Button from "./ui/button/button.svelte";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu";
  import * as AlertDialog from "$lib/components/ui/alert-dialog";
</script>


<DropdownMenu.Root>
        <DropdownMenu.Trigger>
          Open
        </DropdownMenu.Trigger>
        <DropdownMenu.Content>
            <div class="flex-gap items-center pr-2">
              <DropdownMenu.Item class="gap-2 grow">
                Category
              </DropdownMenu.Item>
              <AlertDialog.Root>
                <AlertDialog.Trigger>
                  <Button >Delete</Button>
                </AlertDialog.Trigger>
                <AlertDialog.Content>
                  <AlertDialog.Header>
                    <AlertDialog.Title>
                      Are you sure you want to delete category?
                    </AlertDialog.Title>
                    <AlertDialog.Description>
                      This action cannot be undone. This will permanently delete
                      all prompts in category.
                    </AlertDialog.Description>
                  </AlertDialog.Header>
                  <AlertDialog.Footer>
                    <AlertDialog.Cancel>Cancel</AlertDialog.Cancel>
                    <AlertDialog.Action
                      class="bg-destructive hover:bg-destructive/90"
                    >
                      Delete
                    </AlertDialog.Action>
                  </AlertDialog.Footer>
                </AlertDialog.Content>
              </AlertDialog.Root>
            </div>
        </DropdownMenu.Content>
      </DropdownMenu.Root>
```

2. Click on 'Delete' button
3. Click on 'Cancel' button

**Comment by zomchak-code** [comment]
Also when it's inside of `DropdownMenu.Item` or `DropdownMenu.Item` is inside of `AlertDialog.Trigger` - the dialog is not opening

**Comment by huntabyte** [comment]
You should define the dialog outside of it and use the `bind:open` and open it from the menu like that.

So for example

```svelte
<Dialog.Root bind:open={myOpen}>
	<!-- ... dialog stuff here -->
</Dialog.Root>

<DropdownMenu.Root>
	<!-- other menu stuff -->
	<DropdownMenu.Item on:click={() => myOpen = true}>
		Open dialog
	</DropdownMenu.Item
</DropdownMenu.Root>
```

**Comment by zomchak-code** [comment]
@huntabyte thank you for such fast response
Is current behaviour expected and I should close the issue?

**Comment by huntabyte** [comment]
Yeah that's expected behavior! The way to think about it is technically the dropdown menu closes when the Dialog opens right, so if the Dialog is _inside_ the dropdown content, it will be removed from the DOM as well!

I'm working with a designer for the design of the `bits-ui` docs so it will be getting a big overhaul in the coming weeks which will include documentation/examples for things like this!

**Comment by tristan-valar** [comment]
I just spent several hours figuring out what was going on, this 100% needs to be documented, lmk if you need help.

An example of what works and what doesn't can be found in the stackbliz I was going to submit in the bug report:

https://stackblitz.com/edit/github-voxfzc?file=src%2Froutes%2F%2Bpage.svelte
