### ISSUE TITLE
Live Examples

### ISSUE THREAD

**Issue by weepy** [huntabyte/shadcn-svelte#391]
### Change Type

Addition

### Proposed Changes

It would be great to see some examples of sites that use this. Is it possible ?

**Comment by huntabyte** [comment]
We have people using it in the [discord](https://hbyt.us/discord) that may share their sites, you can also see the "Used by" section if [bits-ui](https://github.com/huntabyte/bits-ui) to find some projects using it :) Or open up a discussion asking for people to showcase the things they're building with it and you may have some luck there!

<img width="282" alt="CleanShot 2023-11-01 at 10 35 50@2x" src="https://github.com/huntabyte/shadcn-svelte/assets/64506580/0e43be85-b3b3-4d4b-9cdf-146bb4448432">
