### ISSUE TITLE
Card.Title tag type does not have value `p` in type `HeadingLevel`

### ISSUE THREAD

**Issue by Skylli202** [huntabyte/shadcn-svelte#392]
### Change Type

Correction

### Proposed Changes

In this section of the documentation, [Modify the heading level](https://www.shadcn-svelte.com/docs/components/card#modify-the-heading-level) there is the following example:

```svelte
<Card.Title tag="p">This will render a P tag</Card.Title>
```

Which in my editor, give me the following error `Type '"p"' is not assignable to type 'HeadingLevel | undefined'` as the screenshot below show.

![image](https://github.com/huntabyte/shadcn-svelte/assets/38432216/68827d9f-9df9-45e4-ba3b-e78d5ac08608)

Which is expected as the type definition of `HeadingLevel` is the following union type: `export type HeadingLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';` defined in [`bits-ui/src/components/ui/card/index.ts`](https://github.com/huntabyte/bits-ui/blob/main/src/components/ui/card/index.ts)

I am not knowledgeable enough to know if the appropriate fix is:
- Remove this example as it is incorrect
- Add `"p"` in the union type of `HeadingLevel`

I'd be really happy to do a PR with the appropriate fix once the appropriate fix has been decided by maintainers. And if it is the latter, which file in which repo to do the PR.

My gut is telling me that it the correct fix is to edit the `HeadingLevel` type as the component is rendering a paragraph tag in the DOM, if so it is then just a TypeScript typing error.

**Comment by huntabyte** [comment]
Hey @Skylli202 thanks for pointing that out! Oversight on my side!

I don't think we should add `'p'` to the `HeadingLevel` type, instead the example should be updated to replace `'p'` with a valid heading. It will still work of course, but you'll get a type error which makes you stop and think is this really what I want to do?

If so, you're more than welcome to modify the `HeadingLevel` in your local component, but from the library side I think we try to nudge peeps into using solid semantics, a card heading is in fact a `heading`, so it should be tagged appropriately.

**Comment by Skylli202** [comment]
I do agree on the semantics side. I'll try to push a PR on the documentation if you have not already done it.

**Comment by huntabyte** [comment]
Closed by #393
