### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by roostad** [huntabyte/shadcn-svelte#395]
### Current Behavior

Encountering an issue where following the installation instructions results in the fonts all ending up the same size (h1, p, etc.). Keeping this very general initially in case this is a common occurrence but happy to share additional details. Thanks

### Expected Behavior

Result should match the typography page: https://www.shadcn-svelte.com/docs/typography

### Steps To Reproduce

Follow installation instructions (See "New Project"), set to New York, and use the defaults: https://www.shadcn-svelte.com/docs/installation

The only difference is that I am using pnpm create for steps #1, pnpm install for #3, and pnpm dlx for #2 and #4

**Comment by huntabyte** [comment]
It doesn't apply those styles to every h1, h2, h3, etc. Those are styles you can copy/paste as you see fit or componentize if you really want, they aren't installed like that as those are meant for specific content related pages, not every h1,h2, p tag across your apps.

**Comment by roostad** [comment]
Got it, thanks. But just confirming that the expected behavior is for shadcn-svelte to override the existing styles when installed? h1 through h6 are all set to inherit as soon you import app.postcss via +layout.svelte

**Comment by roostad** [comment]
Got it, thanks. But if the library by default isn't supposed to have any effect on existing tags I am not following why (for example) h1 through h6 are all set to inherit as soon you import app.postcss via +layout.svelte. They all turn uniform
