### ISSUE TITLE
Cannot bind the value of a select

### ISSUE THREAD

**Issue by jramiroz98** [huntabyte/shadcn-svelte#396]
### Current Behavior

I'm not using a form, all I'm doing is something similar to a todo list. I am storing multiple values of an object on a list. I do this by using a function with spread. The problem is that I can't find how to link that value.

### Expected Behavior

I want the select to bind to a value, which will then be added as part of an object with other values. Had no problem doing this with inputs.

### Steps To Reproduce

let ingredients: any[] = [];
	let ingredient = '';
	let ingredientAmount = '';
	let ingredientUnit = '';
	function addIngredient() {
		ingredients = [
			...ingredients,
			{ name: ingredient, amount: ingredientAmount, unit: ingredientUnit }
		];
		ingredient = '';
		ingredientAmount = '';
		ingredientUnit = '';
	}

<Select.Root bind:selected={ingredientUnit}>
								<Select.Trigger class="w-full">
									<Select.Value placeholder="Unit" />
								</Select.Trigger>
								<Select.Content>
									<Select.Group>
										<Select.Label>Units</Select.Label>
										{#each units as unit}
											<Select.Item value={unit.value} label={unit.label}>{unit.label}</Select.Item>
										{/each}
									</Select.Group>
								</Select.Content>
								<Select.Input name="favoriteFruit" />
							</Select.Root>

**Comment by huntabyte** [comment]
Can you link a reproduction?

I'm able to bind just fine:
https://stackblitz.com/edit/shadcn-svelte?file=src%2Froutes%2F%2Bpage.svelte

**Comment by jramiroz98** [comment]
Just worked man! I tried using yours and turns out my issue was that I wasn't accessing the value key of the select inside the object, instead I was trying to read the object as a whole. Normal select values from svelte work, but in yours we have to tap into the value of the select as an object. Thank you so much for taking your time Hunter, I'm a big fan of your work and courses. _pnpm run thanks ;)_


For others reading this post: when trying to bind do the following:
`<Select.Root bind:selected={ingredientUnit}> etc`
and at the script access the selected value this way:
`ingredientUnit.value`

as the bind returns an object, unlike how svelte docs explain the binding of a select.

Again thank you Hunter! Big Fan of your courses and work

**Comment by huntabyte** [comment]
You're welcome! I'm going to try to do something to make it a bit more like the native select with `bind:value`, the only issue is the label can get out of sync when programmatically updating the value which makes it a bit messy!
