### ISSUE TITLE
FormSelectTrigger submitting

### ISSUE THREAD

**Issue by ftognetto** [huntabyte/shadcn-svelte#398]
### Current Behavior

Hi i've noticed that FormSelectTrigger inside a Form component is causing validation, is this intentional?

### Expected Behavior

FormSelectTrigger should not submit.
I have resolved adding type="button" 

`<FormSelectTrigger type="button" />`

### Steps To Reproduce

1. Create a form
2. Add some required fields in the form
3. Add a select in the form, and use FormSelect component
4. When you open the select component the form get's validated

**Comment by huntabyte** [comment]
What version of bits-ui are you running?

**Comment by ftognetto** [comment]
Hi @huntabyte i'm using 0.7.0

"bits-ui": "^0.7.0"

**Comment by huntabyte** [comment]
This should have been fixed in v9.0. See https://github.com/huntabyte/bits-ui/pull/150 for reference, but let me know if not!
