### ISSUE TITLE
feat: Using a Proxy to Fetch from `shadcn` Registry

### ISSUE THREAD

**Issue by shahradelahi** [huntabyte/shadcn-svelte#401]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I have a feature request related to fetching components from the `shadcn` registry through a proxy. 

To utilize this feature, users must set the `HTTP_PROXY` environment variable to their proxy URL. The feature will then use the `https-proxy-agent` and `node-fetch` packages to send requests.

For instance, users can add a button component from the `shadcn` registry via the proxy using the following command: 

```bash
export HTTP_PROXY=http://your-proxy-url:port
npx shadcn-svelte@latest add button
```

This feature is especially useful for users who need to access the registry behind a corporate firewall.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

See [PR](https://github.com/huntabyte/shadcn-svelte/pull/402)

**Comment by huntabyte** [comment]
Closed by #402
