### ISSUE TITLE
feature: Superforms

### ISSUE THREAD

**Issue by huntabyte** [huntabyte/shadcn-svelte#42]
Update (2023/08/19) - The superforms integration is in a preview state at this time, meaning you can't install the components via the CLI, but they are in the [repository](https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/registry/new-york/ui/super-form) for you to reference. Expect there will be bugs and they aren't perfect just yet. We'll be working through the final implementation details along with a guide to publish once we get everything worked out!

### Describe the feature in detail (code, mocks, or screenshots encouraged)

The original project has an awesome integration with React Hook Form. I want the same with [sveltekit-superforms](https://github.com/ciscoheat/sveltekit-superforms). This issue will be used to track the progress/discussion around this implementation.

### What type of pull request would this be?

New Feature

**Comment by Azizadx** [comment]
I'll would like also contribute to it if that okay @huntabyte

**Comment by huntabyte** [comment]
Hey @Azizadx , of course that's okay! I'm working out a few details and I'm going to update this issue with the progress/route we're thinking of going down and leave it up to discussion/contribution from there!

**Comment by Azizadx** [comment]
alright cool

**Comment by huntabyte** [comment]
This implementation is currently on hold until we get a solid Select component for the project, otherwise, the forms aren't really complete and I wouldn't feel comfortable publishing.

**Comment by magick93** [comment]
> get a solid Select component

Can you clarify the requirements the select component?

Is it possible to do an `alpha` version that doesnt have full support for all form elements?

**Comment by ftognetto** [comment]
Hi all, select component has a temp version now, will this feature be completed? Thank you

**Comment by ftognetto** [comment]
What is the roadmap here? Is there something maybe I could help with?

**Comment by huntabyte** [comment]
@ftognetto waiting to get some early feedback from peeps before adding it to this project :) if you want to be an early adopter: https://github.com/huntabyte/formsnap

**Comment by ftognetto** [comment]
Of course I will, thank you!

**Comment by huntabyte** [comment]
Closed as implemented by #166

**Comment by kelsiesmurphy** [comment]
Is Form now ready to use? It's still marked as preview in the docs, yet this thread makes me think it is completed :)
