### ISSUE TITLE
Type issue with Select component `multiple` prop

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#428]
### Current Behavior

![image](https://github.com/huntabyte/shadcn-svelte/assets/44144724/9e36f71c-3e2e-41f2-8ed8-a83d2316fd8b)

### Expected Behavior

![image](https://github.com/huntabyte/shadcn-svelte/assets/44144724/cb9cb78e-8748-433f-a224-47b169699ac7)

### Steps To Reproduce

1. Add `multiple={true}` to `<Select.Root`.

### More Information

I'm using this component: https://www.shadcn-svelte.com/docs/components/select
This issue may be related to MeltUI.

**Comment by huntabyte** [comment]
Closed by https://github.com/huntabyte/bits-ui/releases/tag/v0.10.0 (some minor breaking changes to check before updating `bits-ui`)
