### ISSUE TITLE
Overflow issue with Select component when using `multiple` prop

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#429]
### Current Behavior

![image](https://github.com/huntabyte/shadcn-svelte/assets/44144724/24de8314-5fd2-4bd6-a976-4bf576b82a45)

### Expected Behavior

A UI like this but put the items outside and under the select box:

![image](https://github.com/huntabyte/shadcn-svelte/assets/44144724/b76dbad6-60fa-41a8-983e-151046ead95f)

### Steps To Reproduce

1. `<Select.Root multiple={true}>`
2. Select a lot of items.

**Comment by huntabyte** [comment]
At the moment, this functionality isn't implemented in the original https://ui.shadcn.com. Only once it is added there will it be added here 😀
