### ISSUE TITLE
"Component Source" link for "Combobox" shows 404

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#431]
https://www.shadcn-svelte.com/docs/components/combobox

I checked the registry and there was no "combobox" folder and in the demo, no component with the name "Combobox" is imported.

**Comment by huntabyte** [comment]
This one shouldn't have a component source at isn't a standalone component rather a combination of multiple.

**Comment by babakfp** [comment]
Cool.
I would like to open a PR for this. I think removing the `source` property in `apps\www\src\content\components\combobox.md` can solve the issue.
