### ISSUE TITLE
`data-table` documentation has two heading with the same wording, leading to erroneous `a` tag

### ISSUE THREAD

**Issue by Skylli202** [huntabyte/shadcn-svelte#433]
### Change Type

Correction

### Proposed Changes

Hi Huntabyte, maintainers,

So, I was taking a lesson while following the steps of the guide on how to implement a data table and I came across this minor issue. 

On the `data-table` documentation page [`data-table.md`](https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/content/components/data-table.md?plain=1) there is two times the same heading `### Update columns definition`.

Which generate the following url fragment `#update-columns-definition` when the user click on the said header in the content table. But because it is twice on the page, the navigator will go the first heading (which is not the correct if you clicked on the second one...)

![image](https://github.com/huntabyte/shadcn-svelte/assets/38432216/075694fc-bdb1-4790-896f-180fdc71017b)

Here is my poor attempt to make a small GIF of the issue, you can see me navigating with the content table, and we can see that when I click on the heading `Update columns definition` I got to the wrong one, and that both of them are highlighted.
![vivaldi_2nVfIplJKc](https://github.com/huntabyte/shadcn-svelte/assets/38432216/d43bee8b-9413-4b1a-901e-39214ecabb00)

**Comment by Skylli202** [comment]
I'm not against doing the PR myself, but I'm not too sure how to reword this. And I guess telling me into what to reword this, as well as reviewing the PR will be as long as doing the changes yourself... Just let me know!

**Comment by huntabyte** [comment]
While we could simply rename this and it would resolve the issue, maybe we need to look into how the TOC handles duplicate names.

**Comment by Skylli202** [comment]
Awesome!
