### ISSUE TITLE
When a select is open and we click on another select, the scrollbar becomes visible 

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#445]
### Current Behavior

https://github.com/huntabyte/shadcn-svelte/assets/44144724/0d861df8-a260-4a3b-8b89-068dd77820f7

### Expected Behavior

.

### Steps To Reproduce

.

**Comment by huntabyte** [comment]
This is also something to be addressed at the lower (melt-ui) level, see: https://github.com/melt-ui/melt-ui/issues/733

**Comment by huntabyte** [comment]
PR submitted to fix this 👍 

https://github.com/melt-ui/melt-ui/pull/809

**Comment by huntabyte** [comment]
Update to bits-ui@0.11.7 and this issue should be fixed ✅
