### ISSUE TITLE
Add the labels on the mobile menu

### ISSUE THREAD

**Issue by NDOY3M4N** [huntabyte/shadcn-svelte#450]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I want to add the label next to the links in the mobile menu like on the bigger screen (`aside` section). It should look like this on mobile

![image](https://github.com/huntabyte/shadcn-svelte/assets/46305144/e71b67e3-4057-4b99-9779-57aa65a12d7f)

### What type of pull request would this be?

Docs

**Comment by huntabyte** [comment]
Go for it!
