### ISSUE TITLE
Playground example on front page no working properly

### ISSUE THREAD

**Issue by saturnonearth** [huntabyte/shadcn-svelte#453]
### Current Behavior

The hovercards do not properly display when hovering over the different options, among some other bugs like the card getting stuck in the top left corner, and when clicking twice on the Select, the hovercard gets centered over the dropdown options

![CleanShot 2023-11-15 at 20 56 21@2x](https://github.com/huntabyte/shadcn-svelte/assets/12503538/175b5d66-c29e-4adc-be88-11a5369cba92)

Should be...

![CleanShot 2023-11-15 at 20 58 00@2x](https://github.com/huntabyte/shadcn-svelte/assets/12503538/236b816f-b48c-4f7a-a61f-a44ddc6e2721)

### Expected Behavior

The example to work so I can copy it in my own app xD

### Steps To Reproduce

Original issue of hovercard data not changing on hover/focus of other items:
![CleanShot 2023-11-15 at 21 08 34](https://github.com/huntabyte/shadcn-svelte/assets/12503538/726a07bd-3c83-4cb4-af27-0bb3ef586353)

Issue where hovercard changes position when Select is click twice:
![CleanShot 2023-11-15 at 21 03 10](https://github.com/huntabyte/shadcn-svelte/assets/12503538/a8189607-f34d-4fc0-a452-7e7a2e293b52)

Issue with Hovercard appearing in top left corner, sometimes getting stuck (make sure to watch left corner closely)
![CleanShot 2023-11-15 at 21 09 34](https://github.com/huntabyte/shadcn-svelte/assets/12503538/54cea0db-34dd-4ca2-a8d3-1528b989494f)

**Comment by huntabyte** [comment]
The playground as a whole requires some updates now that we have `Combobox` capabilities. If someone wants to give it a shit, let me know, otherwise, I will update when I get the chance!

**Comment by HubbeDev** [comment]
@huntabyte I could probably give it some love if i find the time this week. Will let you know if something else get in the way.

**Comment by huntabyte** [comment]
Awesome! @HubbeDev

**Comment by huntabyte** [comment]
Closed by #477
