### ISSUE TITLE
Dialog closes on mouseup outside dialog after mousedown inside dialog

### ISSUE THREAD

**Issue by DePasqualeOrg** [huntabyte/shadcn-svelte#460]
### Current Behavior

The dialog closes when the mouse is released outside the dialog after clicking inside the dialog.

### Expected Behavior

The dialog should only close when the click occurred outside the dialog. For example, if the user selects text with the mouse inside the dialog and the mouse is released outside the dialog, closing the dialog is not the expected behavior.

### Steps To Reproduce

[https://www.shadcn-svelte.com/docs/components/dialog](https://www.shadcn-svelte.com/docs/components/dialog)

In the dialog example, click "Edit profile", select text in one of the input elements, and release the mouse outside the dialog.

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://www.shadcn-svelte.com/docs/components/dialog

**Comment by huntabyte** [comment]
This issue should be raised with https://github.com/melt-ui/melt-ui rather than here.
