### ISSUE TITLE
Unable to set Select component selected value

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#461]
### Current Behavior

I'm unable to set the selected value and the docs for this component are basically missing (https://www.shadcn-svelte.com/docs/components/select) and the bits documentation has the `selected` as `value` (https://www.bits-ui.com/docs/components/select).

### Expected Behavior

It should work.

### Steps To Reproduce

Create new component and notice that you can't use the selected value (also you can't change the glyph icon either).

(ignore `bind:selected` here I was playing around)
![image](https://github.com/huntabyte/shadcn-svelte/assets/1020579/24564189-7ee5-4c39-b92f-267e015912bd)

```
<script lang="ts">
	import * as Select from '$comp/ui/select';

	export let value: string;
</script>

<Select.Root selected={value}>
	<Select.Trigger class="w-[180px]">
		<Select.Value placeholder="" />
	</Select.Trigger>
	<Select.Content>
		<Select.Item value="last hour">Last Hour</Select.Item>
		<Select.Item value="last 24 hours">Last 24 Hours</Select.Item>
		<Select.Item value="last week">Last Week</Select.Item>
		<Select.Item value="last 30 days">Last 30 Days</Select.Item>
		<Select.Item value="">All Time</Select.Item>
	</Select.Content>
</Select.Root>
```

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://stackblitz.com/edit/github-sqktjm?file=src%2Froutes%2F%2Bpage.svelte

### More Information

- Stackblitz repo project has several issues out of the box that cause the site not to work.
- Samples don't even show how to bind to a value.

**Comment by HubbeDev** [comment]
Hi @niemyjski,

Could this help? [#361](https://github.com/huntabyte/shadcn-svelte/issues/361#issuecomment-1776602834)

**Comment by niemyjski** [comment]
I don't think so, I don't want a key value pair selected. It's unnatural to every single web select component / control I've seen or used. I'm using the latest release as Thursday.

**Comment by niemyjski** [comment]
@HubbeDev ^^

**Comment by niemyjski** [comment]
Can we reopen this?

**Comment by huntabyte** [comment]
No. It has nothing to do with this project, rather https://github.com/melt-ui/melt-ui, and it's the expected behavior at the moment.
