### ISSUE TITLE
Feature: Striped Tables

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#463]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

It's quite common to striped/zebra table rows, it would be nice if this was built into this component.

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
This project tries to stay aligned with the original, if table variations are added to that, then we can revisit, but for now this is unplanned as it can easily be added by passing a different class for the background color into the even/odd rows of your table in your local component.

When considering things like this, I think about how much of a PITA is this to implement for the dev/user locally, if it's simple, then adding it just adds bloat to the project that everyone who adds the component may not ever want/need.
