### ISSUE TITLE
Consider renaming the PostCSS files to `*.pcss`?

### ISSUE THREAD

**Issue by shyakadavis** [huntabyte/shadcn-svelte#465]
### Current Behavior

This first threw me off when I tried initialising a new project, and had me worried, but turns out it wasn't an issue on `ss`'s side, but rather on `svelte-add`'s.

Per this, https://github.com/svelte-add/svelte-add/issues/311, they decided to rename the `.postcss` file to `.pcss`. Reasons highlighted there.

Do you think it's a good idea to follow suit and rename the defaults during `init` for ss as well?

If so, I volunteer a P.R.

### Expected Behavior

Not really an issue, but I just want to hit `enter` and use all defaults when initializing a new project.

### Steps To Reproduce

1. `pnpm create svelte@latest my-app`
2. `pnpx svelte-add@latest tailwindcss`

**Comment by huntabyte** [comment]
Sure!
