### ISSUE TITLE
Button icon sizes

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#466]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently it's not possible out of the box to have icon buttons match different sizes of other buttons. Should more sizes be added?
```html
<Button size="sm" variant="outline">Toggle View</Button>
<Button size="icon"><ArrowDownIcon /></Button>
```
![image](https://github.com/huntabyte/shadcn-svelte/assets/1020579/2b30d5b5-4fe2-4073-9941-0ceed0995c73)

### What type of pull request would this be?

None

**Comment by niemyjski** [comment]
@huntabyte what do you recommend as a possible solution or call out to consumers?

**Comment by HubbeDev** [comment]
@niemyjski You could easily get the right size of the icon button by applying the same height class to the icon button like this:

```svelte
<Button variant="outline" size="sm">Toggle View</Button>
<Button variant="outline" size="icon" class="h-8 ml-1">
	<ChevronRight />
</Button>
```

```
sm: h-8
default: h-9
lg: h-10
```
