### ISSUE TITLE
Why doesn't the Dropdown Checkbox behave like an input checkbox?

### ISSUE THREAD

**Issue by hsb-tonmoy** [huntabyte/shadcn-svelte#467]
I was trying to implement a column visibility dropdown for Tanstack Table as shown here: https://tanstack.com/table/v8/docs/examples/svelte/column-visibility

However, the DropdownMenu.CheckboxItem doesn't export an on:change event, and trying to bind to the checked state throws this error: `Can only bind to an identifier (e.g. `foo`) or a member expression (e.g. `foo.bar` or `foo[baz]`)`

I was trying to achieve something like this:

```
<DropdownMenu.CheckboxItem
						bind:checked={column.getIsVisible()}
						on:change={column.getToggleVisibilityHandler()}
					>
						{column.id}
					</DropdownMenu.CheckboxItem>
```

**Comment by huntabyte** [comment]
Because it's not a native checkbox element.

If you want to listen for change, use the `onCheckedChange` handler and add your logic there.
