### ISSUE TITLE
Tags Input component

### ISSUE THREAD

**Issue by pitzzahh** [huntabyte/shadcn-svelte#470]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hello everyone! I appreciate this fantastic component library; I've been happily using it in my recent Svelte projects. Are there any plans to add more components? Thanks!

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://www.melt-ui.com/docs/builders/tags-input

**Comment by huntabyte** [comment]
We are only going to be adding what is in the original!
