### ISSUE TITLE
bind:selected not working as expected when multiple={true}

### ISSUE THREAD

**Issue by hendrikvanb** [huntabyte/shadcn-svelte#473]
### Current Behavior

`bind:selected` within the  `<Select/>` component seems to have no effect when `multiple={true}` in that the bound variable does not appear to update in response to selection changes. 

### Expected Behavior

For `bind:selected` to update the bound variable, as in the case when `multiple={false}`.

### Steps To Reproduce

1. Bind a variable to `selected` within `<Select/>` and observe that all works as expected.
2. Set `multiple={true}` and observe that the bound variable does not update in response to selection changes.

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://stackblitz.com/edit/github-bif7vt?file=src%2Froutes%2F%2Bpage.svelte

**Comment by huntabyte** [comment]
Hey @hendrikvanb, thanks for raising this issue! This is actively being worked on in the underlying library (bits-ui), see: https://github.com/huntabyte/bits-ui/issues/121.

I'm doing a big refactor PR: https://github.com/huntabyte/bits-ui/pull/184, which I plan on addressing this in!

**Comment by hendrikvanb** [comment]
Thank you for the feedback and for the excellent work on this project in general, @huntabyte!  Looking forward to the update!
