### ISSUE TITLE
Incorrect opening selection

### ISSUE THREAD

**Issue by levcom** [huntabyte/shadcn-svelte#474]
### Current Behavior

![Screenshot from 2023-11-23 18-31-44](https://github.com/huntabyte/shadcn-svelte/assets/7757231/86beab75-7241-41a9-b432-dd7a5e10973a)
When you select the **right** element, the list from the **left** opens.

### Expected Behavior

    <div class="col-span-2 grid items-start gap-6 ">
        <DemoContainer>
            <CardsReportIssue />
        </DemoContainer>
    </div>
    <div class="grid items-start gap-6 ">
        <DemoContainer>
            <CardsReportIssue />
        </DemoContainer>
    </div>

### Steps To Reproduce

When you select the **right** element, the list from the **left** opens.

**Comment by huntabyte** [comment]
Oh it looks like we're rendering that component twice! Will fix!

**Comment by huntabyte** [comment]
It's because you are rendering the same component, and the example component has an `id` associated with it, so you need to make sure they have unique IDs, or don't pass one at all and one will be automatically generated for you.
