### ISSUE TITLE
Calendar and Date Picker Component

### ISSUE THREAD

**Issue by FortyGazelle700** [huntabyte/shadcn-svelte#475]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I'd love to see a port of Shadcn's Calendar Component and DatePicker. This might already be planned but if you need a reference to the [Offical Shadcn Docs - Date Picker](https://ui.shadcn.com/docs/components/date-picker) and Offical Shadcn Docs - Calendar](https://ui.shadcn.com/docs/components/calendar).

### What type of pull request would this be?

New Feature

**Comment by sokyran** [comment]
There is already an issue for that, so I guess you probably should close this as duplicate

https://github.com/huntabyte/shadcn-svelte/issues/287
