### ISSUE TITLE
Select Box Power User Functionality

### ISSUE THREAD

**Issue by FortyGazelle700** [huntabyte/shadcn-svelte#476]
### Current Behavior

Clicking (mouse down and mouse up) on the Select Box opens the menu.

### Expected Behavior

Mouse down to open the menu hover over the item to select, release and element is selected. (Expected behavior from [Shadcn React](https://ui.shadcn.com/docs/components/select))

### Steps To Reproduce

1. Using the Component `Select` in [Shadcn Svelte](https://www.shadcn-svelte.com/docs/components/select)
2. Hover over the select box
3. Mouse down
4. [!!] Expected behavior: Menu to be opened (Works in [Shadcn React](https://ui.shadcn.com/docs/components/select))
5. [!!] Expected behavior: Hover over the item to select
6. [!!] Expected behavior: Mouse up
7. [!!] Expected behavior: Item is selected

**Comment by huntabyte** [comment]
This would be something you'd want to create an issue as a feature request/enhancement for https://github.com/melt-ui/melt-ui which powers this project.
