### ISSUE TITLE
Bind not working in <Input type="file />

### ISSUE THREAD

**Issue by artneo7** [huntabyte/shadcn-svelte#478]
### Current Behavior

When I use `<Input type="file" bind:files />`, the variable `files` is not updated, but when I use `<input type="file" bind:files />` it works. Maybe that's a bug, I'm not sure.

![example](https://github.com/huntabyte/shadcn-svelte/assets/17693529/39dcec46-5039-4e11-aadd-bcc56a9b5a7e)

### Expected Behavior

-

### Steps To Reproduce

-

**Comment by huntabyte** [comment]
This is as expected, as components containing inputs with the `type` attribute do not support two-way binding (a Svelte thing). I'd suggest just adding your own `FileInput` or similar to specifically handle files.
