### ISSUE TITLE
Bind:this does not work with focus() and click() for buttons/inputs

### ISSUE THREAD

**Issue by bennettcolecohen** [huntabyte/shadcn-svelte#480]
### Current Behavior

When using bind:this with form elements (buttons, inputs), I often like to use js to focus or click on them like so:
```js
let inputElement;
onMount (  () => inputElement.focus())
```

Later on in the HTML: 
```html
<Input bind:this={inputElement}/>
```

However, I get errors not recognizing the function on undefined.

### Expected Behavior

As with other props (bind value, class name, etc), I feel like we should be able to bind directly to a var in svelte. I can go in the source and hack around it, but feels like it should be native. 

Thx! I've seen other people post about it but not sure if there has been a concrete resolution just yet.

### Steps To Reproduce

Feels fairly self explanatory.

**Comment by huntabyte** [comment]
We'd need to expose the element as a prop that could be bound to for all the components, this can be on the roadmap but it will also require the same within https://github.com/huntabyte/bits-ui as well, so it may be some time. In the meantime, you can handle it yourself within the `Input` component since you own the code!

**Comment by huntabyte** [comment]
Going to close this as it's more related to https://github.com/huntabyte/bits-ui

**Comment by drKreso** [comment]
So in input I would do something like this

```ts
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import type { InputEvents } from './index.js';
	import { cn } from '$lib/utils.js';

	type $$Props = HTMLInputAttributes;
	type $$Events = InputEvents;

	let className: $$Props['class'] = undefined;
	export let value: $$Props['value'] = undefined;
	export { className as class };

	// Workaround for https://github.com/sveltejs/svelte/issues/9305
	// Fixed in Svelte 5, but not backported to 4.x.
	export let readonly: $$Props['readonly'] = undefined;
	let inputRef: HTMLInputElement; //added

	export function focus() { //added
		if (inputRef) {
			inputRef.focus();
		}
	}
</script>

<input
	class={cn(
		'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
		className
	)}
        bind:this={inputRef} //added
	bind:value
	{readonly}
	on:blur
	on:change
	on:click
	on:focus
	on:focusin
	on:focusout
	on:keydown
	on:keypress
	on:keyup
	on:mouseover
	on:mouseenter
	on:mouseleave
	on:paste
	on:input
	on:wheel|passive
	{...$$restProps}
/>
```

Right?

**Comment by shirecoding** [comment]
Don't we need this functionality to be able to set focus on an shadcn input component from the parent? this is quite an important functionality IMO.

for instance the user might want to use a hotkey like backtick to switch focus to an Input element

**Comment by huntabyte** [comment]
Use `bind:ref` in shadcn-svelte@next

**Comment by flodev** [comment]
I'm using svelte-shadcn@latest :/

Only way to solve this for me was to manipulate the component manually.
So after adding it with `npx  shadcn-svelte@latest add input` I changed the component into the following:

```svelte
<script lang="ts">
// component stuff

type $$Props = HTMLInputAttributes & { inputElement: HTMLInputElement }; // props changed here
export let inputElement: HTMLInputElement; // this is added newly
</script>

<input
{/* other bindings */}
bind:this={inputElement} //this needs to be added
{...$$restProps}
/>
```

I'm completely new to svelte.
