### ISSUE TITLE
Can't select radio item on click

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#484]
### Current Behavior

https://github.com/huntabyte/shadcn-svelte/assets/44144724/606de464-232b-4868-8f86-6bafb2e5f50d
https://www.shadcn-svelte.com/examples/cards

### Expected Behavior

I expect the radio item to get selected when a pointer down and up happens on/in it.

### Steps To Reproduce

In the video.
1. Do `pointerdown` on icon.
2. Do `pointerup` on text.
3. Or visa versa.

**Comment by babakfp** [comment]
> Isn't the icon supposed to be the trigger? If you move away from the icon while holding the pointer, it should not trigger it, and vice versa.

The whole box is the trigger because when you just click anywhere in the box (without dragging), that box/item gets selected.

https://github.com/huntabyte/shadcn-svelte/assets/44144724/f9a81aae-d743-4d5a-ac1c-3af791833505

**Comment by huntabyte** [comment]
this is an issue you should raise with https://github.com/melt-ui/melt-ui for how the click events are handled vs pointerdown/pointerup
