### ISSUE TITLE
Linting errors when bringing in components:  error  '$$Events' is defined but never used  @typescript-eslint/no-unused-vars

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#489]
### Current Behavior

Lots of the current components have out of the box linting errors with eslint.  https://github.com/exceptionless/Exceptionless/actions/runs/7032476394/job/19136290542

### Expected Behavior

There should be no linting errors with default eslint configuration.

### Steps To Reproduce

1. Install a component
2. Run `eslint .`

### More Information

Since components are source imported linting is important.

**Comment by niemyjski** [comment]
I feel like it would be easy to fix this in a pr, but the core fix would be to add eslint to the project if it's not already.

**Comment by huntabyte** [comment]
We're not messing with anyone's ESlint configuration as that's a slippery slope. See #449

**Comment by diegoulloao** [comment]
Having the same issue. It just doesn't make sense to have the `$$Events` variable if is not used. This is happening for all the components as I can see. In consequence `import type { InputEvents } from "."` is unnecessary too.

**Comment by huntabyte** [comment]
> Having the same issue. It just doesn't make sense to have the `$$Events` variable if is not used. This is happening for all the components as I can see. In consequence `import type { InputEvents } from "."` is unnecessary too.

It does make sense. That's how you get intellisense/types when using the events on the component from outside of it.

https://github.com/dummdidumm/rfcs/blob/ts-typedefs-within-svelte-components/text/ts-typing-props-slots-events.md

**Comment by diegoulloao** [comment]
I got it. So, what's the solution for fix the lint warnings? I'm using lint-staged so I can't commit having those "issues". I don't want to suppress all `unused-vars` warning by setting it to false in the eslint config, because I want to get alerted if my code have unused vars.

Any workaround?

**Comment by huntabyte** [comment]
@diegoulloao https://gist.github.com/huntabyte/b73073a93a7a664f3cbad7c50376c9c9

**Comment by diegoulloao** [comment]
I added this for now:

```json
ignorePatterns: ['src/lib/components/ui']
```
