### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by janzheng** [huntabyte/shadcn-svelte#495]
### Current Behavior

Clicking the submit <Button> for a simple <form> element (not using forms) like in `user-auth-form.svelte` doesn't trigger the Submit form action. Hitting Enter works, but clicking doesn't work.

### Expected Behavior

Clicking the button at the bottom of a form typically performs the submit action on the form

### Steps To Reproduce

Install the docs and look at the `authentication` example

### More Information

This is happening because the button is expected to be `type="submit"` instead of `type="button"` so I think it'd be nice if in the Button code we could do `export let type = "button"; // "submit"` to set a submit button type. Thoughts?
Example button.svelte
```
<script lang="ts">
	import { Button as ButtonPrimitive } from "bits-ui";
	import { cn } from "$lib/utils";
	import { buttonVariants, type Props, type Events } from ".";

	type $$Props = Props;
	type $$Events = Events;

	let className: $$Props["class"] = undefined;
	export let variant: $$Props["variant"] = "default";
	export let size: $$Props["size"] = "default";
	export let builders: $$Props["builders"] = [];
	export { className as class };
         export let type = "button"; // "submit"
</script>

<ButtonPrimitive.Root
	{builders}
	class={cn(buttonVariants({ variant, size, className }))}
	type={type}
	{...$$restProps}
	on:click
	on:keydown
>
	<slot />
</ButtonPrimitive.Root>

```

**Comment by huntabyte** [comment]
You should be able to override the default `type` set since `...$$restProps` is spread after the `type="button"` prop. Does this not work for you?

**Comment by janzheng** [comment]
you're right it works! Wasn't looking at the examples properly
