### ISSUE TITLE
Link button formatting

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#501]
### Current Behavior

Current formatting uses the default size (`'h-9 px-4 py-2`) which adds tons of padding and height.
![image](https://github.com/huntabyte/shadcn-svelte/assets/1020579/c4e82e39-9e4d-467b-83e9-70fba7ed3fe7)

```html
<Button href="/signup" variant="link">Start a free trial</Button>
```

### Expected Behavior

 I just want my button to show like normal link with theming applied since I did variant link. I'd think the default styling would change based on the specific variant like link (e.g., only height would be specified).

### Steps To Reproduce

1. Use two button components with link variant and see all the whitespace between them.

```html
<Button href="/1" variant="link">One</Button>
<Button href="/2" variant="link">Two</Button>
```

### More Information

latest versions

**Comment by huntabyte** [comment]
This component isn't intended to be used inline with text like that, but rather standalone.

If you want to modify the styles locally you can, but this is not planned for the project itself.

**Comment by niemyjski** [comment]
Sounds good, where do you think the link variant should be used. Since links were not in the typography section I assumed for theming purposes we should use buttons due to the link variant and href.

Just trying to understand and hope this helps others
