### ISSUE TITLE
Broken icon transition in dark mode toggle

### ISSUE THREAD

**Issue by deronek** [huntabyte/shadcn-svelte#508]
### Change Type

Correction

### Proposed Changes

https://github.com/huntabyte/shadcn-svelte/pull/400, following mode-watcher https://github.com/huntabyte/mode-watcher/pull/26/, causes the dark mode toggle in docs to not have the expected icon transition. `rotate` and `scale` classes apply, but are applied immediately with no transition.

This is because of `withoutTransition` function used in mode-watcher, which forces all transition to be disabled when mode is being switched. This was introduced because of flashing screen issues when mode switching.

In docs: https://www.shadcn-svelte.com/docs/dark-mode
https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/default/example/dark-mode-light-switch.svelte#L9-14

**Comment by huntabyte** [comment]
I think I can solve this by waiting for any current transitions running to finish _before_ switching the mode.

**Comment by deronek** [comment]
Hi @huntabyte, the issue is still present in current docs. Do you want me to create this issue in `mode-watcher` instead, since it stems from the change of implementation there?
