### ISSUE TITLE
DropdownMenu.SubTrigger is not affected by accent foreground color

### ISSUE THREAD

**Issue by enchart** [huntabyte/shadcn-svelte#511]
### Current Behavior

While highlighted/open, DropdownMenu.SubTrigger doesn't utilize --accent-foreground color variable
![image](https://github.com/huntabyte/shadcn-svelte/assets/77974051/4fc8f685-812e-492c-ac7e-416eacc655bb) ![image](https://github.com/huntabyte/shadcn-svelte/assets/77974051/3b762a8a-f01c-414b-af1e-27d9a978a0c5)

### Expected Behavior

Accent foreground color is applied to SubTrigger while it's highlighted/open. 

### Steps To Reproduce

1. In app.pcss, change --accent-foreground variable's initial value to something else (I used black or `--accent-foreground: 240 5.9% 10%;`)
2. Create a dropdown with a submenu
3. Highlight the submenu's trigger item

### More Information

Can be fixed by adding `data-[highlighted]:text-accent-foreground` and `data-[state=open]:text-accent-foreground` classes to <DropdownMenuPrimitive.SubTrigger /> in [dropdown-menu-sub-trigger.svelte](https://github.com/huntabyte/shadcn-svelte/blob/1642e55ee7e30b2374787005ad2b2fc414769a9a/apps/www/src/lib/registry/new-york/ui/dropdown-menu/dropdown-menu-sub-trigger.svelte#L18C1-L18C151)

**Comment by huntabyte** [comment]
You got it! Thank you! @enchart
