### ISSUE TITLE
Header > Row vertical misalignment when enabling sort in 'data-table'

### ISSUE THREAD

**Issue by kuatroka** [huntabyte/shadcn-svelte#517]
### Current Behavior

Header > Row vertical misalignment when enabling sort in 'data-table'

CIK - sort disabled
![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/901583b8-818a-4aa9-b0ef-77dd705b4fdf)

CIK - sort enabled
![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/9f00b152-57b9-457b-85fc-a2c8d9133bb8)

### Expected Behavior

It should be aligned as minimum to the left and as maximum to have an option (left or right)

### Steps To Reproduce

enable/disable `sort` in the `data-table` component

**Comment by huntabyte** [comment]
This is how it is in the original as well. It's because they are buttons that have padding. If it gets changed in the original https://ui.shadcn.com then I'll consider it here.
