### ISSUE TITLE
Alert Dialog preview component not found in registry with default style

### ISSUE THREAD

**Issue by lafkpages** [huntabyte/shadcn-svelte#520]
### Current Behavior

If you go to the Alert Dialog component's page in the docs, the preview doesn't show up and instead shows "Component alert-dialog-demo not found in registry."

### Expected Behavior

That I can see the preview/demo.

### Steps To Reproduce

Go to the [component's docs page](https://www.shadcn-svelte.com/docs/components/alert-dialog).

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://www.shadcn-svelte.com/docs/components/alert-dialog

### More Information

Note that the error only shows up if you select the default style. The error does not show in New York style.

**Comment by huntabyte** [comment]
Can you all confirm if this is still happening? (make sure you clear your cache and such via a hard reload of the site)

**Comment by huntabyte** [comment]
No worries, it was likely caused by us switching to the "edge" runtime. We switched it back so hopefully, it remains resolved, if not, feel free to reopen!
