### ISSUE TITLE
bug: updating a component with the CLI does not remove files that are deleted upstream

### ISSUE THREAD

**Issue by ollema** [huntabyte/shadcn-svelte#530]
### Current Behavior

right now, when updating the Select component from a version < #500 to a version >= #500 with the CLI results in a leftover `select.svelte`.

this file was removed in #500 but the CLI only add or modifies files so it's still present after upgrading, which can be confusing (especially if it causes linting issues like it did for me in #528)

### Expected Behavior

the `select.svelte` file should not remain after updating the Select component

### More Information

I think the most reasonable option is to delete all files in a component folder before writing the new version there.

there is already a disclaimer that any potential modifications will be overwritten and the one should use source control.

so I don't think there is any additional risks with clearing the component folder before writing to it. instead I think it will lead to less confusion and fewer surprises

**Comment by ollema** [comment]
if you agree, I can attempt to work on this

**Comment by huntabyte** [comment]
Hmm, this is something I'm not 100% sure if we want to wipe the entire directory out with, even files that we don't control, but if not, we'd basically need a way to track the previous and current versions to determine if a file was deleted.

It should be very very rare that something is deleted from the original, in the case of the `Select` it wasn't necessary to include it in the first place, and was an oversight on my end.

I'll see if @AdrianGonz97 has any thoughts on this one, but my gut tells me we should not blow out the entire directory!

**Comment by AdrianGonz97** [comment]
I'm not really comfortable deleting the whole folder as there may be additional files in there that we may not even own.. Honestly, I don't think any action is really necessary and we should just let the user handle it on their own.

**Comment by huntabyte** [comment]
Closing as not planned for now!
