### ISSUE TITLE
Enhancement: New Props for Calendar Component - Disabled Dates, Multiple Day Selection, and Custom Date Styles

### ISSUE THREAD

**Issue by yb-cs** [huntabyte/shadcn-svelte#533]
# Enhancement Request for Calendar Component 📆🛠️

Hello there! I'm excited to suggest some enhancements for the Calendar component. These features would significantly boost its functionality and user experience.

### 1. Disabled Dates Prop 🚫📅
**Description**: This prop would allow us to specify dates in the calendar that should be disabled. These dates would be non-selectable and visually distinct, ideal for indicating unavailable dates like holidays or past days.

### 2. Multiple Day Pick Prop 🗓️✅
**Description**: This feature would enable users to select multiple dates within the calendar. It's a key functionality for scenarios like booking systems or event scheduling, where multiple distinctive dates needs to be chosen.

### 3. Dates with Different Style Prop 🎨📆
**Description**: This enhancement allows for the custom styling of certain dates. It's perfect for highlighting specific dates (such as birthdays or holidays) with different colors, fonts, or borders for easy identification.

Integrating these features would make the Calendar component more versatile and adaptable for various use cases. I believe they would be valuable additions to your library. Looking forward to your thoughts on this!

Thank you for your continuous efforts in improving this library! 🌟

**Comment by huntabyte** [comment]
1. Disabled Dates already exist, use the `isDateDisabled` prop, or if you want the data to be unavailable, is the `isDateUnavailable` prop.
2. Multiple dates already exist (https://bits-ui.com/docs/components/calendar) use the `multiple` prop.
3. This is something that shouldn't be handled at a library level and should be handled individually. You have access to the date before rendering it in the `<Calendar />` component so you can apply your checks and update the styles there!

**Comment by yb-cs** [comment]
Oh thanks a lot! Sorry to bother you with the useless issue open. Have a great day :D
