### ISSUE TITLE
Forms inside (Alert) Dialog do not work properly

### ISSUE THREAD

**Issue by DarthGigi** [huntabyte/shadcn-svelte#535]
### Current Behavior

In the example below, the form submits. However, only the `onSubmit` event runs, the others do not run.
```svelte
<AlertDialog.Root bind:open={showDelete} closeOnEscape={true} closeOnOutsideClick={true}>
  <AlertDialog.Content>
    <AlertDialog.Header>
      <AlertDialog.Title>Warning</AlertDialog.Title>
      <AlertDialog.Description>Are you sure you want to delete this?</AlertDialog.Description>
    </AlertDialog.Header>
    <AlertDialog.Footer>
      <AlertDialog.Cancel>Cancel</AlertDialog.Cancel>
      <Form.Root
        options={{
          onUpdated: () => {
            console.log("updated");
            showFormDialog = true;
          },
          onError: () => {
            console.log("error");
            showFormDialog = true;
          }
        }}
        form={data.formDelete}
        schema={formSchemaDelete}
        let:config
        method="POST"
        action="?/delete"
      >
        <Form.Field {config} name="id">
          <Form.Input type="hidden" value={id} />
        </Form.Field>
        <AlertDialog.Action type="submit">Delete</AlertDialog.Action>
      </Form.Root>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>
```

### Expected Behavior

The expected behavior is that all the events run if they are triggered.

### Steps To Reproduce

1. Create a Form component inside an AlertDialog with custom events other than `onSubmit` as options.
2. Submit the form with `<AlertDialog.Action type="submit"/>` component
3. You will see that the custom events do not run.

**Comment by huntabyte** [comment]
It's because your form is being rendered inside the `Content` which when you click an action is conditionally removed from the DOM. You can do:

```svelte
<AlertDialog.Action on:click={(e) => e.preventDefault()}
```
and then manually close the dialog yourself by binding to the open state

```svelte
<AlertDialog.Root bind:open>
```

once you confirm whatever you need to confirm with your form.

**Comment by DarthGigi** [comment]
Thank you for your reply, I moved the form outside of the AlertDialog and call the form submit event manually. This time the `onUpdated` event works, but the `onSubmit` event does not (the `onResult and `onUpdate` events do not work either, but I do not need those.).

```svelte
<Form.Root
  options={{
    onSubmit: () => {
      console.log("onSubmit");
      submittingDelete = true;
    },
    onResult: () => {
      console.log("onResult");
    },
    onUpdate: () => {
      console.log("onUpdate");
    },
    onUpdated: () => {
      console.log("onUpdated");
      showFormDialog = true;
    },
    onError: () => {
      console.log("onError");
      showFormDialog = true;
    }
  }}
  form={data.formDelete}
  schema={formSchemaDelete}
  let:config
  action="?/delete"
  class="hidden"
  method="POST"
  id="deleteForm"
>
  <Form.Field {config} name="id">
    <Form.Input type="hidden" value={id} />
  </Form.Field>
</Form.Root>
<AlertDialog.Root bind:open={showDelete} closeOnEscape={true} closeOnOutsideClick={true}>
  <AlertDialog.Content>
    <AlertDialog.Header>
      <AlertDialog.Title>Warning</AlertDialog.Title>
      <AlertDialog.Description>Are you sure you want to delete this?</AlertDialog.Description>
    </AlertDialog.Header>
    <AlertDialog.Footer>
      <AlertDialog.Cancel disabled={submittingDelete}>Cancel</AlertDialog.Cancel>
      <AlertDialog.Action
        disabled={submittingDelete}
        on:click={(e) => {
          e.preventDefault();
          const deleteForm = document.getElementById("deleteForm");
          if (!(deleteForm instanceof HTMLFormElement)) return;
          deleteForm.submit();
        }}
      >
        {#if !submittingDelete}
          Delete
        {:else}
          <Loader2 class="h-4 w-4 animate-spin" />
        {/if}
      </AlertDialog.Action>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>
```
I could add `submittingDelete = true;` in the `on:click` event but I feel like having it in the form `onSubmit` is the "cleaner" way. I also feel like getting the form with `document.getElementById()` and submitting it isn't the "right way" to submit the form, but I couldn't find a better way from the [formsnap documentation](https://www.formsnap.dev/docs/introduction).

**Comment by huntabyte** [comment]
Yeah I'm not sure if `.submit()` bypasses some of the superforms methods or not. You could also just use a regular button instead of the action for submit and then somewhere in your `onUpdated` logic close the dialog.

**Comment by DarthGigi** [comment]
It's more about the form and it's functions/events working properly than the dialog closing. The dialog closes automatically since the `.submit()` bypasses the [Superforms `enhance`](https://superforms.rocks/concepts/enhance) (I think), as it fully reloads the page after the form submits.

**Comment by huntabyte** [comment]
Right... so if you submit the form using a <button type="submit"> as you normally would (without calling `.submit()`), then you will have access to the functions/events.

**Comment by DarthGigi** [comment]
I realised my mistake, I should not use `.submit()` but rather `.requestSubmit()`. As stated on the [MDN HTMLFormElement: submit event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event) docs, the [`SubmitEvent`](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent) is not sent if the `.submit()` method is used.

This change resulted in all of the form events running, the page not fully reloading and the AlertDialog no longer closing as a result of that.
As you stated previously, I can just use one of the form events to close the dialog.

Thanks for your help!

**Comment by huntabyte** [comment]
Of course!

**Comment by lfrancke** [comment]
I'm sorry for resurrecting this old issue. I'm just learning Svelte, shadcn-svelte and all the other libraries and I have trouble getting this to work.

If it's not too much work for you (DarthGigi), would you mind posting your working example of submitting the form? I have the exact same use-case: A confirmation before deletion.

**Comment by DarthGigi** [comment]
Hey @lfrancke,

What I did was place an alert dialog in the root of a +page.svelte component and bind the open status to a boolean variable. When the user clicks on the delete button, the on:click event of the delete button sets the boolean to true so that the alert is shown.

In the alert dialog the delete button / primary button calls the submit function that superforms returns: https://superforms.rocks/api#superform-return-type.

You can take a look at my current implementation [here](https://github.com/DarthGigi/MinionAH/blob/main/src/routes/(main)/(protected)/profile/%2Bpage.svelte#L365-L391).

If you have any questions, feel free to hit me up on discord, @tim_cook (if you have discord) so we don't keep bumping this issue. I'll be happy to help you out!
