### ISSUE TITLE
Hidden Form Field Binding Issue with Store Value

### ISSUE THREAD

**Issue by yb-cs** [huntabyte/shadcn-svelte#536]
## Description :memo:
When binding a value to a hidden field from the store and submitting a form, the submission does not work as expected. However, enabling the debug feature results in successful form submission. This suggests an issue with the form state not being updated correctly without the debug feature.

## Actual Behavior :x:
The form state does not update appropriately when the debug feature is disabled, leading to unsuccessful form submission.

## Expected Behavior :bulb:
The form state should be correctly updated and submitted regardless of the debug feature's status.

## Steps to Reproduce :footprints:
1. Bind a value to a hidden field from the store.
2. Submit the form without the debug feature enabled.
3. Notice the form submission does not work as expected.
4. Enable the debug feature.
5. Submit the form again.
6. Observe that the form submission now works.

## Example Code (Not Working) :keyboard:
```svelte
<Form.Root
  action="?/submitNewApplicantForm"
  form={newApplicantForm}
  schema={defaultNewApplicantSchema}
  let:config
  let:enhance
>
  <form method="POST" use:enhance={{ onResult: onFormSubmitResult }}>
    <!-- Other Form Fields -->
    <Form.Field {config} name="sourceCountry">
      <Form.Item>
        <Form.Input type="hidden" bind:value={sourceCountry} />
      </Form.Item>
    </Form.Field>
    <Form.Field {config} name="destinationCountry">
      <Form.Item>
        <Form.Input type="hidden" bind:value={destinationCountry} />
      </Form.Item>
    </Form.Field>
    <Form.Button>Submit</Form.Button>
  </form>
</Form.Root>
```
## Example Code (Working) :keyboard:
```svelte
<Form.Root
  debug
  action="?/submitNewApplicantForm"
  form={newApplicantForm}
  schema={defaultNewApplicantSchema}
  let:config
  let:enhance
>
  <form method="POST" use:enhance={{ onResult: onFormSubmitResult }}>
    <!-- Other Form Fields -->
    <Form.Field {config} name="sourceCountry">
      <Form.Item>
        <Form.Input type="hidden" bind:value={sourceCountry} />
      </Form.Item>
    </Form.Field>
    <Form.Field {config} name="destinationCountry">
      <Form.Item>
        <Form.Input type="hidden" bind:value={destinationCountry} />
      </Form.Item>
    </Form.Field>
    <Form.Button>Submit</Form.Button>
  </form>
</Form.Root>
```

**Comment by yb-cs** [comment]
---
**Temporary Solution with HiddenSetter Component** :hourglass_flowing_sand:

I've temporarily resolved the issue using the `HiddenSetter` component. This is a workaround until a more permanent fix can be implemented. Here's the current solution:

```svelte
<Form.Field {config} name="destinationCountry" let:setValue>
  <HiddenSetter {setValue} value={destinationCountry} />
  <Form.Item>
    <Form.Input type="hidden" />
  </Form.Item>
</Form.Field>
```

```svelte
// HiddenSetter.svelte
<script>
  export let setValue;
  export let value;

  // Reactive statement that runs whenever `value` changes
  $: setValue(value);
</script>
```

This method effectively updates the form state using the `HiddenSetter` to bind the store value reactively, serving as an interim fix.

**Comment by huntabyte** [comment]
You don't bind to the `Form.Input` - see https://formsnap.dev for more information. You can use them headlessly and bind if you wish.
