### ISSUE TITLE
Allow passing size to Avatar component

### ISSUE THREAD

**Issue by canidam** [huntabyte/shadcn-svelte#537]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The Avatar component doesn't seem to be resizable. It's pretty small and it would be nice if you I could control it's size (either by providing preset such sm, md, lg, xl or the size itself (w-14 h-14)

WDYT?

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
You can update the size by passing `w-whatever h-whatever` to the `Avatar.Root` component

**Comment by canidam** [comment]
Ah! I tried passing it to the Avatar.Image component and didn't get why it doesn't work 😑
Thanks for the fast reply.
