### ISSUE TITLE
Ability to Select month/year in calendar component

### ISSUE THREAD

**Issue by dongumayagay** [huntabyte/shadcn-svelte#539]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

like native html selector. or other date picker. where you can just click the month/year to select month/year you want.

for current implementation, if i want to go to 10 years ago that will be 120 clicks on left button

i use range calendar for selecting date range for research site. so date different is often large

i know that this isn't implemented in ui/shadcn. but for better ux?

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
An example to accomplish this is already on the docs:
https://www.shadcn-svelte.com/docs/components/calendar#advanced-customization
