### ISSUE TITLE
I fear the 'svelte-headless-table' library will not be active anymore - maybe need to switch to another one?

### ISSUE THREAD

**Issue by kuatroka** [huntabyte/shadcn-svelte#540]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hi, this a note from the creator of the awesome svelte-headless-table. This feels like the future of this library is not too bright. Maybe it warrants the move from it to something else,  something more maintained but with the same great features...I don't know many libs with tables, but maybe the tanstack for svelte?

![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/ca269670-01a0-476a-a291-77652f75daca)

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
Tanstack Table for Svelte is 100% off the table. Trying to do anything beyond the basics is an utter nightmare and IMO has more risk of being stale than svelte headless table.

Right now I'm not considering switching to another, as he mentioned he is open to contributions from the community to assist, so it is time for open source to kick in 🚀

**Comment by kuatroka** [comment]
Got it. I've these two, but I'm not sure how long term they are either...

1

https://vincjo.fr/datatables/remote/home

2

https://svelte-ux.techniq.dev/docs/components/Table/
