### ISSUE TITLE
Cli to add component doesn't work if i have different alias/folder structure

### ISSUE THREAD

**Issue by nooblyf** [huntabyte/shadcn-svelte#546]
### Current Behavior

I have a folder structure like this

```
└── package.json/
    ├── apps/
    │   └── web/
    │       └── src/
    │           └── app.html
    └── packages/
        └── ui/
            ├── components.json
            ├── package.json
            └── src/
                ├── base.pcss
                ├── index.ts
                ├── utils.ts
                └── components/
                    └── button/
```

I'm inside packages/ui and trying to add a new component like this
```sh
pnpx shadcn-svelte@latest add sheet
```

here's my `components.json` file
```json
{
	"$schema": "https://shadcn-svelte.com/schema.json",
	"style": "new-york",
	"tailwind": {
		"config": "tailwind.config.js",
		"css": "src/base.pcss",
		"baseColor": "zinc"
	},
	"aliases": {
		"components": "$src/components",
		"utils": "$src/utils"
	}
}
```

### Expected Behavior

Nothing gets added, and when i run the cli command again i'm getting
```sh
Component sheet already exists. Use --overwrite to overwrite.
```

### Steps To Reproduce

1. Create a new repo with `pnpx create-turbo@latest -e with-svelte`
2. cd into packages/ui
3. Run `pnpx shadcn-svelte@latest init`
4. Change default aliases to something like above
5. Run `pnpx shadcn-svelte@latest add sheet`

### More Information

The component is probably being created somewhere in my computer because i'm getting component exists when i run the cli for the second time

**Comment by HubbeDev** [comment]
@huntabyte  Hi! I have done some digging about this issue and what i found out is that in [get-config.ts](https://github.com/huntabyte/shadcn-svelte/blob/99b796f55ec17637c987fa39e88129596d0e34f3/packages/cli/src/utils/get-config.ts#L86C2-L100C4) the paths for utils and compoenets is parsed from the compiled tsconfig found in .svelte-kit which is not regenerated until the dev server is started or a build is made. So if custom alias is added to sveltekit config and try to run shadcn-svelte init before regenerating the sveltekit build. Then the alias is not updated correclty and results in a path like this: 

```
 config.aliases["utils"] === '.../test/.svelte-kit/$packages/utils',
 config.aliases["components"] === '.../test/.svelte-kit/$packages/components'
```

In my example i had an alias named "$packages" in svelte config. And set the components.json aliases to $packages/components and $packages/utils.

This results in that a  folder "$packages" is generated in .svelte-kit instead with the utils.ts and components folder.

@nooblyf I do not know if you have fixed this but if you still need help. Dose it works for you if you add the alias $src to svelte.config.js and run the the dev server before running the cli init command?

**Comment by huntabyte** [comment]
Thanks for digging into this @HubbeDev. We aren't in the business of starting and restarting the dev server/building the app for peeps, so this will need to be resolved at the user level.

When you update your aliases you need to do one of those steps in order for the _true_ `tsconfig` to update so that we can verify the path and install things in the correct locations.
