### ISSUE TITLE
Dialog overlay doesn't prevent bubbling on mobile

### ISSUE THREAD

**Issue by hugotox** [huntabyte/shadcn-svelte#548]
### Current Behavior

When opening a dialog on mobile devices, the overlay is not preventing interactions with elements behind it. This behavior doesn't happen on desktop.

### Expected Behavior

Dialog overlay prevents bubbling for desktop and mobile.

### Steps To Reproduce

Just open a dialog on mobile, and notice how the elements behind the overlay are interactive.

<img width="716" alt="Screenshot 2023-12-17 at 4 54 37 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/1758062/988171c0-b307-4dae-9b5a-5e02d747d569">

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://stackblitz.com/edit/github-hrerew?file=src%2Froutes%2F%2Bpage.svelte

**Comment by huntabyte** [comment]
Were you able to confirm this behavior on an actual mobile device? I've noticed that the browser devtool simulation doesn't actually represent behavior on a mobile device.

**Comment by hugotox** [comment]
Yes, but it only happens on webkit browsers: safari, duckduckgo. Doesn't happen on chrome

**Comment by huntabyte** [comment]
This is an issue occurring with Melt UI, rather than shadcn-svelte, so I am going to close this here. Feel free to open an issue with Melt if this issue is still persisting!
