### ISSUE TITLE
Type error when using component in .svelte file

### ISSUE THREAD

**Issue by alvinsga** [huntabyte/shadcn-svelte#551]
### Current Behavior

Receiving the following error:

"Argument of type 'typeof Tabs' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'typeof Tabs' provides no match for the signature 'new (args: { target: any; props?: any; }): ATypedSvelteComponent'.

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}ts(2345)"

### Expected Behavior

No type errors

### Steps To Reproduce

<script lang="ts">
  import * as Tabs from "$lib/components/ui/tabs";
</script>

<Tabs.Root value="account" class="w-[400px]">
  <Tabs.List>
    <Tabs.Trigger value="account">Account</Tabs.Trigger>
    <Tabs.Trigger value="password">Password</Tabs.Trigger>
  </Tabs.List>
  <Tabs.Content value="account">
    Make changes to your account here.
  </Tabs.Content>
  <Tabs.Content value="password">Change your password here.</Tabs.Content>
</Tabs.Root>

**Comment by huntabyte** [comment]
Can you link a reproduction repo?

**Comment by alvinsga** [comment]
Turns out it was a dependency issue in the existing project.

**Comment by mattlm0831** [comment]
@alvinsga 

What was the dependency issue? I am having the same error.

**Comment by mattlm0831** [comment]
For anybody looking for a solution the issue is caused from not being up to date with your svelte version. I upgraded to 4.2.8 and have no more issues. For reference the issues were only from my interpreter, I was still able to run everything fine.
