### ISSUE TITLE
Docs: `Command.Input` positioning in Dashboard example

### ISSUE THREAD

**Issue by nhuxhr** [huntabyte/shadcn-svelte#552]
### Current Behavior

The `Command.Input` is not functioning as expected; it only accepts default values and does not accept new values.

### Expected Behavior

To allow the acceptance of new values.

### Steps To Reproduce

1. Install the `command` component.
2. Employ the provided code sample below.
3. Attempt to input any value into the command search field.

```svelte
<Command.Root>
	<Command.List>
		<Command.Input placeholder="Search..." />
	</Command.List>
</Command.Root>
```

### More Information

The solution is quite simple tho. Here is my solution (`$lib/components/ui/command/command-input.svelte`):

```diff
<!-- $lib/components/ui/command/command-input.svelte -->
<script lang="ts">
	import { Command as CommandPrimitive } from 'cmdk-sv';
	import { Search } from 'lucide-svelte';
	import { cn } from '$lib/utils';

	type $$Props = CommandPrimitive.InputProps;

	let className: string | undefined | null = undefined;
	export { className as class };
- 	export let value: string = '';
+	export let value: string | undefined = undefined;
</script>

<div class="flex items-center border-b px-2" data-cmdk-input-wrapper="">
	<Search class="mr-2 h-4 w-4 shrink-0 opacity-50" />
	<CommandPrimitive.Input
		class={cn(
			'flex h-11 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50',
			className
		)}
		{...$$restProps}
		bind:value
	/>
</div>
```

I can contribute if you don't mind, or you can help fix the bug. Either way, I'm here and relaxed. 🤞

**Comment by huntabyte** [comment]
The `Input` should be outside of the `List` no?

**Comment by huntabyte** [comment]
Oh, whoops! That's an issue on this end, will address!
