### ISSUE TITLE
Lucide Icons not rendering inside control flow blocks

### ISSUE THREAD

**Issue by StevenStavrakis** [huntabyte/shadcn-svelte#558]
### Current Behavior

In sveltekit, when using icons, anything inside of a conditionally rendered block is not rendered at all.

### Expected Behavior

I would expect icons to render correctly regardless of where they appear in my templates.

### Steps To Reproduce

1. Create template
2. Create state `showIcon` set to `false`
3. In an `$effect` create a setTimout to change `showIcon` to true after some time.
4. Place an icon in an `{#if showIcon}` block
5. Icon does not render

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://github.com/StevenStavrakis/lucide-svelte-csr-issue

### More Information

I know this isn't directly associated with shadcn/svelte, but I'm hoping that someone has run into this issue before can can advise on how to fix it.

**Comment by AdrianGonz97** [comment]
This looks to be a Svelte 5 issue: https://github.com/sveltejs/svelte/issues/9645

As we don't officially support Svelte 5 yet, I would advise sticking with Svelte 4 until v5 is stable.

**Comment by StevenStavrakis** [comment]
Ah. Well, that's unfortunate. Thanks for looking into this.
