### ISSUE TITLE
`h-20` in Textarea component interferes with `rows` attribute

### ISSUE THREAD

**Issue by phenomen** [huntabyte/shadcn-svelte#56]
### Current Behavior

Setting `rows` attribute on Textarea does nothing because its height is overwritten by `h-20` class.

https://github.com/huntabyte/shadcn-svelte/blob/0dd34440e2c61b40b6073ea5f35ce08d6834decd/apps/www/src/lib/components/ui/textarea/Textarea.svelte#LL13C13-L13C13

Sure, I can set a different `h-*` but there are a few utilities that auto-increase textarea height based on its content and they use `rows` for that.

**Comment by huntabyte** [comment]
Thanks for pointing that out.

I believe changing `h-20` to `min-h-[80px]` would solve this problem. I'll test it out and try to get it updated today!
