### ISSUE TITLE
Feature request: carousel

### ISSUE THREAD

**Issue by seanalexfinnell** [huntabyte/shadcn-svelte#561]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Latest shadcn update now includes a carousel component based on Embla library

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://ui.shadcn.com/docs/components/carousel
https://www.embla-carousel.com/get-started/svelte/

**Comment by JustDenP** [comment]
I also switched all my sliders from keen-slider to embla yesterday, very pleasant to work with it.
Take a look at this project https://svelte-embla.vercel.app/

It's a tiny wrapper, that exports slider events and works with stores instead of HTML nodes as the original solution from embla devs

**Comment by davidjerleke** [comment]
Hi @seanalexfinnell and @JustDenP,

This is the **official Svelte** wrapper for Embla which is **actively maintained** (it's minimal too):

- Package: [`embla-carousel-svelte`](https://github.com/davidjerleke/embla-carousel/tree/master/packages/embla-carousel-svelte).
- Docs: [Get started guide here](https://www.embla-carousel.com/get-started/svelte/).

Both `shadcn-react` and `shadcn-vue` use the official wrappers [`embla-carousel-react`](https://github.com/davidjerleke/embla-carousel/tree/master/packages/embla-carousel-react) and [`embla-carousel-vue`](https://github.com/davidjerleke/embla-carousel/tree/master/packages/embla-carousel-vue) respectively.

Best,
David

**Comment by huntabyte** [comment]
Hey @davidjerleke,

Thanks a ton for bringing this to my attention! We'll certainly use your maintained wrapper!

**Comment by JustDenP** [comment]
@davidjerleke Thank you for providing additional information! I just wanted to say that I found it harder to make additional plugins and especially navigation, like thumbnails, where one slider depends on a state of another. The repo I provided makes it very easy and it just wraps embla events with almost the same svelte events, so even if embla will change or add one of these, it will require changing 1 line of code (I also do not recommend using npm package, just copy one small file to be able to control it in case of any updates)

So it would be great if the official wrapper had more examples like for react 👍
