### ISSUE TITLE
Missing Async Await for Froms documentation

### ISSUE THREAD

**Issue by yorickvandervis** [huntabyte/shadcn-svelte#562]
### Change Type

Correction

### Proposed Changes

Unsure if this is correct or not, but according to the docs of Superforms we're supposed to use async/await to return the form from a load function. In step 2 & 5 of the new Form component this is not the case:

```
export const load: PageServerLoad = () => {
  return {
    form: superValidate(formSchema)
  };
};
```

Should it be like this?

```
export const load: PageServerLoad = (async () => {
    return {
        form: await superValidate(createUserSchema)
    };
});
```

Happy to open PR and fix it right away.

**Comment by huntabyte** [comment]
Closed by #572
