### ISSUE TITLE
Select popover position

### ISSUE THREAD

**Issue by hugotox** [huntabyte/shadcn-svelte#565]
### Current Behavior

The select's popover default position is positioned right next to the trigger element, which is different from what we see in the documentation example, where it sits a couple of px below.

Docs: https://www.shadcn-svelte.com/docs/components/select
<img width="661" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/1758062/ce38344b-5ea2-4a37-837a-ea99491e8c8b">

Actual behavior:
<img width="450" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/1758062/2e45f59d-db8d-4829-b2bb-86e09785daf2">

**Note** also the select items are not left aligned

### Expected Behavior

Copying the code from the docs example should produce the same UI

### Steps To Reproduce

Just copy and paste the example code from the select's page docs https://www.shadcn-svelte.com/docs/components/select

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://stackblitz.com/edit/github-3mkwy5?file=README.md,src%2Froutes%2F%2Bpage.svelte

### More Information

This used to be working as expected. I haven't found the update that broke it.
Current versions: 
- `"tailwindcss": "^3.4.0"`
- `"bits-ui": "^0.11.8"`

**Comment by huntabyte** [comment]
You're comparing the `New York` example to the `Default` example. Also, I just updated the reproduction template with the latest component updates, there were some changes to the "Floating" components in a recent update. See: https://github.com/huntabyte/bits-ui/releases/tag/v0.10.0 for more info

**Comment by hugotox** [comment]
Thanks for the quick response! 
My bad on comparing the 2 styles, but still on the docs page, the default style has a little distance between the select and the popover.

**Comment by huntabyte** [comment]
No worries! That was my bad for not updating the repro template! We made some changes to how the positioning is set in the `Select.Content`

**Comment by hugotox** [comment]
Cool! So, in general when updating bits-ui dependency, we should run the `shadcn-svelte@latest add` again?

**Comment by huntabyte** [comment]
Not always necessary, but sometimes it is! You can diff the latest version of the comps to see if any props change, or rely on linter/check to determine if all is still good! Once bits-ui is stable of course this will happen less frequently, which we're getting close to!
