### ISSUE TITLE
Date Picker With Presets documentation example causes permanent scroll lock

### ISSUE THREAD

**Issue by nkooman** [huntabyte/shadcn-svelte#567]
### Current Behavior

When interacting with the With Presets example of the Date Picker, you can permanently lock the scroll of the page.

### Expected Behavior

I would expect that there is no scroll locking at all.

### Steps To Reproduce

1. Interact with the With Presets example in the documentation.
2. Open the date picker.
3. Open the select element. (The scroll lock happens here and is still togglable at this point)
5. Close the popover by clicking outside of the element.

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://www.shadcn-svelte.com/docs/components/date-picker#:~:text=Feb%209%2C%202022-,With%20Presets,-Preview

**Comment by huntabyte** [comment]
This will be closed with an upcoming docs update.

**Comment by huntabyte** [comment]
Closed by #585
