### ISSUE TITLE
Putting .min() on a string in a zod schema causes the input to fail client validation

### ISSUE THREAD

**Issue by StevenStavrakis** [huntabyte/shadcn-svelte#568]
### Current Behavior

```
import { z } from "zod";

export const formSubmitIdentifierSchema = z.object({
  identifier: z.string().min(2).max(32)
});

export type FormSubmitIdentifier = typeof formSubmitIdentifierSchema;
```

The above schema causes any input to fail with error `String must contain at least 2 character(s)`

I experience no issues with the following change:

`identifier: z.string().max(32)`

### Expected Behavior

I would expect the client side validation to work correctly.

### Steps To Reproduce

Just follow the steps for the form in the docs.

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://github.com/StevenStavrakis/svelte-5-formsnap-issue

### More Information

On SvelteKit 2 and Svelte 5

Inputs over 32 characters are handled correctly, so this makes me think there isn't an issue with my code.

**Comment by StevenStavrakis** [comment]
Also, the validation status doesn't change when I change the input values. I suppose that might be related.

**Comment by StevenStavrakis** [comment]
Reproduction: https://github.com/StevenStavrakis/svelte-5-formsnap-issue

**Comment by StevenStavrakis** [comment]
Similar behavior: https://github.com/huntabyte/shadcn-svelte/issues/564#issuecomment-1871931691

**Comment by huntabyte** [comment]
Does this happen on Svelte 4? We aren't officially supporting Svelte 5 yet so any bugs related to it will be ignored until it's stable.
