### ISSUE TITLE
Number Input in a Form Always Fails Validation Due to Type Error

### ISSUE THREAD

**Issue by Owliwik** [huntabyte/shadcn-svelte#574]
### Current Behavior

When creating a form with a number input, the submitted type is a string, which is not converted despite setting type='number'. This causes the zod validation always to fail. 

The form I created:
<img width="916" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/107664911/25d434f7-a0d5-401d-8e67-32953350ef08">

SuperDebug:
<img width="812" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/107664911/bf115a5d-30a4-4c3e-bade-7aecea7c9bd9">

My schema:
<img width="1117" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/107664911/cc68f4bf-5d06-4985-9889-35efe5b75f6d">

### Expected Behavior

If I correctly set up the context and set the input type to be 'number' in the FormInput component, the submitted form data should also have time to be of type 'number' instead of 'string'. 

### Steps To Reproduce

1. Create a form schema that has a field of type number in it (e.g. age)
2. Set up the form context in the format listed in the forms section of the docs (so root - field - item - input) with the props correctly added
3. Add super debug
4. Input a number and submit
5. The error will be displayed

### More Information

The vanilla input component from HTML works fine.

**Comment by jakebennett18505** [comment]
I'm having the same issue. Workaround I found is to use z.coerce.number() in your Zod schema definition.

![Screenshot 2024-01-04 at 14 03 12](https://github.com/huntabyte/shadcn-svelte/assets/143882267/6d6822ab-68b1-4757-81af-9e55a1f03b49)


<img width="466" alt="Screenshot 2024-01-04 at 14 02 39" src="https://github.com/huntabyte/shadcn-svelte/assets/143882267/2a998406-b82b-47cc-8518-16bc510b3cec">

**Comment by huntabyte** [comment]
This is the recommended approach, thanks! @jakebennett18505

**Comment by GimpMaster** [comment]
I came across this as well, it would be great to add a simple call out to the docs for the Input formsnap component
