### ISSUE TITLE
Speed up dev servers; `lucide-svelte` issue

### ISSUE THREAD

**Issue by shyakadavis** [huntabyte/shadcn-svelte#575]
### Current Behavior

Given https://github.com/lucide-icons/lucide/pull/1707, which you also briefly touched over in the stream, I wanted to volunteer to import all `lucide-svelte` icons in the new/faster format.

### Expected Behavior

```
import Circle from "lucide-svelte/icons/circle";
```

### Steps To Reproduce

N/A

**Comment by huntabyte** [comment]
Go for it!

**Comment by AdrianGonz97** [comment]
Thanks for taking this on! 🙂

I just want to note down here (before I forget) that we'll have to validate that changing the import paths to use deep imports doesn't break our registry builder script. There's a good chance that it will, so we'll have to modify it to accommodate. I can handle that part right before we merge your PR.

**Comment by coryvirok** [comment]
Really looking fwd to this! The slow dev server reloads are killing my DevX.

**Comment by gregmsanderson** [comment]
If the docs could be updated, that would be good for new users.

For example I've just been trying it out today. I created a "hello world" app with some basic pages, tried adding a dark mode toggle based on https://www.shadcn-svelte.com/docs/dark-mode and noticed the build took much longer. Sure enough it was looping over _every_ icon as part of the build, despite _only_ needing the sun and moon icon.

Making this change:

```js
//import { Sun, Moon } from 'lucide-svelte';
import SunIcon from 'lucide-svelte/icons/sun';
import MoonIcon from 'lucide-svelte/icons/moon';
```

... and updating the page to match the names resulted in going from ...

```
vite v5.1.3 building for production...
✓ 2023 modules transformed.
```

... to ...

```
vite v5.1.3 building for production...
✓ 595 modules transformed.
```

_Way_ faster.

**Comment by huntabyte** [comment]
We're tracking @gregmsanderson. There's an issue with a dependency that is holding us back at the moment but should be resolved soon.
