### ISSUE TITLE
Screen config replacing all screens rather than extending

### ISSUE THREAD

**Issue by knd775** [huntabyte/shadcn-svelte#577]
The `2xl` screen config belongs under `extend` rather than directly in the `theme` config. As it is, it is replacing all screen breakpoints with this one rather than overriding just `2xl`.

https://github.com/huntabyte/shadcn-svelte/blob/20c6bd623a836b31bbe2fc14068550afcfe53676/apps/www/tailwind.config.js#L12-L14

I can open a quick PR to fix this, but figured I should open an issue first.

**Comment by huntabyte** [comment]
These screens should only be applied to the container. Are you experiencing it conflicting elsewhere? [ref](https://tailwindcss.com/docs/container)

**Comment by knd775** [comment]
That's true, but I guess I don't understand why you'd want the only screen for the container to be `2xl`. It prevents things like setting custom screen-based padding values for the container
