### ISSUE TITLE
Add CLI docs

### ISSUE THREAD

**Issue by Creative-Difficulty** [huntabyte/shadcn-svelte#579]
### Change Type

Addition

### Proposed Changes

In one of my other issues (#298), im asking for a new cli command to be implemented, which was actually done. However i have noticed that there are no docs for the cli commands (correct me if im wrong). This is very suboptimal.

**Comment by huntabyte** [comment]
That PR has not been merged yet.

**Comment by Creative-Difficulty** [comment]
That PR has been merged, but it doesn't have anything to do with this. big fan of your yt btw
