### ISSUE TITLE
Install dependencies in `devDependencies` instead of `dependencies`

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#580]
### Current Behavior

The dependencies are installed in `dependencies` in `package.json`.

### Expected Behavior

I expect the dependencies to be installed in `devDependencies` instead.

### More Information

Hi

It doesn't make sense why the dependencies are installed in `dependencies` rather than `devDependencies`. When we work on Svelte apps, we add them in `devDependencies`, and in some rare scenarios, we may add them to `dependencies`. It's annoying to move them back to `devDependencies`.

I also found this: https://github.com/huntabyte/shadcn-svelte/discussions/120

Thanks

**Comment by AdrianGonz97** [comment]
> It doesn't make sense why the dependencies are installed in dependencies rather than devDependencies. When we work on Svelte apps, we add them in devDependencies, and in some rare scenarios, we may add them to dependencies.

There is no standard for Svelte apps. While it ultimately doesn't matter where the dependency lives, as Vite bundles them the same anyway, we feel that if you're actively using the dependency at the runtime, then it should be installed as a `dependency`. 

If your personal preferences don't match ours, that's completely fine! You're free to move them where ever you prefer.
