### ISSUE TITLE
Use `export default` for `tailwind.config` file

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#582]
### Current Behavior

```js
const config = {
}
export default config
```

### Expected Behavior

```js
export default {
}
```

### More Information

Tailwind CLI uses `export default`. We don't use the data inside the file itself, so the is no reason to name it. It's cleaner to use `export default`.

Thanks.

**Comment by huntabyte** [comment]
This is a bit of a nitpick. You may not use the data inside the file itself, but others may. What is worse, needing it and having to rewrite the statement or just leaving it be and it just works out of the box the same way?
