### ISSUE TITLE
When a `Checkbox` is inside a `Label`, clicking on `Checkbox` doesn't work

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#584]
### Current Behavior

https://github.com/huntabyte/shadcn-svelte/assets/44144724/ad0c44d0-c4df-44ac-a34b-f1cc703117cd

### Expected Behavior

I expect it to toggle.

### Steps To Reproduce

```js
import { Label } from "$lib/components/ui/label"
import { Checkbox } from "$lib/components/ui/checkbox"
```

```html
<Label>
    <Checkbox bind:checked />
    <span>My text</span>
</Label>
```

### More Information

I use this sort of thing when I want to make the whole thing clickable/toggleable.

```html
<label>
    // some stuff here
    <input type="checkbox" />
    // some stuff here
</label>
```

bits-ui uses a `button` element instead of an `input` with a type of `checkbox`.
https://github.com/huntabyte/bits-ui/discussions/251

**Comment by huntabyte** [comment]
It doesn't work the same way since the `Checkbox` is not a normal checkbox, rather a button. You can include a `for` with the `id` of the checkbox to achieve this same behavior.
