### ISSUE TITLE
<Selected selected={...}> isn't reflected in form submission

### ISSUE THREAD

**Issue by mlegls** [huntabyte/shadcn-svelte#587]
### Current Behavior

Default values for a `Select` field set via its `select` prop aren't reflected in the form submission. For example, with `let answer="1"` in the script tag, and an element 
```
<Form.Field {config} name="answer">
	<Form.Item>
		<Form.Label>Select</Form.Label>
		<Form.Select selected={{ value: answer, label: answer }}>
			<Form.SelectTrigger />
			<Form.SelectContent>
				{#each ["1","2","3","4"] as choice (choice)}
					<Form.SelectItem value={choice}>{choice}</Form.SelectItem>
				{/each}
			</Form.SelectContent>
		</Form.Select>
		<Form.Validation />
	</Form.Item>
</Form.Field>
``` 
inside a `Form`, the submitted value is 
```
{
  id: '...',
  valid: true,
  posted: true,
  errors: {},
  data: { answer: '' },
  constraints: { answer: { required: true } }
}
```

### Expected Behavior

The submitted value should be
```
{
  id: '...',
  valid: true,
  posted: true,
  errors: {},
  data: { answer: '1' },
  constraints: { answer: { required: true } }
}
```
which is only the case after manual re-selection

### Steps To Reproduce

Using `<Form.select>` with props `selected={{value: x, label: x}}`, where `x` is any reactive variable initialized to a string, submit the form.

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://stackblitz.com/edit/github-rnv3ep?file=src%2Froutes%2F%2Bpage.server.ts

**Comment by huntabyte** [comment]
Closing as not applicable anymore with updates to Formsnap.
