### ISSUE TITLE
mode-watcher in sonner component

### ISSUE THREAD

**Issue by jramke** [huntabyte/shadcn-svelte#595]
### Current Behavior

i need to install the `mode-watcher` package or remove the `theme={$mode}` attribute to make the sonner component work.

### Expected Behavior

It should be working without `mode-watcher` by default

### Steps To Reproduce

1. Adding Toaster component 
2. Add `<Toaster />` to the layout

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

Missing sonner component

**Comment by huntabyte** [comment]
Please provide more information into the issue you're experiencing, or better yet create a reproduction and I can take a look.

**Comment by PaulDotterer** [comment]
@huntabyte had this same issue.
When installing the Sonner component via pnpx `mode-watcher` does not get installed along side.
A simple `pnpm install mode-watcher` fixes the issue.

When creating a new SvelteKit project with shadcn-svelte the issue pops up, as soon as you add the `<Toaster />` component to the root layout.

My project was created before the sonner component was added to shadcn-svelte, if that is of any help.

**Comment by huntabyte** [comment]
Great, will look into this!
