### ISSUE TITLE
Can't scroll overflowing select menu

### ISSUE THREAD

**Issue by TheOnlyTails** [huntabyte/shadcn-svelte#596]
### Current Behavior

I have a very large select menu, which contains more items than can fit on the screen at once, but there's no way to scroll the list and pick one properly.

![image](https://github.com/huntabyte/shadcn-svelte/assets/65342367/7de69277-021b-474e-b772-018d62650d4d)

### Expected Behavior

The list should be scrollable, or deferred to the browser's native select list.

### Steps To Reproduce

1. Create a new select menu with more items than can fit on one screen.
2. Try scrolling the select list.

**Comment by huntabyte** [comment]
You just need to set a maximum height and set `overflow: scroll` on the content if your list is longer than whatever the max you'd want to be displayed at once is.
