### ISSUE TITLE
Calendar ERR_SVELTE_TOO_MANY_UPDATES

### ISSUE THREAD

**Issue by ConProgramming** [huntabyte/shadcn-svelte#598]
### Current Behavior

Got the error `Error: ERR_SVELTE_TOO_MANY_UPDATES: Maximum update depth exceeded. This can happen when a reactive block or effect repeatedly sets a new value. Svelte limits the number of nested updates to prevent infinite loops.` when trying to paginate the months.

### Expected Behavior

Should not give the error.

### Steps To Reproduce

Use the default Calendar component https://www.shadcn-svelte.com/docs/components/calendar

**Comment by huntabyte** [comment]
We don't support Svelte 5 at this time and won't until a stable release.

**Comment by ConProgramming** [comment]
> We don't support Svelte 5 at this time and won't until a stable release.

Any tips here? I have runes mode off for shadcn components and dependencies. Every other component works great, it's just the next/prev buttons on the calendar that aren't.

**Comment by benny856694** [comment]
> > We don't support Svelte 5 at this time and won't until a stable release.
> 
> Any tips here? I have runes mode off for shadcn components and dependencies. Every other component works great, it's just the next/prev buttons on the calendar that aren't.

Don't use Svelte 5 for now.
