### ISSUE TITLE
Pagination component overflowing its container on mobile devices

### ISSUE THREAD

**Issue by DarthGigi** [huntabyte/shadcn-svelte#600]
### Change Type

Correction

### Proposed Changes

As you can see in the screenshot, on mobile devices the pagination component overflows the container:
![Overflowing pagination](https://github.com/huntabyte/shadcn-svelte/assets/47110839/cec0d676-604b-4e0e-90da-9f30c11d6c5f)

I marked this as a docs issue since a user of this component can easily change the number of pages shown on mobile screens as they desire.

**Comment by huntabyte** [comment]
Thanks! Will look into this!

**Comment by huntabyte** [comment]
If anyone has time to investigate/fix this, let me know!

**Comment by DarthGigi** [comment]
Would changing the amount of pages shown based on the screen size be an idea?

Or maybe an overflow scroll on the container could work as well?

**Comment by HubbeDev** [comment]
@huntabyte I could take a look at it. 

I like the idé about showing less pages.
