### ISSUE TITLE
Enhance shadcn-svelte with DaisyUI

### ISSUE THREAD

**Issue by mmailaender** [huntabyte/shadcn-svelte#608]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

How strong is `shadcn-svelte` trying to be the same as `shadcn`? Or are you also open to discussions about one or another aspect of it? 

Specifically, I would love to see the design system elevated with DaisyUI. With that, we would have out of the box
- support for [elevated surfaces](https://daisyui.com/docs/colors/#-2) (base-100/200/300)
- Colors for `Success`, `Warning` & `Info`
- Extended CSS features like [stacking elements on each other](https://daisyui.com/components/stack/)
- Support for [Themes](https://daisyui.com/docs/themes/) (Instead of only light and dark mode)

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
Going to close this for now as it won't be added to this core project. We'll create a discussion once we're at that point to start taking contributions into this "thing".
