### ISSUE TITLE
 ESLint error in tailwind.config.cjs

### ISSUE THREAD

**Issue by Tihomir971** [huntabyte/shadcn-svelte#61]
### Current Behavior

line: const { fontFamily } = require("tailwindcss/defaultTheme")
get error: Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)

### Expected Behavior

No ESLint error

### Steps To Reproduce

CLI Instalation

**Comment by huntabyte** [comment]
Can you link a reproduction, I don't get that lint error and I haven't ran into this when starting a new project from scratch but I'm definitely interested in seeing if it's something we need to fix.

**Comment by geerew** [comment]
Indeed it’s about ESM imports, but why not just update it to

import { fontFamily } from "tailwindcss/defaultTheme"

instead of changing the .cjs to a .js ?
