### ISSUE TITLE
Previous, Next, and Ellipsis parts of Pagination component should be customizable for i18n purposes

### ISSUE THREAD

**Issue by bfovez** [huntabyte/shadcn-svelte#613]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The Previous, Next, and Ellipsis parts of Pagination component shows English terms: "Previous", "Next", and "More pages".
Those terms should be customizable for i18n purposes.

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
You can edit the component in your code with whatever customization you'd like.

**Comment by bfovez** [comment]
Fair enough. Thank you.
