### ISSUE TITLE
DropdownMenu.Content as individual component

### ISSUE THREAD

**Issue by JannisDev** [huntabyte/shadcn-svelte#616]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I appreciate the concept of having the DropdownMenu.Content, or something similar to the Context Menu, behave like a hovering Table of Contents positioned to the left of the content div.
Have I missed any existing component that can readily accomplish this?

![image](https://github.com/huntabyte/shadcn-svelte/assets/80353903/309fb37f-5f4d-404e-9d93-65692d909159)

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
At this time I don't think this is likely to be added. There are certain accessibility concerns here as the dropdown menu is expected to be triggered by something and a11y standards treat sidebar navigations (like in your example) differently than the "menus".

We'll work on adding a navigation menu component which may help you out.
