### ISSUE TITLE
Can't use Select component within Tabs component in Svelte 5

### ISSUE THREAD

**Issue by 1mehal** [huntabyte/shadcn-svelte#632]
### Describe the bug

Can't use Select component within Tabs component in Svelte 5

When selection changes for select component it jumps and resets the page

### Reproduction

https://stackblitz.com/edit/github-vtdaer

### System Info

```bash
Chrome
```

### Severity

blocking all usage of shadcn-svelte

**Comment by huntabyte** [comment]
We aren't officially supporting Svelte 5 until the API is stable.
