### ISSUE TITLE
Why even have a select component if it won't work in a form context?

### ISSUE THREAD

**Issue by matteopiatti** [huntabyte/shadcn-svelte#637]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I do appreciate the effort that went into the creation of the form components, which I know includes a Form.Select component.

Still I do wonder why no just render out a hidden select input for the select component? The select component has a name and required attribute option, but does not work in a form context. This seems counterintuitive. I know there is the option of using the form compponent, but as it is in preview id be wary. Even if, I would then have to set up zod and the whole form config, just for a simple little form? This seems very user unfriendly.

What's your thoughts? Would there be incentive to change this?

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
There is no incentive to change this, the capability to use the `<Select />` within the context of a form has and always will be there: https://www.bits-ui.com/docs/components/select#selectinput

**Comment by matteopiatti** [comment]
Ah thanks, I didn't see that, that's basically what I meant
