### ISSUE TITLE
Charting components

### ISSUE THREAD

**Issue by JonathonRP** [huntabyte/shadcn-svelte#639]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Would love dataviz charting components that match shadcn/UI style. There are many charting libs for svelte and sveltekit. I know shadcn/UI uses recharts in react but they're not components usable like the others and it would be nice especially with svelte having more of an identity with dataviz

### What type of pull request would this be?

New Feature

**Comment by kuatroka** [comment]
Keep an eye on [layerchart](https://github.com/techniq/layerchart ) I think he is doing something with design tokens to make the integration with shadcn-svelte, daisy, skeleton easier.

**Comment by JonathonRP** [comment]
> Keep an eye on [layerchart](https://github.com/techniq/layerchart ) I think he is doing something with design tokens to make the integration with shadcn-svelte, daisy, skeleton easier.

Layerchart has its own UI - svelte/ux which could be the reason for tokens to integrate with his own lib which also uses tailwind...

There's cakecharts also that I keep an eye on

**Comment by huntabyte** [comment]
Unless shad adds charts to the original, we won't be adding them here. You can get an idea for how you can use them using some of the various examples, or checkout layerchart as the others have mentioned!

**Comment by JonathonRP** [comment]
Darn thought I made a good enough case for svelte shadcn/UI to have charts even if not implemented in react original lib, seeing as svelte is a heavily associated with dataviz 😅

**Comment by gursheyss** [comment]
Since charts are being added to native shadcn now will we be seeing ports to svelte? 

https://twitter.com/shadcn/status/1795920488797188525

**Comment by JonathonRP** [comment]
@huntabyte I'm using layerchart and it works great and is svelte components

**Comment by gursheyss** [comment]
> Unless shad adds charts to the original, we won't be adding them here. You can get an idea for how you can use them using some of the various examples, or checkout layerchart as the others have mentioned!

Charts are officially in shadcn now https://ui.shadcn.com/docs/components/chart

**Comment by JonathonRP** [comment]
[https://github.com/techniq/layerchart](layerchart) is very similar to recharts API but under the hood takes advantage of svelte and SSR @huntabyte

**Comment by kuatroka** [comment]
layerchart is indeed a very cool lib, maybe even better than **recharts**. If it were integrated into shadcn-svelte, it'd be awesome to the max.

 The original shadcn example page for charts looks very slick, especially with different themes
