### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by carwei** [huntabyte/shadcn-svelte#64]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Just found this through YouTube. I'm fairly new to Svelte, but I love what I'm seeing on your channel and your work here. Will you implement the "Navigation Menu" component from the original set of components?

It happens to match something I'm looking for and I'd be willing to throw in a bit of cash to sponsor it/you.

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://ui.shadcn.com/docs/components/navigation-menu

**Comment by huntabyte** [comment]
Hey @carwei ! This component will come once the Radix Svelte primitive that supports it has been created.  Radix Svelte is mostly being developed by one person, so I would direct that compensation incentive over to [Radix Svelte](https://github.com/tglide/radix-svelte). As soon as the Radix primitives that support the nav menu are read to go, I will release the same one that appears on the original `shadcn/ui`.

**Comment by huntabyte** [comment]
Closing this issue due to the new temp component issue created for tracking this - #102
