### ISSUE TITLE
Use Pagination component instead of buttons for Data Table

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/shadcn-svelte#641]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Since the Pagination component is now available, I wanted to know if implementing it into the docs of the Data Table component would be a good idea.

I know it wouldn't make a good parity with [ui.shadcn.com](https://ui.shadcn.com), however, it could look great and make more sense than the two simple buttons. Or maybe add a tab option to the Pagination subsection to offer the option to integrate the Pagination component with the Data Table.

If parity is the only issue, I can try to open the same issue on https://github.com/shadcn-ui/ui and see if I can get it implemented too.

### What type of pull request would this be?

Docs

### Provide relevant links or additional information.

Implementation if you're wondering:
```svelte
...
<div class="flex items-center justify-end space-x-2 py-4">
		...
		<Pagination.Root
			class="mx-0 w-auto flex-row"
			count={$rows.length}
			page={$pageIndex + 1}
			perPage={$pageSize}
			onPageChange={page => ($pageIndex = page - 1)}
			let:pages
			let:currentPage
		>
			<Pagination.Content>
				<Pagination.Item>
					<Pagination.PrevButton>
						<ChevronLeft class="size-4" />
						<span class="hidden sm:block">Previous</span>
					</Pagination.PrevButton>
				</Pagination.Item>
				{#each pages as page (page.key)}
					{#if page.type === "ellipsis"}
						<Pagination.Item>
							<Pagination.Ellipsis />
						</Pagination.Item>
					{:else}
						<Pagination.Item>
							<Pagination.Link {page} isActive={currentPage === page.value}>
								{page.value}
							</Pagination.Link>
						</Pagination.Item>
					{/if}
				{/each}
				<Pagination.Item>
					<Pagination.NextButton>
						<span class="hidden sm:block">Next</span>
						<ChevronRight class="size-4" />
					</Pagination.NextButton>
				</Pagination.Item>
			</Pagination.Content>
		</Pagination.Root>
	</div>
</div>
```
([Link](https://github.com/WarningImHack3r/advent-of-svelte/blob/main/src/routes/2023/productivity-dashboard/DataTable.svelte))

**Comment by huntabyte** [comment]
Parity would be the only issue here, once it happens there it will happen here 😃

**Comment by WarningImHack3r** [comment]
Closing for now while we don't get an answer from shadcn/ui
