### ISSUE TITLE
Package managers dropdown on code copy

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/shadcn-svelte#642]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

[ui.shadcn.com](https://ui.shadcn.com) has a feature that I like: when you press the right button to copy a command in the docs, you get the choice to choose the package manager you want to copy for.

This feature doesn't exist on [shadcn-svelte.com](https://shadcn-svelte.com). Are you okay for me to implement it (using the dropdown menu component?), making it as close as possible to the original design from shadcn?

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
Sounds good to me!
