### ISSUE TITLE
Missing step in docs installation guide for older versions of npm

### ISSUE THREAD

**Issue by Dayonel** [huntabyte/shadcn-svelte#643]
### Change Type

Addition

### Following the installation guide I've received this error in both steps 2 and 5.

**`ENOENT: no such file or directory`**

![image](https://github.com/huntabyte/shadcn-svelte/assets/10290812/baad4d34-4813-4179-ac6e-2fffe8fe1a12)

![image](https://github.com/huntabyte/shadcn-svelte/assets/10290812/a9516bc1-1491-44ce-882b-c4b06f309dd3)

It is assumed you have **svelte-add** and **shadcn-svelte** packages installed globally, without them you can't continue. Usually npx ask you to install them out-of-the-box, but in my case didn't ask about it and only throw me an error.

So I suggest it would be helpful to add this command before step 2 as hint or recommendation, in case this happens to someone else:

`npm i -g svelte-add@latest`

and add this command before step 5:

`npm i -g shadcn-svelte@latest`

Thanks to @dawntraoz helping me solving this issue, you are the best.

**Comment by AdrianGonz97** [comment]
Thanks for raising an issue!

Users are **not** expected to have `svelte-add` or `shadcn-svelte` installed globally. If the package is not cached or installed locally, `npx` should automatically fetch the package from the registry and execute the program. You can learn more about how it works [here](https://docs.npmjs.com/cli/v7/commands/npx).

As for why it didn't work for you, I'm not quite sure. More information is needed to understand why. A good start would be to run the following command _inside of your project_ and print the output here:
```bash
npx envinfo --system --binaries --npmGlobalPackages --npmPackages
```

**Comment by huntabyte** [comment]
We're not going to add documentation to support every possible version of node/npm out there.
