### ISSUE TITLE
Add resizable

### ISSUE THREAD

**Issue by bjk95** [huntabyte/shadcn-svelte#645]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

https://ui.shadcn.com/docs/components/resizable

### What type of pull request would this be?

New Feature

**Comment by Benjamoon** [comment]
In think [svelte-splitpanes](https://github.com/orefalo/svelte-splitpanes) could be a good start for this?

**Comment by huntabyte** [comment]
I'm finalizing a lib that will be used for this - should be ready to ship within the next week or so.

**Comment by huntabyte** [comment]
Closing referencing: #683 (It is assumed that any feature in shadcn/ui is already on the roadmap/being worked on for this project, therefore it doesn't need a feature request issue)
