### ISSUE TITLE
When tapping the carousel previous/next buttons multiple times it triggers page zoom

### ISSUE THREAD

**Issue by davidjerleke** [huntabyte/shadcn-svelte#652]
Hello from the Embla side, I hope you're all doing well 👋!

### Describe the bug

When tapping the carousel previous and next buttons multiple times on an iOS device, it sometimes triggers an unwanted page zoom.

## Suggested solution
I believe adding `touch-action: manipulation;` [here](https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/default/ui/carousel/carousel-previous.svelte#L22) and [here](https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/default/ui/carousel/carousel-next.svelte#L21) solves the problem. As [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action#manipulation) describes it:

> Enable panning and pinch zoom gestures, but disable additional non-standard gestures such as double-tap to zoom. Disabling double-tap to zoom removes the need for browsers to delay the generation of click events when the user taps the screen.

### Reproduction

- Browse to the [carousel page](https://www.shadcn-svelte.com/docs/components/carousel) on an iOS device like an iPhone.
- Tap on the next button twice or more to scroll through the carousel slides.
- See the page gets zoomed which probably isn't what you wanted to do.

### System Info

```bash
Device: iPhone 8
Browser: Safari iOS 16.7.4
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Hey @davidjerleke, thanks for raising this issue!

Will work on the fix as soon as I get the chance!

**Comment by davidjerleke** [comment]
@huntabyte sounds good. Thanks for the swift response 👍🏻.

**Comment by shyakadavis** [comment]
Hey, @huntabyte 

I could send a P.R if you're busy ATM; the fix seems straightforward.

Wdyt?

**Comment by huntabyte** [comment]
> Hey, @huntabyte
> 
> I could send a P.R if you're busy ATM; the fix seems straightforward.
> 
> Wdyt?

I actually had a few minutes just now to take care of this one! Thank you!
