### ISSUE TITLE
text-opacity not working

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#653]
### Describe the bug

Thanks for this library!

It seems like tailwind's own text-opacity-[value] is not working with this library.

### Reproduction

`<h2 class="text-opacity-20">Artist</h2>`

### System Info

```bash
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 2.21 GB / 40.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.6.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 15.6.1
  npmPackages:
    @sveltejs/kit: ^2.3.2 => 2.3.2 
    bits-ui: ^0.14.0 => 0.14.0 
    formsnap: ^0.4.2 => 0.4.2 
    mode-watcher: ^0.1.2 => 0.1.2 
    svelte: 5.0.0-next.35 => 5.0.0-next.35 
    sveltekit-superforms: ^1.13.3 => 1.13.3
```

### Severity

annoyance

**Comment by huntabyte** [comment]
I believe you need to include the color class to the same element as the opacity you're trying to modify:

https://v2.tailwindcss.com/docs/text-opacity#usage this is v2 docs but I think now the recommended approach is to do text-blue-500/90 vs text-blue-500 text-opacity-90.
