### ISSUE TITLE
Carousel momentum doesn't work when tapping the carousel previous/next buttons multiple times

### ISSUE THREAD

**Issue by gustavomorinaga** [huntabyte/shadcn-svelte#659]
### Describe the bug

When tapping the carousel previous and next buttons multiple times or hold the click, it not handle the momentum.

I noticed this when I was checking the new components and comparing them with the official `shadcn` docs:
- [shadcn/ui carousel](https://ui.shadcn.com/docs/components/carousel)
- [shadcn-svelte carousel](https://www.shadcn-svelte.com/docs/components/carousel)

### Reproduction

- Browse to the [carousel page](https://www.shadcn-svelte.com/docs/components/carousel)
- Tap on the next button or previous button multiple times or hold the click to scroll through the carousel slides
- See that the carousel doesn't trigger momentum and freezes when holding down one of these buttons

### System Info

```bash
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 27.97 GB / 31.23 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 4.0.0 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.14.0 - ~/.local/share/pnpm/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  npmPackages:
    @sveltejs/kit: 2.3.2 => 2.3.2 
    bits-ui: 0.14.0 => 0.14.0 
    formsnap: 0.4.2 => 0.4.2 
    svelte: 4.2.8 => 4.2.8 
    sveltekit-superforms: 1.13.2 => 1.13.2
```

### Severity

annoyance

**Comment by Benjamoon** [comment]
Ill have a look :)

**Comment by Benjamoon** [comment]
Looking at the carousel component, it seems we are doing the same thing that shadcn-ui does. 

We are just calling the underlying `api.scrollNext` / `api.scrollPrev`

I would assume the issue is with embla's svelte implementation 😢 
Might be worth opening an issue on that repo?

**Comment by gustavomorinaga** [comment]
Hmm yeah. @davidjerleke opened #652, that is similar to this issue.

**Comment by davidjerleke** [comment]
@gustavomorinaga @Benjamoon have you followed [this guide](https://www.embla-carousel.com/guides/previous-and-next-buttons/#button-placement) in the docs and placed the buttons correctly?

The problem you’re experiencing might be related to that.

Best,
David

**Comment by Benjamoon** [comment]
But a quick look comparing the DOM structures generated from shadcn/ui and shadcn-svelte seem to be the exact same.

# shadcn/ui
![image](https://github.com/huntabyte/shadcn-svelte/assets/102172929/a70aad85-9492-4dd9-a733-bc2199e91253)

# shadcn-svelte
![image](https://github.com/huntabyte/shadcn-svelte/assets/102172929/f0df5e00-a575-4710-b793-38cc2ce7d3bb)

**Comment by davidjerleke** [comment]
@Benjamoon it depends on which element node you attach the `emblaCarouselSvelte` action to. I don’t have access to my computer now so can’t check properly.

**Comment by Benjamoon** [comment]
Ahh, that makes sense, let me have a look and ill get back to you

**Comment by Benjamoon** [comment]
Yep @davidjerleke that is 100% the problem, the action is applied to the Carousel.Root component when i think (might be wrong) it should be applied to the Carousel.Content component as the Previous and Next buttons are children of the Root component.

Or maybe making the Previous and Next buttons not be children of the root component?

**Comment by davidjerleke** [comment]
> Or, in this screenshot, it should be applied to the "embla__viewport" instead of the "embla" div?

@Benjamoon that’s correct 👍🏻.

**Comment by Benjamoon** [comment]
👍 

Not overly sure I'm smart enough to refactor it all to work like that.

Possibly a @huntabyte thing

**Comment by huntabyte** [comment]
The DOM positioning shouldn't matter here because I'm setting the selectors manually rather than relying on the node.children[0]. Will investigate further later though!

**Comment by davidjerleke** [comment]
@huntabyte even of that’s the case, the **root node**, the one that has the `emblaCarouselSvelte` action attached to it, will be the same element that has event listeners for drag events.

If this is the culprit, a click on any of the buttons may trigger unintended drag interactions on the carousel or stop a scrolling carousel momentarily.

Best,
David

**Comment by huntabyte** [comment]
@davidjerleke ahh, that makes much more sense! Thank you!
