### ISSUE TITLE
Increase the max-width of the Calendar card in "Themes" page

### ISSUE THREAD

**Issue by NDOY3M4N** [huntabyte/shadcn-svelte#660]
### Change Type

Correction

### Proposed Changes

We just need to increase the `max-width` on the Calendar card a little. Here's the screenshot on mobile (it's also the same on bigger screens)

![image](https://github.com/huntabyte/shadcn-svelte/assets/46305144/f74ff9b3-f302-4305-9c57-9a0568ecbea8)

**Comment by huntabyte** [comment]
I'm not able to reproduce this behavior?
