### ISSUE TITLE
Scroll area component

### ISSUE THREAD

**Issue by nooblyf** [huntabyte/shadcn-svelte#665]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Would be great if there was a scroll area component like this :)
https://ui.shadcn.com/docs/components/scroll-area

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
Closing referencing: #683 (It is assumed that any feature in shadcn/ui is already on the roadmap/being worked on for this project, therefore it doesn't need a feature request issue)
