### ISSUE TITLE
Can't tab to select component

### ISSUE THREAD

**Issue by cotyhamilton** [huntabyte/shadcn-svelte#667]
### Describe the bug

Can't tab to select component

### Reproduction

https://www.shadcn-svelte.com/examples/forms

Try to tab to select component

### System Info

```bash
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 97.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/n/bin/node
    Yarn: 1.22.21 - ~/n/bin/yarn
    npm: 10.2.3 - ~/n/bin/npm
    pnpm: 8.14.1 - ~/n/bin/pnpm
  Browsers:
    Safari: 15.6.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Safari doesn't support tabbing to non-form components unless you have a specific accessibility setting enabled in your OS, which someone using assistive technology would certainly have enabled.

The same is true for https://ui.shadcn.com, among every other custom (non-native) select implementation out there.
