### ISSUE TITLE
Tooltip not working on mobile? 

### ISSUE THREAD

**Issue by Rar9** [huntabyte/shadcn-svelte#671]
### Describe the bug

https://www.shadcn-svelte.com/docs/components/tooltip

### Reproduction

Test on demo

### Logs

```bash
?
```

### System Info

```bash
Android Chrome
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Tooltips don't work on mobile because there is no "hover" state on mobile. If you need a tooltip on mobile, then a `Popover` may better align with what you're trying to accomplish.

**Comment by Rar9** [comment]
I thought this was based on https://melt-ui.com/docs/builders/tooltip
