### ISSUE TITLE
Prepend and append icons for input fields

### ISSUE THREAD

**Issue by manankarnik** [huntabyte/shadcn-svelte#672]
## Description
It would be great to have a method to add prepend and append icons inside an input field. The field could look something like this:
![input](https://github.com/huntabyte/shadcn-svelte/assets/25849906/3c678009-754f-45ef-8367-f46d75db04ba)

## Possible Implementation
One method could be using named slots as they allow flexibility of elements. I could raise a PR for the same.
```svelte
<Input bind:value={search} placeholder="Search" class="my-4 w-60 gap-2">
  <Search slot="prepend" size={22} class="text-muted-foreground" />
  <Button slot="append" size="icon" variant="ghost" on:click={() => {}} class="w-5 h-5">
    <X class="text-muted-foreground" />
  </Button>
</Input>
```

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
We're not going to use slots because they will no longer be necessary in Svelte 5. Additionally, we're not going to add anything that isn't in the original https://ui.shadcn.com project. If a variant is added for this there, then we will add it here.
