### ISSUE TITLE
Select cannot scroll through items

### ISSUE THREAD

**Issue by samuel-sojka** [huntabyte/shadcn-svelte#674]
### Describe the bug

When I create a select with multiple items, so that they are extending out of the screen, no scroll bar within the select is displayed. Additionally, it doesn't seem that any solutions from the Bits UI docs seem to work. 
![Malfunctioning select](https://github.com/huntabyte/shadcn-svelte/assets/147170976/12b280c8-b1ef-46d0-8ed8-c47720aabf43)

### Reproduction

https://stackblitz.com/edit/github-xtdakw?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 1.76 GB / 15.37 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.13.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @sveltejs/kit: ^1.30.3 => 1.30.3
    bits-ui: ^0.9.9 => 0.9.9
    svelte: ^4.2.8 => 4.2.8
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This is a styling issue, not an issue with the component. Set `h-64` (or whatever) and `overflow-y-auto` to the `Select.Content` and your issue will be resolved.
