### ISSUE TITLE
Dialog closes when selecting input field with mouse

### ISSUE THREAD

**Issue by moreorover** [huntabyte/shadcn-svelte#680]
### Describe the bug

Dialog closes when selecting input field with dragging mouse outside of dialog area.

[dialog_close.webm](https://github.com/huntabyte/shadcn-svelte/assets/17711314/1eac7bc7-8695-4f99-bb41-b1ddec5c8adc)

### Reproduction

https://stackblitz.com/edit/github-zutndn?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^1.27.2 => 1.27.2 
    bits-ui: ^0.11.8 => 0.11.8 
    formsnap: ^0.4.2 => 0.4.2 
    svelte: ^4.2.2 => 4.2.2 
    sveltekit-superforms: ^1.13.1 => 1.13.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This would be an issue you'd need to raise with https://github.com/melt-ui/melt-ui.
