### ISSUE TITLE
Add a Shadcn Navigation Menu, or better, a Sidebar component

### ISSUE THREAD

**Issue by SilvianAchim** [huntabyte/shadcn-svelte#683]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Add a Shadcn Navigation Menu, or better, a Sidebar component that opens the side of the screen on desktop and mobile in the bottom side of the screen, you should see a menu icon, and once opened you'll get 90-80% of the screen with a Drawer containing that sidebar. The behavior should be mostly exactly like the YouTube sidebar of subscriptions, my channel, watch later, etc.

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://ui.shadcn.com/docs/components/navigation-menu
https://www.youtube.com/

**Comment by luxus** [comment]
the youtube link leads to youtube..

**Comment by SilvianAchim** [comment]
> the youtube link leads to youtube..

As it should. That's the mock for the sidemenu

**Comment by huntabyte** [comment]
The Navigation Menu will come soon enough, and the sidebar will come if shad adds one to the original, but not until then. Closing this issue as you can assume everything in shadcn/ui is in the process of being added here.

**Comment by manzt** [comment]
Is resizable implemented?

**Comment by gustavo-bordin** [comment]
Shadcn added a sidebar component, maybe we should reopen this issue

**Comment by SerhiiMandrykin** [comment]
hi, are there any updates on this?

**Comment by AlexVialaBellander** [comment]
why was this closed as not planned?

**Comment by huntabyte** [comment]
Because everything in shadcn/ui is on the roadmap to being added here.
