### ISSUE TITLE
Does ContextMenu.Item expose the "builder" slot property?

### ISSUE THREAD

**Issue by bfovez** [huntabyte/shadcn-svelte#684]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The bits docs https://www.bits-ui.com/docs/components/context-menu#contextmenuitem indicates that ContextMenu.Item  exposes `builder` slot property.

Nevertheless, with shadcn-svelte, I get this error:
```
<ContextMenu.Item asChild let:builder>
...
</ContextMenu.Item>
```
![image](https://github.com/huntabyte/shadcn-svelte/assets/19409008/890a648a-7756-42f1-b2e7-c6b5fb6e8fd8)

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
You'd need to pass that to the slot prop of the `context-menu-item.svelte` component for now. Really we should do this for all the components (I can't wait till snippets are a thing!)

**Comment by bfovez** [comment]
I'll do that. Thank you, and I can't wait either!

Le lun. 22 janv. 2024 à 19:21, Hunter Johnston ***@***.***> a
écrit :

**Comment by huntabyte** [comment]
Close as not planned for the time being, but should more issues start arising like this then we'll consider exposing it on every component.
