### ISSUE TITLE
Error on the command ```npx shadcn-svelte add (component)```

### ISSUE THREAD

**Issue by gooodev** [huntabyte/shadcn-svelte#69]
### Current Behavior

I tried to add component by following command but error occured.
```npx shadcn-svelte add (component)```

Error
```
file:///Users/xxx/.npm/_npx/6326117962061f1d/node_modules/shadcn-svelte/dist/index.js:1001
      (component) => components.includes(component.component)
                                ^

TypeError: components.includes is not a function
    at file:///Users/xxx/.npm/_npx/6326117962061f1d/node_modules/shadcn-svelte/dist/index.js:1001:33
    at Array.filter (<anonymous>)
    at Command.<anonymous> (file:///Users/xxx/.npm/_npx/6326117962061f1d/node_modules/shadcn-svelte/dist/index.js:1000:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I checked the program, and found that this command was broken because of following commit.
https://github.com/huntabyte/shadcn-svelte/commit/ae47aa642c6ae1087409746ac903fbbccc352d90

### Expected Behavior

Add component files by that command.

### Steps To Reproduce

1. Executing `npx shadcn-svelte add accordion`.
2. Error occured.

**Comment by huntabyte** [comment]
Thanks for pointing that out! I'm working on pushing an update for this.

**Comment by huntabyte** [comment]
This should now be resolved. The strange this is that when running the CLI locally, it worked as expected, only when deployed did it not work 🤔 I'll leave this open while I wait to hear back from you @gooodev .
