### ISSUE TITLE
Hover Card in Command in Popover sometimes stays, and sticks to topleft

### ISSUE THREAD

**Issue by Scooter1337** [huntabyte/shadcn-svelte#697]
### Describe the bug

Sometimes while using a hover card in a popover, after clicking outside of the popover, the hover card stays and sticks to top-left.

As seen here:
<video src="https://github.com/huntabyte/shadcn-svelte/assets/11229056/9c69eda8-3ff0-4c30-98c4-20e86b2325fc" />

at: https://www.shadcn-svelte.com/examples/playground

### Reproduction

Visit https://www.shadcn-svelte.com/examples/playground

Click on the textarea after hovering over a model. (doesn't happen 100% of the time)

### System Info

```bash
MacOS Ventura Google Chrome 120.0.6099.234 ARM64
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Thanks for raising this issue! I removed the `bug` flag because those are reserved for bugs with the components themselves, rather than our implementation of them in the docs!

**Comment by Scooter1337** [comment]
I thought it might have something to do with the open={} on the HoverCardRoot, but I came across some weird behavior. If I set it to `open={false}`, the hovercards still show up. How come?

`<HoverCard.Root closeOnOutsideClick={false} open={false} openDelay={0}>`

**Comment by Scooter1337** [comment]
Comparable behaviour occurs when typing in the model selection command search bar, the hovercards will move to top left. Are you sure it's an implementation error? Really seems like a component bug to me. @huntabyte

**Comment by huntabyte** [comment]
Closed by #703
