### ISSUE TITLE
Menubar SubContent not taking the width it needs

### ISSUE THREAD

**Issue by Scooter1337** [huntabyte/shadcn-svelte#700]
### Describe the bug

Shadcn-Svelte music example menu (File -> Library):
<img width="321" alt="Screen 1" src="https://github.com/huntabyte/shadcn-svelte/assets/11229056/299aca0f-5887-4c79-9e02-40da6165d049">

Shadcn-React music example menu (File -> Library):
<img width="371" alt="Screen 2" src="https://github.com/huntabyte/shadcn-svelte/assets/11229056/b3d2dfd0-f7d6-4cc4-b885-0903ef3ca391">

### Reproduction

https://www.shadcn-svelte.com/examples/music
https://ui.shadcn.com/examples/music

### System Info

```bash
MacOS Chrome
```

### Severity

annoyance

**Comment by HubbeDev** [comment]
@Scooter1337 @huntabyte  i think that the ```MenubarPrimitive.SubContent``` should have ```min-w-max``` instead of ```.min-w-\[8rem\]```

The original shadchan-ui has 2 divs wrapping the popover. The inner div has the ```.min-w-\[8rem\]``` while the outer one has ``min-w-max```  while the popover here only has 1 div with the class of the inner div.

**Comment by huntabyte** [comment]
Sounds good, let's just align the DOM structure to the original!

**Comment by HubbeDev** [comment]
@huntabyte you could assign it to me.

**Comment by HubbeDev** [comment]
@huntabyte Looking more into it i the max content style is coming from [radix UI](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/popper/src/Popper.tsx#L240) and not applied directly in shadcn. Do you think we should add it here anyways or is it better to adjust this in bits-ui? Will look in to it more tomorrow. Its late here in sweden.
