### ISSUE TITLE
Theme docs duplicated cards are broken

### ISSUE THREAD

**Issue by Scooter1337** [huntabyte/shadcn-svelte#701]
### Docs issue

Docs theme examples use duplicate cards, with duplicate id's. the duplication of these id's breaks some components' functionality.

### Reproduction

https://www.shadcn-svelte.com/themes (set width to <1280px, click the select area or select security level in the report an issue card)

**Comment by Scooter1337** [comment]
I fixed it in my PR, but it might have to do with some underlying bug.

**Comment by huntabyte** [comment]
I'm not able to reproduce this in an isolated environment:
https://stackblitz.com/edit/github-dw27gc?file=src%2Froutes%2F%2Bpage.svelte

So it may be worth looking into what is causing it, potentially an `id` conflict or similar, rather than the `id` having to be moved to the value, as it has no purpose being there.

**Comment by Scooter1337** [comment]
> I'm not able to reproduce this in an isolated environment: https://stackblitz.com/edit/github-dw27gc?file=src%2Froutes%2F%2Bpage.svelte
> 
> So it may be worth looking into what is causing it, potentially an `id` conflict or similar, rather than the `id` having to be moved to the value, as it has no purpose being there.

The select in your stackblitz doesn't open until I resize the window. So my browser must be the problem here?

**Comment by Scooter1337** [comment]
You're completely correct. My solution is:

Add variant prop to components that are used more than once:
`export let variant: string | undefined | null = undefined;`

Then compute the id's using the variant and a static value:
id/for={"area" + (variant && "_" + variant)}

And set a variant for components that show on a small screen:
`<CardsReportIssue variant={"small"} />`

This solves the issue. Anyone with a cleaner solution?

**Comment by Scooter1337** [comment]
As implemented was already in the dependencies, I implemented it in my test env as follows:

`const id = nanoid(5);`

``for={`area-${id}`}``

Do you approve @huntabyte ?
