### ISSUE TITLE
radix-icons-svelte seems abandoned

### ISSUE THREAD

**Issue by perezd** [huntabyte/shadcn-svelte#707]
### Describe the bug

There are recent sveite/vite deprecation warnings with this package, and the maintainer doesn't seem to be responsive to PRs or issues: https://github.com/Brisklemonade/radix-icons-svelte/issues/1#issuecomment-1913114551

I'd kindly suggest moving to an alternate. This was suggested in the comments: https://lucide.dev/icons/

### Reproduction

The latest version of sveltekit will cause a warning about missing export conditions.

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 149.67 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    pnpm: 8.14.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 121.0.6167.85
    Safari: 17.2.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Lucide is already being used for the `"Default"` style. If that project is no longer being maintained then someone else can fork it and maintain it, that's the beauty of open source 😃
