### ISSUE TITLE
Image Viewer component

### ISSUE THREAD

**Issue by Vaalley** [huntabyte/shadcn-svelte#716]
### Describe the feature

A new component that wraps around an image and adds additional functionality to that image, specifically a zoomed in version of that image with optional description, pagination component combo etc... here's a link to what I mean https://modrinth.com/shader/rethinking-voxels/gallery

Clicking on a picture opens a cool gallery view, the component could be called Image Viewer or gallery

**Comment by huntabyte** [comment]
Hey there,

Here's the note from the form you filled out to create this feature request:

> This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.

So at this time, this feature/component won't be considered here.

**Comment by Vaalley** [comment]
> Hey there,
> 
> Here's the note from the form you filled out to create this feature request:
> 
> > This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.
> 
> So at this time, this feature/component won't be considered here.

No problem! Thanks for the port, it's been amazing using it :D
