### ISSUE TITLE
<Form.Select> doesn't select an initial value

### ISSUE THREAD

**Issue by dkmooers** [huntabyte/shadcn-svelte#717]
### Describe the bug

Maybe I'm missing something here, but when I try to set an initial value on a <Form.Select>, it doesn't actually select the option. Using Formsnap's select directly *does* set the initial value properly.

Stackblitz repo included.

It seems like it might just be a store not reactively updating on initial component load, not sure. When you change a value in the lower select, the upper one updates just fine - it's just the initial render with initial value setting that's not working.

I combed past issues here and didn't see this one. I've been hacking away for the lats couple hours, digging into Formsnap, Bits UI and shadcn-svelte components, and haven't been able to figure it out.

Thanks for all your great work @huntabyte!

### Reproduction

Stackblitz repro: https://stackblitz.com/edit/github-vm72zm-mwtfvx?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 76.89 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 121.0.6167.85
    Safari: 16.6
```

### Severity

annoyance

**Comment by bjornpijnacker** [comment]
I had a similar issue with form reset and the Select not updating. Placing my fix here so in case it helps you.

I noticed that `Select.Root` from bits-ui [requires the `selected` prop](https://www.bits-ui.com/docs/components/select). In `form-select.svelte` that isn't there. I added the following in `form-select.svelte`:

```
let selected: Selected<unknown> | undefined;
$: selected = { value: $value, label: $value as string };
```

and added selected to the `Select.Root`. In my case this solves the problem with reset updating the value but not the UI. Might be the same in this case. In my case the value and label are the same; in the cases where this is not true you won't be able to use this admittedly hacky solution.

**Comment by dkmooers** [comment]
Thanks for the tip! I made a slight modification to your workaround to handle heterogeneous label/value, and now I've got the labels updating with the initial value. It requires that I pass in the `options` object into the <Form.Select> component:

```
export let options: Selected<unknown>[];
$: selected = options?.find((option) => option.value === $value);

...

<Select.Root
	bind:selected
```

And did a similar thing for my hacky MultiSelect component:

```
export let options: Array<Selected<unknown>> = [];
$: selected = options?.filter((option) => ($value as string[])?.includes(option.value as string));

...

<Select.Root
	bind:selected
```

Still a bit hacky though :)

**Comment by huntabyte** [comment]
Did you all try passing a label along with the 'Select.Item'? Does it actually not set or does it not appear to be set because the label is missing?

**Comment by dkmooers** [comment]
@huntabyte do you mean a label like this?

`<Form.SelectItem value={option.value}>{option.label}</Form.SelectItem>`

Or this?

`<Form.SelectItem value={option.value} label={option.label}>{option.label}</Form.SelectItem>`

Or something else?

Neither above option auto-selects the correct initial value. However, when I add the `bind:selected` workaround to `form-select.svelte`, these both display the correct initial value.

 Here's my code for the select input:

```
<Form.Item>
  <Form.Field {config} name="primaryGenre">
    <Form.Label>Primary Genre</Form.Label>
    <Form.Select options={genreOptions}>
      <Form.SelectTrigger class="w-[180px]" placeholder="Primary Genre" />
      <Form.SelectContent>
        {#each genreOptions as option}
          <Form.SelectItem value={option.value}>{option.label}</Form.SelectItem>
        {/each}
      </Form.SelectContent>
    </Form.Select>
    <Form.Description>Select one</Form.Description>
    <Form.Validation />
  </Form.Field>
</Form.Item>
```

**Comment by dexbyte** [comment]
> Did you all try passing a label along with the 'Select.Item'? Does it actually not set or does it not appear to be set because the label is missing?

Yes, it doesn't work still. It seems like it needs the `selected` prop in order to update the default select value. Adding the following code to `form-select.svelte` works:

```
<script lang="ts">
        ...
	export let selected;
</script>
```
```
<Select.Root
	 ...
        selected={selected}
>
        ...
</Select.Root>
```

This also needs to be taken care of when populating the form defaults from the server via superforms.

**Comment by huntabyte** [comment]
> > Did you all try passing a label along with the 'Select.Item'? Does it actually not set or does it not appear to be set because the label is missing?
> 
> 
> 
> Yes, it doesn't work still. It seems like it needs the `selected` prop in order to update the default select value. Adding the following code to `form-select.svelte` works:
> 
> 
> 
> ```
> 
> <script lang="ts">
> 
>         ...
> 
> 	export let selected;
> 
> </script>
> 
> ```
> 
> ```
> 
> <Select.Root
> 
> 	 ...
> 
>         selected={selected}
> 
> >
> 
>         ...
> 
> </Select.Root>
> 
> ```
> 
> 
> 
> This also needs to be taken care of when populating the form defaults from the server via superforms.

You shouldn't need to manually set the selected prop there in 'form-select.svelte' it should be being passed through via $$restProps.

**Comment by huntabyte** [comment]
Here's an example from the examples in the documentation:

https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/routes/examples/forms/account/account-form.svelte

If I set a default value in the schema, the select does in fact populate the default value.

It needs a label and a value. If you want the label to equal the value then you can set it to both. Or you can use a lookup like I'm doing in that example.

You don't need to modify the `form-select.svelte`.

**Comment by dexbyte** [comment]
> You shouldn't need to manually set the selected prop there in 'form-select.svelte' it should be being passed through via $$restProps.

Yes, I am aware, my bad since it wasn't working that time, so I had to add it manually (weird).


> Here's an example from the examples in the documentation:
> 
> https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/routes/examples/forms/account/account-form.svelte
> 
> If I set a default value in the schema, the select does in fact populate the default value.
> 
> It needs a label and a value. If you want the label to equal the value then you can set it to both. Or you can use a lookup like I'm doing in that example.
> 
> You don't need to modify the `form-select.svelte`.

I can confirm this works, thanks! It would be great if this was also highlighted in the docs somewhere, especially how to populate select values using a lookup, it would be really helpful.

**Comment by prima-ram** [comment]
Hi, I think this fits this issue. 

I am having trouble resetting the selected value. 

Am I missing something?

```
<script lang="ts">
	import * as Select from '$lib/components/ui/select/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import X from 'lucide-svelte/icons/x';

	const fruits = [
		{ value: 'apple', label: 'Apple' },
		{ value: 'banana', label: 'Banana' },
	];

	let selected: ItemSelected = undefined;
	type ItemSelected = { value: string; label: string; disabled: boolean } | undefined;

	function resetSelected() {
		selected = undefined;
	}
</script>

<Select.Root portal={null} bind:selected>
	<Select.Trigger class="w-[180px]">
		<Select.Value placeholder="Select a fruit" />
	</Select.Trigger>
	<Select.Content>
		<Select.Group>
			<Select.Label>Fruits</Select.Label>
			{#each fruits as fruit}
				<Select.Item value={fruit.value} label={fruit.label}>{fruit.label}</Select.Item>
			{/each}
		</Select.Group>
	</Select.Content>
	<Select.Input name="favoriteFruit" />
</Select.Root>
<Button variant="outline" size="icon" on:click={resetSelected}>
	<X class="h-4 w-4" />
</Button>
```

After clicking the X the select value becomes undefined but the select component does not update to reflect it

**Comment by dkmooers** [comment]
@prima-ram As per the shadcn-svelte docs, maybe try instead of using bind:selected on Select.Root, use plain selected=..., and add an onSelectedChange handler. See example code here:

https://www.shadcn-svelte.com/docs/components/select#form

This is how I've implemented it in my app
