### ISSUE TITLE
Drawer Direction is not active as per vaul-svelte examples

### ISSUE THREAD

**Issue by hmiiro** [huntabyte/shadcn-svelte#718]
### Describe the bug

The drawer component doesnt have optional Direction Prop to define the direction of the drawer as expressed in the examples below
https://www.vaul-svelte.com/examples

### Reproduction

https://www.vaul-svelte.com/examples

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 64.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.1 - /usr/local/bin/npm
    pnpm: 8.14.3 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.85
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0
    bits-ui: ^0.15.1 => 0.15.1
    cmdk-sv: ^0.0.12 => 0.0.12
    formsnap: ^0.4.1 => 0.4.3
    mode-watcher: ^0.1.2 => 0.1.2
    svelte: ^4.2.7 => 4.2.9
    sveltekit-superforms: ^1.13.4 => 1.13.4
    vaul-svelte: ^0.1.0 => 0.1.0
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
If you notice in your environment output, you're running `0.1.0` of vaul-svelte. The direction prop was added in a later version - https://github.com/huntabyte/vaul-svelte/releases.

`npm i vaul-svelte@latest`
