### ISSUE TITLE
feature: Select

### ISSUE THREAD

**Issue by acidlake** [huntabyte/shadcn-svelte#72]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The original project have Select, i think that a list of options its something basic to build forms.

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
We're currently waiting for Radix Svelte to finish this and then it will be added here as well!

**Comment by huntabyte** [comment]
Closing this issue as we'll be using the temp component issue to track this - #105

**Comment by jakob-fiegerl** [comment]
@huntabyte would you mind if I contribute this component without the Radix Svelte?
