### ISSUE TITLE
Tailwindcss text-sm in drawer with form zoom in issue

### ISSUE THREAD

**Issue by milimyname** [huntabyte/shadcn-svelte#720]
### Describe the bug

As user, I wanna input a value to a form but it gets zoomed in to the input and disturbs the ux. Later, I need to zoom out manually. 

The solution is that I needed to remove the text-sm from the shadcn input etc.  

### Reproduction

Scroll down to the drawer form example. I personally don't like it when it gets zoomed in and not out. 

https://www.shadcn-svelte.com/docs/components/drawer

### System Info

```bash
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 182.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.15.0 - ~/Library/pnpm/pnpm
    bun: 1.0.24 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 16.6
  npmPackages:
    @sveltejs/kit: ^2.5.0 => 2.5.0
    bits-ui: ^0.14.0 => 0.14.0
    formsnap: ^0.4.3 => 0.4.3
    svelte: 4.2.8 => 4.2.8
    sveltekit-superforms: ^1.13.4 => 1.13.4
    vaul-svelte: ^0.0.6 => 0.0.6
```

### Severity

annoyance

**Comment by huntabyte** [comment]
I'm not sure if this is a bug, but a personal preference you have.

I believe updating your `app.html` to the following would address this across your app:
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`

**Comment by milimyname** [comment]
Solved!
