### ISSUE TITLE
CLI not creating components.json (bun)

### ISSUE THREAD

**Issue by diegoulloao** [huntabyte/shadcn-svelte#724]
### Describe the bug

I'm running the command that the docs suggested `bunx --bun shadcn-svelte@latest init` but after complete all the steps I can't see the components.json file.

The file isn't created.

### Reproduction

- Create a sveltekit project (latest version)
- Add tailwind, typescript if not added, etc.
- Run the command, follow the steps
- Check for the `components.json` file

I'm using bun and node v20.

### Logs

```bash
The process exits with 0 code. No errors.
```

### System Info

```bash
Need to install the following packages:
envinfo@7.11.0
Ok to proceed? (y) 
  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 54.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.12.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    svelte: ^4.2.7 => 4.2.9
```

### Severity

annoyance

**Comment by AdrianGonz97** [comment]
@diegoulloao Thanks for raising the issue!

I'm not sure why the `--bun` flag is included in the instructions. We haven't verified that the CLI works in the bun runtime, so it shouldn't be there. 

Instead, try running `bunx shadcn-svelte@latest init`.

**Comment by diegoulloao** [comment]
Additionally when I try to manually create the file, I get the following message when installing components
`bunx --bun shadcn-svelte@latest add input`:

```
ERROR: Invalid configuration found in /Users/diego/Projects/carta-dashboard/components.json.
error: "shadcn-svelte" exited with code 1 (SIGHUP)
```

**Comment by diegoulloao** [comment]
> @diegoulloao Thanks for raising the issue!
> 
> I'm not sure why the `--bun` flag is included in the instructions. We haven't verified that the CLI works in the bun runtime, so it shouldn't be there.
> 
> Instead, try running `bunx shadcn-svelte@latest init`.

I already tried it. It throws an error saying this: 
```
ERROR: Cannot find package 'typescript' imported from /private/tmp/shadcn-svelte@latest--bunx/node_modules/shadcn-svelte/dist/index.js
error: "shadcn-svelte" exited with code 1 (SIGHUP)
```

**Comment by diegoulloao** [comment]
@AdrianGonz97 are you sure about this #725? Not using the `--bun` flag returns an error. Please check my previous comments here.

**Comment by AdrianGonz97** [comment]
@diegoulloao I know for sure that we don't want `--bun`. We enforce using `node` with the shebang `#!/usr/bin/env node` in the CLI script, `--bun` overrides that. 

The other error you're experiencing is a separate issue, which we're looking into now.

**Comment by AdrianGonz97** [comment]
@diegoulloao It looks to be some sort of module resolution issue for peer-dependencies with older versions of bun. 

See if the following works for you:
```bash
bun upgrade
bun pm cache rm
rm -rf /private/tmp/shadcn-svelte@latest--bunx
```

After that, you should be able to run:
```bash
bunx shadcn-svelte@latest init
```

**Comment by smartexpert** [comment]
When I try to run, the program quits after response to the first question is answered and no components.js file is created:

<img width="1241" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/1627433/f3c3c38f-7748-45f9-ba83-757fe5b3aeb0">

**Comment by smartexpert** [comment]
One thing I just want to document is that when I initially ran 
`bunx shadcn-svelte@latest init`
I said no to the first question and then quite (I just want to commit existing code before running it).
That was the first time I was running the command.
Now the questions don't proceed after the first one. The second question shows up but I don't get an opportunity to answer it and then I just get back to shell.

**Comment by diegoulloao** [comment]
> When I try to run, the program quits after response to the first question is answered and no components.js file is created:
> 
> <img alt="image" width="1241" src="https://private-user-images.githubusercontent.com/1627433/305735389-f3c3c38f-7748-45f9-ba83-757fe5b3aeb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzk1OTQsIm5iZiI6MTcwODI3OTI5NCwicGF0aCI6Ii8xNjI3NDMzLzMwNTczNTM4OS1mM2MzYzM4Zi03NzQ4LTQ1ZjktYmE4My03NTdmZTViM2FlYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTgwMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRjYWQwMWFmMThlNzBiMjBlMjc4ZTg4OTk3OTcwYWVkMzY3OTA1YzM0MDJmYzdiNjI0ZTg5YThiMDVkYmU4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rjYQlQwroOZXLSXE_cyXoYnkc5gEkBFX60aP01VIvx0">

Same happened to me. You can just use npx for add a new component, it will respect the bun lock file.

**Comment by diegoulloao** [comment]
> One thing I just want to document is that when I initially ran `bunx shadcn-svelte@latest init` I said no to the first question and then quite (I just want to commit existing code before running it). That was the first time I was running the command. Now the questions don't proceed after the first one. The second question shows up but I don't get an opportunity to answer it and then I just get back to shell.

Have you tried passing the —bun flag?

**Comment by leoalipazaga** [comment]
It throws me the same error :(. Any solution?. I can not add more components and already tried with npx

<img width="960" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/10076586/77710c47-7e3d-4a1a-ac8a-8dfc581b30f3">
