### ISSUE TITLE
Don't require tsconfig.json if typescript is set to false

### ISSUE THREAD

**Issue by kobe-ra** [huntabyte/shadcn-svelte#732]
### Describe the bug

I've been trying to fix this on my own for four hours now, but I'll need someone else to look at it.

After js support was added, I completed the manual installation in my Laravel-Inertia-Svelte project. So I wanted to use for example `npx shadcn-svelte@latest add button`. This didn't work because
```
ERROR: no tsconfig file found for C:\laragon\www\zzz\package.json
PS C:\laragon\www\zzz> npx shadcn-svelte@latest add button
```
I figured js support might not contain npx installations, so I went to grab the button folder from `apps/www/src/lib/registry/new-york/ui` however, only `ts` versions are present there.
Therefore the js support that has been added today must mean it's intended for the npx add command, not hard copying, as there are also json files in `apps/www/static/registry/styles/new-york-js` ready to be copied to our code.

I think we need to make the `add` command aware of `"typescript"` key from `components.json`.

### Reproduction

Start a project that has Svelte and no typescript.
Use `components.json` similar to this:
```
{
    "$schema": "https://shadcn-svelte.com/schema.json",
    "style": "new-york",
    "typescript": false,
    "tailwind": {
      "config": "tailwind.config.js",
      "css": "resources/css/app.pcss",
      "baseColor": "zinc"
    },
    "aliases": {
      "components": "resources/js/Components/Ui",
      "utils": "resources/js/Services/utils"
    }
  }
```
Install shadcn-svelte according to [installation page](https://www.shadcn-svelte.com/docs/installation) and try to run
```
npx shadcn-svelte@latest add button
```

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 18.21 GB / 31.92 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    bits-ui: ^0.16.0 => 0.16.0
    mode-watcher: ^0.2.0 => 0.2.0
    svelte: 4.0.0 => 4.0.0
```
```


### Severity

blocking all usage of shadcn-svelte

**Comment by huntabyte** [comment]
You need to create a 'jsconfig.json' file with your aliases for it to work. Need to add this to the docs! Check the 'app/playground-js' directory in the source code to see!

**Comment by kobe-ra** [comment]
Thank you very much, it works! While you are at it, please, also add info about possiblity of `"typescript": false` in the `components.json` because I had to find that one in `commands/init.ts`
