### ISSUE TITLE
Expose the 'builder' property in the slots whenever the parent exposes the 'asChild' property.

### ISSUE THREAD

**Issue by bfovez** [huntabyte/shadcn-svelte#735]
### Describe the feature

I use this kind of thing:
```
<DropdownMenu.Item href={myHref} on:click={(e) => { ... e.preventDefault() ... }>
   ...
</DropdownMenu.Item>
```
I need fine control over the click event on the anchor. Indeed, the `e.preventDefault()` does not prevent the child anchor to actually trigger a nav action.
For that matter, I need to activate the `asChild` property, which is present, but the `builder` property is not exposed in the slot.

We could modify the code, but we would end up modify the code of a bunch of shadcn-svelte components, which would prevent us to take advantage of the improvements yet to come.

**Comment by walker-tx** [comment]
I can pick this up

**Comment by lixelv** [comment]
I think with snippets this issue might be closed

**Comment by shyakadavis** [comment]
I don't think this is _really_ necessary now that we have snippets. Something like this should work, right?
```svelte
<DropdownMenu.Item>
    {#snippet child({ props })}
        <a {...props} href="/">Home</a>
    {/snippet}
</DropdownMenu.Item 
```

**Comment by bfovez** [comment]
I close the issue now that we have snippets.
