### ISSUE TITLE
Drop Zone File Upload

### ISSUE THREAD

**Issue by vexkiddy** [huntabyte/shadcn-svelte#737]
### Describe the feature

Hiya, would it be possible to have a drag and drop zone component that also has a click handler as back up ?

1. User can drag and drop a file for upload
2. User can click a button to open the file explorer
3. Settings for allowed file types would be a bonus
4. A store for returning the files and their details like file name, size etc

Thanks in advance! and congrats on the amazing work!

**Comment by huntabyte** [comment]
Hey there, as the issue template notes, this project won't have any features beyond what the original https://github.com/shadcn-ui/ui has, so it would be best to start the discussion there first.

**Comment by vexkiddy** [comment]
ah ok! thanks @huntabyte have raised an issue there instead :D
