### ISSUE TITLE
Bits UI slider changes break current Sliders

### ISSUE THREAD

**Issue by vyconm** [huntabyte/shadcn-svelte#743]
### Describe the bug

"Type '{ class: string; }' is not assignable to type 'ThumbProps'.
  Property 'thumb' is missing in type '{ class: string; }' but required in type '{ thumb: { readonly role: "slider"; readonly 'aria-valuemin': number; readonly 'aria-valuemax': number; readonly 'aria-valuenow': number; readonly 'aria-disabled': true | undefined; readonly 'aria-orientation': SliderOrientation; readonly 'data-melt-part': "thumb"; readonly 'data-value': number; readonly style: stri...'.ts(2322)"

The silder component currently causes a TypeError because of this:

"TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)"
    
    
My knowledge of Svelte-Libraries and bits-ui is fairly new and limited, so I hope I reported the correct issue - feel free to correct me or give me instructions on how to help!

### Reproduction

Using a <Slider /> from shadcn-svelte with bits-ui 0.17.0, even with empty props.

### System Info

```bash
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 15.02 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    bits-ui: ^0.17.0 => 0.17.0 
    cmdk-sv: ^0.0.13 => 0.0.13 
    formsnap: ^0.4.3 => 0.4.3 
    mode-watcher: ^0.1.2 => 0.1.2 
    svelte: ^4.2.7 => 4.2.9 
    sveltekit-superforms: ^1.13.4 => 1.13.4
```

### Severity

blocking an upgrade

**Comment by vyconm** [comment]
obviously, rolling back to bits-ui 0.16.0 temporarily fixes this, for anyone finding this thread and needing a quick solution.

npm install bits-ui@0.16.0

**Comment by huntabyte** [comment]
Not a bug. Sliders were updated recently. See Bits UI changelog
