### ISSUE TITLE
Checkbox checked binding doesn't seem to work with undefined

### ISSUE THREAD

**Issue by amit13k** [huntabyte/shadcn-svelte#750]
### Describe the bug

When binding 'checked' to a Checkbox, 'undefined' doesn't reset or change the checked state. With HTML input, 'undefined' leads to unchecking of the input. Undefined leading to unchecked makes it convenient when binding dynamically created checkboxes to properties of an object. The absence of a property would mean 'undefined' is used for the binding and should lead to unchecking, but currently, this doesn't work as expected.

```svelte
<script lang="ts">
import { Checkbox } from '$lib/components/ui/checkbox';

let checked: boolean | undefined = true;
</script>

<div>Checked: {checked === undefined ? "undefined": checked}</div>

<button on:click={() => (checked = undefined)}>set undefined</button>

<p>
	html input type=checkbox
	<input type="checkbox" bind:checked={checked} />
</p>

<p>
	Shadcn Svelte Checkbox
	<Checkbox bind:checked={checked} />
</p>
```

### Reproduction

https://stackblitz.com/edit/github-6ptzxs?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^1.27.2 => 1.27.2 
    bits-ui: ^0.15.1 => 0.15.1 
    cmdk-sv: ^0.0.13 => 0.0.13 
    formsnap: ^0.4.3 => 0.4.3 
    mode-watcher: ^0.1.2 => 0.1.2 
    svelte: ^4.2.9 => 4.2.9 
    sveltekit-superforms: ^1.13.4 => 1.13.4 
    vaul-svelte: ^0.1.0 => 0.1.0
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
This isn't a bug and is how it was designed. There are 3 states, `checked` (true) `unchecked` (false) and `"indeterminate"`. Use one of those and be more explicit rather than using `undefined` and you'll be golden.

**Comment by amit13k** [comment]
@huntabyte Thanks a lot for the response. I later realized that there were better ways to solve the issue, and using the 'indeterminate' state was better
