### ISSUE TITLE
Init CLI fails when refusing typescript

### ISSUE THREAD

**Issue by ww-wolt** [huntabyte/shadcn-svelte#752]
### Describe the bug

When following the exact steps from the documentation to set up the project with plain javascript the CLI aborts with the error message that no tsconfig file was found and components.json is not written. 

However a tsconfig.json exists inside the hidden folder .svelte-kit

Console output
<img width="855" alt="Bildschirmfoto 2024-02-07 um 17 14 34" src="https://github.com/huntabyte/shadcn-svelte/assets/55745851/ea4bb9f2-0d81-4c0f-a3b4-6aa79f3efbf8">

package.json
<img width="381" alt="Bildschirmfoto 2024-02-07 um 17 20 18" src="https://github.com/huntabyte/shadcn-svelte/assets/55745851/6f35f5fb-b90d-4fd9-a82d-6181793de2c6">

Node Version: v20.9.0
npm Version: 10.1.0

### Reproduction

Follow the exact steps from the documentation and choose no typescript in the sveltekit setup as well as the shadcn-svelte setup. 

### System Info

```bash
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 90.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.139
    Safari: 16.6
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0
    svelte: ^4.2.7 => 4.2.10
```

### Severity

blocking all usage of shadcn-svelte

**Comment by AdrianGonz97** [comment]
We specify this in the [installation guide](https://www.shadcn-svelte.com/docs/installation#typescript). However, I can see how it's not immediately clear that adding a `jsconfig.json` is a necessary step if you're not using TS.

The documentation around this can be improved, as well as the CLI error message could also be improved. The CLI could link back to this section of the docs if a `tsconfig.json` or `jsconfig.json` is missing.

**Comment by LucasRTonin** [comment]
hello, i'm pretty new to webdev, i'm also having problems with the installation because I'm not using TS, I'm cloned a repo so i'm not starting from the beginning,

I tried to add the files as the installation says (when not using TS) but now i get a different error @AdrianGonz97 
![image](https://github.com/huntabyte/shadcn-svelte/assets/30559272/c56b00ba-3925-4b1b-8578-5b0ac7c056ab)

If someone could tell me what i'm doing wrong, that would be of great help
