### ISSUE TITLE
Remove redundant `clsx`

### ISSUE THREAD

**Issue by phenomen** [huntabyte/shadcn-svelte#762]
### Describe the feature

Since `tailwind-merge` 2.0 it has every feature of `clsx` so there is no need to chain them in the `cn` util function. `cn` can be optimized to use just one library:
```js
import { type ClassNameValue, twMerge } from "tailwind-merge";

export function cn(...inputs: ClassNameValue[]) {
  return twMerge(inputs);
}
```

**Comment by armchair-traveller** [comment]
Haha at this point cn is just an alias for twMerge

**Comment by huntabyte** [comment]
Are we sure about this? The last time someone brought this up and I tried replacing it, it broke when used with objects.

**Comment by armchair-traveller** [comment]
The types don't match so it's likely that it's still using logic like twJoin internally, which means if people need to use objects this is not a direct replacement. Thanks for mentioning that

I'm personally going to alias it as I was already using twJoin throughout my codebase(s). I'd prefer having one less dependency to keep updated as I don't use it, but I'm sure some people need object support in Svelte as opposed to React.

**Comment by huntabyte** [comment]
Closing as not planned for now until there is complete parity or shad switches the `cn` helper to use this instead.

Thanks all!
