### ISSUE TITLE
Can we add Mail page example from shadcn examples?

### ISSUE THREAD

**Issue by eriknyk** [huntabyte/shadcn-svelte#766]
### Describe the feature

Can we add Chat page example from shadcn examples, please?

https://ui.shadcn.com/examples/mail

<img width="1406" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/205721/277213ae-e40f-4a5f-b101-296a6014c5f9">

Regards,

**Comment by shyakadavis** [comment]
Hi;

Related, https://github.com/huntabyte/shadcn-svelte/issues/560

> It is assumed that any feature in shadcn/ui is already on the roadmap/being worked on for this project, therefore it doesn't need a feature request issue

**Comment by eriknyk** [comment]
Closed in favor of #560
