### ISSUE TITLE
Describing the installation instructions

### ISSUE THREAD

**Issue by james-kaguru** [huntabyte/shadcn-svelte#768]
### Change Type

Addition

### Proposed Changes

The installation step seems pretty straight forward but I cant seem to find info about the items that Im choosing. I think it needs some more details like for example the difference between vite and sveltekit, default vs new york, slate vs the others..to a new user It feels like I dont know what Im selecting. Additionally the selection of the global css file uses .pcss . Honestly its my first time using .pcss and Im not quite sure how to use it...im sure there are other fellas out there who might encounter this so documenting about this would easen the onboarding

**Comment by huntabyte** [comment]
This isn't something we're going to add at this time. If you aren't sure what something is, you should look into that technology. We don't have the cycles for this atm, however if someone wants to submit a PR, I'll definitely consider it!
