### ISSUE TITLE
Issue with Context Menu Closing Immediately on Right-Click in macOS 14.3.1+

### ISSUE THREAD

**Issue by jamesfebin** [huntabyte/shadcn-svelte#775]
### Describe the bug

On macOS version 14.3.1 and later, the context menu does not remain open upon right-clicking. This problem is likely due to the context menu appearing far from the cursor's location rather than directly adjacent to it. Consequently, because the cursor is not detected within the boundaries of the context menu upon its opening, the menu automatically closes. 

### Reproduction

Right-click on a context menu trigger area from macOS version 14.3.1 or above on Safari.

### System Info

```bash
NA
```

### Severity

annoyance

**Comment by huntabyte** [comment]
What browser?

**Comment by jamesfebin** [comment]
Safari

**Comment by shyakadavis** [comment]
Hi;

Confirming for `macOS 13.6.3` and `Safari Version 17.2.1`


https://github.com/huntabyte/shadcn-svelte/assets/87414827/3d705475-4c2f-4b0f-900b-5ac69e4f34ac

**Comment by huntabyte** [comment]
Related: https://github.com/melt-ui/melt-ui/issues/992

**Comment by huntabyte** [comment]
Will be closed once https://github.com/melt-ui/melt-ui/pull/977 is merged and Bits UI is updated to the latest version of Melt 👍

**Comment by huntabyte** [comment]
This should now be closed when you update to bits-ui@0.18.2 🎉
