### ISSUE TITLE
DialogContent forces you to have a DialogPrimitive.Close

### ISSUE THREAD

**Issue by geerew** [huntabyte/shadcn-svelte#78]
### Current Behavior

This is not a bug persay but more a discussion around the topic of whether `DialogContent` should include the `DialogPrimitive.Close`?

I would rather this be moved to a DialogClose.svelte component and then you can pass the DialogClose along with the content. So something like

```
...
<DialogContent>
    <DialogClose />
    <div>Test</div>
    <DialogFooter>
        <Button type="submit">Save changes</Button>
    </DialogFooter>
</DialogContent>
...
```

In addition the DialogClose should allow you to override the content, if, for example, you want to use a different icon

So the DialogClose.svelte could be something like 

```
<script lang="ts">
	import { cn } from '$lib/utils';
	import { X } from 'lucide-svelte';
	import { Dialog as DialogPrimitive } from 'radix-svelte';

	let className: string | undefined | null = undefined;
	export { className as class };
</script>

<DialogPrimitive.Close
	class={cn(
		'absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground',
		className
	)}
	{...$$restProps}
>
	<slot>
		<X className="h-4 w-4" />
	</slot>
	<span class="sr-only">Close</span>
</DialogPrimitive.Close>
```

### Expected Behavior

The freedom to decide if I want to have a close icon in my dialog progmatically on a dialog-per-dialog basis as well as the ability to decide on the close icon to use

### Steps To Reproduce

See `DialogContent.svelte`

**Comment by huntabyte** [comment]
If I remember correctly, the reason it's "forced" into that position is that it has to be used within the `<DialogContent>`, so to avoid confusion it's included by default. I'll look into this a bit further and see if it's something worth changing, but in the meantime, the nice thing is that you can always remove it/hide it from your components via props!

**Comment by huntabyte** [comment]
Closing this issue as the current implementation aligns with [shadcn/ui](https://shadcn-ui.com/docs/components/dialog).

You're more than welcome to move the component out within your local component if you'd like!
