### ISSUE TITLE
Change the Radix icon library used in the New York style?

### ISSUE THREAD

**Issue by gregmsanderson** [huntabyte/shadcn-svelte#783]
### Describe the feature

I notice that in keeping with the original Shadcn UI you use the Radix icons for the New York style. Nice! That's using `radix-icons-svelte`.

However that package results in this warning for me:

> WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte radix-icons-svelte@1.2.1

I wonder if it would be an idea to switch to a more recently updated equivalent Radix icon library. Perhaps this one `svelte-radix` as that does mention Svelte (which I assume would solve the warning):

https://github.com/shinokada/svelte-radix/blob/main/package.json#L72

**Comment by huntabyte** [comment]
One step ahead of ya @gregmsanderson  https://github.com/huntabyte/shadcn-svelte/pull/591

**Comment by gregmsanderson** [comment]
@huntabyte Ha 🥇  Awesome.

I'll go ahead and close this one then :)
