### ISSUE TITLE
[Docs]: Improve the metric data-vis example under /themes

### ISSUE THREAD

**Issue by shyakadavis** [huntabyte/shadcn-svelte#789]
### Change Type

Addition

### Proposed Changes

Hi;

Was wondering if you're open to accepting a close-but-not-exact replica of the `Metrics` data-vis example used from the original under the `/themes` route.

I tried doing an experiment, and before submitting a P.R, was wondering if a compromise is acceptable.

Currently, a blocking-ish issue is this, https://github.com/f5/unovis/issues/338, other than that, I'm open to requests/suggestions in terms of aligning with the original.

Here's what I have so far:

https://github.com/huntabyte/shadcn-svelte/assets/87414827/55bade9b-7d05-4f69-8ae7-9ea43975bcb3

Cheers.

**Comment by huntabyte** [comment]
I'd totally be open to this! Are you able to style it using the `style` prop with those variables overridden? I think I'm doing something similar for the colors!

**Comment by shyakadavis** [comment]
Awesome.

> Are you able to style it using the style prop with those variables overridden?

Sadly, no. Ran into an issue there, and opened another issue, https://github.com/f5/unovis/issues/337. Hoping to get a response soon. 🙂 

For now, as you'll see, I'm settling for styling through the `style` tags, but of course `[vite-plugin-svelte]` complains:

```
No scopable elements found in template. If you're using global styles in the style tag, you should move it into an external stylesheet file and import it in JS. See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles.
```

Maybe you'll provide a more practical way to handle the customizations.

Give me a few, and I'll submit the P.R. 🙂
