### ISSUE TITLE
The Dialog example result in a button within a button

### ISSUE THREAD

**Issue by geerew** [huntabyte/shadcn-svelte#79]
### Current Behavior

The example in the docs has this 

```
<DialogTrigger>
    <Button variant="outline">Edit Profile</Button>
</DialogTrigger>
...
```

This results in a `button` element with a `button` element, as dialogTrigger creates a `button`. This results in a confusing tabbing behavious.

The actual code should be something like 

```
<DialogTrigger class={buttonVariants({ variant: 'default' })}>
    <Icons.plus class="mr-2 h-4 w-4" />
    Click me
</DialogTrigger>
```

The docs should be updated to reflec this

### Expected Behavior

Only one button element should exist to launch the dialog

### Steps To Reproduce

1. Create a dialog using the example in the docs
2. View the code to see a `button` within a `button`
3. Attempt to tab over elements

**Comment by huntabyte** [comment]
Thanks for pointing this out! I'm traveling for a work trip atm, but ill take a look as soon as I'm back in town tomorrow!
