### ISSUE TITLE
Form values reset on invalidate and invalidateAll

### ISSUE THREAD

**Issue by orenaksakal** [huntabyte/shadcn-svelte#790]
### Describe the bug

Hello 👋

Just figured that form values e.g. textarea value resets when `invalidate` or `invalidateAll` is called making polling difficult on pages with forms

### Reproduction

- setup the example form from docs
- enter text to input field
- call invalidate or invalidate all from sveltekit
- observe form value resets

### System Info

```bash
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 106.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.14.3 - ~/Library/pnpm/pnpm
    bun: 1.0.15 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.114
    Chrome: 121.0.6167.184
    Safari: 17.3.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    bits-ui: ^0.18.1 => 0.18.1 
    cmdk-sv: ^0.0.13 => 0.0.13 
    formsnap: ^0.5.0 => 0.5.0 
    mode-watcher: ^0.2.1 => 0.2.1 
    svelte: ^4.2.11 => 4.2.11 
    sveltekit-superforms: ^2.5.0 => 2.5.0 
    vaul-svelte: ^0.2.3 => 0.2.3
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This is the expected behavior; you're invalidating the `form` returned from the load function, which will reset it. This issue isn't related to formsnap but rather the expected behavior of superforms.
