### ISSUE TITLE
The Calendar component has a height jump during month paging

### ISSUE THREAD

**Issue by nickludlam** [huntabyte/shadcn-svelte#791]
### Describe the bug

As shown in the video, the Date Picker component jumps height as you page between months. This does not happen with Bits UI Date Picker component, so there's some kind of porting issue at work.

https://github.com/huntabyte/shadcn-svelte/assets/7568/869dfb28-8e13-484a-ab0a-81663aafd0c7

### Reproduction

See video. Happens on the Calendar component example page https://www.shadcn-svelte.com/docs/components/calendar

### System Info

```bash
I'm using Safari Version 17.3.1 (19617.2.4.11.12) on MacOS 14.3.1
```

### Severity

annoyance

**Comment by pywolf1503** [comment]
I believe this is caused because new lines correspondant to the month days gets added, February got 29 december got 31 so new line gets added and the height jumps
