### ISSUE TITLE
Programmatically close the Dialog

### ISSUE THREAD

**Issue by omar2205** [huntabyte/shadcn-svelte#80]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I'm using a Dialog with a simple form. I had to change the `AlertDialogAction` with a simple button to allow the form to be submitted. 

How to close the dialog after a successful submission?

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
For this specific ability, you'd want to reference the [Radix Svelte Docs](https://www.radix-svelte.com/docs/alertdialog). From what I can tell you're trying to do, you'd need to pass/bind `open` to the `<AlertDialog>` component.

**Comment by omar2205** [comment]
OK, thanks. When you're free, can you add a note about that?

**Comment by omar2205** [comment]
@huntabyte sorry to ping you, but how to get events (in dialogs)? Like clicking cancel or ok?
I can't do `on:click`
