### ISSUE TITLE
docs: correct update command

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#804]
### Change Type

Correction

### Proposed Changes

The update command as indicated in the docs does not work, might still be the old from the react version (the docs don't seem to be on github, else I'd have made a PR).

`npx shadcn-svelte@latest update componentName` should be correct.

**Comment by shyakadavis** [comment]
Hi;

Do you mean this section right here: https://www.shadcn-svelte.com/docs/cli#update? May you confirm this before I submit a P.R?!

> the docs don't seem to be on github

Pretty sure they are. Check here: https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/content

**Comment by MentalGear** [comment]
I added a PR for it here:
https://github.com/huntabyte/shadcn-svelte/pull/824
