### ISSUE TITLE
Form.Select missing

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#805]
### Describe the bug

On the latest components version (didn't change anything), yet the mentioned <Form.Select> from the Form docs has no exported member in the current version's Form.

### Reproduction

install fresh version
try to use `<Form.Select>`

<img width="403" alt="Screenshot 2024-02-23 at 21 37 41" src="https://github.com/huntabyte/shadcn-svelte/assets/2837147/edce88a3-d1d8-4066-bb44-1d0342de2b3a">

### System Info

```bash
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 356.83 MB / 40.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 121.0.6167.184
    Firefox: 123.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/kit: ^2.5.0 => 2.5.0 
    bits-ui: ^0.18.1 => 0.18.1 
    formsnap: ^0.5.0 => 0.5.0 
    mode-watcher: ^0.2.1 => 0.2.1 
    svelte: 5.0.0-next.66 => 5.0.0-next.66 
    sveltekit-superforms: ^2.5.0 => 2.5.0 
    vaul-svelte: ^0.2.3 => 0.2.3
```

### Severity

blocking an upgrade

**Comment by shyakadavis** [comment]
Hi;

Ah, I see; guessing it was purposely removed in order to have more _flexible_ control over the component?.

Guessing it's also related to this: https://github.com/huntabyte/shadcn-svelte/issues/801

If it's a simple case of removing/updating the references, I could submit a P.R. Just want @huntabyte to confirm. 🙂

**Comment by huntabyte** [comment]
Form.Select does not exist anymore. The docs just need to be updated to use a regular select!

**Comment by shyakadavis** [comment]
Actually, just noticed several instances in the docs referencing the <Form.<something>> when that _something_ has been removed in the latest Formsnap version.

If you're busy atm, @huntabyte please let me know and I'll update them. 🙂
