### ISSUE TITLE
Layout shift when using Dialog buttons

### ISSUE THREAD

**Issue by omar2205** [huntabyte/shadcn-svelte#81]
### Current Behavior

I have this layout shift when using the `AlertDialog` component:

https://github.com/huntabyte/shadcn-svelte/assets/1373867/ea6a2c68-f632-4a00-8d92-969a1b1f7d22

### Expected Behavior

No layout shift

### Steps To Reproduce

1. Clone the repo and install deps
2. Reload the page the button shifts after reload

### Link to Reproduction / Stackblitz

https://github.com/omar2205/l-s-rep

**Comment by huntabyte** [comment]
I see this as well and it seems like it happens anytime the scrollbar disappears. If anyone wants to submit a PR to fix, let me know and I'll assign it to you.

**Comment by huntabyte** [comment]
After investigating this a bit further, it was due to have a `<Button>` inside the `<AlertDialogTrigger>` component. The trigger already renders a button, and this was my bad for having a bad example in the docs.
