### ISSUE TITLE
Remove outdated files on CLI update

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/shadcn-svelte#827]
### Describe the feature

With #776, some Form component files have been deleted in favor of others.
Using the CLI update adds the new files and updates the modified ones, but does _not_ remove the no-longer-existing ones.

As I’m implementing this feature in my JetBrains plugin, can I also push the change to the CLI update command?

**Comment by huntabyte** [comment]
Hmm, I'm not sure we should go deleting all files in a folder that we don't own (and we aren't going to keep a running record of all past files). I'll defer to @AdrianGonz97 to get his thoughts on this!

**Comment by AdrianGonz97** [comment]
Yeah, I don't think deleting would be the best idea, especially when we're not keeping track of the history of files that we've created/own. 

Perhaps printing a list of files that are _potentially_ no longer needed would suffice instead?

**Comment by WarningImHack3r** [comment]
> we aren't going to keep a running record of all past files


No need for that! Just removing all files that are not currently listed remotely

**Comment by WarningImHack3r** [comment]
> Perhaps printing a list of files that are _potentially_ no longer needed would suffice instead?

IMO that's not _that_ an issue, but I get you fear. What about deleting them only if a git repository is initiated, else list the files? We could even check if the file starts with the name of the component as a triple check safety net.

But I'm pretty sure we _should_ do something about it instead of leaving useless files in users' projects

**Comment by huntabyte** [comment]
> We could even check if the file starts with the name of the component (or == `index.ts`) as a triple check safety net.

Still don't like this idea, if I create a custom `form-input.svelte`, I don't expect it to be obliterated by updating the form. At the moment, listing the files that exist that are "no longer necessary" is the only approach I feel comfortable with.

You also have to remember the whole idea behind this project. You own the code. You are responsible for keeping the components up to date and cleaning up any leftovers during an update.

**Comment by WarningImHack3r** [comment]
Get it. You're right. Will do that!

**Comment by ollema** [comment]
this has been brought up in the past:
https://github.com/huntabyte/shadcn-svelte/issues/530

and I also ran into this today.

@huntabyte 
I understand:
> Still don't like this idea, if I create a custom form-input.svelte, I don't expect it to be obliterated by updating the form.

but at the same time, say that I customize `form-legend.svelte`, then those changes are in fact obliterated by updating the form.

I personally believe that the warning that you should commit your changes, whether or not they are custom changes to existing files added by shadcn-svelte or custom changes to new files added by the user.

more specifically, the file names used by shadcn-svelte are not reserved in any way or form, so if I create a custom `form-input.svelte` and then I update shadcn-svelte those changes might as well get obliterated if shadcn-svelte decides to add a new `form-input.svelte` component in the `form` directory, right?

therefore, I don't feel like this argument is super solid 🤔 

at the very least, could this be a CLI option? so user who wants to remove unused files can do so with for example `pnpx shadcn-svelte@latest update --all --clean-up` or whatever that option could be called
