### ISSUE TITLE
sheet make it more universal out of the box

### ISSUE THREAD

**Issue by skelawsky** [huntabyte/shadcn-svelte#842]
### Describe the feature

This component would be much better out of the box if it had 'overflow-auto' set. Additionally, `text-center` on smaller screens doesn't look very good and it spoils the look of the forms by making them look worse.

Before:
![image](https://github.com/huntabyte/shadcn-svelte/assets/75502784/ab8ab5e9-75fe-4b0a-922f-01c0a9a64e3c)
After:
![image](https://github.com/huntabyte/shadcn-svelte/assets/75502784/b5718d13-9d3e-4022-bda7-6b37f9c26528)

**Comment by skelawsky** [comment]
#843

**Comment by huntabyte** [comment]
We aren't going to deviate from the defaults set by the original.
