### ISSUE TITLE
Add "shift + mouse scroll" action for carousel

### ISSUE THREAD

**Issue by wineTGH** [huntabyte/shadcn-svelte#845]
### Describe the feature

I don't know if I should ask for it here or in the original project, but it would be nice if the user could scroll through the contents of the carousel using the scroll wheel (as is already implemented in all browsers for horizontal overflow).

**Comment by shyakadavis** [comment]
Hi;

Haven't tested it with a mouse, only the trackpad, but there is a plugin you need to add in order to achieve this: https://www.embla-carousel.com/plugins/wheel-gestures/

Does that meet your needs?

**Comment by huntabyte** [comment]
Closing as this is outside the scope of this project and a plugin for embla-carousel can be used if this feature is required.
