### ISSUE TITLE
form-element-field unexpected ","

### ISSUE THREAD

**Issue by anixan** [huntabyte/shadcn-svelte#849]
### Describe the bug

I have recently upgraded my form elements to the new approach just released. I re-run through the documentation and get the following error when trying to load any page with a form:

`[plugin:vite-plugin-svelte] Error while preprocessing /home/MYAPP/src/lib/components/ui/form/form-element-field.svelte - Transform failed with 1 error:
/home/MYAPP/src/lib/components/ui/form/form-element-field.svelte:1:0: ERROR: Unexpected ","
/home/MYAPP/src/lib/components/ui/form/form-element-field.svelte
Unexpected ","
 1  |  , U extends FormPathLeaves<T>">
    |  ^
 2  |  	import type { HTMLAttributes } from "svelte/elements";
 3  |  	import * as FormPrimitive from "formsnap";`

This is topping me using form at all and I have checked the offending file are there are no errors in the file on that line so I have no idea what is causing this 🤔

Any help greatly appreciated!

### Reproduction

This is my Schema file:

```
import { z } from "zod";

export const projectSchema = z.object({
  username: z.string().min(2).max(50),
});

export type ProjectSchema = typeof projectSchema;`


This my +page.server.ts:

`import type { PageServerLoad, Actions } from "./$types";
import { fail } from "@sveltejs/kit";
import { superValidate } from "sveltekit-superforms";
import { projectSchema } from "$lib/components/forms/schema";
import { zod } from "sveltekit-superforms/adapters";


export const load: PageServerLoad = async () => {
    return {
      form: await superValidate(zod(projectSchema)),
    };
  };

  export const actions: Actions = {
    default: async (event) => {
      const form = await superValidate(event, zod(projectSchema));
      if (!form.valid) {
        return fail(400, {
          form,
        });
      }
      return {
        form,
      };
    },
  };
```

This is my form component:

```
<script lang="ts">
    import * as Form from "$lib/components/ui/form";
    import { Input } from "$lib/components/ui/input";
    import { projectSchema, type ProjectSchema } from "./schema";
    import {
      type SuperValidated,
      type Infer,
      superForm,
    } from "sveltekit-superforms";
    import { zodClient } from "sveltekit-superforms/adapters";
   
    export let data: SuperValidated<Infer<ProjectSchema>>;
   
    const form = superForm(data, {
      validators: zodClient(projectSchema),
    });
   
    const { form: formData, enhance } = form;
  </script>
   
  <form method="POST" use:enhance>
    <Form.Field {form} name="username">
      <Form.Control let:attrs>
        <Form.Label>Username</Form.Label>
        <Input {...attrs} bind:value={$formData.username} />
      </Form.Control>
      <Form.Description>This is your public display name.</Form.Description>
      <Form.FieldErrors />
    </Form.Field>
    <Form.Button>Submit</Form.Button>
  </form>
```

This is my page to display the form:

```
<script lang="ts">
	import ProjectCreate from '$lib/components/forms/projectCreate.svelte';
	import type { PageData } from "./$types";
	export let data: PageData;
</script>

		<ProjectCreate data={data.form} />
```
		

### System Info

```bash
Using: 
"svelte": "^4.0.5"
"sveltekit-superforms": "^2.6.2"
"formsnap": "^0.5.1"
"zod": "^3.22.4"
```

### Severity

blocking an upgrade

**Comment by anixan** [comment]
Hey All,

Ok so I have tried to reproduce this error but when following a fresh clean install like int the link provided I don't get this error:

[Reproduction Failure](https://stackblitz.com/edit/github-ezz4sz?file=package.json)

I then started to think this was an issue with using Generics in the <script> tag somehow and this might be vite or svelte struggling so I completely stripped back my package.json and implemented all the packages like in my failed reproduction as that is actually working, and I still get this error 😣

I have also tried removing the node_modules folder and re-installing several times with no joy 😣😣😣

Can someone please advise any other steps I can try to get this working as I really want to upgrade but I can't start a whole new project as its already quite verbose 🙏🙏🙏🙏🙏

Thanks

**Comment by huntabyte** [comment]
If you're able to create a minimal reproduction of the issue we can investigate further. If not, you need to check the versions of your packages and ensure they align. It seems like this is a Svelte/Vite version issue, I know in your initial example you listed an older version of Svelte 4, so look at each of your dependencies until the problem is reintroduced and then you'll know where the issue is.

**Comment by anixan** [comment]
Thanks @huntabyte I really appreciate any help/advice you can give as i have no idea what could be causing this. As per your suggestion above I have already tried aligning the Svelte/Vite versions to the same that is in the emo app attached above as this works with those versions.

Here are the packages from the demo app above:

``` json
"devDependencies": {
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.27.2",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"autoprefixer": "^10.4.16",
		"eslint": "^8.52.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte": "^2.34.0",
		"paneforge": "latest",
		"postcss": "^8.4.31",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.10.1",
		"svelte": "^4.2.9",
		"svelte-check": "^3.6.3",
		"tailwindcss": "^3.4.1",
		"tslib": "^2.6.2",
		"typescript": "^5.3.3",
		"vite": "^4.5.0",
		"vitest": "^0.32.2"
	},
	"type": "module",
	"dependencies": {
		"@internationalized/date": "^3.5.1",
		"bits-ui": "latest",
		"clsx": "^2.1.0",
		"cmdk-sv": "latest",
		"embla-carousel-svelte": "8.0.0-rc20",
		"formsnap": "latest",
		"lucide-svelte": "^0.303.0",
		"mode-watcher": "latest",
		"svelte-sonner": "latest",
		"sveltekit-superforms": "latest",
		"tailwind-merge": "^2.2.1",
		"tailwind-variants": "^0.1.20",
		"tailwindcss-animate": "^1.0.7",
		"vaul-svelte": "latest",
		"zod": "^3.22.4"
	}
```

And here are the ones in my app, as you can see they are exactly the same, I have no idea what else to try.

``` json
"devDependencies": {
		"@edge-runtime/cookies": "^4.0.1",
		"@egoist/tailwindcss-icons": "^1.1.0",
		"@iconify/json": "^2.2.117",
		"@iconify/svelte": "^3.1.4",
		"@playwright/test": "^1.28.1",
		"@sused/shared-types": "workspace:^",
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/adapter-vercel": "^4.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"@tailwindcss/forms": "^0.5.6",
		"@types/jsonwebtoken": "^9",
		"@vercel/edge": "^1.1.0",
		"@vercel/node": "^3.0.7",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"amazon-cognito-identity-js": "^6.3.6",
		"flowbite": "^1.8.1",
		"flowbite-svelte": "^0.44.15",
		"jose": "^4.15.4",
		"svelte-preprocess": "^5.0.4",
		"svelte-sequential-preprocessor": "^2.0.1",
		"autoprefixer": "^10.4.16",
		"eslint": "^8.52.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte": "^2.34.0",
		"postcss": "^8.4.31",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.10.1",
		"svelte": "^4.2.9",
		"svelte-check": "^3.6.3",
		"tailwindcss": "^3.4.1",
		"tslib": "^2.6.2",
		"typescript": "^5.3.3",
		"vite": "^4.5.0",
		"vitest": "^0.32.2"
	},
	"type": "module",
	"dependencies": {
		"@types/chart.js": "^2.9.41",
		"@internationalized/date": "^3.5.1",
		"chart.js": "^4.4.1",
		"paneforge": "latest",
		"svelte-media-queries": "^1.6.1",
		"taos": "^1.0.5",
		"bits-ui": "latest",
		"clsx": "^2.1.0",
		"cmdk-sv": "latest",
		"embla-carousel-svelte": "8.0.0-rc20",
		"formsnap": "latest",
		"lucide-svelte": "^0.303.0",
		"mode-watcher": "latest",
		"svelte-sonner": "latest",
		"sveltekit-superforms": "latest",
		"tailwind-merge": "^2.2.1",
		"tailwind-variants": "^0.1.20",
		"tailwindcss-animate": "^1.0.7",
		"vaul-svelte": "latest",
		"zod": "^3.22.4"
	}
```

**Comment by huntabyte** [comment]
If you notice you're running SvelteKit v2 in your app, which needs Vite 5. I'll update the reproduction template to SvelteKit 2 so you can compare it again. You're definitely going to get issues trying to run those vite/svelte packages with SvelteKit 2.

**Comment by anixan** [comment]
Thanks for all your help @huntabyte I know this was more of a unique problem for me rather than a problem with this project 😉

So I managed to get all my dependencies setup correctly and this working, here they are for anyone else who may face this issue, I also performed a full purge and cleanup in NPM in case there where any issues there:

"devDependencies": {
		"@edge-runtime/cookies": "^4.1.0",
		"@egoist/tailwindcss-icons": "^1.7.4",
		"@iconify/json": "^2.2.189",
		"@iconify/svelte": "^3.1.6",
		"@playwright/test": "^1.42.1",
		"@sveltejs/adapter-auto": "^3.1.1",
		"@sveltejs/adapter-vercel": "^5.1.0",
		**"@sveltejs/kit": "^2.5.2",
		"@sveltejs/vite-plugin-svelte": "^3.0.2",**
		"@tailwindcss/forms": "^0.5.7",
		"@types/jsonwebtoken": "^9.0.6",
		"@typescript-eslint/eslint-plugin": "^5.62.0",
		"@typescript-eslint/parser": "^5.62.0",
		"@vercel/edge": "^1.1.1",
		"@vercel/node": "^3.0.20",
		"autoprefixer": "^10.4.18",
		"eslint": "^8.57.0",
		"eslint-config-prettier": "^8.10.0",
		"eslint-plugin-svelte": "^2.35.1",
		"flowbite": "^1.8.1",
		"flowbite-svelte": "^0.44.24",
		"jose": "^4.15.4",
		"postcss": "^8.4.35",
		"postcss-load-config": "^4.0.2",
		"prettier": "^3.2.5",
		"prettier-plugin-svelte": "^3.2.2",
		**"svelte": "^4.2.12",**
		"svelte-check": "^3.6.6",
		**"svelte-preprocess": "^5.1.3",
		"svelte-sequential-preprocessor": "^2.0.1",**
		"tailwindcss": "^3.4.1",
		"tslib": "^2.6.2",
		"typescript": "^5.3.3",
		**"vite": "^5.1.5",
		"vitest": "^1.3.1"**
	},
	"type": "module",
	"dependencies": {
		"@internationalized/date": "^3.5.2",
		"@types/chart.js": "^2.9.41",
		**"bits-ui": "latest",**
		"chart.js": "^4.4.2",
		"clsx": "^2.1.0",
		"cmdk-sv": "latest",
		"embla-carousel-svelte": "8.0.0-rc20",
		**"formsnap": "latest",**
		**"lucide-svelte": "^0.303.0",**
		"mode-watcher": "latest",
		"paneforge": "latest",
		"svelte-media-queries": "^1.6.2",
		"svelte-sonner": "latest",
		**"sveltekit-superforms": "latest",**
		"tailwind-merge": "^2.2.1",
		"tailwind-variants": "^0.1.20",
		"tailwindcss-animate": "^1.0.7",
		"taos": "^1.0.5",
		"vaul-svelte": "latest",
		**"zod": "^3.22.4"**
	}

**Comment by cmr-a** [comment]
I encountered a very similar problem. I updated to the latest version the form component, then `form-field.svelte` caused a CompileError.

I found this line was the cause (specifically the `generics` part):
```
<script lang="ts" generics="T extends Record<string, unknown>, U extends FormPath<T>">
```

Here is the trace:
```
CompileError [ParseError]: Expected =
    at error (file:///home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/src/compiler/utils/error.js:56:16)
    at Parser.error (file:///home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/src/compiler/parse/index.js:143:3)
    at read_attribute (file:///home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/src/compiler/parse/state/tag.js:355:10)
    at tag (file:///home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/src/compiler/parse/state/tag.js:166:22)
    at new Parser (file:///home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/src/compiler/parse/index.js:91:12)
    at parse (file:///home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/src/compiler/parse/index.js:268:17)
    at parse (file:///home/project/node_modules/.pnpm/svelte-parse-markup@0.1.2_svelte@4.2.12/node_modules/svelte-parse-markup/index.js:50:15)
    at markup (file:///home/project/node_modules/.pnpm/svelte-preprocess-import-assets@1.1.0_svelte@4.2.12/node_modules/svelte-preprocess-import-assets/src/index.js:33:19)
    at process_markup (/home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/compiler.cjs:46081:26)
    at Object.preprocess (/home/project/node_modules/.pnpm/svelte@4.2.12/node_modules/svelte/compiler.cjs:46127:31) {
```

Removing `svelte-preprocess-import-assets` from my project solved the problem.

**Comment by fnimick** [comment]
I ran into a similar problem, and updating `houdini` to latest solved it for me.
