### ISSUE TITLE
The Hover Card example result in a <button> tag within a <a> tag

### ISSUE THREAD

**Issue by dcheglakov** [huntabyte/shadcn-svelte#86]
### Current Behavior

The example in the docs:
```js
...
  <HoverCardTrigger>
    <Button variant="link">@sveltejs</Button>
  </HoverCardTrigger>
...
```
This results in a `<button>` tag with a `<a>` tag, as `HoverCardTrigger` creates a `<a>` tag. This results in incorrect behavior.
A hover card will not appear if you switch to the trigger using the `Tab` key.

Similar to this [issue](https://github.com/huntabyte/shadcn-svelte/issues/79).

### Expected Behavior

As for now `asChild` prop is not implemented in [radix-svelte](https://github.com/radix-svelte/radix-svelte/issues/145) I think `Button` component must be replaced with plain text or `<span>` tag with the necessary tailwind classes.

### Steps To Reproduce

1. Add a `hover card` using the example in the docs (code tab in the docs).
2. View the code to see a `<button>` tag within a `<a>` tag
3. Attempt to `Tab` over elements

**Comment by dcheglakov** [comment]
@huntabyte I can fix this issue. Assign this task to me if needed. Thanks.

**Comment by huntabyte** [comment]
@dcheglakov all yours! Thank you!
