### ISSUE TITLE
Documentation site is down?

### ISSUE THREAD

**Issue by StevenStavrakis** [huntabyte/shadcn-svelte#864]
### Change Type

Correction

### Proposed Changes

Going through the docs just now and I'm getting an error:

Secure Connection Failed

An error occurred during a connection to www.shadcn-svelte.com. Cannot communicate securely with peer: no common encryption algorithm(s).

Error code: SSL_ERROR_NO_CYPHER_OVERLAP

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by vladyslavpavlenko** [comment]
+ Having the same issue

**Comment by svex99** [comment]
Same issue on my side.
![image](https://github.com/huntabyte/shadcn-svelte/assets/64504660/b4d0765d-6b46-49cc-a5e5-7c02f3f297ec)

**Comment by huntabyte** [comment]
We're tracking! Working on migrating to Cloudflare since we're about to be shutdown by Vercel for exceeding free-tier bandwidth.

If you're experiencing issues, please use https://shadcn-svelte.vercel.app/ until the migration is complete (DNS takes time to propagate)
