### ISSUE TITLE
Unexpected focusing behavior using keyboard navigation

### ISSUE THREAD

**Issue by dslatkin** [huntabyte/shadcn-svelte#867]
### Describe the bug

If you focus on certain interactive elements using keyboard navigation, then move focus to the next focusable element, you'll find focus moves one level _deeper_ into the same interactive element that is already focused.

This is confusing for those using keyboard navigation or assistive technologies as you would expect focus to move to the _next_ interactive element.

It's made more confusing by the fact that you can't see the second focus ring in dark mode.

The issue only reproduces on Mac Chrome for me, but Firefox and Safari seem fine.

### Reproduction

1. Open the [calendar component](https://shadcn-svelte.com/docs/components/calendar) in the docs
2. Click the month to put focus roughly within the component
3. Push <kbd>Tab</kbd> until focus is on one of the buttons
4. Push <kbd>Tab</kbd> again and notice focus is still within the button

This does not happen on the [same component](https://ui.shadcn.com/docs/components/calendar) on the official shad-ui library.

<details>

<summary>Screenshots</summary>

Before focus:

<img width="274" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/9263640/31b65fc1-be8b-40c3-8dcf-a27110a44c94">

After focusing on button:

<img width="277" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/9263640/5835ad23-b3f4-400b-81d3-8d919911371b">

After moving to "next" focusable element:

<img width="268" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/9263640/9dcb0525-c721-40b6-86ea-810ec70f85e1">

</details>

### System Info

Able to reproduce on Chrome, but not Safari or Firefox.

### Severity

annoyance

**Comment by shyakadavis** [comment]
Hi;

Something to note; this only happens for the `New York` style.


https://github.com/huntabyte/shadcn-svelte/assets/87414827/ea0ce500-88c5-4103-b88e-043616fc1e6b

**Comment by shyakadavis** [comment]
Could it be that `svelte-radix` icons are applying their own `tab index` or something?

**Comment by dslatkin** [comment]
Only have a bit of time right now, but if I open up dev tools on the calendar component and remove both the blur and focus events, the issue doesn't seem to happen.

I made a [little demo](https://codepen.io/DSlatkin/pen/XWQXKrO?editors=1111) on Codepen. If you add a focus event listener to an SVG, it becomes focusable. If you comment out the event listener, it's no longer focusable. Still only on Chrome, but not Firefox or Safari.

One short term fix in `shadcn-svelte` could be to capture the focus and blur events on the Radix icon and stop it propagating before it reaches the SVG.

**Comment by shyakadavis** [comment]
This tracks indeed.

> One short term fix in shadcn-svelte could be to capture the focus and blur events on the Radix icon and stop it propagating before it reaches the SVG.

My main concern about this, is that wouldn't we be forced to apply that patch/fix to every instance of the `New York` style that is using a `svelte-radix` icon? IMO, this doesn't feel right.

Let me play around and look into possible solutions for this; hope to arrive to an ideal one. 🙂

**Comment by huntabyte** [comment]
Hmm, this will definitely be problematic/annoying/unideal.

**Comment by shyakadavis** [comment]
Hey, @huntabyte 

There is a solution I found, but I'm not sure about the efficacy/accessibility/better implementation of it, and it would have to be implemented at `svelte-radix` level.

Basically, it's just applying a negative `tabindex` to all svg's since from mdn they say
> A negative value (the exact negative value doesn't actually matter, usually tabindex="-1") means that the element is not reachable via sequential keyboard navigation. 

I am yet to try this specifically for our use case, but it works and brings up 2 solutions:

1. Mention somewhere in shadcn-svelte docs about this, encourage/ask to add a negative tabindex to overcome this
2. Or, if it sounds reasonable, ask the author of `svelte-radix` to apply this. I'm not sure about this, though.

Wdyt? Whichever, lmt, and I'll try to see it through.

**Comment by huntabyte** [comment]
I think opening up an issue/PR with svelte-radix would be best tbh. I don't imagine anyone expects that to be the default behavior of an SVG to receive focus.

**Comment by huntabyte** [comment]
Didn't mean to close!

**Comment by dslatkin** [comment]
Digging a bit more (thanks to these references - [[1]](https://github.com/software-mansion/react-native-svg/issues/1471#issuecomment-716953627), [[2]](https://allyjs.io/tutorials/focusing-in-svg.html#focusing-svg-elements)), apparently this is actually part of [the SVG spec](https://allyjs.io/tutorials/focusing-in-svg.html#event-listeners) as an _optional_ implementation detail, which Blink/Chrome adopted and I guess the other browser engines didn't.

> In particular, user agents **may** ... allow focus to reach elements which have been assigned listeners for mouse, pointer, or focus events.

The issue definitely comes from `svelte-radix` - specifically it seems that with event forwarding, [like done here](https://github.com/shinokada/svelte-radix/blob/main/src/lib/Backpack.svelte), Svelte _always_ sets up an event listener, regardless if any consumers of the component actually listen to the event.

If `svelte-radix` adds a negative `tabindex` attribute by default, I think they should _also_ remove the `on:focus` and `on:blur` events anyways, because those functions have effectively become inert by doing that. So in general, I would say they should either

1. remove `on:blur` and `on:focus` or
2. forward all events using a library [like this](https://github.com/baseballyama/svelte-preprocess-delegate-events)

It looks like the core issue (Svelte setting essentially up inactive listeners) will be [addressed in Svelte 5](https://github.com/sveltejs/svelte/issues/2837#issuecomment-1848225140) anyways and that should be the preferred way moving forward to forward _all_ listeners instead of guessing at the ones devs will care about. I can give a stab at addressing it in a PR with `svelte-radix` (or at least opening an issue) later tonight. 🙂

**Comment by huntabyte** [comment]
Closing as this is resolved when updating to the latest version of the icon pack.
