### ISSUE TITLE
Drawer breaks page scrolling

### ISSUE THREAD

**Issue by gdude2002** [huntabyte/shadcn-svelte#871]
### Describe the bug

I'm not sure if this is an integration issue or a Vaul bug, but opening a drawer seems to break scrolling - neither the menu nor the page can be scrolled until the page is reloaded.

### Reproduction

Live: https://moderation.wiki/a/2024-03-04-test
GitHub: https://github.com/cmc-discord/site/blob/main/src/lib/components/ui/navbar/navbar.svelte#L17

1. Open the page on mobile, or make the viewpoint less wide until you can see the menu button in the navbar
2. Click/tap the menu button
3. Scrolling no longer works

Reproduced using Chrome on Windows, and Vivaldi and Chrome on Android.

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 93.23 GB / 127.91 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
Please provide a more minimal reproduction without the addition of all the extra styles and structure you have going on.

**Comment by gdude2002** [comment]
Having tried to work on a lighter reproduction, I've realised that my IDE completed Vaul's import instead of shadcn's, and I didn't notice. Sorry about that! I'll close this issue immediately.

One thing to note, though, is that your Stackblitz link isn't working for me:
![image](https://github.com/huntabyte/shadcn-svelte/assets/204153/b6809a4d-3460-47fe-bf79-6703660aea0c)

**Comment by huntabyte** [comment]
Will take a look at the repro template to get it worked out! This is why we started enforcing minimal repros haha oftentimes we find it is something small that ends up showing itself when you peel back the layers! Thank you!
