### ISSUE TITLE
Dropdown Menu items should be "cursor-pointer" by default

### ISSUE THREAD

**Issue by StevenStavrakis** [huntabyte/shadcn-svelte#872]
### Describe the feature

I can't think of a reason that `DropdownMenu.Item` should not have a pointer cursor by default. In general, I would expect its uses to overwhelmingly be for links to something or otherwise interactive.

**Comment by huntabyte** [comment]
Not planned. You can add them if you wish to your local project. Even the native `<button>` doesn't have `cursor: pointer`, only links do.
