### ISSUE TITLE
Missing Installation Step for Mode-Watcher in Sonner Component Manual

### ISSUE THREAD

**Issue by sphade** [huntabyte/shadcn-svelte#876]
### Change Type

Addition

### Proposed Changes

The absence of instructions for installing the mode-watcher in the Sonner component's manual installation guide may result in errors and bugs within applications . This crucial omission needs to be addressed to ensure smooth functionality and mitigate potential issues.

**Comment by xiBread** [comment]
The first step links to installation instructions. I don't think adding it again is really necessary.

<img width="727" alt="Screenshot 2024-03-08 at 2 50 48 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/60681223/160b3169-182e-45b6-a22c-3974f38c7cbe">

**Comment by huntabyte** [comment]
> The first step links to installation instructions. I don't think adding it again is really necessary.
👆
