### ISSUE TITLE
Dark mode transition not working

### ISSUE THREAD

**Issue by Saad5400** [huntabyte/shadcn-svelte#880]
### Describe the bug

When using `!transition-all` and `xyz-0 dark:xyz-1`, xyz is not being animated

### Reproduction

https://stackblitz.com/edit/github-ehve3t?file=src%2Froutes%2F%2Bpage.svelte

pnpm install mode-watcher
Use the ModeWatcher component
Add toggleMode to a button
Add transition-all and some css classes that change with dark:
click the button
switching to dark mode is not animating any css property

Another example is [shadcn-svelte website](https://www.shadcn-svelte.com/), the theme switcher icons on the top-right corner. I am getting the exact same issue.

![image](https://github.com/huntabyte/shadcn-svelte/assets/86385454/0cf0c75d-2744-48ce-bb2a-0512cd68c18f)

Although that it has transition and different value for dark, it's not being animated.

### System Info

```bash
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 5.91 GB / 15.96 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.0.30 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.3 
    bits-ui: ^0.18.6 => 0.18.6 
    mode-watcher: ^0.2.1 => 0.2.2 
    svelte: ^4.2.7 => 4.2.12 
    vaul-svelte: ^0.2.4 => 0.2.4 
```

### Severity

annoyance

**Comment by Saad5400** [comment]
I am not really sure how is it related to shadcn tbh, but I tried to reproduced it without having shadcn. The animation worked just fine.

But in my project with shadcn, it is not animating, just like in the website.

**Comment by Saad5400** [comment]
### Reproduction.

https://stackblitz.com/edit/github-ehve3t?file=src%2Froutes%2F%2Bpage.svelte

pnpm install mode-watcher
Use the ModeWatcher component
Add toggleMode to a button
Add transition-all and some css classes that change with dark:
click the button
switching to dark mode is not animating any css property

**Comment by huntabyte** [comment]
Ah yeah, I see what you're on about now.

This was actually introduced as people were complaining about the transitions happening when toggling. If you don't have transitions on every element, it looks super buggy. Perhaps we can expose a way to disable this behavior. If you create an issue over at https://github.com/svecosystem/mode-watcher we'll take a look as soon as we can!

**Comment by huntabyte** [comment]
Going to close this as it's unrelated to shadcn-svelte specifically, but feel free to use the same repro over there.

**Comment by Saad5400** [comment]
Thank you so much, I'll do
