### ISSUE TITLE
day 1 of requesting for input otp & breadcrumb 🔥🔥

### ISSUE THREAD

**Issue by malsvn** [huntabyte/shadcn-svelte#881]
### Describe the feature

day 1 of requesting for input otp & breadcrumb 🔥🔥

edit:
for reference
https://ui.shadcn.com/docs/components/breadcrumb
https://ui.shadcn.com/docs/components/input-otp

**Comment by shyakadavis** [comment]
Hello, 

Tbh, these reminders are very distracting and not necessary. 

> It is assumed that any feature in shadcn/ui is already on the roadmap/being worked on for this project, therefore it doesn't need a feature request issue

Related:
- https://github.com/huntabyte/shadcn-svelte/issues/645#issuecomment-1908562871
- https://github.com/huntabyte/shadcn-svelte/issues/683
- And others...

**Comment by shyakadavis** [comment]
Also, for some additional context on the `otp input`, the origina/headless author is working on a Svelte wrapper/version here, https://github.com/guilhermerodz/input-otp/tree/feat/multi-frameworks, and until that is merged/released, the best we can do is wait for Svelte support to arrive.

Cheers.

**Comment by huntabyte** [comment]
Yep, exactly what @shyakadavis said! You can sleep easy knowing that everything in the original is making its way here!
