### ISSUE TITLE
Example account form date of birth is stored in UTC

### ISSUE THREAD

**Issue by Spenhouet** [huntabyte/shadcn-svelte#884]
### Change Type

Correction

### Proposed Changes

The [account form example](https://www.shadcn-svelte.com/examples/forms/account) shows a date picker for date of birth, but when I (German timezone) select March 6, 2024 as date of birth at 1 AM my timezone, it shows 
```
dob: "2024-03-05T23:00:00.000Z"
```
in UTC time relative to my current local time, which for a date of birth field make zero sense.

Sorry that I even bring this up, as it is absolutely not important, but actually Microsoft had a similar bug in their system for years, changing stored birthdays of my contacts to a day before, resulting in embarrassing calls.... so seeing this handling of fixed dates which should not have timezone handling in the example woke up some memories.

**Comment by cd-slash** [comment]
It seems like this can be resolved by hardcoding the timezone as UTC in the `onValueChange()` function for the form field - this should ensure the value is always midnight on the date the user has selected, regardless of their timezone.
```
$formData.dob = value.toDate("UTC").toISOString();
```
It makes sense to use the local timezone of the user when it's being auto-populated to today's date (i.e. before the user has selected a date), but if it's a date-only field, I think setting to midnight UTC is better.
