### ISSUE TITLE
The icons of the toggle dark and light mode in the docs and also the sample implementation is inverted.

### ISSUE THREAD

**Issue by SaiedWork** [huntabyte/shadcn-svelte#892]
### Change Type

Correction

### Proposed Changes

When a website is currently in light mode, the icon that should be visible is typically the moon icon. This is because the moon icon represents dark mode, and clicking it would switch the website to dark mode. It’s a common practice in user interface design to display the icon of the mode that can be switched to, not the mode that is currently active. So in light mode, you see a moon (for dark mode), and in dark mode, you see a sun (for light mode). The original shadcn-ui docs page has also the icons inverted. The rotate transitions also not working. For example the bits-ui docs page has the correct toggle behavior and the transitions are also working.
However at the end, it's a design decisions. Saying that just in case of user friendliness.

**Comment by huntabyte** [comment]
We'll update this if also updated at https://ui.shadcn.com, which we are trying to remain aligned with 😃
