### ISSUE TITLE
bug: scroll bar length doesn't get recomputed on window resize

### ISSUE THREAD

**Issue by errmayank** [huntabyte/shadcn-svelte#894]
### Describe the bug

Horizontal scrollbar length doesn't seem like it's being recomputed from what i understand, resulting in this:

https://github.com/huntabyte/shadcn-svelte/assets/64462998/4e2c3b7e-38d7-4535-8cd3-43104cec96f4

### Reproduction

I wasn't able to import ScrollArea in the stackblitz so i created a repo [here](https://github.com/errmayank/shadcn-svelte-scroll-bug)

### System Info

```bash
System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1 Pro
  Memory: 4.38 GB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  bun: 1.0.18 - ~/.bun/bin/bun
Browsers:
  Chrome: 122.0.6261.112
  Safari: 17.4
npmPackages:
  @sveltejs/kit: ^2.0.0 => 2.5.3
  bits-ui: ^0.19.6 => 0.19.6
  svelte: ^4.2.7 => 4.2.12
```

### Severity

annoyance

**Comment by benediktms** [comment]
I'm encountering the same issue. I think this is related to the underlying library and related to: https://github.com/huntabyte/bits-ui/issues/567

**Comment by huntabyte** [comment]
This is resolved in `bits-ui@next` :)
