### ISSUE TITLE
import Pagination/Breadcrumb fails

### ISSUE THREAD

**Issue by brucegl** [huntabyte/shadcn-svelte#897]
### Describe the bug

Including `import * as Pagination from '$lib/components/ui/pagination/index.js';` generates the following runtime error:

'[plugin:vite:import-analysis] Failed to resolve import "lucide-svelte/icons/more-horizontal" from "src/lib/components/ui/pagination/pagination-ellipsis.svelte". Does the file exist?
31 |  
32 |  import "svelte/internal/disclose-version";
33 |  import MoreHorizontal from "lucide-svelte/icons/more-horizontal";
   |                              ^
34 |  import { cn } from "$lib/utils.js.js";
35 |  const file = "src/lib/components/ui/pagination/pagination-ellipsis.svelte";`

I couldn't find any mention in the documentation to install lucide-svelte. I did so anyway but that didn't help because there isn't a `more-horizontal` file in my $lib

I get the same issue for Breadcrumb

### Reproduction

Add this line to any new project

import * as Pagination from '$lib/components/ui/pagination/index.js';

### System Info

```bash
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 22.50 GB / 30.59 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - /opt/node-v18.14.2-linux-x64/bin/node
    npm: 9.7.2 - /opt/node-v18.14.2-linux-x64/bin/npm
  Browsers:
    Chrome: 122.0.6261.128
  npmPackages:
    @sveltejs/kit: ^1.27.4 => 1.27.6 
    bits-ui: ^0.19.6 => 0.19.6 
    svelte: ^4.0.5 => 4.2.3
```

### Severity

blocking all usage of shadcn-svelte

**Comment by shyakadavis** [comment]
Hi;

This seems to be an oversight. Lucide-svelte exports `<Ellipsis />` not `more-horizontal`.

Let me send a fix P.R.

**Comment by shyakadavis** [comment]
Think I found it;

https://github.com/lucide-icons/lucide/pull/1459/commits/23d92cef176f43013d022db2144e76594c81ccde via https://github.com/lucide-icons/lucide/pull/1459

@huntabyte, if it's cool, I could update the `lucide-svelte` version: i.e from `0.303.0` to `0.356.0(latest)`

**Comment by brucegl** [comment]
So quick! So great!! Thanks :-)
