### ISSUE TITLE
Can't use components

### ISSUE THREAD

**Issue by sudo-sand** [huntabyte/shadcn-svelte#91]
I really like this components, but for the general components like buttons this works. With something like Alert, I don't have access to any events or the ability to close it.

I have this code
```svelte
<script>
// ...
  const dispatch = createEventDispatcher()
  const toggle_is_open = () => is_open = false
  const handle_ok = () => {
    dispatch('ok')
    is_open = false
  }
</script>

<AlertDialog bind:open={is_open}>
```

I've been trying to get if the user actually pressed yes with no luck. The current way is it just closes the dialog without firing any events.
So I had to use a custom button to get `on:click` to work but I have this bug where I can't seem to close the `AlertDialog`.

**Comment by huntabyte** [comment]
If you could provide a stackblitz link to this I'd be more than happy to take a look!
