### ISSUE TITLE
Input Form example in Docs not working for me

### ISSUE THREAD

**Issue by brucegl** [huntabyte/shadcn-svelte#933]
### Change Type

Correction

### Proposed Changes

Hi,

This page: https://www.shadcn-svelte.com/docs/components/input#form shows a "loading spinner" for me.

Not sure if this is a bug in the example code or something else.

Thanks
Gary

**Comment by brucegl** [comment]
Thank you. The preview now works but the code tab has gone.

**Comment by AdrianGonz97** [comment]
@brucegl Thank you again for the headsup! This should be fixed in #937
