### ISSUE TITLE
Indeterminate progress bar

### ISSUE THREAD

**Issue by marchellodev** [huntabyte/shadcn-svelte#955]
### Describe the feature

It would be great to have an indeterminate horizontal progress bar, similar to skeleton's: https://www.skeleton.dev/components/progress-bars

Related to https://github.com/shadcn-ui/ui/issues/700

**Comment by huntabyte** [comment]
If it gets added to the original, it will get added here, thanks!

**Comment by laith43d** [comment]
hi @huntabyte , thanks for the great work here, I would like to ask about the charts, as it is part of the original Shadcn, is there any plan to add it?

**Comment by bengabp** [comment]
This wasnt added ?
