### ISSUE TITLE
0.9.3 Expected string but received undefined

### ISSUE THREAD

**Issue by kobe-ra** [huntabyte/shadcn-svelte#956]
### Describe the bug

![image](https://github.com/huntabyte/shadcn-svelte/assets/32091524/6978e235-2740-43f8-8ef7-39e603d485d6)
![image](https://github.com/huntabyte/shadcn-svelte/assets/32091524/61821749-abe9-425e-bf78-586cc74e207c)

I cannot use the add command in version 0.9.3
error message:
`Invalid type: Expected string but received undefined`
Tested version 0.9.2, which works properly.

### Reproduction

Use command `npx shadcn-svelte@latest add accordion` in Laravel-Inertia-Svelte project. No sveltekit, no typescript. If neccessary I'll create a new project with the same setup tomorrow.

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 20.06 GB / 31.92 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    bits-ui: ^0.16.0 => 0.16.0
    mode-watcher: ^0.2.1 => 0.2.1
    svelte: ^4.2.11 => 4.2.11
    svelte-radix: ^1.1.0 => 1.1.0
    svelte-sonner: ^0.3.17 => 0.3.17
    vaul-svelte: ^0.2.2 => 0.2.2
```

### Severity

annoyance

**Comment by AdrianGonz97** [comment]
Thanks for raising the issue.

> If neccessary I'll create a new project with the same setup tomorrow.

Please create the reproduction. It's easier for us to fix if we have a complete repro to work with, especially when it uses outside tech that we may not be familiar with!

**Comment by kobe-ra** [comment]
[here is the example repo](https://github.com/kobe-ra/laravel-svelte)

i also wrote the readme. if you have any troubles running it i can help.

**Comment by AdrianGonz97** [comment]
@kobe-ra 

Your `jsconfig.json` is missing path aliases in the reproduction, which is causing this issue (I'm not quite sure why it was working in previous versions in the first place either 🤔). 

Configuring the following will fix your issue:

`components.json`
```json
{
    "$schema": "https://shadcn-svelte.com/schema.json",
    "style": "new-york",
    "typescript": false,
    "tailwind": {
        "config": "tailwind.config.js",
        "css": "resources/css/app.pcss",
        "baseColor": "zinc"
    },
    "aliases": {
        "components": "@/components",
        "utils": "@/services/utils"
    }
}
```

`jsconfig.json`
```json
{
    "compilerOptions": {
        "paths": {
            "@/*": ["./resources/js/*"]
        }
    }
}
```

---

However, the error presented in the issue should definitely be _more descriptive_. `Invalid type: Expected string but received undefined` is neither particularly meaningful, nor helpful. We'll keep this issue open until that's fixed. 

Thank you!
