### ISSUE TITLE
Vertical orientation for tabs

### ISSUE THREAD

**Issue by martinjo** [huntabyte/shadcn-svelte#960]
### Describe the feature

Tabs have a ”orientation” property that I was expecting to affect how the tabs orient themselves visually. It seems to have no or another effect. But having an orientation property that affects layout (horizontal/vertical) would be so nice. 

Are there any plans for this or examples of how it could be achieved?

**Comment by huntabyte** [comment]
The orientation is for accessibility purposes. We could possibly add an example for vertical tabs.

**Comment by martinjo** [comment]
I figured it had some function :). An example with vertical tabs would be great! 🙏

**Comment by BeGeos** [comment]
What would the example need to be? Like just a piece of code or a with a selectable preview also?

**Comment by oluijks** [comment]
@huntabyte The name of the property `orientation' (The orientation of the tabs) is a bit misleading, it suggests that the tabs could be visually rendered horizontally or vertically. The documentation in the code of bits-ui is clear about this but I can imagine that people would be a little disappointed when finding out that it only applies to keyboard navigation...

What to do? Update bits-ui property name and docs or update the shadcn-svelte docs with a remark about the tabs properties? Or a third option: implement visually vertically rendered tabs?

**Comment by huntabyte** [comment]
The orientation is documented in Bits UI @next as determining keyboard navigation. If you wish to add vertical tabs to shadcn-svelte, the code is yours. You're more than welcome to add a variation to your codebase, but until it's added to the original [shadcn/ui](https://ui.shadcn.com), then it won't be added here.

**Comment by dskvr** [comment]
At minimum having two separate orientation properties `orientation` and `data-orientation`, with identical descriptions, and mismatches parameters (some are listed as enum with a tooltip, is extremely misleading.

**Comment by christophhehl** [comment]
Maybe this could be reopened, as it does seem to be in the current documentation of [shadcn/ui](https://ui.shadcn.com/docs/components/base/tabs#vertical).
