### ISSUE TITLE
Sheet reactivity breaks (if nested ?)

### ISSUE THREAD

**Issue by Scooter1337** [huntabyte/shadcn-svelte#968]
### Describe the bug

Very weird bug I came across when recreating some of the shadcn blocks.

It only happens in nested layouts/pages.

Wrapping the sheetcontent in a key (of path.url.pathname) solves the reactivity problem, but breaks send/receive transitions. (and does not seem the right solution)

### Reproduction

https://stackblitz.com/edit/github-bwwacm?file=src%2Flib%2Fcomponents%2Flayoutwrapper.svelte

1. click the big red button (might take a hot minute, stackblitz is not that fast, you might need to click 2/3 times due to the optimizing deps)
2. Click 'click to open sheet'
3. Alternate clicking the buttons. Notice that the big bold value does not change.
4. If you are on '/ambs' and it shows false, reopening sheet correctly shows true, and vice versa.

### System Info

```bash
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 405.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.6.7 - /opt/homebrew/bin/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 123.0.6312.86
    Edge: 119.0.2151.72
    Safari: 17.4.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.4 
    bits-ui: ^0.19.7 => 0.19.7 
    cmdk-sv: ^0.0.15 => 0.0.15 
    formsnap: ^0.5.1 => 0.5.1 
    lucide-svelte: ^0.320.0 => 0.320.0 
    mode-watcher: ^0.3.0 => 0.3.0 
    svelte: ^4.2.7 => 4.2.12 
    svelte-radix: ^1.1.0 => 1.1.0 
    svelte-sonner: ^0.3.19 => 0.3.19 
    sveltekit-superforms: ^2.10.6 => 2.10.6 
    vaul-svelte: ^0.0.6 => 0.0.6
```

### Severity

blocking an upgrade

**Comment by huntabyte** [comment]
This _feels_ more like a Svelte/Kit bug than a bug with shadcn-svelte. I'll investigate further.

**Comment by huntabyte** [comment]
Yep, my suspicion has been confirmed: https://github.com/sveltejs/kit/issues/10116.

Going to close this as it isn't related to shadcn-svelte specifically.

**Comment by Scooter1337** [comment]
> Yep, my suspicion has been confirmed: https://github.com/sveltejs/kit/issues/10116.
> 
> 
> 
> Going to close this as it isn't related to shadcn-svelte specifically.

It seems Svelte 5 fixes this. As if I needed more reason to be hyped for v5... I need it now!!!

Thanks for looking into it, you're the reason I can keep loving webdev.
