### ISSUE TITLE
docs: wrong code highlighting for some Data Table component plugins

### ISSUE THREAD

**Issue by meeusnietmeus** [huntabyte/shadcn-svelte#996]
### Change Type

Cleanup (formatting, typos, etc.)

### Proposed Changes

On the data table section under 'components', there is wrong code highlighting for enabling the `addHiddenColumns` plugin.
The pagination plugin and some closing brackets are highlighted instead.

![image](https://github.com/huntabyte/shadcn-svelte/assets/91123727/2c377573-4e10-4e03-8314-53d9d8adadd3)

This is true for `Row Selection` as well.
![image](https://github.com/huntabyte/shadcn-svelte/assets/91123727/49e171e4-74f7-4354-b29b-a6ab75f07c26)

**Comment by meeusnietmeus** [comment]
I see the issue is marked for help. I could fix it maybe? Isn't a lot of work.

**Comment by huntabyte** [comment]
PRs welcome :)
